###############################################################
#  Generated by:      Cadence Innovus 21.16-s078_1
#  OS:                Linux x86_64(Host ID cadpc19)
#  Generated on:      Sun Mar 22 10:45:34 2026
#  Design:            systolic_array_wrapper
#  Command:           create_clock_tree_spec -views { av_normal_typ } -keep_all_sdc_clocks -out_file ctsSpec_ccopt.tcl
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Common UI
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_db clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_db port:clk .cts_is_sdc_clock_root true

# Clocks present at pin clk
#   clk (period 20.000ns) in timing_config mode_normal([../../syn/output/systolic_array_wrapper.syn.sdc])
create_clock_tree -name clk -source clk -no_skew_group
set_db clock_tree:clk .cts_target_max_transition_time_sdc_early -index delay_corner:dc_max 0.150
set_db clock_tree:clk .cts_target_max_transition_time_sdc_late -index delay_corner:dc_max 0.150
set_db clock_tree:clk .cts_target_max_transition_time_sdc_early -index delay_corner:dc_typ 0.150
set_db clock_tree:clk .cts_target_max_transition_time_sdc_late -index delay_corner:dc_typ 0.150
set_db clock_tree:clk .cts_target_max_transition_time_sdc_early -index delay_corner:dc_min 0.150
set_db clock_tree:clk .cts_target_max_transition_time_sdc_late -index delay_corner:dc_min 0.150
set_db clock_tree:clk .cts_target_max_transition_time_sdc_early -index delay_corner:dc_min_lt 0.150
set_db clock_tree:clk .cts_target_max_transition_time_sdc_late -index delay_corner:dc_min_lt 0.150
# Clock period setting for source pin of clk
set_db port:clk .cts_clock_period 20

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_db cts_timing_connectivity_info {}

# Skew group to balance non generated clock:clk in timing_config:mode_normal (sdc ../../syn/output/systolic_array_wrapper.syn.sdc)
create_skew_group -name clk/mode_normal -sources clk -auto_sinks
set_db skew_group:clk/mode_normal .cts_skew_group_include_source_latency true
set_db skew_group:clk/mode_normal .cts_skew_group_created_from_clock clk
set_db skew_group:clk/mode_normal .cts_skew_group_created_from_constraint_mode mode_normal
set_db skew_group:clk/mode_normal .cts_skew_group_created_from_delay_corners {dc_max dc_typ dc_min dc_min_lt}


check_clock_tree_convergence
# Restore the ILM status if possible
if { [get_db ccopt_auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

