/*
###############################################################
#  Generated by:      Cadence Innovus 21.16-s078_1
#  OS:                Linux x86_64(Host ID cadpc15)
#  Generated on:      Wed Apr  1 00:29:41 2026
#  Design:            sram_wrapper
#  Command:           write_netlist ../report/export.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.16-s062_1
// Generated on: Mar 31 2026 23:32:31 EDT (Apr  1 2026 03:32:31 UTC)
// Verification Directory fv/sram_wrapper 
module sram_wrapper (
	clk, 
	rstn, 
	bus_we, 
	bus_addr, 
	bus_din, 
	tpu_re, 
	tpu_addr, 
	tpu_dout);
   input clk;
   input rstn;
   input bus_we;
   input [11:0] bus_addr;
   input [7:0] bus_din;
   input tpu_re;
   input [8:0] tpu_addr;
   output [63:0] tpu_dout;

   // Internal wires
   wire FE_PDN541_tpu_dout_58;
   wire FE_PDN539_tpu_dout_54;
   wire FE_PHN538_bus_din_5;
   wire FE_PHN537_bus_din_5;
   wire FE_PHN536_bus_din_5;
   wire FE_PHN535_bus_din_5;
   wire FE_PHN534_bus_din_5;
   wire FE_PHN533_bus_din_5;
   wire FE_PHN532_bus_din_5;
   wire FE_PHN531_bus_din_5;
   wire FE_PHN530_bus_din_5;
   wire FE_PHN529_bus_din_5;
   wire FE_PHN528_bus_din_5;
   wire FE_PHN527_bus_din_5;
   wire FE_PHN526_bus_din_3;
   wire FE_PHN525_bus_din_5;
   wire FE_PHN524_bus_din_5;
   wire FE_PHN523_bus_din_3;
   wire FE_PHN522_bus_din_5;
   wire FE_PHN521_bus_din_5;
   wire FE_PHN520_bus_din_3;
   wire FE_PHN519_bus_din_1;
   wire FE_PHN518_bus_din_3;
   wire FE_PHN517_bus_din_0;
   wire FE_PHN516_bus_din_5;
   wire FE_PHN515_bus_din_4;
   wire FE_PHN514_bus_addr_2;
   wire FE_PHN513_bus_din_5;
   wire FE_PHN512_bus_din_1;
   wire FE_PHN511_bus_din_2;
   wire FE_PHN510_bus_din_7;
   wire FE_PHN509_bus_din_0;
   wire FE_PHN508_bus_din_0;
   wire FE_PHN507_bus_din_0;
   wire FE_PHN506_bus_din_0;
   wire FE_PHN505_bus_din_0;
   wire FE_PHN504_bus_din_0;
   wire FE_PHN503_bus_din_0;
   wire FE_PHN502_bus_din_0;
   wire FE_PHN501_bus_din_3;
   wire FE_PHN500_bus_din_0;
   wire FE_PHN499_bus_din_3;
   wire FE_PHN498_bus_din_0;
   wire FE_PHN497_bus_din_3;
   wire FE_PHN496_bus_din_6;
   wire FE_PHN495_bus_din_0;
   wire FE_PHN494_bus_din_3;
   wire FE_PHN493_bus_din_6;
   wire FE_PHN492_bus_din_0;
   wire FE_PHN491_bus_din_3;
   wire FE_PHN490_bus_din_1;
   wire FE_PHN489_bus_din_6;
   wire FE_PHN488_bus_din_0;
   wire FE_PHN487_bus_din_3;
   wire FE_PHN486_bus_din_6;
   wire FE_PHN485_bus_din_1;
   wire FE_PHN484_bus_din_3;
   wire FE_PHN483_bus_din_0;
   wire FE_PHN482_bus_din_1;
   wire FE_PHN481_bus_din_6;
   wire FE_PHN480_bus_din_0;
   wire FE_PHN479_bus_din_3;
   wire FE_PHN478_bus_din_1;
   wire FE_PHN477_bus_din_6;
   wire FE_PHN476_bus_din_4;
   wire FE_PHN475_bus_din_6;
   wire FE_PHN474_bus_din_1;
   wire FE_PHN473_bus_din_0;
   wire FE_PHN472_bus_din_3;
   wire FE_PHN471_bus_din_2;
   wire FE_PHN470_bus_din_4;
   wire FE_PHN469_bus_din_6;
   wire FE_PHN468_bus_din_3;
   wire FE_PHN467_bus_din_1;
   wire FE_PHN466_bus_din_2;
   wire FE_PHN465_bus_din_0;
   wire FE_PHN464_bus_din_4;
   wire FE_PHN463_bus_din_2;
   wire FE_PHN462_bus_din_0;
   wire FE_PHN461_bus_din_1;
   wire FE_PHN460_bus_din_6;
   wire FE_PHN459_bus_din_4;
   wire FE_PHN458_bus_din_1;
   wire FE_PHN457_bus_din_6;
   wire FE_PHN456_bus_din_3;
   wire FE_PHN455_bus_din_1;
   wire FE_PHN454_bus_din_0;
   wire FE_PHN453_bus_din_2;
   wire FE_PHN452_bus_din_4;
   wire FE_PHN451_bus_din_1;
   wire FE_PHN450_bus_din_2;
   wire FE_PHN449_bus_din_0;
   wire FE_PHN448_bus_din_1;
   wire FE_PHN447_bus_din_2;
   wire FE_PHN446_bus_din_4;
   wire FE_PHN445_bus_din_3;
   wire FE_PHN444_bus_din_6;
   wire FE_PHN443_bus_din_1;
   wire FE_PHN442_bus_din_2;
   wire FE_PHN441_bus_din_3;
   wire FE_PHN440_bus_din_4;
   wire FE_PHN439_bus_din_0;
   wire FE_PHN438_bus_din_1;
   wire FE_PHN437_bus_din_3;
   wire FE_PHN436_bus_din_2;
   wire FE_PHN435_bus_din_4;
   wire FE_PHN434_bus_din_6;
   wire FE_PHN433_bus_din_7;
   wire FE_PHN432_bus_din_0;
   wire FE_PHN431_bus_din_6;
   wire FE_PHN430_bus_din_2;
   wire FE_PHN429_bus_din_1;
   wire FE_PHN428_bus_din_3;
   wire FE_PHN427_bus_din_4;
   wire FE_PHN426_bus_din_7;
   wire FE_PHN425_bus_din_1;
   wire FE_PHN424_bus_din_0;
   wire FE_PHN423_bus_din_2;
   wire FE_PHN422_bus_din_4;
   wire FE_PHN421_bus_din_3;
   wire FE_PHN420_bus_din_7;
   wire FE_PHN419_bus_addr_7;
   wire FE_PHN418_FE_OFN4_sram_addr_7;
   wire FE_PHN417_bus_addr_11;
   wire FE_PHN416_bus_addr_9;
   wire FE_PHN415_bus_addr_6;
   wire FE_PHN414_bus_addr_10;
   wire FE_PHN413_bus_addr_2;
   wire FE_PHN412_bus_din_1;
   wire FE_PHN411_bus_din_6;
   wire FE_PHN410_bus_din_2;
   wire FE_PHN409_bus_din_5;
   wire FE_PHN408_bus_addr_8;
   wire FE_PHN407_bus_addr_8;
   wire FE_PHN406_bus_addr_8;
   wire FE_PHN405_bus_addr_8;
   wire FE_PHN404_bus_addr_8;
   wire FE_PHN403_bus_addr_8;
   wire FE_PHN402_bus_addr_8;
   wire FE_PHN401_tpu_dout_3;
   wire FE_PHN400_tpu_dout_1;
   wire FE_PHN399_bus_addr_8;
   wire FE_PHN398_tpu_dout_3;
   wire FE_PHN397_tpu_dout_1;
   wire FE_PHN396_bus_addr_9;
   wire FE_PHN395_bus_addr_8;
   wire FE_PHN394_tpu_dout_0;
   wire FE_PHN393_tpu_dout_3;
   wire FE_PHN392_tpu_dout_1;
   wire FE_PHN391_bus_addr_9;
   wire FE_PHN390_bus_addr_8;
   wire FE_PHN389_tpu_dout_1;
   wire FE_PHN388_tpu_dout_3;
   wire FE_PHN387_bus_addr_9;
   wire FE_PHN386_tpu_dout_0;
   wire FE_PHN385_bus_addr_8;
   wire FE_PHN384_bus_addr_9;
   wire FE_PHN383_tpu_dout_1;
   wire FE_PHN382_tpu_dout_3;
   wire FE_PHN381_tpu_dout_0;
   wire FE_PHN380_bus_addr_8;
   wire FE_PHN379_bus_addr_9;
   wire FE_PHN378_tpu_dout_1;
   wire FE_PHN377_tpu_dout_3;
   wire FE_PHN376_tpu_dout_0;
   wire FE_PHN375_bus_addr_9;
   wire FE_PHN374_bus_addr_8;
   wire FE_PHN373_tpu_dout_1;
   wire FE_PHN372_tpu_dout_3;
   wire FE_PHN371_tpu_dout_0;
   wire FE_PHN370_bus_addr_3;
   wire FE_PHN369_bus_addr_11;
   wire FE_PHN368_bus_addr_8;
   wire FE_PHN367_bus_addr_9;
   wire FE_PHN366_tpu_dout_1;
   wire FE_PHN365_tpu_dout_3;
   wire FE_PHN364_tpu_dout_0;
   wire FE_PHN363_bus_addr_3;
   wire FE_PHN362_bus_addr_11;
   wire FE_PHN361_bus_addr_9;
   wire FE_PHN360_bus_addr_8;
   wire FE_PHN359_tpu_dout_3;
   wire FE_PHN358_tpu_dout_1;
   wire FE_PHN357_tpu_dout_0;
   wire FE_PHN356_bus_addr_3;
   wire FE_PHN355_bus_addr_11;
   wire FE_PHN354_bus_addr_9;
   wire FE_PHN353_bus_addr_8;
   wire FE_PHN352_tpu_dout_3;
   wire FE_PHN351_tpu_dout_1;
   wire FE_PHN350_bus_addr_11;
   wire FE_PHN349_bus_addr_7;
   wire FE_PHN348_bus_wbuf_0;
   wire FE_PHN347_FE_OFN10_sram_addr_1;
   wire FE_PHN346_bus_addr_11;
   wire FE_PHN345_tpu_dout_0;
   wire FE_PHN344_bus_addr_7;
   wire FE_PHN343_bus_wbuf_0;
   wire FE_PHN342_bus_addr_3;
   wire FE_PHN341_bus_addr_6;
   wire FE_PHN340_bus_addr_5;
   wire FE_PHN339_bus_addr_4;
   wire FE_PHN338_tpu_addr_7;
   wire FE_PHN337_bus_addr_10;
   wire FE_PHN336_FE_OFN10_sram_addr_1;
   wire FE_PHN335_tpu_dout_31;
   wire FE_PHN334_FE_OFN11_sram_addr_0;
   wire FE_PHN332_tpu_dout_31;
   wire FE_PHN331_tpu_dout_12;
   wire FE_PHN330_tpu_dout_18;
   wire FE_PHN329_tpu_dout_19;
   wire FE_PHN328_tpu_dout_2;
   wire FE_PHN327_tpu_dout_17;
   wire FE_PHN326_tpu_dout_5;
   wire FE_PHN325_tpu_dout_8;
   wire FE_PHN324_bus_wbuf_0;
   wire FE_PHN323_tpu_re;
   wire FE_PHN322_bus_addr_6;
   wire FE_PHN321_tpu_addr_7;
   wire FE_PHN320_bus_addr_5;
   wire FE_PHN319_bus_addr_4;
   wire FE_PHN318_bus_addr_10;
   wire FE_PHN317_tpu_dout_23;
   wire FE_PHN316_tpu_dout_21;
   wire FE_PHN315_tpu_dout_20;
   wire FE_PHN314_FE_OFN9_sram_addr_2;
   wire FE_PHN313_FE_OFN8_sram_addr_3;
   wire FE_PHN312_FE_OFN7_sram_addr_4;
   wire FE_PHN311_FE_OFN6_sram_addr_5;
   wire FE_PHN310_FE_OFN5_sram_addr_6;
   wire FE_PHN309_FE_OFN10_sram_addr_1;
   wire FE_PHN308_FE_OFN11_sram_addr_0;
   wire FE_PHN307_n_8;
   wire FE_PHN306_bus_din_1;
   wire FE_PHN305_bus_din_0;
   wire FE_PHN304_bus_wbuf_0;
   wire FE_PHN303_bus_din_6;
   wire FE_PHN302_bus_din_2;
   wire FE_PHN301_bus_din_3;
   wire FE_PHN300_bus_din_4;
   wire FE_PHN299_bus_din_5;
   wire FE_PHN298_bus_din_7;
   wire FE_PHN297_tpu_addr_8;
   wire FE_PHN296_tpu_dout_19;
   wire FE_PHN295_tpu_dout_18;
   wire FE_PHN294_tpu_dout_13;
   wire FE_PHN293_tpu_dout_7;
   wire FE_PHN292_tpu_dout_11;
   wire FE_PHN291_tpu_dout_6;
   wire FE_PHN290_tpu_dout_4;
   wire FE_PHN289_tpu_dout_9;
   wire FE_PHN288_tpu_dout_2;
   wire FE_PHN287_tpu_dout_10;
   wire FE_PHN286_tpu_dout_8;
   wire FE_PHN285_tpu_dout_14;
   wire FE_PHN284_tpu_dout_5;
   wire FE_PHN283_tpu_dout_17;
   wire FE_PHN282_tpu_dout_52;
   wire FE_PHN281_tpu_dout_60;
   wire FE_PHN280_tpu_dout_56;
   wire FE_PHN279_tpu_dout_55;
   wire FE_PHN278_tpu_dout_12;
   wire FE_PHN277_tpu_dout_54;
   wire FE_PHN276_tpu_dout_58;
   wire FE_PHN275_tpu_dout_57;
   wire FE_PHN274_tpu_dout_59;
   wire FE_PHN273_tpu_dout_50;
   wire FE_PHN272_tpu_dout_51;
   wire FE_PHN271_tpu_dout_53;
   wire FE_PHN270_tpu_dout_62;
   wire FE_PHN269_tpu_dout_47;
   wire FE_PHN268_tpu_dout_48;
   wire FE_PHN267_tpu_dout_49;
   wire FE_PHN266_tpu_dout_61;
   wire FE_PHN265_tpu_dout_44;
   wire FE_PHN264_tpu_dout_63;
   wire FE_PHN263_tpu_dout_40;
   wire FE_PHN262_tpu_dout_46;
   wire FE_PHN261_tpu_dout_43;
   wire FE_PHN260_tpu_dout_39;
   wire FE_PHN259_tpu_dout_45;
   wire FE_PHN258_tpu_dout_41;
   wire FE_PHN257_tpu_dout_38;
   wire FE_PHN256_tpu_dout_37;
   wire FE_PHN255_tpu_dout_36;
   wire FE_PHN254_tpu_dout_32;
   wire FE_PHN253_tpu_dout_34;
   wire FE_PHN252_tpu_dout_35;
   wire FE_PHN251_tpu_dout_33;
   wire FE_PHN250_tpu_dout_27;
   wire FE_PHN249_tpu_dout_24;
   wire FE_PHN248_tpu_dout_22;
   wire FE_PHN247_tpu_dout_25;
   wire FE_PHN246_tpu_dout_26;
   wire FE_PHN245_tpu_dout_28;
   wire FE_PHN244_tpu_dout_29;
   wire FE_PHN243_tpu_dout_30;
   wire FE_PHN242_bus_addr_11;
   wire FE_PHN241_bus_addr_8;
   wire FE_PHN240_bus_addr_9;
   wire FE_PHN239_tpu_re;
   wire FE_PHN238_tpu_dout_42;
   wire FE_PHN237_tpu_dout_16;
   wire FE_PHN236_tpu_dout_15;
   wire FE_PHN235_bus_addr_1;
   wire FE_PHN234_FE_OFN9_sram_addr_2;
   wire FE_PHN233_FE_OFN8_sram_addr_3;
   wire FE_PHN232_FE_OFN5_sram_addr_6;
   wire FE_PHN231_FE_OFN6_sram_addr_5;
   wire FE_PHN230_bus_wbuf_57;
   wire FE_PHN229_bus_wbuf_58;
   wire FE_PHN228_bus_wbuf_59;
   wire FE_PHN227_bus_wbuf_61;
   wire FE_PHN226_bus_wbuf_60;
   wire FE_PHN225_bus_wbuf_63;
   wire FE_PHN224_bus_wbuf_56;
   wire FE_PHN223_bus_wbuf_62;
   wire FE_PHN222_bus_wbuf_47;
   wire FE_PHN221_bus_wbuf_46;
   wire FE_PHN220_bus_wbuf_43;
   wire FE_PHN219_bus_wbuf_41;
   wire FE_PHN218_bus_wbuf_45;
   wire FE_PHN217_bus_wbuf_32;
   wire FE_PHN216_bus_wbuf_44;
   wire FE_PHN215_bus_wbuf_42;
   wire FE_PHN214_bus_wbuf_38;
   wire FE_PHN213_bus_wbuf_37;
   wire FE_PHN212_bus_wbuf_40;
   wire FE_PHN211_bus_wbuf_39;
   wire FE_PHN210_bus_wbuf_36;
   wire FE_PHN209_bus_wbuf_35;
   wire FE_PHN208_bus_wbuf_34;
   wire FE_PHN207_bus_wbuf_33;
   wire FE_PHN206_FE_OFN4_sram_addr_7;
   wire FE_PHN205_bus_wbuf_18;
   wire FE_PHN204_bus_wbuf_17;
   wire FE_PHN203_bus_wbuf_27;
   wire FE_PHN202_bus_wbuf_22;
   wire FE_PHN201_bus_wbuf_21;
   wire FE_PHN200_bus_wbuf_20;
   wire FE_PHN199_bus_wbuf_16;
   wire FE_PHN198_bus_wbuf_26;
   wire FE_PHN197_bus_wbuf_25;
   wire FE_PHN196_bus_wbuf_23;
   wire FE_PHN195_bus_wbuf_29;
   wire FE_PHN194_bus_wbuf_28;
   wire FE_PHN193_bus_wbuf_19;
   wire FE_PHN192_bus_wbuf_31;
   wire FE_PHN191_bus_wbuf_30;
   wire FE_PHN190_bus_wbuf_24;
   wire FE_PHN189_n_91;
   wire FE_PHN188_n_4;
   wire FE_PHN187_FE_OFN7_sram_addr_4;
   wire FE_PHN186_n_10;
   wire FE_PHN185_n_12;
   wire FE_PHN184_n_6;
   wire FE_PHN183_bus_addr_10;
   wire FE_PHN182_FE_OFN3_sram_addr_8;
   wire FE_PHN181_n_3;
   wire FE_PHN180_bus_din_6;
   wire FE_PHN179_bus_din_7;
   wire FE_PHN178_bus_din_5;
   wire FE_PHN177_bus_din_0;
   wire FE_PHN176_bus_din_4;
   wire FE_PHN175_bus_din_1;
   wire FE_PHN174_bus_din_3;
   wire FE_PHN173_bus_din_2;
   wire FE_PHN171_tpu_dout_27;
   wire FE_PHN169_tpu_dout_11;
   wire FE_PHN167_tpu_dout_18;
   wire FE_PHN165_tpu_dout_22;
   wire FE_PHN163_tpu_dout_24;
   wire FE_PHN161_tpu_dout_30;
   wire FE_PHN159_tpu_dout_16;
   wire FE_PHN157_tpu_dout_28;
   wire FE_PHN155_tpu_dout_6;
   wire FE_PHN153_tpu_dout_25;
   wire FE_PHN151_tpu_dout_31;
   wire FE_PHN149_tpu_dout_12;
   wire FE_PHN147_tpu_dout_17;
   wire FE_PHN145_tpu_dout_19;
   wire FE_PHN143_tpu_dout_9;
   wire FE_PHN141_tpu_dout_0;
   wire FE_PHN139_tpu_dout_23;
   wire FE_PHN137_tpu_dout_26;
   wire FE_PHN135_tpu_dout_29;
   wire FE_PHN133_tpu_dout_33;
   wire FE_PHN131_tpu_dout_7;
   wire FE_PHN129_tpu_dout_8;
   wire FE_PHN127_tpu_dout_15;
   wire FE_PHN125_tpu_dout_21;
   wire FE_PHN123_tpu_dout_20;
   wire FE_PHN121_tpu_dout_42;
   wire FE_PHN119_tpu_dout_45;
   wire FE_PHN117_tpu_dout_36;
   wire FE_PHN115_tpu_dout_5;
   wire FE_PHN113_tpu_dout_13;
   wire FE_PHN111_tpu_dout_56;
   wire FE_PHN109_tpu_dout_59;
   wire FE_PHN107_tpu_dout_47;
   wire FE_PHN105_tpu_dout_40;
   wire FE_PHN103_tpu_dout_38;
   wire FE_PHN101_tpu_dout_34;
   wire FE_PHN99_tpu_dout_1;
   wire FE_PHN97_tpu_dout_2;
   wire FE_PHN95_tpu_dout_14;
   wire FE_PHN93_tpu_dout_60;
   wire FE_PHN91_tpu_dout_52;
   wire FE_PHN89_tpu_dout_37;
   wire FE_PHN87_tpu_dout_32;
   wire FE_PHN85_tpu_dout_35;
   wire FE_PHN83_tpu_dout_10;
   wire FE_PHN81_tpu_dout_62;
   wire FE_PHN79_tpu_dout_58;
   wire FE_PHN77_tpu_dout_55;
   wire FE_PHN75_tpu_dout_44;
   wire FE_PHN73_tpu_dout_46;
   wire FE_PHN71_tpu_dout_39;
   wire FE_PHN69_tpu_dout_41;
   wire FE_PHN67_tpu_dout_3;
   wire FE_PHN65_tpu_dout_63;
   wire FE_PHN63_tpu_dout_49;
   wire FE_PHN61_tpu_dout_4;
   wire FE_PHN59_tpu_dout_54;
   wire FE_PHN57_tpu_dout_61;
   wire FE_PHN55_tpu_dout_57;
   wire FE_PHN53_tpu_dout_53;
   wire FE_PHN51_tpu_dout_51;
   wire FE_PHN49_tpu_dout_50;
   wire FE_PHN47_tpu_dout_48;
   wire FE_PHN45_tpu_dout_43;
   wire FE_PHN44_bus_wbuf_1;
   wire FE_PHN43_bus_wbuf_2;
   wire FE_PHN42_bus_wbuf_4;
   wire FE_PHN41_bus_wbuf_3;
   wire FE_PHN40_bus_wbuf_6;
   wire FE_PHN39_bus_wbuf_7;
   wire FE_PHN38_bus_wbuf_8;
   wire FE_PHN37_bus_wbuf_5;
   wire FE_PHN36_bus_wbuf_11;
   wire FE_PHN35_bus_wbuf_9;
   wire FE_PHN34_bus_wbuf_15;
   wire FE_PHN33_bus_wbuf_13;
   wire FE_PHN32_bus_wbuf_10;
   wire FE_PHN31_bus_wbuf_12;
   wire FE_PHN30_bus_wbuf_14;
   wire FE_PHN29_bus_wbuf_54;
   wire FE_PHN28_bus_wbuf_53;
   wire FE_PHN27_bus_wbuf_50;
   wire FE_PHN26_bus_wbuf_55;
   wire FE_PHN25_bus_wbuf_51;
   wire FE_PHN24_bus_wbuf_52;
   wire FE_PHN23_bus_wbuf_49;
   wire FE_PHN22_bus_wbuf_48;
   wire FE_PHN21_rstn;
   wire FE_PHN20_bus_addr_3;
   wire FE_PHN19_bus_addr_4;
   wire FE_PHN18_bus_addr_5;
   wire FE_PHN17_bus_addr_6;
   wire FE_PHN16_bus_addr_7;
   wire FE_PHN15_tpu_re;
   wire FE_PHN14_bus_we;
   wire FE_PHN13_bus_addr_0;
   wire FE_PHN12_bus_addr_1;
   wire CTS_12;
   wire CTS_11;
   wire CTS_8;
   wire CTS_7;
   wire CTS_6;
   wire CTS_5;
   wire CTS_4;
   wire CTS_3;
   wire CTS_2;
   wire CTS_1;
   wire CTS_10;
   wire CTS_9;
   wire LTIELO_NET;
   wire LTIEHI_NET;
   wire FE_OFN11_sram_addr_0;
   wire FE_OFN10_sram_addr_1;
   wire FE_OFN9_sram_addr_2;
   wire FE_OFN8_sram_addr_3;
   wire FE_OFN7_sram_addr_4;
   wire FE_OFN6_sram_addr_5;
   wire FE_OFN5_sram_addr_6;
   wire FE_OFN4_sram_addr_7;
   wire FE_OFN3_sram_addr_8;
   wire FE_OFN2_bus_we_d1;
   wire FE_OFN1_tpu_re;
   wire FE_OFN0_rstn;
   wire [8:0] sram_addr;
   wire [63:0] sram_din;
   wire [8:0] bus_waddr_d1;
   wire [8:0] sram_addr_ff;
   wire [63:0] sram_din_ff;
   wire [63:0] bus_wbuf;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire UNCONNECTED9;
   wire UNCONNECTED10;
   wire UNCONNECTED11;
   wire UNCONNECTED12;
   wire UNCONNECTED13;
   wire UNCONNECTED14;
   wire UNCONNECTED15;
   wire UNCONNECTED16;
   wire UNCONNECTED17;
   wire UNCONNECTED18;
   wire UNCONNECTED19;
   wire UNCONNECTED20;
   wire UNCONNECTED21;
   wire UNCONNECTED22;
   wire UNCONNECTED23;
   wire UNCONNECTED24;
   wire UNCONNECTED25;
   wire UNCONNECTED26;
   wire UNCONNECTED27;
   wire UNCONNECTED28;
   wire UNCONNECTED29;
   wire UNCONNECTED30;
   wire UNCONNECTED31;
   wire UNCONNECTED32;
   wire UNCONNECTED33;
   wire UNCONNECTED34;
   wire UNCONNECTED35;
   wire UNCONNECTED36;
   wire UNCONNECTED37;
   wire UNCONNECTED38;
   wire UNCONNECTED39;
   wire UNCONNECTED40;
   wire UNCONNECTED41;
   wire UNCONNECTED42;
   wire UNCONNECTED43;
   wire UNCONNECTED44;
   wire UNCONNECTED45;
   wire UNCONNECTED46;
   wire UNCONNECTED47;
   wire UNCONNECTED48;
   wire UNCONNECTED49;
   wire UNCONNECTED50;
   wire UNCONNECTED51;
   wire UNCONNECTED52;
   wire UNCONNECTED53;
   wire UNCONNECTED54;
   wire UNCONNECTED55;
   wire UNCONNECTED56;
   wire UNCONNECTED57;
   wire UNCONNECTED58;
   wire UNCONNECTED59;
   wire UNCONNECTED60;
   wire UNCONNECTED61;
   wire UNCONNECTED62;
   wire UNCONNECTED63;
   wire UNCONNECTED64;
   wire UNCONNECTED65;
   wire UNCONNECTED66;
   wire UNCONNECTED67;
   wire UNCONNECTED68;
   wire UNCONNECTED69;
   wire UNCONNECTED70;
   wire UNCONNECTED71;
   wire UNCONNECTED72;
   wire bus_we_d1;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_89;
   wire n_90;
   wire n_91;
   wire sram_cen;
   wire sram_cen_ff;
   wire sram_wen;

   BUFFD8 FE_PDC542_tpu_dout_58 (.I(FE_PDN541_tpu_dout_58),
	.Z(tpu_dout[58]));
   BUFFD8 FE_PDC540_tpu_dout_54 (.I(FE_PDN539_tpu_dout_54),
	.Z(tpu_dout[54]));
   BUFFD1 FE_PHC538_bus_din_5 (.I(FE_PHN537_bus_din_5),
	.Z(FE_PHN538_bus_din_5));
   DEL005 FE_PHC537_bus_din_5 (.I(FE_PHN178_bus_din_5),
	.Z(FE_PHN537_bus_din_5));
   CKBD0 FE_PHC536_bus_din_5 (.I(FE_PHN536_bus_din_5),
	.Z(FE_PHN534_bus_din_5));
   CKBD0 FE_PHC535_bus_din_5 (.I(FE_PHN535_bus_din_5),
	.Z(FE_PHN533_bus_din_5));
   CKBD0 FE_PHC534_bus_din_5 (.I(FE_PHN534_bus_din_5),
	.Z(FE_PHN532_bus_din_5));
   CKBD0 FE_PHC533_bus_din_5 (.I(FE_PHN533_bus_din_5),
	.Z(FE_PHN531_bus_din_5));
   CKBD0 FE_PHC532_bus_din_5 (.I(FE_PHN532_bus_din_5),
	.Z(FE_PHN530_bus_din_5));
   CKBD0 FE_PHC531_bus_din_5 (.I(FE_PHN531_bus_din_5),
	.Z(FE_PHN529_bus_din_5));
   CKBD0 FE_PHC530_bus_din_5 (.I(FE_PHN530_bus_din_5),
	.Z(FE_PHN527_bus_din_5));
   CKBD0 FE_PHC529_bus_din_5 (.I(FE_PHN529_bus_din_5),
	.Z(FE_PHN528_bus_din_5));
   CKBD0 FE_PHC528_bus_din_5 (.I(FE_PHN528_bus_din_5),
	.Z(FE_PHN409_bus_din_5));
   CKBD0 FE_PHC527_bus_din_5 (.I(FE_PHN527_bus_din_5),
	.Z(FE_PHN513_bus_din_5));
   CKBD1 FE_PHC526_bus_din_3 (.I(FE_PHN445_bus_din_3),
	.Z(FE_PHN526_bus_din_3));
   DEL0 FE_PHC525_bus_din_5 (.I(FE_PHN516_bus_din_5),
	.Z(FE_PHN525_bus_din_5));
   CKBD0 FE_PHC524_bus_din_5 (.I(FE_PHN178_bus_din_5),
	.Z(FE_PHN524_bus_din_5));
   CKBD0 FE_PHC523_bus_din_3 (.I(FE_PHN523_bus_din_3),
	.Z(FE_PHN520_bus_din_3));
   DEL0 FE_PHC522_bus_din_5 (.I(FE_PHN516_bus_din_5),
	.Z(FE_PHN522_bus_din_5));
   CKBD0 FE_PHC521_bus_din_5 (.I(FE_PHN178_bus_din_5),
	.Z(FE_PHN521_bus_din_5));
   DEL005 FE_PHC520_bus_din_3 (.I(FE_PHN520_bus_din_3),
	.Z(FE_PHN472_bus_din_3));
   CKBD1 FE_PHC519_bus_din_1 (.I(FE_PHN512_bus_din_1),
	.Z(FE_PHN519_bus_din_1));
   DEL005 FE_PHC518_bus_din_3 (.I(FE_PHN501_bus_din_3),
	.Z(FE_PHN518_bus_din_3));
   BUFFD1 FE_PHC517_bus_din_0 (.I(FE_PHN509_bus_din_0),
	.Z(FE_PHN517_bus_din_0));
   DEL0 FE_PHC516_bus_din_5 (.I(FE_PHN524_bus_din_5),
	.Z(FE_PHN516_bus_din_5));
   DEL015 FE_PHC515_bus_din_4 (.I(FE_PHN515_bus_din_4),
	.Z(FE_PHN435_bus_din_4));
   CKBD1 FE_PHC514_bus_addr_2 (.I(bus_addr[2]),
	.Z(FE_PHN514_bus_addr_2));
   CKBD1 FE_PHC513_bus_din_5 (.I(FE_PHN513_bus_din_5),
	.Z(FE_PHN178_bus_din_5));
   DEL005 FE_PHC512_bus_din_1 (.I(FE_PHN490_bus_din_1),
	.Z(FE_PHN512_bus_din_1));
   BUFFD1 FE_PHC511_bus_din_2 (.I(FE_PHN471_bus_din_2),
	.Z(FE_PHN511_bus_din_2));
   DEL01 FE_PHC510_bus_din_7 (.I(FE_PHN433_bus_din_7),
	.Z(FE_PHN510_bus_din_7));
   DEL01 FE_PHC509_bus_din_0 (.I(FE_PHN454_bus_din_0),
	.Z(FE_PHN509_bus_din_0));
   BUFFD1 FE_PHC508_bus_din_0 (.I(FE_PHN507_bus_din_0),
	.Z(FE_PHN508_bus_din_0));
   CKBD0 FE_PHC507_bus_din_0 (.I(FE_PHN506_bus_din_0),
	.Z(FE_PHN507_bus_din_0));
   CKBD0 FE_PHC506_bus_din_0 (.I(FE_PHN473_bus_din_0),
	.Z(FE_PHN506_bus_din_0));
   CKBD1 FE_PHC505_bus_din_0 (.I(FE_PHN439_bus_din_0),
	.Z(FE_PHN505_bus_din_0));
   DEL005 FE_PHC504_bus_din_0 (.I(FE_PHN503_bus_din_0),
	.Z(FE_PHN504_bus_din_0));
   DEL005 FE_PHC503_bus_din_0 (.I(FE_PHN502_bus_din_0),
	.Z(FE_PHN503_bus_din_0));
   CKBD0 FE_PHC502_bus_din_0 (.I(FE_PHN504_bus_din_0),
	.Z(FE_PHN498_bus_din_0));
   CKBD0 FE_PHC501_bus_din_3 (.I(FE_PHN518_bus_din_3),
	.Z(FE_PHN499_bus_din_3));
   DEL005 FE_PHC500_bus_din_0 (.I(FE_PHN500_bus_din_0),
	.Z(FE_PHN502_bus_din_0));
   CKBD0 FE_PHC499_bus_din_3 (.I(FE_PHN499_bus_din_3),
	.Z(FE_PHN497_bus_din_3));
   CKBD0 FE_PHC498_bus_din_0 (.I(FE_PHN498_bus_din_0),
	.Z(FE_PHN495_bus_din_0));
   CKBD0 FE_PHC497_bus_din_3 (.I(FE_PHN497_bus_din_3),
	.Z(FE_PHN494_bus_din_3));
   CKBD1 FE_PHC496_bus_din_6 (.I(FE_PHN493_bus_din_6),
	.Z(FE_PHN496_bus_din_6));
   DEL005 FE_PHC495_bus_din_0 (.I(FE_PHN495_bus_din_0),
	.Z(FE_PHN488_bus_din_0));
   CKBD0 FE_PHC494_bus_din_3 (.I(FE_PHN494_bus_din_3),
	.Z(FE_PHN491_bus_din_3));
   DEL005 FE_PHC493_bus_din_6 (.I(FE_PHN460_bus_din_6),
	.Z(FE_PHN493_bus_din_6));
   DEL005 FE_PHC492_bus_din_0 (.I(FE_PHN492_bus_din_0),
	.Z(FE_PHN500_bus_din_0));
   CKBD0 FE_PHC491_bus_din_3 (.I(FE_PHN491_bus_din_3),
	.Z(FE_PHN487_bus_din_3));
   DEL005 FE_PHC490_bus_din_1 (.I(FE_PHN485_bus_din_1),
	.Z(FE_PHN490_bus_din_1));
   CKBD0 FE_PHC489_bus_din_6 (.I(FE_PHN489_bus_din_6),
	.Z(FE_PHN180_bus_din_6));
   CKBD0 FE_PHC488_bus_din_0 (.I(FE_PHN488_bus_din_0),
	.Z(FE_PHN483_bus_din_0));
   CKBD0 FE_PHC487_bus_din_3 (.I(FE_PHN487_bus_din_3),
	.Z(FE_PHN484_bus_din_3));
   CKBD0 FE_PHC486_bus_din_6 (.I(FE_PHN180_bus_din_6),
	.Z(FE_PHN486_bus_din_6));
   CKBD0 FE_PHC485_bus_din_1 (.I(FE_PHN519_bus_din_1),
	.Z(FE_PHN478_bus_din_1));
   CKBD0 FE_PHC484_bus_din_3 (.I(FE_PHN484_bus_din_3),
	.Z(FE_PHN479_bus_din_3));
   CKBD0 FE_PHC483_bus_din_0 (.I(FE_PHN465_bus_din_0),
	.Z(FE_PHN492_bus_din_0));
   DEL005 FE_PHC482_bus_din_1 (.I(FE_PHN482_bus_din_1),
	.Z(FE_PHN485_bus_din_1));
   CKBD0 FE_PHC481_bus_din_6 (.I(FE_PHN486_bus_din_6),
	.Z(FE_PHN481_bus_din_6));
   CKBD0 FE_PHC480_bus_din_0 (.I(FE_PHN432_bus_din_0),
	.Z(FE_PHN480_bus_din_0));
   CKBD0 FE_PHC479_bus_din_3 (.I(FE_PHN479_bus_din_3),
	.Z(FE_PHN523_bus_din_3));
   DEL005 FE_PHC478_bus_din_1 (.I(FE_PHN474_bus_din_1),
	.Z(FE_PHN482_bus_din_1));
   DEL005 FE_PHC477_bus_din_6 (.I(FE_PHN481_bus_din_6),
	.Z(FE_PHN477_bus_din_6));
   CKBD1 FE_PHC476_bus_din_4 (.I(FE_PHN476_bus_din_4),
	.Z(FE_PHN470_bus_din_4));
   CKBD0 FE_PHC475_bus_din_6 (.I(FE_PHN434_bus_din_6),
	.Z(FE_PHN475_bus_din_6));
   CKBD0 FE_PHC474_bus_din_1 (.I(FE_PHN478_bus_din_1),
	.Z(FE_PHN467_bus_din_1));
   DEL005 FE_PHC473_bus_din_0 (.I(FE_PHN432_bus_din_0),
	.Z(FE_PHN473_bus_din_0));
   CKBD0 FE_PHC472_bus_din_3 (.I(FE_PHN472_bus_din_3),
	.Z(FE_PHN468_bus_din_3));
   CKBD1 FE_PHC471_bus_din_2 (.I(bus_din[2]),
	.Z(FE_PHN471_bus_din_2));
   DEL01 FE_PHC470_bus_din_4 (.I(FE_PHN470_bus_din_4),
	.Z(FE_PHN464_bus_din_4));
   CKBD0 FE_PHC469_bus_din_6 (.I(FE_PHN475_bus_din_6),
	.Z(FE_PHN469_bus_din_6));
   DEL005 FE_PHC468_bus_din_3 (.I(FE_PHN468_bus_din_3),
	.Z(FE_PHN421_bus_din_3));
   DEL005 FE_PHC467_bus_din_1 (.I(FE_PHN461_bus_din_1),
	.Z(FE_PHN474_bus_din_1));
   DEL005 FE_PHC466_bus_din_2 (.I(FE_PHN466_bus_din_2),
	.Z(FE_PHN463_bus_din_2));
   CKBD0 FE_PHC465_bus_din_0 (.I(FE_PHN424_bus_din_0),
	.Z(FE_PHN465_bus_din_0));
   CKBD0 FE_PHC464_bus_din_4 (.I(FE_PHN464_bus_din_4),
	.Z(FE_PHN459_bus_din_4));
   DEL005 FE_PHC463_bus_din_2 (.I(FE_PHN447_bus_din_2),
	.Z(FE_PHN466_bus_din_2));
   CKBD0 FE_PHC462_bus_din_0 (.I(FE_PHN483_bus_din_0),
	.Z(FE_PHN462_bus_din_0));
   CKBD0 FE_PHC461_bus_din_1 (.I(FE_PHN429_bus_din_1),
	.Z(FE_PHN461_bus_din_1));
   DEL005 FE_PHC460_bus_din_6 (.I(FE_PHN434_bus_din_6),
	.Z(FE_PHN460_bus_din_6));
   DEL01 FE_PHC459_bus_din_4 (.I(FE_PHN459_bus_din_4),
	.Z(FE_PHN452_bus_din_4));
   CKBD1 FE_PHC458_bus_din_1 (.I(FE_PHN451_bus_din_1),
	.Z(FE_PHN458_bus_din_1));
   CKBD0 FE_PHC457_bus_din_6 (.I(FE_PHN469_bus_din_6),
	.Z(FE_PHN457_bus_din_6));
   DEL0 FE_PHC456_bus_din_3 (.I(FE_PHN174_bus_din_3),
	.Z(FE_PHN456_bus_din_3));
   DEL005 FE_PHC455_bus_din_1 (.I(FE_PHN412_bus_din_1),
	.Z(FE_PHN455_bus_din_1));
   CKBD0 FE_PHC454_bus_din_0 (.I(FE_PHN462_bus_din_0),
	.Z(FE_PHN454_bus_din_0));
   DEL015 FE_PHC453_bus_din_2 (.I(FE_PHN511_bus_din_2),
	.Z(FE_PHN453_bus_din_2));
   CKBD0 FE_PHC452_bus_din_4 (.I(FE_PHN452_bus_din_4),
	.Z(FE_PHN446_bus_din_4));
   CKBD1 FE_PHC451_bus_din_1 (.I(FE_PHN443_bus_din_1),
	.Z(FE_PHN451_bus_din_1));
   DEL01 FE_PHC450_bus_din_2 (.I(FE_PHN442_bus_din_2),
	.Z(FE_PHN450_bus_din_2));
   CKBD0 FE_PHC449_bus_din_0 (.I(FE_PHN517_bus_din_0),
	.Z(FE_PHN449_bus_din_0));
   CKBD0 FE_PHC448_bus_din_1 (.I(FE_PHN455_bus_din_1),
	.Z(FE_PHN448_bus_din_1));
   DEL005 FE_PHC447_bus_din_2 (.I(FE_PHN453_bus_din_2),
	.Z(FE_PHN447_bus_din_2));
   DEL015 FE_PHC446_bus_din_4 (.I(FE_PHN446_bus_din_4),
	.Z(FE_PHN515_bus_din_4));
   DEL015 FE_PHC445_bus_din_3 (.I(FE_PHN174_bus_din_3),
	.Z(FE_PHN445_bus_din_3));
   DEL0 FE_PHC444_bus_din_6 (.I(FE_PHN434_bus_din_6),
	.Z(FE_PHN444_bus_din_6));
   CKBD1 FE_PHC443_bus_din_1 (.I(FE_PHN425_bus_din_1),
	.Z(FE_PHN443_bus_din_1));
   CKBD1 FE_PHC442_bus_din_2 (.I(FE_PHN423_bus_din_2),
	.Z(FE_PHN442_bus_din_2));
   DEL0 FE_PHC441_bus_din_3 (.I(FE_PHN428_bus_din_3),
	.Z(FE_PHN441_bus_din_3));
   DEL0 FE_PHC440_bus_din_4 (.I(FE_PHN427_bus_din_4),
	.Z(FE_PHN440_bus_din_4));
   CKBD1 FE_PHC439_bus_din_0 (.I(FE_PHN480_bus_din_0),
	.Z(FE_PHN439_bus_din_0));
   DEL005 FE_PHC438_bus_din_1 (.I(FE_PHN412_bus_din_1),
	.Z(FE_PHN438_bus_din_1));
   DEL015 FE_PHC437_bus_din_3 (.I(FE_PHN174_bus_din_3),
	.Z(FE_PHN437_bus_din_3));
   CKBD0 FE_PHC436_bus_din_2 (.I(FE_PHN463_bus_din_2),
	.Z(FE_PHN436_bus_din_2));
   DEL015 FE_PHC435_bus_din_4 (.I(FE_PHN435_bus_din_4),
	.Z(FE_PHN422_bus_din_4));
   DEL01 FE_PHC434_bus_din_6 (.I(FE_PHN431_bus_din_6),
	.Z(FE_PHN434_bus_din_6));
   DEL0 FE_PHC433_bus_din_7 (.I(FE_PHN510_bus_din_7),
	.Z(FE_PHN420_bus_din_7));
   CKBD1 FE_PHC432_bus_din_0 (.I(FE_PHN449_bus_din_0),
	.Z(FE_PHN432_bus_din_0));
   DEL01 FE_PHC431_bus_din_6 (.I(FE_PHN411_bus_din_6),
	.Z(FE_PHN431_bus_din_6));
   DEL01 FE_PHC430_bus_din_2 (.I(FE_PHN436_bus_din_2),
	.Z(FE_PHN430_bus_din_2));
   CKBD1 FE_PHC429_bus_din_1 (.I(FE_PHN175_bus_din_1),
	.Z(FE_PHN429_bus_din_1));
   DEL0 FE_PHC428_bus_din_3 (.I(FE_PHN456_bus_din_3),
	.Z(FE_PHN428_bus_din_3));
   DEL0 FE_PHC427_bus_din_4 (.I(FE_PHN176_bus_din_4),
	.Z(FE_PHN427_bus_din_4));
   DEL0 FE_PHC426_bus_din_7 (.I(FE_PHN179_bus_din_7),
	.Z(FE_PHN426_bus_din_7));
   DEL005 FE_PHC425_bus_din_1 (.I(FE_PHN448_bus_din_1),
	.Z(FE_PHN425_bus_din_1));
   CKBD1 FE_PHC424_bus_din_0 (.I(FE_PHN177_bus_din_0),
	.Z(FE_PHN424_bus_din_0));
   DEL01 FE_PHC423_bus_din_2 (.I(FE_PHN173_bus_din_2),
	.Z(FE_PHN423_bus_din_2));
   CKBD1 FE_PHC422_bus_din_4 (.I(FE_PHN422_bus_din_4),
	.Z(FE_PHN176_bus_din_4));
   CKBD1 FE_PHC421_bus_din_3 (.I(FE_PHN421_bus_din_3),
	.Z(FE_PHN174_bus_din_3));
   DEL0 FE_PHC420_bus_din_7 (.I(FE_PHN420_bus_din_7),
	.Z(FE_PHN179_bus_din_7));
   CKBD1 FE_PHC419_bus_addr_7 (.I(bus_addr[7]),
	.Z(FE_PHN419_bus_addr_7));
   BUFFD1 FE_PHC418_FE_OFN4_sram_addr_7 (.I(FE_OFN4_sram_addr_7),
	.Z(FE_PHN418_FE_OFN4_sram_addr_7));
   BUFFD1 FE_PHC417_bus_addr_11 (.I(bus_addr[11]),
	.Z(FE_PHN417_bus_addr_11));
   CKBD1 FE_PHC416_bus_addr_9 (.I(bus_addr[9]),
	.Z(FE_PHN416_bus_addr_9));
   CKBD1 FE_PHC415_bus_addr_6 (.I(bus_addr[6]),
	.Z(FE_PHN415_bus_addr_6));
   CKBD1 FE_PHC414_bus_addr_10 (.I(FE_PHN183_bus_addr_10),
	.Z(FE_PHN414_bus_addr_10));
   CKBD0 FE_PHC413_bus_addr_2 (.I(bus_addr[2]),
	.Z(FE_PHN413_bus_addr_2));
   DEL0 FE_PHC412_bus_din_1 (.I(FE_PHN467_bus_din_1),
	.Z(FE_PHN412_bus_din_1));
   DEL0 FE_PHC411_bus_din_6 (.I(FE_PHN477_bus_din_6),
	.Z(FE_PHN411_bus_din_6));
   DEL0 FE_PHC410_bus_din_2 (.I(FE_PHN410_bus_din_2),
	.Z(FE_PHN173_bus_din_2));
   BUFFD2 FE_PHC409_bus_din_5 (.I(FE_PHN409_bus_din_5),
	.Z(FE_PHN536_bus_din_5));
   BUFFD1 FE_PHC408_bus_addr_8 (.I(bus_addr[8]),
	.Z(FE_PHN408_bus_addr_8));
   CKBD0 FE_PHC407_bus_addr_8 (.I(FE_PHN408_bus_addr_8),
	.Z(FE_PHN407_bus_addr_8));
   DEL005 FE_PHC406_bus_addr_8 (.I(FE_PHN407_bus_addr_8),
	.Z(FE_PHN406_bus_addr_8));
   CKBD0 FE_PHC405_bus_addr_8 (.I(FE_PHN406_bus_addr_8),
	.Z(FE_PHN405_bus_addr_8));
   CKBD0 FE_PHC404_bus_addr_8 (.I(FE_PHN405_bus_addr_8),
	.Z(FE_PHN404_bus_addr_8));
   DEL005 FE_PHC403_bus_addr_8 (.I(FE_PHN404_bus_addr_8),
	.Z(FE_PHN403_bus_addr_8));
   CKBD0 FE_PHC402_bus_addr_8 (.I(FE_PHN403_bus_addr_8),
	.Z(FE_PHN402_bus_addr_8));
   CKBD1 FE_PHC401_tpu_dout_3 (.I(FE_PHN398_tpu_dout_3),
	.Z(FE_PHN401_tpu_dout_3));
   BUFFD1 FE_PHC400_tpu_dout_1 (.I(FE_PHN378_tpu_dout_1),
	.Z(FE_PHN400_tpu_dout_1));
   DEL005 FE_PHC399_bus_addr_8 (.I(FE_PHN402_bus_addr_8),
	.Z(FE_PHN399_bus_addr_8));
   DEL005 FE_PHC398_tpu_dout_3 (.I(FE_PHN67_tpu_dout_3),
	.Z(FE_PHN398_tpu_dout_3));
   DEL005 FE_PHC397_tpu_dout_1 (.I(FE_PHN400_tpu_dout_1),
	.Z(FE_PHN397_tpu_dout_1));
   CKBD0 FE_PHC396_bus_addr_9 (.I(FE_PHN416_bus_addr_9),
	.Z(FE_PHN396_bus_addr_9));
   CKBD0 FE_PHC395_bus_addr_8 (.I(FE_PHN399_bus_addr_8),
	.Z(FE_PHN395_bus_addr_8));
   CKBD1 FE_PHC394_tpu_dout_0 (.I(FE_PHN141_tpu_dout_0),
	.Z(FE_PHN394_tpu_dout_0));
   CKBD0 FE_PHC393_tpu_dout_3 (.I(FE_PHN401_tpu_dout_3),
	.Z(FE_PHN393_tpu_dout_3));
   CKBD0 FE_PHC392_tpu_dout_1 (.I(FE_PHN397_tpu_dout_1),
	.Z(FE_PHN392_tpu_dout_1));
   DEL015 FE_PHC391_bus_addr_9 (.I(FE_PHN396_bus_addr_9),
	.Z(FE_PHN391_bus_addr_9));
   DEL005 FE_PHC390_bus_addr_8 (.I(FE_PHN395_bus_addr_8),
	.Z(FE_PHN390_bus_addr_8));
   DEL005 FE_PHC389_tpu_dout_1 (.I(FE_PHN392_tpu_dout_1),
	.Z(FE_PHN389_tpu_dout_1));
   CKBD0 FE_PHC388_tpu_dout_3 (.I(FE_PHN393_tpu_dout_3),
	.Z(FE_PHN388_tpu_dout_3));
   DEL01 FE_PHC387_bus_addr_9 (.I(FE_PHN391_bus_addr_9),
	.Z(FE_PHN387_bus_addr_9));
   CKBD0 FE_PHC386_tpu_dout_0 (.I(FE_PHN394_tpu_dout_0),
	.Z(FE_PHN386_tpu_dout_0));
   CKBD0 FE_PHC385_bus_addr_8 (.I(FE_PHN390_bus_addr_8),
	.Z(FE_PHN385_bus_addr_8));
   DEL005 FE_PHC384_bus_addr_9 (.I(FE_PHN387_bus_addr_9),
	.Z(FE_PHN384_bus_addr_9));
   CKBD0 FE_PHC383_tpu_dout_1 (.I(FE_PHN389_tpu_dout_1),
	.Z(FE_PHN383_tpu_dout_1));
   DEL005 FE_PHC382_tpu_dout_3 (.I(FE_PHN388_tpu_dout_3),
	.Z(FE_PHN382_tpu_dout_3));
   DEL005 FE_PHC381_tpu_dout_0 (.I(FE_PHN386_tpu_dout_0),
	.Z(FE_PHN381_tpu_dout_0));
   DEL005 FE_PHC380_bus_addr_8 (.I(FE_PHN385_bus_addr_8),
	.Z(FE_PHN380_bus_addr_8));
   DEL005 FE_PHC379_bus_addr_9 (.I(FE_PHN384_bus_addr_9),
	.Z(FE_PHN379_bus_addr_9));
   BUFFD4 FE_PHC378_tpu_dout_1 (.I(FE_PHN373_tpu_dout_1),
	.Z(FE_PHN378_tpu_dout_1));
   CKBD0 FE_PHC377_tpu_dout_3 (.I(FE_PHN382_tpu_dout_3),
	.Z(FE_PHN377_tpu_dout_3));
   CKBD0 FE_PHC376_tpu_dout_0 (.I(FE_PHN381_tpu_dout_0),
	.Z(FE_PHN376_tpu_dout_0));
   CKBD0 FE_PHC375_bus_addr_9 (.I(FE_PHN379_bus_addr_9),
	.Z(FE_PHN375_bus_addr_9));
   CKBD0 FE_PHC374_bus_addr_8 (.I(FE_PHN380_bus_addr_8),
	.Z(FE_PHN374_bus_addr_8));
   DEL005 FE_PHC373_tpu_dout_1 (.I(FE_PHN99_tpu_dout_1),
	.Z(FE_PHN373_tpu_dout_1));
   DEL005 FE_PHC372_tpu_dout_3 (.I(FE_PHN365_tpu_dout_3),
	.Z(FE_PHN372_tpu_dout_3));
   DEL005 FE_PHC371_tpu_dout_0 (.I(FE_PHN376_tpu_dout_0),
	.Z(FE_PHN371_tpu_dout_0));
   CKBD1 FE_PHC370_bus_addr_3 (.I(bus_addr[3]),
	.Z(FE_PHN370_bus_addr_3));
   BUFFD1 FE_PHC369_bus_addr_11 (.I(FE_PHN417_bus_addr_11),
	.Z(FE_PHN369_bus_addr_11));
   DEL005 FE_PHC368_bus_addr_8 (.I(FE_PHN374_bus_addr_8),
	.Z(FE_PHN368_bus_addr_8));
   DEL005 FE_PHC367_bus_addr_9 (.I(FE_PHN375_bus_addr_9),
	.Z(FE_PHN367_bus_addr_9));
   CKBD0 FE_PHC366_tpu_dout_1 (.I(FE_PHN383_tpu_dout_1),
	.Z(FE_PHN366_tpu_dout_1));
   DEL005 FE_PHC365_tpu_dout_3 (.I(FE_PHN359_tpu_dout_3),
	.Z(FE_PHN365_tpu_dout_3));
   CKBD0 FE_PHC364_tpu_dout_0 (.I(FE_PHN371_tpu_dout_0),
	.Z(FE_PHN364_tpu_dout_0));
   CKBD0 FE_PHC363_bus_addr_3 (.I(FE_PHN370_bus_addr_3),
	.Z(FE_PHN363_bus_addr_3));
   DEL015 FE_PHC362_bus_addr_11 (.I(FE_PHN369_bus_addr_11),
	.Z(FE_PHN362_bus_addr_11));
   CKBD0 FE_PHC361_bus_addr_9 (.I(FE_PHN367_bus_addr_9),
	.Z(FE_PHN361_bus_addr_9));
   CKBD0 FE_PHC360_bus_addr_8 (.I(FE_PHN368_bus_addr_8),
	.Z(FE_PHN360_bus_addr_8));
   DEL005 FE_PHC359_tpu_dout_3 (.I(FE_PHN377_tpu_dout_3),
	.Z(FE_PHN359_tpu_dout_3));
   DEL005 FE_PHC358_tpu_dout_1 (.I(FE_PHN366_tpu_dout_1),
	.Z(FE_PHN358_tpu_dout_1));
   CKBD0 FE_PHC357_tpu_dout_0 (.I(FE_PHN364_tpu_dout_0),
	.Z(FE_PHN357_tpu_dout_0));
   CKBD0 FE_PHC356_bus_addr_3 (.I(FE_PHN363_bus_addr_3),
	.Z(FE_PHN356_bus_addr_3));
   DEL015 FE_PHC355_bus_addr_11 (.I(FE_PHN362_bus_addr_11),
	.Z(FE_PHN355_bus_addr_11));
   DEL005 FE_PHC354_bus_addr_9 (.I(FE_PHN361_bus_addr_9),
	.Z(FE_PHN354_bus_addr_9));
   DEL005 FE_PHC353_bus_addr_8 (.I(FE_PHN360_bus_addr_8),
	.Z(FE_PHN353_bus_addr_8));
   CKBD0 FE_PHC352_tpu_dout_3 (.I(FE_PHN372_tpu_dout_3),
	.Z(FE_PHN352_tpu_dout_3));
   CKBD0 FE_PHC351_tpu_dout_1 (.I(FE_PHN358_tpu_dout_1),
	.Z(FE_PHN351_tpu_dout_1));
   DEL015 FE_PHC350_bus_addr_11 (.I(FE_PHN355_bus_addr_11),
	.Z(FE_PHN350_bus_addr_11));
   DEL01 FE_PHC349_bus_addr_7 (.I(FE_PHN419_bus_addr_7),
	.Z(FE_PHN349_bus_addr_7));
   DEL0 FE_PHC348_bus_wbuf_0 (.I(FE_PHN304_bus_wbuf_0),
	.Z(FE_PHN348_bus_wbuf_0));
   DEL0 FE_PHC347_FE_OFN10_sram_addr_1 (.I(FE_PHN336_FE_OFN10_sram_addr_1),
	.Z(FE_PHN347_FE_OFN10_sram_addr_1));
   DEL01 FE_PHC346_bus_addr_11 (.I(FE_PHN350_bus_addr_11),
	.Z(FE_PHN346_bus_addr_11));
   DEL01 FE_PHC345_tpu_dout_0 (.I(FE_PHN357_tpu_dout_0),
	.Z(FE_PHN345_tpu_dout_0));
   DEL01 FE_PHC344_bus_addr_7 (.I(FE_PHN349_bus_addr_7),
	.Z(FE_PHN344_bus_addr_7));
   DEL01 FE_PHC343_bus_wbuf_0 (.I(FE_PHN324_bus_wbuf_0),
	.Z(FE_PHN343_bus_wbuf_0));
   DEL01 FE_PHC342_bus_addr_3 (.I(FE_PHN356_bus_addr_3),
	.Z(FE_PHN342_bus_addr_3));
   DEL005 FE_PHC341_bus_addr_6 (.I(FE_PHN322_bus_addr_6),
	.Z(FE_PHN341_bus_addr_6));
   DEL01 FE_PHC340_bus_addr_5 (.I(bus_addr[5]),
	.Z(FE_PHN340_bus_addr_5));
   DEL01 FE_PHC339_bus_addr_4 (.I(bus_addr[4]),
	.Z(FE_PHN339_bus_addr_4));
   CKBD0 FE_PHC338_tpu_addr_7 (.I(tpu_addr[7]),
	.Z(FE_PHN338_tpu_addr_7));
   CKBD0 FE_PHC337_bus_addr_10 (.I(bus_addr[10]),
	.Z(FE_PHN337_bus_addr_10));
   DEL0 FE_PHC336_FE_OFN10_sram_addr_1 (.I(FE_PHN309_FE_OFN10_sram_addr_1),
	.Z(FE_PHN336_FE_OFN10_sram_addr_1));
   DEL0 FE_PHC335_tpu_dout_31 (.I(FE_PHN332_tpu_dout_31),
	.Z(FE_PHN335_tpu_dout_31));
   DEL1 FE_PHC334_FE_OFN11_sram_addr_0 (.I(FE_PHN308_FE_OFN11_sram_addr_0),
	.Z(FE_PHN334_FE_OFN11_sram_addr_0));
   CKBD12 FE_PHC333_tpu_dout_31 (.I(FE_PHN335_tpu_dout_31),
	.Z(tpu_dout[31]));
   CKBD1 FE_PHC331_tpu_dout_12 (.I(FE_PHN149_tpu_dout_12),
	.Z(FE_PHN331_tpu_dout_12));
   BUFFD1 FE_PHC330_tpu_dout_18 (.I(FE_PHN167_tpu_dout_18),
	.Z(FE_PHN330_tpu_dout_18));
   BUFFD1 FE_PHC329_tpu_dout_19 (.I(FE_PHN145_tpu_dout_19),
	.Z(FE_PHN329_tpu_dout_19));
   CKBD1 FE_PHC328_tpu_dout_2 (.I(FE_PHN97_tpu_dout_2),
	.Z(FE_PHN328_tpu_dout_2));
   CKBD1 FE_PHC327_tpu_dout_17 (.I(FE_PHN147_tpu_dout_17),
	.Z(FE_PHN327_tpu_dout_17));
   CKBD1 FE_PHC326_tpu_dout_5 (.I(FE_PHN115_tpu_dout_5),
	.Z(FE_PHN326_tpu_dout_5));
   CKBD1 FE_PHC325_tpu_dout_8 (.I(FE_PHN129_tpu_dout_8),
	.Z(FE_PHN325_tpu_dout_8));
   DEL015 FE_PHC324_bus_wbuf_0 (.I(FE_PHN348_bus_wbuf_0),
	.Z(FE_PHN324_bus_wbuf_0));
   DEL01 FE_PHC323_tpu_re (.I(FE_PHN15_tpu_re),
	.Z(FE_PHN323_tpu_re));
   DEL015 FE_PHC322_bus_addr_6 (.I(FE_PHN415_bus_addr_6),
	.Z(FE_PHN322_bus_addr_6));
   DEL015 FE_PHC321_tpu_addr_7 (.I(FE_PHN338_tpu_addr_7),
	.Z(FE_PHN321_tpu_addr_7));
   DEL015 FE_PHC320_bus_addr_5 (.I(FE_PHN340_bus_addr_5),
	.Z(FE_PHN320_bus_addr_5));
   DEL015 FE_PHC319_bus_addr_4 (.I(FE_PHN339_bus_addr_4),
	.Z(FE_PHN319_bus_addr_4));
   DEL015 FE_PHC318_bus_addr_10 (.I(FE_PHN337_bus_addr_10),
	.Z(FE_PHN318_bus_addr_10));
   DEL0 FE_PHC317_tpu_dout_23 (.I(FE_PHN139_tpu_dout_23),
	.Z(FE_PHN317_tpu_dout_23));
   DEL0 FE_PHC316_tpu_dout_21 (.I(FE_PHN125_tpu_dout_21),
	.Z(FE_PHN316_tpu_dout_21));
   DEL0 FE_PHC315_tpu_dout_20 (.I(FE_PHN123_tpu_dout_20),
	.Z(FE_PHN315_tpu_dout_20));
   DEL0 FE_PHC314_FE_OFN9_sram_addr_2 (.I(FE_PHN234_FE_OFN9_sram_addr_2),
	.Z(FE_PHN314_FE_OFN9_sram_addr_2));
   DEL0 FE_PHC313_FE_OFN8_sram_addr_3 (.I(FE_PHN233_FE_OFN8_sram_addr_3),
	.Z(FE_PHN313_FE_OFN8_sram_addr_3));
   DEL0 FE_PHC312_FE_OFN7_sram_addr_4 (.I(FE_PHN187_FE_OFN7_sram_addr_4),
	.Z(FE_PHN312_FE_OFN7_sram_addr_4));
   DEL0 FE_PHC311_FE_OFN6_sram_addr_5 (.I(FE_PHN231_FE_OFN6_sram_addr_5),
	.Z(FE_PHN311_FE_OFN6_sram_addr_5));
   DEL0 FE_PHC310_FE_OFN5_sram_addr_6 (.I(FE_PHN232_FE_OFN5_sram_addr_6),
	.Z(FE_PHN310_FE_OFN5_sram_addr_6));
   DEL0 FE_PHC309_FE_OFN10_sram_addr_1 (.I(FE_OFN10_sram_addr_1),
	.Z(FE_PHN309_FE_OFN10_sram_addr_1));
   DEL0 FE_PHC308_FE_OFN11_sram_addr_0 (.I(FE_OFN11_sram_addr_0),
	.Z(FE_PHN308_FE_OFN11_sram_addr_0));
   BUFFD1 FE_PHC307_n_8 (.I(n_8),
	.Z(FE_PHN307_n_8));
   BUFFD1 FE_PHC306_bus_din_1 (.I(bus_din[1]),
	.Z(FE_PHN306_bus_din_1));
   BUFFD1 FE_PHC305_bus_din_0 (.I(bus_din[0]),
	.Z(FE_PHN305_bus_din_0));
   DEL0 FE_PHC304_bus_wbuf_0 (.I(bus_wbuf[0]),
	.Z(FE_PHN304_bus_wbuf_0));
   CKBD1 FE_PHC303_bus_din_6 (.I(bus_din[6]),
	.Z(FE_PHN303_bus_din_6));
   BUFFD1 FE_PHC302_bus_din_2 (.I(FE_PHN430_bus_din_2),
	.Z(FE_PHN302_bus_din_2));
   CKBD1 FE_PHC301_bus_din_3 (.I(bus_din[3]),
	.Z(FE_PHN301_bus_din_3));
   CKBD1 FE_PHC300_bus_din_4 (.I(bus_din[4]),
	.Z(FE_PHN300_bus_din_4));
   CKBD1 FE_PHC299_bus_din_5 (.I(bus_din[5]),
	.Z(FE_PHN299_bus_din_5));
   CKBD1 FE_PHC298_bus_din_7 (.I(bus_din[7]),
	.Z(FE_PHN298_bus_din_7));
   DEL0 FE_PHC297_tpu_addr_8 (.I(tpu_addr[8]),
	.Z(FE_PHN297_tpu_addr_8));
   DEL0 FE_PHC296_tpu_dout_19 (.I(FE_PHN329_tpu_dout_19),
	.Z(FE_PHN296_tpu_dout_19));
   DEL0 FE_PHC295_tpu_dout_18 (.I(FE_PHN330_tpu_dout_18),
	.Z(FE_PHN295_tpu_dout_18));
   DEL0 FE_PHC294_tpu_dout_13 (.I(FE_PHN113_tpu_dout_13),
	.Z(FE_PHN294_tpu_dout_13));
   DEL0 FE_PHC293_tpu_dout_7 (.I(FE_PHN131_tpu_dout_7),
	.Z(FE_PHN293_tpu_dout_7));
   DEL0 FE_PHC292_tpu_dout_11 (.I(FE_PHN169_tpu_dout_11),
	.Z(FE_PHN292_tpu_dout_11));
   DEL0 FE_PHC291_tpu_dout_6 (.I(FE_PHN155_tpu_dout_6),
	.Z(FE_PHN291_tpu_dout_6));
   DEL0 FE_PHC290_tpu_dout_4 (.I(FE_PHN61_tpu_dout_4),
	.Z(FE_PHN290_tpu_dout_4));
   DEL0 FE_PHC289_tpu_dout_9 (.I(FE_PHN143_tpu_dout_9),
	.Z(FE_PHN289_tpu_dout_9));
   DEL0 FE_PHC288_tpu_dout_2 (.I(FE_PHN328_tpu_dout_2),
	.Z(FE_PHN288_tpu_dout_2));
   DEL0 FE_PHC287_tpu_dout_10 (.I(FE_PHN83_tpu_dout_10),
	.Z(FE_PHN287_tpu_dout_10));
   DEL0 FE_PHC286_tpu_dout_8 (.I(FE_PHN325_tpu_dout_8),
	.Z(FE_PHN286_tpu_dout_8));
   DEL0 FE_PHC285_tpu_dout_14 (.I(FE_PHN95_tpu_dout_14),
	.Z(FE_PHN285_tpu_dout_14));
   DEL0 FE_PHC284_tpu_dout_5 (.I(FE_PHN326_tpu_dout_5),
	.Z(FE_PHN284_tpu_dout_5));
   DEL0 FE_PHC283_tpu_dout_17 (.I(FE_PHN327_tpu_dout_17),
	.Z(FE_PHN283_tpu_dout_17));
   DEL1 FE_PHC282_tpu_dout_52 (.I(FE_PHN91_tpu_dout_52),
	.Z(FE_PHN282_tpu_dout_52));
   DEL1 FE_PHC281_tpu_dout_60 (.I(FE_PHN93_tpu_dout_60),
	.Z(FE_PHN281_tpu_dout_60));
   DEL1 FE_PHC280_tpu_dout_56 (.I(FE_PHN111_tpu_dout_56),
	.Z(FE_PHN280_tpu_dout_56));
   DEL1 FE_PHC279_tpu_dout_55 (.I(FE_PHN77_tpu_dout_55),
	.Z(FE_PHN279_tpu_dout_55));
   DEL0 FE_PHC278_tpu_dout_12 (.I(FE_PHN331_tpu_dout_12),
	.Z(FE_PHN278_tpu_dout_12));
   DEL1 FE_PHC277_tpu_dout_54 (.I(FE_PHN59_tpu_dout_54),
	.Z(FE_PHN277_tpu_dout_54));
   DEL1 FE_PHC276_tpu_dout_58 (.I(FE_PHN79_tpu_dout_58),
	.Z(FE_PHN276_tpu_dout_58));
   DEL1 FE_PHC275_tpu_dout_57 (.I(FE_PHN55_tpu_dout_57),
	.Z(FE_PHN275_tpu_dout_57));
   DEL1 FE_PHC274_tpu_dout_59 (.I(FE_PHN109_tpu_dout_59),
	.Z(FE_PHN274_tpu_dout_59));
   DEL1 FE_PHC273_tpu_dout_50 (.I(FE_PHN49_tpu_dout_50),
	.Z(FE_PHN273_tpu_dout_50));
   DEL1 FE_PHC272_tpu_dout_51 (.I(FE_PHN51_tpu_dout_51),
	.Z(FE_PHN272_tpu_dout_51));
   DEL1 FE_PHC271_tpu_dout_53 (.I(FE_PHN53_tpu_dout_53),
	.Z(FE_PHN271_tpu_dout_53));
   DEL1 FE_PHC270_tpu_dout_62 (.I(FE_PHN81_tpu_dout_62),
	.Z(FE_PHN270_tpu_dout_62));
   DEL1 FE_PHC269_tpu_dout_47 (.I(FE_PHN107_tpu_dout_47),
	.Z(FE_PHN269_tpu_dout_47));
   DEL1 FE_PHC268_tpu_dout_48 (.I(FE_PHN47_tpu_dout_48),
	.Z(FE_PHN268_tpu_dout_48));
   DEL1 FE_PHC267_tpu_dout_49 (.I(FE_PHN63_tpu_dout_49),
	.Z(FE_PHN267_tpu_dout_49));
   DEL1 FE_PHC266_tpu_dout_61 (.I(FE_PHN57_tpu_dout_61),
	.Z(FE_PHN266_tpu_dout_61));
   DEL1 FE_PHC265_tpu_dout_44 (.I(FE_PHN75_tpu_dout_44),
	.Z(FE_PHN265_tpu_dout_44));
   DEL1 FE_PHC264_tpu_dout_63 (.I(FE_PHN65_tpu_dout_63),
	.Z(FE_PHN264_tpu_dout_63));
   DEL1 FE_PHC263_tpu_dout_40 (.I(FE_PHN105_tpu_dout_40),
	.Z(FE_PHN263_tpu_dout_40));
   DEL1 FE_PHC262_tpu_dout_46 (.I(FE_PHN73_tpu_dout_46),
	.Z(FE_PHN262_tpu_dout_46));
   DEL1 FE_PHC261_tpu_dout_43 (.I(FE_PHN45_tpu_dout_43),
	.Z(FE_PHN261_tpu_dout_43));
   DEL1 FE_PHC260_tpu_dout_39 (.I(FE_PHN71_tpu_dout_39),
	.Z(FE_PHN260_tpu_dout_39));
   DEL1 FE_PHC259_tpu_dout_45 (.I(FE_PHN119_tpu_dout_45),
	.Z(FE_PHN259_tpu_dout_45));
   DEL1 FE_PHC258_tpu_dout_41 (.I(FE_PHN69_tpu_dout_41),
	.Z(FE_PHN258_tpu_dout_41));
   DEL1 FE_PHC257_tpu_dout_38 (.I(FE_PHN103_tpu_dout_38),
	.Z(FE_PHN257_tpu_dout_38));
   DEL1 FE_PHC256_tpu_dout_37 (.I(FE_PHN89_tpu_dout_37),
	.Z(FE_PHN256_tpu_dout_37));
   DEL1 FE_PHC255_tpu_dout_36 (.I(FE_PHN117_tpu_dout_36),
	.Z(FE_PHN255_tpu_dout_36));
   DEL1 FE_PHC254_tpu_dout_32 (.I(FE_PHN87_tpu_dout_32),
	.Z(FE_PHN254_tpu_dout_32));
   DEL1 FE_PHC253_tpu_dout_34 (.I(FE_PHN101_tpu_dout_34),
	.Z(FE_PHN253_tpu_dout_34));
   DEL1 FE_PHC252_tpu_dout_35 (.I(FE_PHN85_tpu_dout_35),
	.Z(FE_PHN252_tpu_dout_35));
   DEL1 FE_PHC251_tpu_dout_33 (.I(FE_PHN133_tpu_dout_33),
	.Z(FE_PHN251_tpu_dout_33));
   DEL1 FE_PHC250_tpu_dout_27 (.I(FE_PHN171_tpu_dout_27),
	.Z(FE_PHN250_tpu_dout_27));
   DEL1 FE_PHC249_tpu_dout_24 (.I(FE_PHN163_tpu_dout_24),
	.Z(FE_PHN249_tpu_dout_24));
   DEL1 FE_PHC248_tpu_dout_22 (.I(FE_PHN165_tpu_dout_22),
	.Z(FE_PHN248_tpu_dout_22));
   DEL1 FE_PHC247_tpu_dout_25 (.I(FE_PHN153_tpu_dout_25),
	.Z(FE_PHN247_tpu_dout_25));
   DEL1 FE_PHC246_tpu_dout_26 (.I(FE_PHN137_tpu_dout_26),
	.Z(FE_PHN246_tpu_dout_26));
   DEL1 FE_PHC245_tpu_dout_28 (.I(FE_PHN157_tpu_dout_28),
	.Z(FE_PHN245_tpu_dout_28));
   DEL1 FE_PHC244_tpu_dout_29 (.I(FE_PHN135_tpu_dout_29),
	.Z(FE_PHN244_tpu_dout_29));
   DEL1 FE_PHC243_tpu_dout_30 (.I(FE_PHN161_tpu_dout_30),
	.Z(FE_PHN243_tpu_dout_30));
   DEL0 FE_PHC242_bus_addr_11 (.I(FE_PHN346_bus_addr_11),
	.Z(FE_PHN242_bus_addr_11));
   DEL0 FE_PHC241_bus_addr_8 (.I(FE_PHN353_bus_addr_8),
	.Z(FE_PHN241_bus_addr_8));
   DEL0 FE_PHC240_bus_addr_9 (.I(FE_PHN354_bus_addr_9),
	.Z(FE_PHN240_bus_addr_9));
   DEL0 FE_PHC239_tpu_re (.I(FE_PHN323_tpu_re),
	.Z(FE_PHN239_tpu_re));
   DEL0 FE_PHC238_tpu_dout_42 (.I(FE_PHN121_tpu_dout_42),
	.Z(FE_PHN238_tpu_dout_42));
   DEL0 FE_PHC237_tpu_dout_16 (.I(FE_PHN159_tpu_dout_16),
	.Z(FE_PHN237_tpu_dout_16));
   DEL0 FE_PHC236_tpu_dout_15 (.I(FE_PHN127_tpu_dout_15),
	.Z(FE_PHN236_tpu_dout_15));
   DEL0 FE_PHC235_bus_addr_1 (.I(FE_PHN12_bus_addr_1),
	.Z(FE_PHN235_bus_addr_1));
   DEL1 FE_PHC234_FE_OFN9_sram_addr_2 (.I(FE_OFN9_sram_addr_2),
	.Z(FE_PHN234_FE_OFN9_sram_addr_2));
   DEL1 FE_PHC233_FE_OFN8_sram_addr_3 (.I(FE_OFN8_sram_addr_3),
	.Z(FE_PHN233_FE_OFN8_sram_addr_3));
   DEL1 FE_PHC232_FE_OFN5_sram_addr_6 (.I(FE_OFN5_sram_addr_6),
	.Z(FE_PHN232_FE_OFN5_sram_addr_6));
   DEL1 FE_PHC231_FE_OFN6_sram_addr_5 (.I(FE_OFN6_sram_addr_5),
	.Z(FE_PHN231_FE_OFN6_sram_addr_5));
   DEL2 FE_PHC230_bus_wbuf_57 (.I(bus_wbuf[57]),
	.Z(FE_PHN230_bus_wbuf_57));
   DEL2 FE_PHC229_bus_wbuf_58 (.I(bus_wbuf[58]),
	.Z(FE_PHN229_bus_wbuf_58));
   DEL2 FE_PHC228_bus_wbuf_59 (.I(bus_wbuf[59]),
	.Z(FE_PHN228_bus_wbuf_59));
   DEL2 FE_PHC227_bus_wbuf_61 (.I(bus_wbuf[61]),
	.Z(FE_PHN227_bus_wbuf_61));
   DEL2 FE_PHC226_bus_wbuf_60 (.I(bus_wbuf[60]),
	.Z(FE_PHN226_bus_wbuf_60));
   DEL2 FE_PHC225_bus_wbuf_63 (.I(bus_wbuf[63]),
	.Z(FE_PHN225_bus_wbuf_63));
   DEL2 FE_PHC224_bus_wbuf_56 (.I(bus_wbuf[56]),
	.Z(FE_PHN224_bus_wbuf_56));
   DEL2 FE_PHC223_bus_wbuf_62 (.I(bus_wbuf[62]),
	.Z(FE_PHN223_bus_wbuf_62));
   DEL2 FE_PHC222_bus_wbuf_47 (.I(bus_wbuf[47]),
	.Z(FE_PHN222_bus_wbuf_47));
   DEL2 FE_PHC221_bus_wbuf_46 (.I(bus_wbuf[46]),
	.Z(FE_PHN221_bus_wbuf_46));
   DEL2 FE_PHC220_bus_wbuf_43 (.I(bus_wbuf[43]),
	.Z(FE_PHN220_bus_wbuf_43));
   DEL2 FE_PHC219_bus_wbuf_41 (.I(bus_wbuf[41]),
	.Z(FE_PHN219_bus_wbuf_41));
   DEL2 FE_PHC218_bus_wbuf_45 (.I(bus_wbuf[45]),
	.Z(FE_PHN218_bus_wbuf_45));
   DEL2 FE_PHC217_bus_wbuf_32 (.I(bus_wbuf[32]),
	.Z(FE_PHN217_bus_wbuf_32));
   DEL2 FE_PHC216_bus_wbuf_44 (.I(bus_wbuf[44]),
	.Z(FE_PHN216_bus_wbuf_44));
   DEL2 FE_PHC215_bus_wbuf_42 (.I(bus_wbuf[42]),
	.Z(FE_PHN215_bus_wbuf_42));
   DEL2 FE_PHC214_bus_wbuf_38 (.I(bus_wbuf[38]),
	.Z(FE_PHN214_bus_wbuf_38));
   DEL2 FE_PHC213_bus_wbuf_37 (.I(bus_wbuf[37]),
	.Z(FE_PHN213_bus_wbuf_37));
   DEL2 FE_PHC212_bus_wbuf_40 (.I(bus_wbuf[40]),
	.Z(FE_PHN212_bus_wbuf_40));
   DEL2 FE_PHC211_bus_wbuf_39 (.I(bus_wbuf[39]),
	.Z(FE_PHN211_bus_wbuf_39));
   DEL2 FE_PHC210_bus_wbuf_36 (.I(bus_wbuf[36]),
	.Z(FE_PHN210_bus_wbuf_36));
   DEL2 FE_PHC209_bus_wbuf_35 (.I(bus_wbuf[35]),
	.Z(FE_PHN209_bus_wbuf_35));
   DEL2 FE_PHC208_bus_wbuf_34 (.I(bus_wbuf[34]),
	.Z(FE_PHN208_bus_wbuf_34));
   DEL2 FE_PHC207_bus_wbuf_33 (.I(bus_wbuf[33]),
	.Z(FE_PHN207_bus_wbuf_33));
   DEL1 FE_PHC206_FE_OFN4_sram_addr_7 (.I(FE_PHN418_FE_OFN4_sram_addr_7),
	.Z(FE_PHN206_FE_OFN4_sram_addr_7));
   DEL2 FE_PHC205_bus_wbuf_18 (.I(bus_wbuf[18]),
	.Z(FE_PHN205_bus_wbuf_18));
   DEL2 FE_PHC204_bus_wbuf_17 (.I(bus_wbuf[17]),
	.Z(FE_PHN204_bus_wbuf_17));
   DEL2 FE_PHC203_bus_wbuf_27 (.I(bus_wbuf[27]),
	.Z(FE_PHN203_bus_wbuf_27));
   DEL2 FE_PHC202_bus_wbuf_22 (.I(bus_wbuf[22]),
	.Z(FE_PHN202_bus_wbuf_22));
   DEL2 FE_PHC201_bus_wbuf_21 (.I(bus_wbuf[21]),
	.Z(FE_PHN201_bus_wbuf_21));
   DEL2 FE_PHC200_bus_wbuf_20 (.I(bus_wbuf[20]),
	.Z(FE_PHN200_bus_wbuf_20));
   DEL2 FE_PHC199_bus_wbuf_16 (.I(bus_wbuf[16]),
	.Z(FE_PHN199_bus_wbuf_16));
   DEL2 FE_PHC198_bus_wbuf_26 (.I(bus_wbuf[26]),
	.Z(FE_PHN198_bus_wbuf_26));
   DEL2 FE_PHC197_bus_wbuf_25 (.I(bus_wbuf[25]),
	.Z(FE_PHN197_bus_wbuf_25));
   DEL2 FE_PHC196_bus_wbuf_23 (.I(bus_wbuf[23]),
	.Z(FE_PHN196_bus_wbuf_23));
   DEL2 FE_PHC195_bus_wbuf_29 (.I(bus_wbuf[29]),
	.Z(FE_PHN195_bus_wbuf_29));
   DEL2 FE_PHC194_bus_wbuf_28 (.I(bus_wbuf[28]),
	.Z(FE_PHN194_bus_wbuf_28));
   DEL2 FE_PHC193_bus_wbuf_19 (.I(bus_wbuf[19]),
	.Z(FE_PHN193_bus_wbuf_19));
   DEL2 FE_PHC192_bus_wbuf_31 (.I(bus_wbuf[31]),
	.Z(FE_PHN192_bus_wbuf_31));
   DEL2 FE_PHC191_bus_wbuf_30 (.I(bus_wbuf[30]),
	.Z(FE_PHN191_bus_wbuf_30));
   DEL2 FE_PHC190_bus_wbuf_24 (.I(bus_wbuf[24]),
	.Z(FE_PHN190_bus_wbuf_24));
   DEL2 FE_PHC189_n_91 (.I(n_91),
	.Z(FE_PHN189_n_91));
   DEL2 FE_PHC188_n_4 (.I(n_4),
	.Z(FE_PHN188_n_4));
   DEL1 FE_PHC187_FE_OFN7_sram_addr_4 (.I(FE_OFN7_sram_addr_4),
	.Z(FE_PHN187_FE_OFN7_sram_addr_4));
   DEL1 FE_PHC186_n_10 (.I(n_10),
	.Z(FE_PHN186_n_10));
   DEL1 FE_PHC185_n_12 (.I(n_12),
	.Z(FE_PHN185_n_12));
   DEL2 FE_PHC184_n_6 (.I(n_6),
	.Z(FE_PHN184_n_6));
   DEL1 FE_PHC183_bus_addr_10 (.I(FE_PHN318_bus_addr_10),
	.Z(FE_PHN183_bus_addr_10));
   DEL1 FE_PHC182_FE_OFN3_sram_addr_8 (.I(FE_OFN3_sram_addr_8),
	.Z(FE_PHN182_FE_OFN3_sram_addr_8));
   DEL1 FE_PHC181_n_3 (.I(n_3),
	.Z(FE_PHN181_n_3));
   BUFFD1 FE_PHC180_bus_din_6 (.I(FE_PHN303_bus_din_6),
	.Z(FE_PHN489_bus_din_6));
   BUFFD2 FE_PHC179_bus_din_7 (.I(FE_PHN298_bus_din_7),
	.Z(FE_PHN433_bus_din_7));
   BUFFD2 FE_PHC178_bus_din_5 (.I(FE_PHN299_bus_din_5),
	.Z(FE_PHN535_bus_din_5));
   BUFFD2 FE_PHC177_bus_din_0 (.I(FE_PHN305_bus_din_0),
	.Z(FE_PHN177_bus_din_0));
   BUFFD2 FE_PHC176_bus_din_4 (.I(FE_PHN300_bus_din_4),
	.Z(FE_PHN476_bus_din_4));
   BUFFD2 FE_PHC175_bus_din_1 (.I(FE_PHN306_bus_din_1),
	.Z(FE_PHN175_bus_din_1));
   BUFFD2 FE_PHC174_bus_din_3 (.I(FE_PHN301_bus_din_3),
	.Z(FE_PHN501_bus_din_3));
   BUFFD2 FE_PHC173_bus_din_2 (.I(FE_PHN302_bus_din_2),
	.Z(FE_PHN410_bus_din_2));
   BUFFD8 FE_PHC172_tpu_dout_27 (.I(FE_PHN250_tpu_dout_27),
	.Z(tpu_dout[27]));
   CKBD12 FE_PHC170_tpu_dout_11 (.I(FE_PHN292_tpu_dout_11),
	.Z(tpu_dout[11]));
   BUFFD8 FE_PHC168_tpu_dout_18 (.I(FE_PHN295_tpu_dout_18),
	.Z(tpu_dout[18]));
   BUFFD8 FE_PHC166_tpu_dout_22 (.I(FE_PHN248_tpu_dout_22),
	.Z(tpu_dout[22]));
   BUFFD8 FE_PHC164_tpu_dout_24 (.I(FE_PHN249_tpu_dout_24),
	.Z(tpu_dout[24]));
   BUFFD8 FE_PHC162_tpu_dout_30 (.I(FE_PHN243_tpu_dout_30),
	.Z(tpu_dout[30]));
   BUFFD8 FE_PHC160_tpu_dout_16 (.I(FE_PHN237_tpu_dout_16),
	.Z(tpu_dout[16]));
   BUFFD8 FE_PHC158_tpu_dout_28 (.I(FE_PHN245_tpu_dout_28),
	.Z(tpu_dout[28]));
   BUFFD8 FE_PHC156_tpu_dout_6 (.I(FE_PHN291_tpu_dout_6),
	.Z(tpu_dout[6]));
   BUFFD8 FE_PHC154_tpu_dout_25 (.I(FE_PHN247_tpu_dout_25),
	.Z(tpu_dout[25]));
   BUFFD8 FE_PHC152_tpu_dout_31 (.I(FE_PHN151_tpu_dout_31),
	.Z(FE_PHN332_tpu_dout_31));
   BUFFD8 FE_PHC150_tpu_dout_12 (.I(FE_PHN278_tpu_dout_12),
	.Z(tpu_dout[12]));
   BUFFD8 FE_PHC148_tpu_dout_17 (.I(FE_PHN283_tpu_dout_17),
	.Z(tpu_dout[17]));
   BUFFD8 FE_PHC146_tpu_dout_19 (.I(FE_PHN296_tpu_dout_19),
	.Z(tpu_dout[19]));
   BUFFD8 FE_PHC144_tpu_dout_9 (.I(FE_PHN289_tpu_dout_9),
	.Z(tpu_dout[9]));
   BUFFD8 FE_PHC142_tpu_dout_0 (.I(FE_PHN345_tpu_dout_0),
	.Z(tpu_dout[0]));
   BUFFD8 FE_PHC140_tpu_dout_23 (.I(FE_PHN317_tpu_dout_23),
	.Z(tpu_dout[23]));
   BUFFD8 FE_PHC138_tpu_dout_26 (.I(FE_PHN246_tpu_dout_26),
	.Z(tpu_dout[26]));
   BUFFD8 FE_PHC136_tpu_dout_29 (.I(FE_PHN244_tpu_dout_29),
	.Z(tpu_dout[29]));
   BUFFD8 FE_PHC134_tpu_dout_33 (.I(FE_PHN251_tpu_dout_33),
	.Z(tpu_dout[33]));
   BUFFD8 FE_PHC132_tpu_dout_7 (.I(FE_PHN293_tpu_dout_7),
	.Z(tpu_dout[7]));
   BUFFD8 FE_PHC130_tpu_dout_8 (.I(FE_PHN286_tpu_dout_8),
	.Z(tpu_dout[8]));
   BUFFD8 FE_PHC128_tpu_dout_15 (.I(FE_PHN236_tpu_dout_15),
	.Z(tpu_dout[15]));
   BUFFD8 FE_PHC126_tpu_dout_21 (.I(FE_PHN316_tpu_dout_21),
	.Z(tpu_dout[21]));
   BUFFD8 FE_PHC124_tpu_dout_20 (.I(FE_PHN315_tpu_dout_20),
	.Z(tpu_dout[20]));
   BUFFD8 FE_PHC122_tpu_dout_42 (.I(FE_PHN238_tpu_dout_42),
	.Z(tpu_dout[42]));
   BUFFD8 FE_PHC120_tpu_dout_45 (.I(FE_PHN259_tpu_dout_45),
	.Z(tpu_dout[45]));
   BUFFD8 FE_PHC118_tpu_dout_36 (.I(FE_PHN255_tpu_dout_36),
	.Z(tpu_dout[36]));
   BUFFD8 FE_PHC116_tpu_dout_5 (.I(FE_PHN284_tpu_dout_5),
	.Z(tpu_dout[5]));
   BUFFD8 FE_PHC114_tpu_dout_13 (.I(FE_PHN294_tpu_dout_13),
	.Z(tpu_dout[13]));
   CKBD12 FE_PHC112_tpu_dout_56 (.I(FE_PHN280_tpu_dout_56),
	.Z(tpu_dout[56]));
   CKBD12 FE_PHC110_tpu_dout_59 (.I(FE_PHN274_tpu_dout_59),
	.Z(tpu_dout[59]));
   BUFFD8 FE_PHC108_tpu_dout_47 (.I(FE_PHN269_tpu_dout_47),
	.Z(tpu_dout[47]));
   BUFFD8 FE_PHC106_tpu_dout_40 (.I(FE_PHN263_tpu_dout_40),
	.Z(tpu_dout[40]));
   BUFFD8 FE_PHC104_tpu_dout_38 (.I(FE_PHN257_tpu_dout_38),
	.Z(tpu_dout[38]));
   BUFFD8 FE_PHC102_tpu_dout_34 (.I(FE_PHN253_tpu_dout_34),
	.Z(tpu_dout[34]));
   BUFFD8 FE_PHC100_tpu_dout_1 (.I(FE_PHN351_tpu_dout_1),
	.Z(tpu_dout[1]));
   BUFFD8 FE_PHC98_tpu_dout_2 (.I(FE_PHN288_tpu_dout_2),
	.Z(tpu_dout[2]));
   BUFFD8 FE_PHC96_tpu_dout_14 (.I(FE_PHN285_tpu_dout_14),
	.Z(tpu_dout[14]));
   CKBD12 FE_PHC94_tpu_dout_60 (.I(FE_PHN281_tpu_dout_60),
	.Z(tpu_dout[60]));
   CKBD12 FE_PHC92_tpu_dout_52 (.I(FE_PHN282_tpu_dout_52),
	.Z(tpu_dout[52]));
   BUFFD8 FE_PHC90_tpu_dout_37 (.I(FE_PHN256_tpu_dout_37),
	.Z(tpu_dout[37]));
   BUFFD8 FE_PHC88_tpu_dout_32 (.I(FE_PHN254_tpu_dout_32),
	.Z(tpu_dout[32]));
   BUFFD8 FE_PHC86_tpu_dout_35 (.I(FE_PHN252_tpu_dout_35),
	.Z(tpu_dout[35]));
   BUFFD8 FE_PHC84_tpu_dout_10 (.I(FE_PHN287_tpu_dout_10),
	.Z(tpu_dout[10]));
   CKBD12 FE_PHC82_tpu_dout_62 (.I(FE_PHN270_tpu_dout_62),
	.Z(tpu_dout[62]));
   BUFFD8 FE_PHC80_tpu_dout_58 (.I(FE_PHN276_tpu_dout_58),
	.Z(FE_PDN541_tpu_dout_58));
   CKBD12 FE_PHC78_tpu_dout_55 (.I(FE_PHN279_tpu_dout_55),
	.Z(tpu_dout[55]));
   BUFFD8 FE_PHC76_tpu_dout_44 (.I(FE_PHN265_tpu_dout_44),
	.Z(tpu_dout[44]));
   BUFFD8 FE_PHC74_tpu_dout_46 (.I(FE_PHN262_tpu_dout_46),
	.Z(tpu_dout[46]));
   BUFFD8 FE_PHC72_tpu_dout_39 (.I(FE_PHN260_tpu_dout_39),
	.Z(tpu_dout[39]));
   BUFFD8 FE_PHC70_tpu_dout_41 (.I(FE_PHN258_tpu_dout_41),
	.Z(tpu_dout[41]));
   BUFFD8 FE_PHC68_tpu_dout_3 (.I(FE_PHN352_tpu_dout_3),
	.Z(tpu_dout[3]));
   BUFFD8 FE_PHC66_tpu_dout_63 (.I(FE_PHN264_tpu_dout_63),
	.Z(tpu_dout[63]));
   CKBD12 FE_PHC64_tpu_dout_49 (.I(FE_PHN267_tpu_dout_49),
	.Z(tpu_dout[49]));
   BUFFD8 FE_PHC62_tpu_dout_4 (.I(FE_PHN290_tpu_dout_4),
	.Z(tpu_dout[4]));
   BUFFD8 FE_PHC60_tpu_dout_54 (.I(FE_PHN277_tpu_dout_54),
	.Z(FE_PDN539_tpu_dout_54));
   CKBD12 FE_PHC58_tpu_dout_61 (.I(FE_PHN266_tpu_dout_61),
	.Z(tpu_dout[61]));
   BUFFD8 FE_PHC56_tpu_dout_57 (.I(FE_PHN275_tpu_dout_57),
	.Z(tpu_dout[57]));
   BUFFD8 FE_PHC54_tpu_dout_53 (.I(FE_PHN271_tpu_dout_53),
	.Z(tpu_dout[53]));
   BUFFD8 FE_PHC52_tpu_dout_51 (.I(FE_PHN272_tpu_dout_51),
	.Z(tpu_dout[51]));
   BUFFD8 FE_PHC50_tpu_dout_50 (.I(FE_PHN273_tpu_dout_50),
	.Z(tpu_dout[50]));
   BUFFD8 FE_PHC48_tpu_dout_48 (.I(FE_PHN268_tpu_dout_48),
	.Z(tpu_dout[48]));
   BUFFD8 FE_PHC46_tpu_dout_43 (.I(FE_PHN261_tpu_dout_43),
	.Z(tpu_dout[43]));
   DEL2 FE_PHC44_bus_wbuf_1 (.I(bus_wbuf[1]),
	.Z(FE_PHN44_bus_wbuf_1));
   DEL2 FE_PHC43_bus_wbuf_2 (.I(bus_wbuf[2]),
	.Z(FE_PHN43_bus_wbuf_2));
   DEL2 FE_PHC42_bus_wbuf_4 (.I(bus_wbuf[4]),
	.Z(FE_PHN42_bus_wbuf_4));
   DEL2 FE_PHC41_bus_wbuf_3 (.I(bus_wbuf[3]),
	.Z(FE_PHN41_bus_wbuf_3));
   DEL2 FE_PHC40_bus_wbuf_6 (.I(bus_wbuf[6]),
	.Z(FE_PHN40_bus_wbuf_6));
   DEL2 FE_PHC39_bus_wbuf_7 (.I(bus_wbuf[7]),
	.Z(FE_PHN39_bus_wbuf_7));
   DEL2 FE_PHC38_bus_wbuf_8 (.I(bus_wbuf[8]),
	.Z(FE_PHN38_bus_wbuf_8));
   DEL2 FE_PHC37_bus_wbuf_5 (.I(bus_wbuf[5]),
	.Z(FE_PHN37_bus_wbuf_5));
   DEL2 FE_PHC36_bus_wbuf_11 (.I(bus_wbuf[11]),
	.Z(FE_PHN36_bus_wbuf_11));
   DEL2 FE_PHC35_bus_wbuf_9 (.I(bus_wbuf[9]),
	.Z(FE_PHN35_bus_wbuf_9));
   DEL2 FE_PHC34_bus_wbuf_15 (.I(bus_wbuf[15]),
	.Z(FE_PHN34_bus_wbuf_15));
   DEL2 FE_PHC33_bus_wbuf_13 (.I(bus_wbuf[13]),
	.Z(FE_PHN33_bus_wbuf_13));
   DEL2 FE_PHC32_bus_wbuf_10 (.I(bus_wbuf[10]),
	.Z(FE_PHN32_bus_wbuf_10));
   DEL2 FE_PHC31_bus_wbuf_12 (.I(bus_wbuf[12]),
	.Z(FE_PHN31_bus_wbuf_12));
   DEL2 FE_PHC30_bus_wbuf_14 (.I(bus_wbuf[14]),
	.Z(FE_PHN30_bus_wbuf_14));
   DEL2 FE_PHC29_bus_wbuf_54 (.I(bus_wbuf[54]),
	.Z(FE_PHN29_bus_wbuf_54));
   DEL2 FE_PHC28_bus_wbuf_53 (.I(bus_wbuf[53]),
	.Z(FE_PHN28_bus_wbuf_53));
   DEL2 FE_PHC27_bus_wbuf_50 (.I(bus_wbuf[50]),
	.Z(FE_PHN27_bus_wbuf_50));
   DEL2 FE_PHC26_bus_wbuf_55 (.I(bus_wbuf[55]),
	.Z(FE_PHN26_bus_wbuf_55));
   DEL2 FE_PHC25_bus_wbuf_51 (.I(bus_wbuf[51]),
	.Z(FE_PHN25_bus_wbuf_51));
   DEL2 FE_PHC24_bus_wbuf_52 (.I(bus_wbuf[52]),
	.Z(FE_PHN24_bus_wbuf_52));
   DEL2 FE_PHC23_bus_wbuf_49 (.I(bus_wbuf[49]),
	.Z(FE_PHN23_bus_wbuf_49));
   DEL2 FE_PHC22_bus_wbuf_48 (.I(bus_wbuf[48]),
	.Z(FE_PHN22_bus_wbuf_48));
   DEL1 FE_PHC21_rstn (.I(rstn),
	.Z(FE_PHN21_rstn));
   DEL1 FE_PHC20_bus_addr_3 (.I(FE_PHN342_bus_addr_3),
	.Z(FE_PHN20_bus_addr_3));
   DEL1 FE_PHC19_bus_addr_4 (.I(FE_PHN319_bus_addr_4),
	.Z(FE_PHN19_bus_addr_4));
   DEL1 FE_PHC18_bus_addr_5 (.I(FE_PHN320_bus_addr_5),
	.Z(FE_PHN18_bus_addr_5));
   DEL1 FE_PHC17_bus_addr_6 (.I(FE_PHN341_bus_addr_6),
	.Z(FE_PHN17_bus_addr_6));
   DEL1 FE_PHC16_bus_addr_7 (.I(FE_PHN344_bus_addr_7),
	.Z(FE_PHN16_bus_addr_7));
   DEL0 FE_PHC15_tpu_re (.I(tpu_re),
	.Z(FE_PHN15_tpu_re));
   DEL1 FE_PHC14_bus_we (.I(bus_we),
	.Z(FE_PHN14_bus_we));
   DEL1 FE_PHC13_bus_addr_0 (.I(bus_addr[0]),
	.Z(FE_PHN13_bus_addr_0));
   DEL0 FE_PHC12_bus_addr_1 (.I(bus_addr[1]),
	.Z(FE_PHN12_bus_addr_1));
   CKND2 CTS_ccl_a_inv_00009 (.I(CTS_8),
	.ZN(CTS_7));
   CKND2 CTS_ccl_a_inv_00008 (.I(CTS_8),
	.ZN(CTS_6));
   CKND2 CTS_ccl_a_inv_00007 (.I(CTS_8),
	.ZN(CTS_5));
   CKND2 CTS_ccl_a_inv_00006 (.I(CTS_8),
	.ZN(CTS_4));
   CKND3 CTS_ccl_a_inv_00005 (.I(CTS_8),
	.ZN(CTS_3));
   CKND2 CTS_ccl_a_inv_00004 (.I(CTS_8),
	.ZN(CTS_2));
   CKND2 CTS_ccl_a_inv_00003 (.I(CTS_8),
	.ZN(CTS_1));
   CKND2 CTS_ccl_a_inv_00002 (.I(CTS_8),
	.ZN(CTS_10));
   CKND2 CTS_ccl_a_inv_00001 (.I(CTS_8),
	.ZN(CTS_9));
   CKND6 CTS_ccl_a_inv_00010 (.I(CTS_11),
	.ZN(CTS_8));
   CKND3 CTS_ccl_a_inv_00011 (.I(CTS_12),
	.ZN(CTS_11));
   CKND1 CTS_cmf_inv_00057 (.I(clk),
	.ZN(CTS_12));
   TIEL LTIELO (.ZN(LTIELO_NET));
   TIEH LTIEHI (.Z(LTIEHI_NET));
   CKBD1 FE_OFC11_sram_addr_0 (.I(sram_addr[0]),
	.Z(FE_OFN11_sram_addr_0));
   CKBD1 FE_OFC10_sram_addr_1 (.I(sram_addr[1]),
	.Z(FE_OFN10_sram_addr_1));
   CKBD1 FE_OFC9_sram_addr_2 (.I(sram_addr[2]),
	.Z(FE_OFN9_sram_addr_2));
   CKBD1 FE_OFC8_sram_addr_3 (.I(sram_addr[3]),
	.Z(FE_OFN8_sram_addr_3));
   CKBD1 FE_OFC7_sram_addr_4 (.I(sram_addr[4]),
	.Z(FE_OFN7_sram_addr_4));
   CKBD1 FE_OFC6_sram_addr_5 (.I(sram_addr[5]),
	.Z(FE_OFN6_sram_addr_5));
   CKBD1 FE_OFC5_sram_addr_6 (.I(sram_addr[6]),
	.Z(FE_OFN5_sram_addr_6));
   CKBD1 FE_OFC4_sram_addr_7 (.I(sram_addr[7]),
	.Z(FE_OFN4_sram_addr_7));
   CKBD1 FE_OFC3_sram_addr_8 (.I(sram_addr[8]),
	.Z(FE_OFN3_sram_addr_8));
   BUFFD2 FE_OFC2_bus_we_d1 (.I(bus_we_d1),
	.Z(FE_OFN2_bus_we_d1));
   CKBD1 FE_OFC1_tpu_re (.I(FE_PHN239_tpu_re),
	.Z(FE_OFN1_tpu_re));
   CKBD1 FE_OFC0_rstn (.I(FE_PHN21_rstn),
	.Z(FE_OFN0_rstn));
   sram00 u_sram (.Q({ FE_PHN65_tpu_dout_63,
		FE_PHN81_tpu_dout_62,
		FE_PHN57_tpu_dout_61,
		FE_PHN93_tpu_dout_60,
		FE_PHN109_tpu_dout_59,
		FE_PHN79_tpu_dout_58,
		FE_PHN55_tpu_dout_57,
		FE_PHN111_tpu_dout_56,
		FE_PHN77_tpu_dout_55,
		FE_PHN59_tpu_dout_54,
		FE_PHN53_tpu_dout_53,
		FE_PHN91_tpu_dout_52,
		FE_PHN51_tpu_dout_51,
		FE_PHN49_tpu_dout_50,
		FE_PHN63_tpu_dout_49,
		FE_PHN47_tpu_dout_48,
		FE_PHN107_tpu_dout_47,
		FE_PHN73_tpu_dout_46,
		FE_PHN119_tpu_dout_45,
		FE_PHN75_tpu_dout_44,
		FE_PHN45_tpu_dout_43,
		FE_PHN121_tpu_dout_42,
		FE_PHN69_tpu_dout_41,
		FE_PHN105_tpu_dout_40,
		FE_PHN71_tpu_dout_39,
		FE_PHN103_tpu_dout_38,
		FE_PHN89_tpu_dout_37,
		FE_PHN117_tpu_dout_36,
		FE_PHN85_tpu_dout_35,
		FE_PHN101_tpu_dout_34,
		FE_PHN133_tpu_dout_33,
		FE_PHN87_tpu_dout_32,
		FE_PHN151_tpu_dout_31,
		FE_PHN161_tpu_dout_30,
		FE_PHN135_tpu_dout_29,
		FE_PHN157_tpu_dout_28,
		FE_PHN171_tpu_dout_27,
		FE_PHN137_tpu_dout_26,
		FE_PHN153_tpu_dout_25,
		FE_PHN163_tpu_dout_24,
		FE_PHN139_tpu_dout_23,
		FE_PHN165_tpu_dout_22,
		FE_PHN125_tpu_dout_21,
		FE_PHN123_tpu_dout_20,
		FE_PHN145_tpu_dout_19,
		FE_PHN167_tpu_dout_18,
		FE_PHN147_tpu_dout_17,
		FE_PHN159_tpu_dout_16,
		FE_PHN127_tpu_dout_15,
		FE_PHN95_tpu_dout_14,
		FE_PHN113_tpu_dout_13,
		FE_PHN149_tpu_dout_12,
		FE_PHN169_tpu_dout_11,
		FE_PHN83_tpu_dout_10,
		FE_PHN143_tpu_dout_9,
		FE_PHN129_tpu_dout_8,
		FE_PHN131_tpu_dout_7,
		FE_PHN155_tpu_dout_6,
		FE_PHN115_tpu_dout_5,
		FE_PHN61_tpu_dout_4,
		FE_PHN67_tpu_dout_3,
		FE_PHN97_tpu_dout_2,
		FE_PHN99_tpu_dout_1,
		FE_PHN141_tpu_dout_0 }),
	.CLK(CTS_3),
	.CEN(sram_cen),
	.WEN(sram_wen),
	.A({ FE_PHN182_FE_OFN3_sram_addr_8,
		FE_PHN206_FE_OFN4_sram_addr_7,
		FE_PHN310_FE_OFN5_sram_addr_6,
		FE_PHN311_FE_OFN6_sram_addr_5,
		FE_PHN312_FE_OFN7_sram_addr_4,
		FE_PHN313_FE_OFN8_sram_addr_3,
		FE_PHN314_FE_OFN9_sram_addr_2,
		FE_PHN347_FE_OFN10_sram_addr_1,
		FE_PHN334_FE_OFN11_sram_addr_0 }),
	.D(sram_din),
	.EMA({ LTIELO_NET,
		LTIEHI_NET,
		LTIELO_NET }),
	.RETN(LTIEHI_NET));
   DFCNQD1 \bus_waddr_d1_reg[0]  (.CDN(FE_OFN0_rstn),
	.CP(CTS_7),
	.D(FE_PHN20_bus_addr_3),
	.Q(bus_waddr_d1[0]));
   DFCNQD1 \bus_waddr_d1_reg[1]  (.CDN(FE_OFN0_rstn),
	.CP(CTS_7),
	.D(FE_PHN19_bus_addr_4),
	.Q(bus_waddr_d1[1]));
   DFCNQD1 \bus_waddr_d1_reg[2]  (.CDN(FE_OFN0_rstn),
	.CP(CTS_7),
	.D(FE_PHN18_bus_addr_5),
	.Q(bus_waddr_d1[2]));
   DFCNQD1 \bus_waddr_d1_reg[3]  (.CDN(FE_OFN0_rstn),
	.CP(CTS_7),
	.D(FE_PHN17_bus_addr_6),
	.Q(bus_waddr_d1[3]));
   DFCNQD1 \bus_waddr_d1_reg[4]  (.CDN(FE_OFN0_rstn),
	.CP(CTS_7),
	.D(FE_PHN16_bus_addr_7),
	.Q(bus_waddr_d1[4]));
   DFCNQD1 \bus_waddr_d1_reg[5]  (.CDN(FE_OFN0_rstn),
	.CP(CTS_6),
	.D(FE_PHN241_bus_addr_8),
	.Q(bus_waddr_d1[5]));
   DFCNQD1 \bus_waddr_d1_reg[6]  (.CDN(FE_OFN0_rstn),
	.CP(CTS_6),
	.D(FE_PHN240_bus_addr_9),
	.Q(bus_waddr_d1[6]));
   DFCNQD1 \bus_waddr_d1_reg[7]  (.CDN(FE_PHN21_rstn),
	.CP(CTS_6),
	.D(FE_PHN414_bus_addr_10),
	.Q(bus_waddr_d1[7]));
   DFCNQD1 \bus_waddr_d1_reg[8]  (.CDN(FE_PHN21_rstn),
	.CP(CTS_6),
	.D(FE_PHN242_bus_addr_11),
	.Q(bus_waddr_d1[8]));
   DFNCND1 \sram_addr_ff_reg[0]  (.CDN(FE_OFN0_rstn),
	.CPN(CTS_7),
	.D(n_16),
	.Q(UNCONNECTED),
	.QN(sram_addr_ff[0]));
   DFNCND1 \sram_addr_ff_reg[1]  (.CDN(FE_OFN0_rstn),
	.CPN(CTS_7),
	.D(n_76),
	.Q(UNCONNECTED0),
	.QN(sram_addr_ff[1]));
   DFNCND1 \sram_addr_ff_reg[2]  (.CDN(FE_OFN0_rstn),
	.CPN(CTS_7),
	.D(n_50),
	.Q(UNCONNECTED1),
	.QN(sram_addr_ff[2]));
   DFNCND1 \sram_addr_ff_reg[3]  (.CDN(FE_OFN0_rstn),
	.CPN(CTS_7),
	.D(n_15),
	.Q(UNCONNECTED2),
	.QN(sram_addr_ff[3]));
   DFNCND1 \sram_addr_ff_reg[4]  (.CDN(FE_OFN0_rstn),
	.CPN(CTS_7),
	.D(n_19),
	.Q(UNCONNECTED3),
	.QN(sram_addr_ff[4]));
   DFNCND1 \sram_addr_ff_reg[5]  (.CDN(rstn),
	.CPN(CTS_6),
	.D(n_17),
	.Q(UNCONNECTED4),
	.QN(sram_addr_ff[5]));
   DFNCND1 \sram_addr_ff_reg[6]  (.CDN(rstn),
	.CPN(CTS_6),
	.D(n_28),
	.Q(UNCONNECTED5),
	.QN(sram_addr_ff[6]));
   DFNCND1 \sram_addr_ff_reg[7]  (.CDN(rstn),
	.CPN(CTS_6),
	.D(n_22),
	.Q(UNCONNECTED6),
	.QN(sram_addr_ff[7]));
   DFNCND1 \sram_addr_ff_reg[8]  (.CDN(rstn),
	.CPN(CTS_6),
	.D(n_20),
	.Q(UNCONNECTED7),
	.QN(sram_addr_ff[8]));
   DFNCND1 \sram_din_ff_reg[0]  (.CDN(FE_OFN0_rstn),
	.CPN(CTS_7),
	.D(n_71),
	.Q(UNCONNECTED8),
	.QN(sram_din_ff[0]));
   DFNCND1 \sram_din_ff_reg[1]  (.CDN(FE_OFN0_rstn),
	.CPN(CTS_7),
	.D(n_21),
	.Q(UNCONNECTED9),
	.QN(sram_din_ff[1]));
   DFNCND1 \sram_din_ff_reg[2]  (.CDN(FE_OFN0_rstn),
	.CPN(CTS_7),
	.D(n_24),
	.Q(UNCONNECTED10),
	.QN(sram_din_ff[2]));
   DFNCND1 \sram_din_ff_reg[3]  (.CDN(FE_OFN0_rstn),
	.CPN(CTS_7),
	.D(n_23),
	.Q(UNCONNECTED11),
	.QN(sram_din_ff[3]));
   DFNCND1 \sram_din_ff_reg[4]  (.CDN(rstn),
	.CPN(CTS_6),
	.D(n_69),
	.Q(UNCONNECTED12),
	.QN(sram_din_ff[4]));
   DFNCND1 \sram_din_ff_reg[5]  (.CDN(rstn),
	.CPN(CTS_6),
	.D(n_27),
	.Q(UNCONNECTED13),
	.QN(sram_din_ff[5]));
   DFNCND1 \sram_din_ff_reg[6]  (.CDN(rstn),
	.CPN(CTS_6),
	.D(n_26),
	.Q(UNCONNECTED14),
	.QN(sram_din_ff[6]));
   DFNCND1 \sram_din_ff_reg[7]  (.CDN(rstn),
	.CPN(CTS_5),
	.D(n_25),
	.Q(UNCONNECTED15),
	.QN(sram_din_ff[7]));
   DFNCND1 \sram_din_ff_reg[8]  (.CDN(rstn),
	.CPN(CTS_5),
	.D(n_67),
	.Q(UNCONNECTED16),
	.QN(sram_din_ff[8]));
   DFNCND1 \sram_din_ff_reg[9]  (.CDN(rstn),
	.CPN(CTS_5),
	.D(n_30),
	.Q(UNCONNECTED17),
	.QN(sram_din_ff[9]));
   DFNCND1 \sram_din_ff_reg[10]  (.CDN(rstn),
	.CPN(CTS_5),
	.D(n_68),
	.Q(UNCONNECTED18),
	.QN(sram_din_ff[10]));
   DFNCND1 \sram_din_ff_reg[11]  (.CDN(rstn),
	.CPN(CTS_5),
	.D(n_48),
	.Q(UNCONNECTED19),
	.QN(sram_din_ff[11]));
   DFNCND1 \sram_din_ff_reg[12]  (.CDN(rstn),
	.CPN(CTS_5),
	.D(n_64),
	.Q(UNCONNECTED20),
	.QN(sram_din_ff[12]));
   DFNCND1 \sram_din_ff_reg[13]  (.CDN(rstn),
	.CPN(CTS_5),
	.D(n_33),
	.Q(UNCONNECTED21),
	.QN(sram_din_ff[13]));
   DFNCND1 \sram_din_ff_reg[14]  (.CDN(rstn),
	.CPN(CTS_5),
	.D(n_31),
	.Q(UNCONNECTED22),
	.QN(sram_din_ff[14]));
   DFNCND1 \sram_din_ff_reg[15]  (.CDN(rstn),
	.CPN(CTS_4),
	.D(n_32),
	.Q(UNCONNECTED23),
	.QN(sram_din_ff[15]));
   DFNCND1 \sram_din_ff_reg[16]  (.CDN(rstn),
	.CPN(CTS_4),
	.D(n_61),
	.Q(UNCONNECTED24),
	.QN(sram_din_ff[16]));
   DFNCND1 \sram_din_ff_reg[17]  (.CDN(rstn),
	.CPN(CTS_4),
	.D(n_58),
	.Q(UNCONNECTED25),
	.QN(sram_din_ff[17]));
   DFNCND1 \sram_din_ff_reg[18]  (.CDN(rstn),
	.CPN(CTS_4),
	.D(n_44),
	.Q(UNCONNECTED26),
	.QN(sram_din_ff[18]));
   DFNCND1 \sram_din_ff_reg[19]  (.CDN(rstn),
	.CPN(CTS_4),
	.D(n_40),
	.Q(UNCONNECTED27),
	.QN(sram_din_ff[19]));
   DFNCND1 \sram_din_ff_reg[20]  (.CDN(rstn),
	.CPN(CTS_4),
	.D(n_36),
	.Q(UNCONNECTED28),
	.QN(sram_din_ff[20]));
   DFNCND1 \sram_din_ff_reg[21]  (.CDN(rstn),
	.CPN(CTS_4),
	.D(n_34),
	.Q(UNCONNECTED29),
	.QN(sram_din_ff[21]));
   DFNCND1 \sram_din_ff_reg[22]  (.CDN(rstn),
	.CPN(CTS_4),
	.D(n_35),
	.Q(UNCONNECTED30),
	.QN(sram_din_ff[22]));
   DFNCND1 \sram_din_ff_reg[23]  (.CDN(rstn),
	.CPN(CTS_4),
	.D(n_38),
	.Q(UNCONNECTED31),
	.QN(sram_din_ff[23]));
   DFNCND1 \sram_din_ff_reg[24]  (.CDN(rstn),
	.CPN(CTS_9),
	.D(n_37),
	.Q(UNCONNECTED32),
	.QN(sram_din_ff[24]));
   DFNCND1 \sram_din_ff_reg[25]  (.CDN(rstn),
	.CPN(CTS_9),
	.D(n_47),
	.Q(UNCONNECTED33),
	.QN(sram_din_ff[25]));
   DFNCND1 \sram_din_ff_reg[26]  (.CDN(rstn),
	.CPN(CTS_9),
	.D(n_43),
	.Q(UNCONNECTED34),
	.QN(sram_din_ff[26]));
   DFNCND1 \sram_din_ff_reg[27]  (.CDN(rstn),
	.CPN(CTS_9),
	.D(n_41),
	.Q(UNCONNECTED35),
	.QN(sram_din_ff[27]));
   DFNCND1 \sram_din_ff_reg[28]  (.CDN(rstn),
	.CPN(CTS_9),
	.D(n_62),
	.Q(UNCONNECTED36),
	.QN(sram_din_ff[28]));
   DFNCND1 \sram_din_ff_reg[29]  (.CDN(rstn),
	.CPN(CTS_9),
	.D(n_45),
	.Q(UNCONNECTED37),
	.QN(sram_din_ff[29]));
   DFNCND1 \sram_din_ff_reg[30]  (.CDN(rstn),
	.CPN(CTS_9),
	.D(n_83),
	.Q(UNCONNECTED38),
	.QN(sram_din_ff[30]));
   DFNCND1 \sram_din_ff_reg[31]  (.CDN(rstn),
	.CPN(CTS_9),
	.D(n_65),
	.Q(UNCONNECTED39),
	.QN(sram_din_ff[31]));
   DFNCND1 \sram_din_ff_reg[32]  (.CDN(rstn),
	.CPN(CTS_3),
	.D(n_55),
	.Q(UNCONNECTED40),
	.QN(sram_din_ff[32]));
   DFNCND1 \sram_din_ff_reg[33]  (.CDN(rstn),
	.CPN(CTS_3),
	.D(n_14),
	.Q(UNCONNECTED41),
	.QN(sram_din_ff[33]));
   DFNCND1 \sram_din_ff_reg[34]  (.CDN(rstn),
	.CPN(CTS_3),
	.D(n_49),
	.Q(UNCONNECTED42),
	.QN(sram_din_ff[34]));
   DFNCND1 \sram_din_ff_reg[35]  (.CDN(rstn),
	.CPN(CTS_3),
	.D(n_51),
	.Q(UNCONNECTED43),
	.QN(sram_din_ff[35]));
   DFNCND1 \sram_din_ff_reg[36]  (.CDN(rstn),
	.CPN(CTS_2),
	.D(n_53),
	.Q(UNCONNECTED44),
	.QN(sram_din_ff[36]));
   DFNCND1 \sram_din_ff_reg[37]  (.CDN(rstn),
	.CPN(CTS_2),
	.D(n_52),
	.Q(UNCONNECTED45),
	.QN(sram_din_ff[37]));
   DFNCND1 \sram_din_ff_reg[38]  (.CDN(rstn),
	.CPN(CTS_2),
	.D(n_54),
	.Q(UNCONNECTED46),
	.QN(sram_din_ff[38]));
   DFNCND1 \sram_din_ff_reg[39]  (.CDN(rstn),
	.CPN(CTS_2),
	.D(n_63),
	.Q(UNCONNECTED47),
	.QN(sram_din_ff[39]));
   DFNCND1 \sram_din_ff_reg[40]  (.CDN(rstn),
	.CPN(CTS_2),
	.D(n_46),
	.Q(UNCONNECTED48),
	.QN(sram_din_ff[40]));
   DFNCND1 \sram_din_ff_reg[41]  (.CDN(rstn),
	.CPN(CTS_2),
	.D(n_56),
	.Q(UNCONNECTED49),
	.QN(sram_din_ff[41]));
   DFNCND1 \sram_din_ff_reg[42]  (.CDN(rstn),
	.CPN(CTS_2),
	.D(n_57),
	.Q(UNCONNECTED50),
	.QN(sram_din_ff[42]));
   DFNCND1 \sram_din_ff_reg[43]  (.CDN(rstn),
	.CPN(CTS_2),
	.D(n_86),
	.Q(UNCONNECTED51),
	.QN(sram_din_ff[43]));
   DFNCND1 \sram_din_ff_reg[44]  (.CDN(rstn),
	.CPN(CTS_2),
	.D(n_59),
	.Q(UNCONNECTED52),
	.QN(sram_din_ff[44]));
   DFNCND1 \sram_din_ff_reg[45]  (.CDN(rstn),
	.CPN(CTS_2),
	.D(n_81),
	.Q(UNCONNECTED53),
	.QN(sram_din_ff[45]));
   DFNCND1 \sram_din_ff_reg[46]  (.CDN(rstn),
	.CPN(CTS_1),
	.D(n_73),
	.Q(UNCONNECTED54),
	.QN(sram_din_ff[46]));
   DFNCND1 \sram_din_ff_reg[47]  (.CDN(rstn),
	.CPN(CTS_1),
	.D(n_72),
	.Q(UNCONNECTED55),
	.QN(sram_din_ff[47]));
   DFNCND1 \sram_din_ff_reg[48]  (.CDN(rstn),
	.CPN(CTS_1),
	.D(n_42),
	.Q(UNCONNECTED56),
	.QN(sram_din_ff[48]));
   DFNCND1 \sram_din_ff_reg[49]  (.CDN(rstn),
	.CPN(CTS_1),
	.D(n_70),
	.Q(UNCONNECTED57),
	.QN(sram_din_ff[49]));
   DFNCND1 \sram_din_ff_reg[50]  (.CDN(rstn),
	.CPN(CTS_1),
	.D(n_77),
	.Q(UNCONNECTED58),
	.QN(sram_din_ff[50]));
   DFNCND1 \sram_din_ff_reg[51]  (.CDN(rstn),
	.CPN(CTS_1),
	.D(n_74),
	.Q(UNCONNECTED59),
	.QN(sram_din_ff[51]));
   DFNCND1 \sram_din_ff_reg[52]  (.CDN(rstn),
	.CPN(CTS_1),
	.D(n_75),
	.Q(UNCONNECTED60),
	.QN(sram_din_ff[52]));
   DFNCND1 \sram_din_ff_reg[53]  (.CDN(rstn),
	.CPN(CTS_10),
	.D(n_85),
	.Q(UNCONNECTED61),
	.QN(sram_din_ff[53]));
   DFNCND1 \sram_din_ff_reg[54]  (.CDN(rstn),
	.CPN(CTS_10),
	.D(n_79),
	.Q(UNCONNECTED62),
	.QN(sram_din_ff[54]));
   DFNCND1 \sram_din_ff_reg[55]  (.CDN(rstn),
	.CPN(CTS_10),
	.D(n_78),
	.Q(UNCONNECTED63),
	.QN(sram_din_ff[55]));
   DFNCND1 \sram_din_ff_reg[56]  (.CDN(rstn),
	.CPN(CTS_10),
	.D(n_39),
	.Q(UNCONNECTED64),
	.QN(sram_din_ff[56]));
   DFNCND1 \sram_din_ff_reg[57]  (.CDN(rstn),
	.CPN(CTS_10),
	.D(n_18),
	.Q(UNCONNECTED65),
	.QN(sram_din_ff[57]));
   DFNCND1 \sram_din_ff_reg[58]  (.CDN(rstn),
	.CPN(CTS_10),
	.D(n_29),
	.Q(UNCONNECTED66),
	.QN(sram_din_ff[58]));
   DFNCND1 \sram_din_ff_reg[59]  (.CDN(rstn),
	.CPN(CTS_10),
	.D(n_80),
	.Q(UNCONNECTED67),
	.QN(sram_din_ff[59]));
   DFNCND1 \sram_din_ff_reg[60]  (.CDN(rstn),
	.CPN(CTS_10),
	.D(n_60),
	.Q(UNCONNECTED68),
	.QN(sram_din_ff[60]));
   DFNCND1 \sram_din_ff_reg[61]  (.CDN(rstn),
	.CPN(CTS_10),
	.D(n_84),
	.Q(UNCONNECTED69),
	.QN(sram_din_ff[61]));
   DFNCND1 \sram_din_ff_reg[62]  (.CDN(rstn),
	.CPN(CTS_10),
	.D(n_66),
	.Q(UNCONNECTED70),
	.QN(sram_din_ff[62]));
   DFNCND1 \sram_din_ff_reg[63]  (.CDN(rstn),
	.CPN(CTS_10),
	.D(n_82),
	.Q(UNCONNECTED71),
	.QN(sram_din_ff[63]));
   MOAI22D0 p11362A__2398 (.A1(FE_PHN15_tpu_re),
	.A2(sram_addr_ff[5]),
	.B1(FE_PHN15_tpu_re),
	.B2(tpu_addr[5]),
	.ZN(sram_addr[5]));
   MOAI22D0 p11362A3056__5107 (.A1(FE_PHN15_tpu_re),
	.A2(sram_addr_ff[7]),
	.B1(FE_PHN15_tpu_re),
	.B2(FE_PHN321_tpu_addr_7),
	.ZN(sram_addr[7]));
   MOAI22D0 p11362A3057__6260 (.A1(FE_PHN15_tpu_re),
	.A2(sram_addr_ff[8]),
	.B1(FE_PHN15_tpu_re),
	.B2(FE_PHN297_tpu_addr_8),
	.ZN(sram_addr[8]));
   MOAI22D0 p11362A3058__4319 (.A1(FE_PHN15_tpu_re),
	.A2(sram_addr_ff[2]),
	.B1(FE_PHN15_tpu_re),
	.B2(tpu_addr[2]),
	.ZN(sram_addr[2]));
   MOAI22D0 p11362A3059__8428 (.A1(FE_PHN15_tpu_re),
	.A2(sram_addr_ff[6]),
	.B1(FE_PHN15_tpu_re),
	.B2(tpu_addr[6]),
	.ZN(sram_addr[6]));
   MOAI22D0 p11362A3060__5526 (.A1(FE_PHN239_tpu_re),
	.A2(sram_addr_ff[0]),
	.B1(FE_PHN239_tpu_re),
	.B2(tpu_addr[0]),
	.ZN(sram_addr[0]));
   MOAI22D0 p11362A3061__6783 (.A1(FE_PHN239_tpu_re),
	.A2(sram_addr_ff[1]),
	.B1(FE_PHN239_tpu_re),
	.B2(tpu_addr[1]),
	.ZN(sram_addr[1]));
   MOAI22D0 p11362A3062__3680 (.A1(FE_PHN15_tpu_re),
	.A2(sram_addr_ff[4]),
	.B1(FE_PHN15_tpu_re),
	.B2(tpu_addr[4]),
	.ZN(sram_addr[4]));
   MOAI22D0 p11362A3063__1617 (.A1(FE_PHN15_tpu_re),
	.A2(sram_addr_ff[3]),
	.B1(FE_PHN15_tpu_re),
	.B2(tpu_addr[3]),
	.ZN(sram_addr[3]));
   NR2D0 p11608A__2802 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[13]),
	.ZN(sram_din[13]));
   NR2D0 p11608A3064__1705 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[23]),
	.ZN(sram_din[23]));
   NR2D0 p11608A3065__5122 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[22]),
	.ZN(sram_din[22]));
   NR2D0 p11608A3066__8246 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[54]),
	.ZN(sram_din[54]));
   NR2D0 p11608A3067__7098 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[21]),
	.ZN(sram_din[21]));
   NR2D0 p11608A3068__6131 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[20]),
	.ZN(sram_din[20]));
   NR2D0 p11608A3069__1881 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[53]),
	.ZN(sram_din[53]));
   NR2D0 p11608A3070__5115 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[19]),
	.ZN(sram_din[19]));
   NR2D0 p11608A3071__7482 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[18]),
	.ZN(sram_din[18]));
   NR2D0 p11608A3072__4733 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[52]),
	.ZN(sram_din[52]));
   NR2D0 p11608A3073__6161 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[17]),
	.ZN(sram_din[17]));
   NR2D0 p11608A3074__9315 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[16]),
	.ZN(sram_din[16]));
   NR2D0 p11608A3075__9945 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[51]),
	.ZN(sram_din[51]));
   NR2D0 p11608A3076__2883 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[15]),
	.ZN(sram_din[15]));
   NR2D0 p11608A3077__2346 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[14]),
	.ZN(sram_din[14]));
   NR2D0 p11608A3078__1666 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[50]),
	.ZN(sram_din[50]));
   NR2D0 p11608A3079__7410 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[55]),
	.ZN(sram_din[55]));
   NR2D0 p11608A3080__6417 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[12]),
	.ZN(sram_din[12]));
   NR2D0 p11608A3081__5477 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[49]),
	.ZN(sram_din[49]));
   NR2D0 p11608A3082__2398 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[11]),
	.ZN(sram_din[11]));
   NR2D0 p11608A3083__5107 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[10]),
	.ZN(sram_din[10]));
   NR2D0 p11608A3084__6260 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[48]),
	.ZN(sram_din[48]));
   NR2D0 p11608A3085__4319 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[9]),
	.ZN(sram_din[9]));
   NR2D0 p11608A3086__8428 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[8]),
	.ZN(sram_din[8]));
   NR2D0 p11608A3087__5526 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[47]),
	.ZN(sram_din[47]));
   NR2D0 p11608A3088__6783 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[7]),
	.ZN(sram_din[7]));
   NR2D0 p11608A3089__3680 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[6]),
	.ZN(sram_din[6]));
   NR2D0 p11608A3090__1617 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[46]),
	.ZN(sram_din[46]));
   NR2D0 p11608A3091__2802 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[5]),
	.ZN(sram_din[5]));
   NR2D0 p11608A3092__1705 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[4]),
	.ZN(sram_din[4]));
   NR2D0 p11608A3093__5122 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[45]),
	.ZN(sram_din[45]));
   NR2D0 p11608A3094__8246 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[3]),
	.ZN(sram_din[3]));
   NR2D0 p11608A3095__7098 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[34]),
	.ZN(sram_din[34]));
   NR2D0 p11608A3096__6131 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[44]),
	.ZN(sram_din[44]));
   NR2D0 p11608A3097__1881 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[1]),
	.ZN(sram_din[1]));
   NR2D0 p11608A3098__5115 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[0]),
	.ZN(sram_din[0]));
   NR2D0 p11608A3099__7482 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[43]),
	.ZN(sram_din[43]));
   NR2D0 p11608A3100__4733 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[42]),
	.ZN(sram_din[42]));
   NR2D0 p11608A3101__6161 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[41]),
	.ZN(sram_din[41]));
   NR2D0 p11608A3102__9315 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[40]),
	.ZN(sram_din[40]));
   NR2D0 p11608A3103__9945 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[63]),
	.ZN(sram_din[63]));
   NR2D0 p11608A3104__2883 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[39]),
	.ZN(sram_din[39]));
   NR2D0 p11608A3105__2346 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[38]),
	.ZN(sram_din[38]));
   NR2D0 p11608A3106__1666 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[62]),
	.ZN(sram_din[62]));
   NR2D0 p11608A3107__7410 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[37]),
	.ZN(sram_din[37]));
   NR2D0 p11608A3108__6417 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[36]),
	.ZN(sram_din[36]));
   NR2D0 p11608A3109__5477 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[61]),
	.ZN(sram_din[61]));
   NR2D0 p11608A3110__2398 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[35]),
	.ZN(sram_din[35]));
   NR2D0 p11608A3111__5107 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[2]),
	.ZN(sram_din[2]));
   NR2D0 p11608A3112__6260 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[60]),
	.ZN(sram_din[60]));
   NR2D0 p11608A3113__4319 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[33]),
	.ZN(sram_din[33]));
   NR2D0 p11608A3114__8428 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[32]),
	.ZN(sram_din[32]));
   NR2D0 p11608A3115__5526 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[59]),
	.ZN(sram_din[59]));
   NR2D0 p11608A3116__6783 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[31]),
	.ZN(sram_din[31]));
   NR2D0 p11608A3117__3680 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[30]),
	.ZN(sram_din[30]));
   NR2D0 p11608A3118__1617 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[58]),
	.ZN(sram_din[58]));
   NR2D0 p11608A3119__2802 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[29]),
	.ZN(sram_din[29]));
   NR2D0 p11608A3120__1705 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[28]),
	.ZN(sram_din[28]));
   NR2D0 p11608A3121__5122 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[57]),
	.ZN(sram_din[57]));
   NR2D0 p11608A3122__8246 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[27]),
	.ZN(sram_din[27]));
   NR2D0 p11608A3123__7098 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[26]),
	.ZN(sram_din[26]));
   NR2D0 p11608A3124__6131 (.A1(FE_OFN1_tpu_re),
	.A2(sram_din_ff[56]),
	.ZN(sram_din[56]));
   NR2D0 p11608A3125__1881 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[25]),
	.ZN(sram_din[25]));
   NR2D0 p11608A3126__5115 (.A1(FE_PHN239_tpu_re),
	.A2(sram_din_ff[24]),
	.ZN(sram_din[24]));
   CKAN2D0 p11422A__7482 (.A1(bus_wbuf[43]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_86));
   CKAN2D0 p11422A3200__4733 (.A1(bus_wbuf[53]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_85));
   CKAN2D0 p11422A3201__6161 (.A1(bus_wbuf[61]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_84));
   CKAN2D0 p11422A3202__9315 (.A1(bus_wbuf[30]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_83));
   CKAN2D0 p11422A3203__9945 (.A1(bus_wbuf[63]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_82));
   CKAN2D0 p11422A3204__2883 (.A1(bus_wbuf[45]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_81));
   CKAN2D0 p11422A3205__2346 (.A1(bus_wbuf[59]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_80));
   CKAN2D0 p11422A3206__1666 (.A1(bus_wbuf[54]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_79));
   CKAN2D0 p11422A3207__7410 (.A1(bus_wbuf[55]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_78));
   CKAN2D0 p11422A3208__6417 (.A1(bus_wbuf[50]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_77));
   CKAN2D0 p11774A__5477 (.A1(FE_OFN2_bus_we_d1),
	.A2(bus_waddr_d1[1]),
	.Z(n_76));
   CKAN2D0 p11422A3209__2398 (.A1(bus_wbuf[52]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_75));
   CKAN2D0 p11422A3210__5107 (.A1(bus_wbuf[51]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_74));
   CKAN2D0 p11422A3211__6260 (.A1(bus_wbuf[46]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_73));
   CKAN2D0 p11422A3212__4319 (.A1(bus_wbuf[47]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_72));
   CKAN2D0 p11422A3213__8428 (.A1(bus_wbuf[0]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_71));
   CKAN2D0 p11422A3214__5526 (.A1(bus_wbuf[49]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_70));
   CKAN2D0 p11422A3215__6783 (.A1(bus_wbuf[4]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_69));
   CKAN2D0 p11422A3216__3680 (.A1(bus_wbuf[10]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_68));
   CKAN2D0 p11422A3217__1617 (.A1(bus_wbuf[8]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_67));
   CKAN2D0 p11422A3218__2802 (.A1(bus_wbuf[62]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_66));
   CKAN2D0 p11422A3219__1705 (.A1(bus_wbuf[31]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_65));
   CKAN2D0 p11422A3220__5122 (.A1(bus_wbuf[12]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_64));
   CKAN2D0 p11422A3221__8246 (.A1(bus_wbuf[39]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_63));
   CKAN2D0 p11422A3222__7098 (.A1(bus_wbuf[28]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_62));
   CKAN2D0 p11422A3223__6131 (.A1(bus_wbuf[16]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_61));
   CKAN2D0 p11422A3224__1881 (.A1(bus_wbuf[60]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_60));
   CKAN2D0 p11422A3225__5115 (.A1(bus_wbuf[44]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_59));
   CKAN2D0 p11422A3226__7482 (.A1(bus_wbuf[17]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_58));
   CKAN2D0 p11422A3227__4733 (.A1(bus_wbuf[42]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_57));
   CKAN2D0 p11422A3228__6161 (.A1(bus_wbuf[41]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_56));
   CKAN2D0 p11422A3229__9315 (.A1(bus_wbuf[32]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_55));
   CKAN2D0 p11422A3230__9945 (.A1(bus_wbuf[38]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_54));
   CKAN2D0 p11422A3231__2883 (.A1(bus_wbuf[36]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_53));
   CKAN2D0 p11422A3232__2346 (.A1(bus_wbuf[37]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_52));
   CKAN2D0 p11422A3233__1666 (.A1(bus_wbuf[35]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_51));
   CKAN2D0 p11774A3234__7410 (.A1(FE_OFN2_bus_we_d1),
	.A2(bus_waddr_d1[2]),
	.Z(n_50));
   CKAN2D0 p11422A3235__6417 (.A1(bus_wbuf[34]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_49));
   CKAN2D0 p11422A3236__5477 (.A1(bus_wbuf[11]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_48));
   CKAN2D0 p11422A3237__2398 (.A1(bus_wbuf[25]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_47));
   CKAN2D0 p11422A3238__5107 (.A1(bus_wbuf[40]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_46));
   CKAN2D0 p11422A3239__6260 (.A1(bus_wbuf[29]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_45));
   CKAN2D0 p11422A3240__4319 (.A1(bus_wbuf[18]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_44));
   CKAN2D0 p11422A3241__8428 (.A1(bus_wbuf[26]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_43));
   CKAN2D0 p11422A3242__5526 (.A1(bus_wbuf[48]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_42));
   CKAN2D0 p11422A3243__6783 (.A1(bus_wbuf[27]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_41));
   CKAN2D0 p11422A3244__3680 (.A1(bus_wbuf[19]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_40));
   CKAN2D0 p11422A3245__1617 (.A1(bus_wbuf[56]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_39));
   CKAN2D0 p11422A3246__2802 (.A1(bus_wbuf[23]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_38));
   CKAN2D0 p11422A3247__1705 (.A1(bus_wbuf[24]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_37));
   CKAN2D0 p11422A3248__5122 (.A1(bus_wbuf[20]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_36));
   CKAN2D0 p11422A3249__8246 (.A1(bus_wbuf[22]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_35));
   CKAN2D0 p11422A3250__7098 (.A1(bus_wbuf[21]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_34));
   CKAN2D0 p11422A3251__6131 (.A1(bus_wbuf[13]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_33));
   CKAN2D0 p11422A3252__1881 (.A1(bus_wbuf[15]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_32));
   CKAN2D0 p11422A3253__5115 (.A1(bus_wbuf[14]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_31));
   CKAN2D0 p11422A3254__7482 (.A1(bus_wbuf[9]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_30));
   CKAN2D0 p11422A3255__4733 (.A1(bus_wbuf[58]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_29));
   CKAN2D0 p11774A3256__6161 (.A1(FE_OFN2_bus_we_d1),
	.A2(bus_waddr_d1[6]),
	.Z(n_28));
   CKAN2D0 p11422A3257__9315 (.A1(bus_wbuf[5]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_27));
   CKAN2D0 p11422A3258__9945 (.A1(bus_wbuf[6]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_26));
   CKAN2D0 p11422A3259__2883 (.A1(bus_wbuf[7]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_25));
   CKAN2D0 p11422A3260__2346 (.A1(bus_wbuf[2]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_24));
   CKAN2D0 p11422A3261__1666 (.A1(bus_wbuf[3]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_23));
   CKAN2D0 p11774A3262__7410 (.A1(FE_OFN2_bus_we_d1),
	.A2(bus_waddr_d1[7]),
	.Z(n_22));
   CKAN2D0 p11422A3263__6417 (.A1(bus_wbuf[1]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_21));
   CKAN2D0 p11774A3264__5477 (.A1(FE_OFN2_bus_we_d1),
	.A2(bus_waddr_d1[8]),
	.Z(n_20));
   CKAN2D0 p11774A3265__2398 (.A1(FE_OFN2_bus_we_d1),
	.A2(bus_waddr_d1[4]),
	.Z(n_19));
   CKAN2D0 p11422A3266__5107 (.A1(bus_wbuf[57]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_18));
   CKAN2D0 p11774A3267__6260 (.A1(FE_OFN2_bus_we_d1),
	.A2(bus_waddr_d1[5]),
	.Z(n_17));
   CKAN2D0 p11774A3268__4319 (.A1(FE_OFN2_bus_we_d1),
	.A2(bus_waddr_d1[0]),
	.Z(n_16));
   CKAN2D0 p11774A3269__8428 (.A1(FE_OFN2_bus_we_d1),
	.A2(bus_waddr_d1[3]),
	.Z(n_15));
   CKAN2D0 p11422A3270__5526 (.A1(bus_wbuf[33]),
	.A2(FE_OFN2_bus_we_d1),
	.Z(n_14));
   CKND0 Fp23701A (.I(FE_PHN189_n_91),
	.ZN(n_13));
   IND2D1 p23616A__6783 (.A1(n_89),
	.B1(FE_PHN12_bus_addr_1),
	.ZN(n_91));
   IND2D0 p23543A__3680 (.A1(n_90),
	.B1(bus_addr[2]),
	.ZN(n_89));
   OR2D0 p11189A__1617 (.A1(sram_cen_ff),
	.A2(FE_OFN1_tpu_re),
	.Z(sram_wen));
   INR2D0 p11168A__2802 (.A1(sram_cen_ff),
	.B1(FE_OFN1_tpu_re),
	.ZN(sram_cen));
   CKND2D0 p23533A__1705 (.A1(FE_PHN14_bus_we),
	.A2(FE_PHN13_bus_addr_0),
	.ZN(n_90));
   DFXQD1 \bus_wbuf_reg[0]  (.CP(CTS_6),
	.DA(FE_PHN343_bus_wbuf_0),
	.DB(FE_PHN508_bus_din_0),
	.Q(bus_wbuf[0]),
	.SA(n_11));
   DFXQD1 \bus_wbuf_reg[1]  (.CP(CTS_6),
	.DA(FE_PHN44_bus_wbuf_1),
	.DB(FE_PHN438_bus_din_1),
	.Q(bus_wbuf[1]),
	.SA(n_11));
   DFXQD1 \bus_wbuf_reg[2]  (.CP(CTS_5),
	.DA(FE_PHN43_bus_wbuf_2),
	.DB(FE_PHN173_bus_din_2),
	.Q(bus_wbuf[2]),
	.SA(n_11));
   DFXQD1 \bus_wbuf_reg[3]  (.CP(CTS_5),
	.DA(FE_PHN41_bus_wbuf_3),
	.DB(FE_PHN437_bus_din_3),
	.Q(bus_wbuf[3]),
	.SA(n_11));
   DFXQD1 \bus_wbuf_reg[4]  (.CP(CTS_5),
	.DA(FE_PHN42_bus_wbuf_4),
	.DB(FE_PHN176_bus_din_4),
	.Q(bus_wbuf[4]),
	.SA(n_11));
   DFXQD1 \bus_wbuf_reg[5]  (.CP(CTS_5),
	.DA(FE_PHN37_bus_wbuf_5),
	.DB(FE_PHN521_bus_din_5),
	.Q(bus_wbuf[5]),
	.SA(n_11));
   DFXQD1 \bus_wbuf_reg[6]  (.CP(CTS_5),
	.DA(FE_PHN40_bus_wbuf_6),
	.DB(FE_PHN457_bus_din_6),
	.Q(bus_wbuf[6]),
	.SA(n_11));
   DFXQD1 \bus_wbuf_reg[7]  (.CP(CTS_5),
	.DA(FE_PHN39_bus_wbuf_7),
	.DB(FE_PHN179_bus_din_7),
	.Q(bus_wbuf[7]),
	.SA(n_11));
   DFXQD1 \bus_wbuf_reg[8]  (.CP(CTS_5),
	.DA(FE_PHN38_bus_wbuf_8),
	.DB(FE_PHN505_bus_din_0),
	.Q(bus_wbuf[8]),
	.SA(n_5));
   DFXQD1 \bus_wbuf_reg[9]  (.CP(CTS_5),
	.DA(FE_PHN35_bus_wbuf_9),
	.DB(FE_PHN458_bus_din_1),
	.Q(bus_wbuf[9]),
	.SA(n_5));
   DFXQD1 \bus_wbuf_reg[10]  (.CP(CTS_5),
	.DA(FE_PHN32_bus_wbuf_10),
	.DB(FE_PHN450_bus_din_2),
	.Q(bus_wbuf[10]),
	.SA(n_5));
   DFXQD1 \bus_wbuf_reg[11]  (.CP(CTS_5),
	.DA(FE_PHN36_bus_wbuf_11),
	.DB(FE_PHN437_bus_din_3),
	.Q(bus_wbuf[11]),
	.SA(n_5));
   DFXQD1 \bus_wbuf_reg[12]  (.CP(CTS_5),
	.DA(FE_PHN31_bus_wbuf_12),
	.DB(FE_PHN176_bus_din_4),
	.Q(bus_wbuf[12]),
	.SA(n_5));
   DFXQD1 \bus_wbuf_reg[13]  (.CP(CTS_5),
	.DA(FE_PHN33_bus_wbuf_13),
	.DB(FE_PHN521_bus_din_5),
	.Q(bus_wbuf[13]),
	.SA(n_5));
   DFXQD1 \bus_wbuf_reg[14]  (.CP(CTS_4),
	.DA(FE_PHN30_bus_wbuf_14),
	.DB(FE_PHN457_bus_din_6),
	.Q(bus_wbuf[14]),
	.SA(n_5));
   DFXQD1 \bus_wbuf_reg[15]  (.CP(CTS_4),
	.DA(FE_PHN34_bus_wbuf_15),
	.DB(FE_PHN179_bus_din_7),
	.Q(bus_wbuf[15]),
	.SA(n_5));
   DFXQD1 \bus_wbuf_reg[16]  (.CP(CTS_4),
	.DA(FE_PHN199_bus_wbuf_16),
	.DB(FE_PHN505_bus_din_0),
	.Q(bus_wbuf[16]),
	.SA(n_9));
   DFXQD1 \bus_wbuf_reg[17]  (.CP(CTS_4),
	.DA(FE_PHN204_bus_wbuf_17),
	.DB(FE_PHN458_bus_din_1),
	.Q(bus_wbuf[17]),
	.SA(n_9));
   DFXQD1 \bus_wbuf_reg[18]  (.CP(CTS_4),
	.DA(FE_PHN205_bus_wbuf_18),
	.DB(FE_PHN450_bus_din_2),
	.Q(bus_wbuf[18]),
	.SA(n_9));
   DFXQD1 \bus_wbuf_reg[19]  (.CP(CTS_4),
	.DA(FE_PHN193_bus_wbuf_19),
	.DB(FE_PHN526_bus_din_3),
	.Q(bus_wbuf[19]),
	.SA(n_9));
   DFXQD1 \bus_wbuf_reg[20]  (.CP(CTS_4),
	.DA(FE_PHN200_bus_wbuf_20),
	.DB(FE_PHN176_bus_din_4),
	.Q(bus_wbuf[20]),
	.SA(n_9));
   DFXQD1 \bus_wbuf_reg[21]  (.CP(CTS_4),
	.DA(FE_PHN201_bus_wbuf_21),
	.DB(FE_PHN538_bus_din_5),
	.Q(bus_wbuf[21]),
	.SA(n_9));
   DFXQD1 \bus_wbuf_reg[22]  (.CP(CTS_4),
	.DA(FE_PHN202_bus_wbuf_22),
	.DB(FE_PHN496_bus_din_6),
	.Q(bus_wbuf[22]),
	.SA(n_9));
   DFXQD1 \bus_wbuf_reg[23]  (.CP(CTS_4),
	.DA(FE_PHN196_bus_wbuf_23),
	.DB(FE_PHN179_bus_din_7),
	.Q(bus_wbuf[23]),
	.SA(n_9));
   DFXQD1 \bus_wbuf_reg[24]  (.CP(CTS_4),
	.DA(FE_PHN190_bus_wbuf_24),
	.DB(FE_PHN505_bus_din_0),
	.Q(bus_wbuf[24]),
	.SA(n_7));
   DFXQD1 \bus_wbuf_reg[25]  (.CP(CTS_9),
	.DA(FE_PHN197_bus_wbuf_25),
	.DB(FE_PHN458_bus_din_1),
	.Q(bus_wbuf[25]),
	.SA(n_7));
   DFXQD1 \bus_wbuf_reg[26]  (.CP(CTS_9),
	.DA(FE_PHN198_bus_wbuf_26),
	.DB(FE_PHN450_bus_din_2),
	.Q(bus_wbuf[26]),
	.SA(n_7));
   DFXQD1 \bus_wbuf_reg[27]  (.CP(CTS_9),
	.DA(FE_PHN203_bus_wbuf_27),
	.DB(FE_PHN428_bus_din_3),
	.Q(bus_wbuf[27]),
	.SA(n_7));
   DFXQD1 \bus_wbuf_reg[28]  (.CP(CTS_9),
	.DA(FE_PHN194_bus_wbuf_28),
	.DB(FE_PHN427_bus_din_4),
	.Q(bus_wbuf[28]),
	.SA(n_7));
   DFXQD1 \bus_wbuf_reg[29]  (.CP(CTS_9),
	.DA(FE_PHN195_bus_wbuf_29),
	.DB(FE_PHN524_bus_din_5),
	.Q(bus_wbuf[29]),
	.SA(n_7));
   DFXQD1 \bus_wbuf_reg[30]  (.CP(CTS_9),
	.DA(FE_PHN191_bus_wbuf_30),
	.DB(FE_PHN444_bus_din_6),
	.Q(bus_wbuf[30]),
	.SA(n_7));
   DFXQD1 \bus_wbuf_reg[31]  (.CP(CTS_9),
	.DA(FE_PHN192_bus_wbuf_31),
	.DB(FE_PHN426_bus_din_7),
	.Q(bus_wbuf[31]),
	.SA(n_7));
   DFXQD1 \bus_wbuf_reg[32]  (.CP(CTS_9),
	.DA(FE_PHN505_bus_din_0),
	.DB(FE_PHN217_bus_wbuf_32),
	.Q(bus_wbuf[32]),
	.SA(FE_PHN185_n_12));
   DFXQD1 \bus_wbuf_reg[33]  (.CP(CTS_3),
	.DA(FE_PHN458_bus_din_1),
	.DB(FE_PHN207_bus_wbuf_33),
	.Q(bus_wbuf[33]),
	.SA(FE_PHN185_n_12));
   DFXQD1 \bus_wbuf_reg[34]  (.CP(CTS_3),
	.DA(FE_PHN450_bus_din_2),
	.DB(FE_PHN208_bus_wbuf_34),
	.Q(bus_wbuf[34]),
	.SA(FE_PHN185_n_12));
   DFXQD1 \bus_wbuf_reg[35]  (.CP(CTS_3),
	.DA(FE_PHN441_bus_din_3),
	.DB(FE_PHN209_bus_wbuf_35),
	.Q(bus_wbuf[35]),
	.SA(FE_PHN185_n_12));
   DFXQD1 \bus_wbuf_reg[36]  (.CP(CTS_2),
	.DA(FE_PHN440_bus_din_4),
	.DB(FE_PHN210_bus_wbuf_36),
	.Q(bus_wbuf[36]),
	.SA(FE_PHN185_n_12));
   DFXQD1 \bus_wbuf_reg[37]  (.CP(CTS_2),
	.DA(FE_PHN525_bus_din_5),
	.DB(FE_PHN213_bus_wbuf_37),
	.Q(bus_wbuf[37]),
	.SA(FE_PHN185_n_12));
   DFXQD1 \bus_wbuf_reg[38]  (.CP(CTS_2),
	.DA(FE_PHN444_bus_din_6),
	.DB(FE_PHN214_bus_wbuf_38),
	.Q(bus_wbuf[38]),
	.SA(FE_PHN185_n_12));
   DFXQD1 \bus_wbuf_reg[39]  (.CP(CTS_2),
	.DA(FE_PHN426_bus_din_7),
	.DB(FE_PHN211_bus_wbuf_39),
	.Q(bus_wbuf[39]),
	.SA(FE_PHN185_n_12));
   DFXQD1 \bus_wbuf_reg[40]  (.CP(CTS_2),
	.DA(FE_PHN505_bus_din_0),
	.DB(FE_PHN212_bus_wbuf_40),
	.Q(bus_wbuf[40]),
	.SA(FE_PHN188_n_4));
   DFXQD1 \bus_wbuf_reg[41]  (.CP(CTS_2),
	.DA(FE_PHN458_bus_din_1),
	.DB(FE_PHN219_bus_wbuf_41),
	.Q(bus_wbuf[41]),
	.SA(FE_PHN188_n_4));
   DFXQD1 \bus_wbuf_reg[42]  (.CP(CTS_2),
	.DA(FE_PHN450_bus_din_2),
	.DB(FE_PHN215_bus_wbuf_42),
	.Q(bus_wbuf[42]),
	.SA(FE_PHN188_n_4));
   DFXQD1 \bus_wbuf_reg[43]  (.CP(CTS_2),
	.DA(FE_PHN441_bus_din_3),
	.DB(FE_PHN220_bus_wbuf_43),
	.Q(bus_wbuf[43]),
	.SA(FE_PHN188_n_4));
   DFXQD1 \bus_wbuf_reg[44]  (.CP(CTS_2),
	.DA(FE_PHN440_bus_din_4),
	.DB(FE_PHN216_bus_wbuf_44),
	.Q(bus_wbuf[44]),
	.SA(FE_PHN188_n_4));
   DFXQD1 \bus_wbuf_reg[45]  (.CP(CTS_2),
	.DA(FE_PHN522_bus_din_5),
	.DB(FE_PHN218_bus_wbuf_45),
	.Q(bus_wbuf[45]),
	.SA(FE_PHN188_n_4));
   DFXQD1 \bus_wbuf_reg[46]  (.CP(CTS_1),
	.DA(FE_PHN444_bus_din_6),
	.DB(FE_PHN221_bus_wbuf_46),
	.Q(bus_wbuf[46]),
	.SA(FE_PHN188_n_4));
   DFXQD1 \bus_wbuf_reg[47]  (.CP(CTS_1),
	.DA(FE_PHN426_bus_din_7),
	.DB(FE_PHN222_bus_wbuf_47),
	.Q(bus_wbuf[47]),
	.SA(FE_PHN188_n_4));
   DFXQD1 \bus_wbuf_reg[48]  (.CP(CTS_1),
	.DA(FE_PHN505_bus_din_0),
	.DB(FE_PHN22_bus_wbuf_48),
	.Q(bus_wbuf[48]),
	.SA(FE_PHN186_n_10));
   DFXQD1 \bus_wbuf_reg[49]  (.CP(CTS_1),
	.DA(FE_PHN458_bus_din_1),
	.DB(FE_PHN23_bus_wbuf_49),
	.Q(bus_wbuf[49]),
	.SA(FE_PHN186_n_10));
   DFXQD1 \bus_wbuf_reg[50]  (.CP(CTS_1),
	.DA(FE_PHN450_bus_din_2),
	.DB(FE_PHN27_bus_wbuf_50),
	.Q(bus_wbuf[50]),
	.SA(FE_PHN186_n_10));
   DFXQD1 \bus_wbuf_reg[51]  (.CP(CTS_1),
	.DA(FE_PHN441_bus_din_3),
	.DB(FE_PHN25_bus_wbuf_51),
	.Q(bus_wbuf[51]),
	.SA(FE_PHN186_n_10));
   DFXQD1 \bus_wbuf_reg[52]  (.CP(CTS_1),
	.DA(FE_PHN440_bus_din_4),
	.DB(FE_PHN24_bus_wbuf_52),
	.Q(bus_wbuf[52]),
	.SA(FE_PHN186_n_10));
   DFXQD1 \bus_wbuf_reg[53]  (.CP(CTS_1),
	.DA(FE_PHN522_bus_din_5),
	.DB(FE_PHN28_bus_wbuf_53),
	.Q(bus_wbuf[53]),
	.SA(FE_PHN186_n_10));
   DFXQD1 \bus_wbuf_reg[54]  (.CP(CTS_10),
	.DA(FE_PHN444_bus_din_6),
	.DB(FE_PHN29_bus_wbuf_54),
	.Q(bus_wbuf[54]),
	.SA(FE_PHN186_n_10));
   DFXQD1 \bus_wbuf_reg[55]  (.CP(CTS_10),
	.DA(FE_PHN426_bus_din_7),
	.DB(FE_PHN26_bus_wbuf_55),
	.Q(bus_wbuf[55]),
	.SA(FE_PHN186_n_10));
   DFXQD1 \bus_wbuf_reg[56]  (.CP(CTS_1),
	.DA(FE_PHN224_bus_wbuf_56),
	.DB(FE_PHN505_bus_din_0),
	.Q(bus_wbuf[56]),
	.SA(FE_PHN189_n_91));
   DFXQD1 \bus_wbuf_reg[57]  (.CP(CTS_1),
	.DA(FE_PHN230_bus_wbuf_57),
	.DB(FE_PHN458_bus_din_1),
	.Q(bus_wbuf[57]),
	.SA(FE_PHN189_n_91));
   DFXQD1 \bus_wbuf_reg[58]  (.CP(CTS_1),
	.DA(FE_PHN229_bus_wbuf_58),
	.DB(FE_PHN450_bus_din_2),
	.Q(bus_wbuf[58]),
	.SA(FE_PHN189_n_91));
   DFXQD1 \bus_wbuf_reg[59]  (.CP(CTS_1),
	.DA(FE_PHN228_bus_wbuf_59),
	.DB(FE_PHN441_bus_din_3),
	.Q(bus_wbuf[59]),
	.SA(FE_PHN189_n_91));
   DFXQD1 \bus_wbuf_reg[60]  (.CP(CTS_1),
	.DA(FE_PHN226_bus_wbuf_60),
	.DB(FE_PHN440_bus_din_4),
	.Q(bus_wbuf[60]),
	.SA(FE_PHN189_n_91));
   DFXQD1 \bus_wbuf_reg[61]  (.CP(CTS_10),
	.DA(FE_PHN227_bus_wbuf_61),
	.DB(FE_PHN522_bus_din_5),
	.Q(bus_wbuf[61]),
	.SA(FE_PHN189_n_91));
   DFXQD1 \bus_wbuf_reg[62]  (.CP(CTS_10),
	.DA(FE_PHN223_bus_wbuf_62),
	.DB(FE_PHN444_bus_din_6),
	.Q(bus_wbuf[62]),
	.SA(FE_PHN189_n_91));
   DFXQD1 \bus_wbuf_reg[63]  (.CP(CTS_10),
	.DA(FE_PHN225_bus_wbuf_63),
	.DB(FE_PHN426_bus_din_7),
	.Q(bus_wbuf[63]),
	.SA(FE_PHN189_n_91));
   DFNSND1 sram_cen_ff_reg (.CPN(CTS_9),
	.D(n_1),
	.Q(sram_cen_ff),
	.QN(UNCONNECTED72),
	.SDN(rstn));
   NR2D1 p23572A__5122 (.A1(FE_PHN307_n_8),
	.A2(FE_PHN12_bus_addr_1),
	.ZN(n_12));
   ND2D1 p23649A__8246 (.A1(FE_PHN184_n_6),
	.A2(n_0),
	.ZN(n_11));
   NR2D2 p23572A3363__7098 (.A1(n_8),
	.A2(n_0),
	.ZN(n_10));
   CKND2D0 p23649A3364__6131 (.A1(FE_PHN184_n_6),
	.A2(FE_PHN235_bus_addr_1),
	.ZN(n_9));
   CKND2D0 p23566A__1881 (.A1(n_2),
	.A2(FE_PHN413_bus_addr_2),
	.ZN(n_8));
   ND2D0 p23658A__5115 (.A1(FE_PHN181_n_3),
	.A2(FE_PHN235_bus_addr_1),
	.ZN(n_7));
   INR2D0 p23607A__7482 (.A1(n_2),
	.B1(bus_addr[2]),
	.ZN(n_6));
   CKND2D0 p23658A3365__4733 (.A1(FE_PHN181_n_3),
	.A2(n_0),
	.ZN(n_5));
   NR2XD0 p23566A3367__6161 (.A1(n_89),
	.A2(FE_PHN12_bus_addr_1),
	.ZN(n_4));
   NR2D0 p23639A__9315 (.A1(n_90),
	.A2(FE_PHN514_bus_addr_2),
	.ZN(n_3));
   INR2D0 p23529A__9945 (.A1(FE_PHN14_bus_we),
	.B1(FE_PHN13_bus_addr_0),
	.ZN(n_2));
   CKND0 Fp23597A (.I(FE_PHN235_bus_addr_1),
	.ZN(n_0));
   DFCND1 bus_we_d1_reg (.CDN(FE_PHN21_rstn),
	.CP(CTS_9),
	.D(n_13),
	.Q(bus_we_d1),
	.QN(n_1));
endmodule

