/*
###############################################################
#  Generated by:      Cadence Innovus 21.16-s078_1
#  OS:                Linux x86_64(Host ID cadpc19)
#  Generated on:      Sun Mar 22 14:17:38 2026
#  Design:            output_idx_controller
#  Command:           write_netlist ../output/output_idx_controller.funct.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.16-s062_1
// Generated on: Mar 22 2026 14:07:19 EDT (Mar 22 2026 18:07:19 UTC)
// Verification Directory fv/output_idx_controller 
module output_idx_controller (
	clk, 
	rstn, 
	alu_init, 
	in_valid, 
	row_idx, 
	num_computation, 
	m, 
	k, 
	c_row_idx, 
	c_col_idx, 
	done_flag);
   input clk;
   input rstn;
   input alu_init;
   input in_valid;
   input [2:0] row_idx;
   input [6:0] num_computation;
   input [6:0] m;
   input [6:0] k;
   output [8:0] c_row_idx;
   output [8:0] c_col_idx;
   output done_flag;

   // Internal wires
   wire FE_PHN78_c_row_idx_1;
   wire FE_PHN76_c_row_idx_0;
   wire FE_PHN74_c_row_idx_2;
   wire FE_PHN73_rstn;
   wire FE_PHN72_n_5;
   wire FE_PHN71_n_6;
   wire FE_PHN70_n_181;
   wire FE_PHN69_n_171;
   wire FE_PHN68_n_168;
   wire FE_PHN67_n_167;
   wire FE_PHN66_n_176;
   wire FE_PHN65_n_160;
   wire FE_PHN64_n_170;
   wire FE_PHN63_n_190;
   wire FE_PHN62_n_179;
   wire FE_PHN61_FE_OFN3_c_col_idx_7;
   wire FE_PHN60_FE_OFN5_c_col_idx_6;
   wire FE_PHN59_FE_OFN1_c_col_idx_8;
   wire FE_PHN58_n_71;
   wire FE_PHN57_n_107;
   wire FE_PHN56_n_145;
   wire FE_PHN55_n_157;
   wire FE_PHN54_n_189;
   wire FE_PHN53_n_186;
   wire FE_PHN52_done_flag_166;
   wire FE_RN_4;
   wire FE_RN_3;
   wire FE_RN_2;
   wire FE_PHN48_n_250;
   wire FE_PHN47_c_col_os_5;
   wire FE_PHN46_c_col_os_4;
   wire FE_PHN45_c_col_idx_temp_4;
   wire FE_PHN44_n_4;
   wire FE_PHN43_n_5;
   wire FE_PHN42_n_6;
   wire FE_PHN41_n_24;
   wire FE_PHN40_c_col_os_6;
   wire FE_PHN39_c_col_idx_temp_5;
   wire FE_PHN38_n_15;
   wire FE_PHN37_n_18;
   wire FE_PHN36_n_14;
   wire FE_PHN35_n_0;
   wire FE_PHN34_n_16;
   wire FE_PHN33_n_17;
   wire FE_PHN32_c_col_os_3;
   wire FE_PHN31_n_232;
   wire FE_PHN30_n_238;
   wire FE_PHN29_c_col_idx_temp_6;
   wire FE_PHN28_c_col_idx_temp_7;
   wire FE_PHN27_c_col_idx_temp_3;
   wire FE_PHN26_num_computated_1;
   wire FE_PHN25_num_computated_6;
   wire FE_PHN24_n_109;
   wire FE_PHN23_num_computated_0;
   wire FE_PHN22_num_computated_3;
   wire FE_PHN21_num_computated_5;
   wire FE_PHN20_n_32;
   wire FE_PHN19_u_out_ac_i_4;
   wire FE_PHN18_u_out_ac_i_3;
   wire FE_PHN17_rstn;
   wire FE_OFN16_c_col_idx_2;
   wire FE_OFN15_c_col_idx_1;
   wire FE_OFN14_c_col_idx_0;
   wire CTS_1;
   wire CTS_3;
   wire CTS_2;
   wire n_10;
   wire n_8;
   wire n_3;
   wire FE_OFN13_n_190;
   wire FE_OFN12_c_col_idx_3;
   wire FE_OFN11_c_col_idx_3;
   wire FE_OFN10_c_col_idx_4;
   wire FE_OFN9_c_col_idx_4;
   wire FE_OFN8_c_col_idx_5;
   wire FE_OFN7_c_col_idx_5;
   wire FE_OFN6_c_col_idx_6;
   wire FE_OFN5_c_col_idx_6;
   wire FE_OFN4_c_col_idx_7;
   wire FE_OFN3_c_col_idx_7;
   wire FE_OFN2_c_col_idx_8;
   wire FE_OFN1_c_col_idx_8;
   wire [8:0] c_col_os;
   wire [6:0] num_computated;
   wire [8:0] c_col_idx_temp;
   wire [8:0] u_out_ac_i;
   wire done_flag_166;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_9;
   wire n_12;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_47;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_73;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_93;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_99;
   wire n_100;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_232;
   wire n_238;
   wire n_250;
   wire n_254;
   wire n_255;

   assign c_row_idx[0] = FE_RN_3 ;
   assign c_row_idx[1] = FE_RN_4 ;
   assign c_row_idx[2] = FE_RN_2 ;

   BUFFD12 FE_PHC79_c_row_idx_1 (.I(FE_PHN78_c_row_idx_1),
	.Z(FE_RN_4));
   BUFFD12 FE_PHC77_c_row_idx_0 (.I(FE_PHN76_c_row_idx_0),
	.Z(FE_RN_3));
   BUFFD12 FE_PHC75_c_row_idx_2 (.I(FE_PHN74_c_row_idx_2),
	.Z(FE_RN_2));
   DEL01 FE_PHC73_rstn (.I(rstn),
	.Z(FE_PHN73_rstn));
   DEL015 FE_PHC72_n_5 (.I(FE_PHN43_n_5),
	.Z(FE_PHN72_n_5));
   DEL015 FE_PHC71_n_6 (.I(FE_PHN42_n_6),
	.Z(FE_PHN71_n_6));
   DEL0 FE_PHC70_n_181 (.I(n_181),
	.Z(FE_PHN70_n_181));
   DEL0 FE_PHC69_n_171 (.I(n_171),
	.Z(FE_PHN69_n_171));
   DEL0 FE_PHC68_n_168 (.I(n_168),
	.Z(FE_PHN68_n_168));
   DEL0 FE_PHC67_n_167 (.I(n_167),
	.Z(FE_PHN67_n_167));
   DEL0 FE_PHC66_n_176 (.I(n_176),
	.Z(FE_PHN66_n_176));
   DEL0 FE_PHC65_n_160 (.I(n_160),
	.Z(FE_PHN65_n_160));
   DEL0 FE_PHC64_n_170 (.I(n_170),
	.Z(FE_PHN64_n_170));
   DEL015 FE_PHC63_n_190 (.I(n_190),
	.Z(FE_PHN63_n_190));
   DEL0 FE_PHC62_n_179 (.I(n_179),
	.Z(FE_PHN62_n_179));
   DEL01 FE_PHC61_FE_OFN3_c_col_idx_7 (.I(FE_OFN3_c_col_idx_7),
	.Z(FE_PHN61_FE_OFN3_c_col_idx_7));
   DEL01 FE_PHC60_FE_OFN5_c_col_idx_6 (.I(FE_OFN5_c_col_idx_6),
	.Z(FE_PHN60_FE_OFN5_c_col_idx_6));
   DEL01 FE_PHC59_FE_OFN1_c_col_idx_8 (.I(FE_OFN1_c_col_idx_8),
	.Z(FE_PHN59_FE_OFN1_c_col_idx_8));
   CKBD0 FE_PHC58_n_71 (.I(n_71),
	.Z(FE_PHN58_n_71));
   DEL0 FE_PHC57_n_107 (.I(n_107),
	.Z(FE_PHN57_n_107));
   DEL0 FE_PHC56_n_145 (.I(n_145),
	.Z(FE_PHN56_n_145));
   DEL0 FE_PHC55_n_157 (.I(n_157),
	.Z(FE_PHN55_n_157));
   DEL0 FE_PHC54_n_189 (.I(n_189),
	.Z(FE_PHN54_n_189));
   DEL0 FE_PHC53_n_186 (.I(n_186),
	.Z(FE_PHN53_n_186));
   DEL0 FE_PHC52_done_flag_166 (.I(done_flag_166),
	.Z(FE_PHN52_done_flag_166));
   BUFFD12 FE_PHC51_c_row_idx_1 (.I(row_idx[1]),
	.Z(FE_PHN78_c_row_idx_1));
   BUFFD12 FE_PHC50_c_row_idx_0 (.I(row_idx[0]),
	.Z(FE_PHN76_c_row_idx_0));
   BUFFD12 FE_PHC49_c_row_idx_2 (.I(row_idx[2]),
	.Z(FE_PHN74_c_row_idx_2));
   DEL0 FE_PHC48_n_250 (.I(n_250),
	.Z(FE_PHN48_n_250));
   DEL0 FE_PHC47_c_col_os_5 (.I(c_col_os[5]),
	.Z(FE_PHN47_c_col_os_5));
   DEL0 FE_PHC46_c_col_os_4 (.I(c_col_os[4]),
	.Z(FE_PHN46_c_col_os_4));
   DEL0 FE_PHC45_c_col_idx_temp_4 (.I(c_col_idx_temp[4]),
	.Z(FE_PHN45_c_col_idx_temp_4));
   DEL0 FE_PHC44_n_4 (.I(n_4),
	.Z(FE_PHN44_n_4));
   CKBD0 FE_PHC43_n_5 (.I(n_5),
	.Z(FE_PHN43_n_5));
   CKBD0 FE_PHC42_n_6 (.I(n_6),
	.Z(FE_PHN42_n_6));
   DEL0 FE_PHC41_n_24 (.I(n_24),
	.Z(FE_PHN41_n_24));
   DEL0 FE_PHC40_c_col_os_6 (.I(c_col_os[6]),
	.Z(FE_PHN40_c_col_os_6));
   DEL0 FE_PHC39_c_col_idx_temp_5 (.I(c_col_idx_temp[5]),
	.Z(FE_PHN39_c_col_idx_temp_5));
   DEL0 FE_PHC38_n_15 (.I(n_15),
	.Z(FE_PHN38_n_15));
   DEL0 FE_PHC37_n_18 (.I(n_18),
	.Z(FE_PHN37_n_18));
   DEL0 FE_PHC36_n_14 (.I(n_14),
	.Z(FE_PHN36_n_14));
   DEL0 FE_PHC35_n_0 (.I(n_0),
	.Z(FE_PHN35_n_0));
   DEL0 FE_PHC34_n_16 (.I(n_16),
	.Z(FE_PHN34_n_16));
   DEL015 FE_PHC33_n_17 (.I(n_17),
	.Z(FE_PHN33_n_17));
   DEL0 FE_PHC32_c_col_os_3 (.I(c_col_os[3]),
	.Z(FE_PHN32_c_col_os_3));
   DEL0 FE_PHC31_n_232 (.I(n_232),
	.Z(FE_PHN31_n_232));
   DEL0 FE_PHC30_n_238 (.I(n_238),
	.Z(FE_PHN30_n_238));
   DEL0 FE_PHC29_c_col_idx_temp_6 (.I(c_col_idx_temp[6]),
	.Z(FE_PHN29_c_col_idx_temp_6));
   DEL0 FE_PHC28_c_col_idx_temp_7 (.I(c_col_idx_temp[7]),
	.Z(FE_PHN28_c_col_idx_temp_7));
   DEL0 FE_PHC27_c_col_idx_temp_3 (.I(c_col_idx_temp[3]),
	.Z(FE_PHN27_c_col_idx_temp_3));
   DEL0 FE_PHC26_num_computated_1 (.I(num_computated[1]),
	.Z(FE_PHN26_num_computated_1));
   DEL0 FE_PHC25_num_computated_6 (.I(num_computated[6]),
	.Z(FE_PHN25_num_computated_6));
   DEL0 FE_PHC24_n_109 (.I(n_109),
	.Z(FE_PHN24_n_109));
   DEL0 FE_PHC23_num_computated_0 (.I(num_computated[0]),
	.Z(FE_PHN23_num_computated_0));
   DEL0 FE_PHC22_num_computated_3 (.I(num_computated[3]),
	.Z(FE_PHN22_num_computated_3));
   DEL0 FE_PHC21_num_computated_5 (.I(num_computated[5]),
	.Z(FE_PHN21_num_computated_5));
   DEL0 FE_PHC20_n_32 (.I(n_32),
	.Z(FE_PHN20_n_32));
   DEL0 FE_PHC19_u_out_ac_i_4 (.I(u_out_ac_i[4]),
	.Z(FE_PHN19_u_out_ac_i_4));
   DEL0 FE_PHC18_u_out_ac_i_3 (.I(u_out_ac_i[3]),
	.Z(FE_PHN18_u_out_ac_i_3));
   BUFFD1 FE_PHC17_rstn (.I(FE_PHN73_rstn),
	.Z(FE_PHN17_rstn));
   BUFFD12 FE_OFC16_c_col_idx_2 (.I(FE_OFN16_c_col_idx_2),
	.Z(c_col_idx[2]));
   BUFFD12 FE_OFC15_c_col_idx_1 (.I(FE_OFN15_c_col_idx_1),
	.Z(c_col_idx[1]));
   BUFFD12 FE_OFC14_c_col_idx_0 (.I(FE_OFN14_c_col_idx_0),
	.Z(c_col_idx[0]));
   CKND2 CTS_ccl_a_inv_00002 (.I(CTS_1),
	.ZN(CTS_3));
   CKND1 CTS_ccl_a_inv_00001 (.I(CTS_1),
	.ZN(CTS_2));
   CKND1 CTS_cmf_inv_00050 (.I(clk),
	.ZN(CTS_1));
   TIEL LTIELO_2 (.ZN(FE_OFN14_c_col_idx_0));
   TIEL LTIELO_1 (.ZN(FE_OFN15_c_col_idx_1));
   TIEL LTIELO (.ZN(FE_OFN16_c_col_idx_2));
   CKBD1 FE_OFC13_n_190 (.I(FE_PHN63_n_190),
	.Z(FE_OFN13_n_190));
   CKND12 FE_OFC12_c_col_idx_3 (.I(FE_OFN12_c_col_idx_3),
	.ZN(c_col_idx[3]));
   INVD1 FE_OFC11_c_col_idx_3 (.I(FE_OFN11_c_col_idx_3),
	.ZN(FE_OFN12_c_col_idx_3));
   CKND12 FE_OFC10_c_col_idx_4 (.I(FE_OFN10_c_col_idx_4),
	.ZN(c_col_idx[4]));
   INVD1 FE_OFC9_c_col_idx_4 (.I(FE_OFN9_c_col_idx_4),
	.ZN(FE_OFN10_c_col_idx_4));
   CKND12 FE_OFC8_c_col_idx_5 (.I(FE_OFN8_c_col_idx_5),
	.ZN(c_col_idx[5]));
   INVD1 FE_OFC7_c_col_idx_5 (.I(FE_OFN7_c_col_idx_5),
	.ZN(FE_OFN8_c_col_idx_5));
   CKND12 FE_OFC6_c_col_idx_6 (.I(FE_OFN6_c_col_idx_6),
	.ZN(c_col_idx[6]));
   INVD1 FE_OFC5_c_col_idx_6 (.I(FE_PHN60_FE_OFN5_c_col_idx_6),
	.ZN(FE_OFN6_c_col_idx_6));
   CKND12 FE_OFC4_c_col_idx_7 (.I(FE_OFN4_c_col_idx_7),
	.ZN(c_col_idx[7]));
   INVD1 FE_OFC3_c_col_idx_7 (.I(FE_PHN61_FE_OFN3_c_col_idx_7),
	.ZN(FE_OFN4_c_col_idx_7));
   CKND12 FE_OFC2_c_col_idx_8 (.I(FE_OFN2_c_col_idx_8),
	.ZN(c_col_idx[8]));
   INVD1 FE_OFC1_c_col_idx_8 (.I(FE_PHN59_FE_OFN1_c_col_idx_8),
	.ZN(FE_OFN2_c_col_idx_8));
   EDFKCNQD1 \c_col_os_reg[8]  (.CN(FE_PHN17_rstn),
	.CP(CTS_3),
	.D(FE_PHN54_n_189),
	.E(FE_OFN13_n_190),
	.Q(c_col_os[8]));
   MOAI22D0 p18291A__2398 (.A1(n_188),
	.A2(n_187),
	.B1(n_188),
	.B2(n_187),
	.ZN(n_189));
   DFKCNQD1 \num_computated_reg[5]  (.CN(FE_PHN17_rstn),
	.CP(CTS_2),
	.D(n_185),
	.Q(num_computated[5]));
   DFKCNQD1 \num_computated_reg[1]  (.CN(FE_PHN17_rstn),
	.CP(CTS_2),
	.D(n_182),
	.Q(num_computated[1]));
   DFKCNQD1 \num_computated_reg[3]  (.CN(FE_PHN17_rstn),
	.CP(CTS_2),
	.D(n_184),
	.Q(num_computated[3]));
   DFKCNQD1 \c_col_os_reg[3]  (.CN(FE_PHN17_rstn),
	.CP(CTS_2),
	.D(FE_PHN70_n_181),
	.Q(c_col_os[3]));
   DFKCNQD1 \num_computated_reg[0]  (.CN(FE_PHN17_rstn),
	.CP(CTS_2),
	.D(n_180),
	.Q(num_computated[0]));
   FA1D0 p18250A__5107 (.A(c_col_os[7]),
	.B(k[4]),
	.CI(n_156),
	.CO(n_188),
	.S(n_186));
   IOA21D0 p18246A3671__6260 (.A1(n_183),
	.A2(FE_PHN21_num_computated_5),
	.B(n_163),
	.ZN(n_185));
   IOA21D0 p18246A3670__4319 (.A1(n_183),
	.A2(FE_PHN22_num_computated_3),
	.B(n_165),
	.ZN(n_184));
   IOA21D0 p18246A3669__8428 (.A1(n_183),
	.A2(FE_PHN26_num_computated_1),
	.B(n_164),
	.ZN(n_182));
   IOA21D0 p18246A__5526 (.A1(n_183),
	.A2(FE_PHN32_c_col_os_3),
	.B(n_162),
	.ZN(n_181));
   EDFKCNQD1 \num_computated_reg[6]  (.CN(FE_PHN17_rstn),
	.CP(CTS_2),
	.D(n_137),
	.E(FE_OFN13_n_190),
	.Q(num_computated[6]));
   EDFKCNQD1 \c_col_os_reg[5]  (.CN(FE_PHN17_rstn),
	.CP(CTS_3),
	.D(FE_PHN56_n_145),
	.E(FE_OFN13_n_190),
	.Q(c_col_os[5]));
   EDFKCNQD1 \c_col_os_reg[4]  (.CN(FE_PHN17_rstn),
	.CP(CTS_3),
	.D(FE_PHN57_n_107),
	.E(FE_OFN13_n_190),
	.Q(c_col_os[4]));
   MUX2ND0 p18240A__6783 (.I0(n_183),
	.I1(FE_OFN13_n_190),
	.S(FE_PHN23_num_computated_0),
	.ZN(n_180));
   AO22D0 p18289A3679__3680 (.A1(n_178),
	.A2(n_121),
	.B1(n_177),
	.B2(c_col_idx_temp[8]),
	.Z(n_179));
   MOAI22D0 p18332A3678__1617 (.A1(FE_PHN64_n_170),
	.A2(n_206),
	.B1(n_175),
	.B2(u_out_ac_i[8]),
	.ZN(n_176));
   AO22D0 p18289A3680__2802 (.A1(n_178),
	.A2(n_31),
	.B1(n_177),
	.B2(FE_PHN45_c_col_idx_temp_4),
	.Z(n_174));
   AO22D0 p18289A3681__1705 (.A1(n_178),
	.A2(n_44),
	.B1(n_177),
	.B2(FE_PHN39_c_col_idx_temp_5),
	.Z(n_173));
   AO22D0 p18289A3682__5122 (.A1(n_178),
	.A2(n_63),
	.B1(n_177),
	.B2(FE_PHN29_c_col_idx_temp_6),
	.Z(n_172));
   MOAI22D0 p18332A3683__8246 (.A1(FE_PHN64_n_170),
	.A2(n_210),
	.B1(n_175),
	.B2(u_out_ac_i[5]),
	.ZN(n_171));
   MOAI22D0 p18332A__7098 (.A1(FE_PHN64_n_170),
	.A2(n_147),
	.B1(n_175),
	.B2(FE_PHN19_u_out_ac_i_4),
	.ZN(n_169));
   MOAI22D0 p18332A3676__6131 (.A1(FE_PHN64_n_170),
	.A2(n_209),
	.B1(n_175),
	.B2(u_out_ac_i[6]),
	.ZN(n_168));
   MOAI22D0 p18332A3677__1881 (.A1(FE_PHN64_n_170),
	.A2(n_207),
	.B1(n_175),
	.B2(u_out_ac_i[7]),
	.ZN(n_167));
   AO22D0 p18289A__5115 (.A1(n_178),
	.A2(n_96),
	.B1(n_177),
	.B2(FE_PHN28_c_col_idx_temp_7),
	.Z(n_166));
   OAI211D0 p18222A__7482 (.A1(FE_PHN22_num_computated_3),
	.A2(n_58),
	.B(FE_OFN13_n_190),
	.C(n_110),
	.ZN(n_165));
   OAI211D0 p18222A3674__4733 (.A1(FE_PHN23_num_computated_0),
	.A2(FE_PHN26_num_computated_1),
	.B(FE_OFN13_n_190),
	.C(n_59),
	.ZN(n_164));
   OAI211D0 p18222A3675__6161 (.A1(FE_PHN21_num_computated_5),
	.A2(n_108),
	.B(FE_OFN13_n_190),
	.C(n_136),
	.ZN(n_163));
   OAI211D0 p18221A__9315 (.A1(k[0]),
	.A2(FE_PHN32_c_col_os_3),
	.B(FE_OFN13_n_190),
	.C(n_20),
	.ZN(n_162));
   CKND0 Fp18296A (.I(FE_PHN64_n_170),
	.ZN(n_161));
   OAI31D0 p18260A__9945 (.A1(n_155),
	.A2(n_158),
	.A3(n_159),
	.B(FE_PHN17_rstn),
	.ZN(n_160));
   CKND0 Fp18200A (.I(FE_OFN13_n_190),
	.ZN(n_183));
   IND3D0 p18227A__2883 (.A1(n_159),
	.B1(FE_PHN17_rstn),
	.B2(n_158),
	.ZN(n_170));
   NR2D0 p18251A__2346 (.A1(n_154),
	.A2(n_177),
	.ZN(n_178));
   FA1D0 p18212A__1666 (.A(FE_PHN40_c_col_os_6),
	.B(k[3]),
	.CI(n_144),
	.CO(n_156),
	.S(n_157));
   INR3D0 p17878A__7410 (.A1(n_155),
	.B1(n_158),
	.B2(n_159),
	.ZN(n_190));
   CKND0 Fp18257A (.I(n_154),
	.ZN(n_175));
   CKND2D0 p18258A__6417 (.A1(n_159),
	.A2(FE_PHN17_rstn),
	.ZN(n_154));
   OAI211D0 p17867A__5477 (.A1(m[6]),
	.A2(n_124),
	.B(n_148),
	.C(n_125),
	.ZN(n_158));
   OR2XD1 p13248A__2398 (.A1(n_151),
	.A2(n_152),
	.Z(FE_OFN1_c_col_idx_8));
   ND4D0 p17946A__5107 (.A1(n_143),
	.A2(n_131),
	.A3(n_127),
	.A4(n_115),
	.ZN(n_155));
   OAI211D0 p17850A__6260 (.A1(k[0]),
	.A2(FE_PHN27_c_col_idx_temp_3),
	.B(n_142),
	.C(FE_PHN58_n_71),
	.ZN(n_159));
   NR2D0 p13239A__4319 (.A1(n_150),
	.A2(n_149),
	.ZN(n_152));
   CKAN2D0 p13247A__8428 (.A1(n_150),
	.A2(n_149),
	.Z(n_151));
   AOI221D0 p17717A__5526 (.A1(n_132),
	.A2(n_133),
	.B1(n_147),
	.B2(m[1]),
	.C(n_134),
	.ZN(n_148));
   OR2XD1 p13293A__6783 (.A1(n_141),
	.A2(n_139),
	.Z(FE_OFN3_c_col_idx_7));
   FA1D0 p18170A__3680 (.A(FE_PHN47_c_col_os_5),
	.B(k[2]),
	.CI(n_106),
	.CO(n_144),
	.S(n_145));
   IOA21D0 p13222A__1617 (.A1(n_140),
	.A2(n_40),
	.B(n_39),
	.ZN(n_150));
   AOI221D0 p17922A__2802 (.A1(n_12),
	.A2(n_9),
	.B1(FE_PHN22_num_computated_3),
	.B2(n_128),
	.C(n_129),
	.ZN(n_143));
   AN4D0 p17815A__1705 (.A1(n_126),
	.A2(n_79),
	.A3(n_99),
	.A4(n_83),
	.Z(n_142));
   CKAN2D0 p13290A__5122 (.A1(n_140),
	.A2(n_138),
	.Z(n_141));
   NR2D0 p13282A__8246 (.A1(n_140),
	.A2(n_138),
	.ZN(n_139));
   MOAI22D0 p18366A__7098 (.A1(n_136),
	.A2(FE_PHN25_num_computated_6),
	.B1(n_136),
	.B2(FE_PHN25_num_computated_6),
	.ZN(n_137));
   OR2XD1 p13336A__6131 (.A1(n_117),
	.A2(n_119),
	.Z(FE_OFN5_c_col_idx_6));
   OAI211D0 p17705A__1881 (.A1(n_133),
	.A2(n_132),
	.B(n_114),
	.C(n_86),
	.ZN(n_134));
   MAOI22D0 p18007A__5115 (.A1(FE_PHN21_num_computated_5),
	.A2(n_130),
	.B1(FE_PHN21_num_computated_5),
	.B2(n_130),
	.ZN(n_131));
   OAI211D0 p17928A__7482 (.A1(n_128),
	.A2(FE_PHN22_num_computated_3),
	.B(n_102),
	.C(n_104),
	.ZN(n_129));
   IOA21D0 p13197A__4733 (.A1(n_118),
	.A2(n_38),
	.B(n_37),
	.ZN(n_140));
   MUX2ND0 p18008A__6161 (.I0(FE_PHN24_n_109),
	.I1(num_computated[4]),
	.S(n_105),
	.ZN(n_127));
   AOI211D0 p17772A__9315 (.A1(n_81),
	.A2(n_80),
	.B(n_100),
	.C(n_91),
	.ZN(n_126));
   AOI211D0 p17875A__9945 (.A1(n_124),
	.A2(m[6]),
	.B(n_208),
	.C(n_211),
	.ZN(n_125));
   MOAI22D0 p18432A__2346 (.A1(n_120),
	.A2(c_col_idx_temp[8]),
	.B1(n_120),
	.B2(c_col_idx_temp[8]),
	.ZN(n_121));
   CKAN2D0 p13327A__1666 (.A1(n_118),
	.A2(n_116),
	.Z(n_119));
   NR2D0 p13336A3684__7410 (.A1(n_118),
	.A2(n_116),
	.ZN(n_117));
   XNR3D0 p17951A__6417 (.A1(n_113),
	.A2(num_computation[6]),
	.A3(FE_PHN25_num_computated_6),
	.ZN(n_115));
   OA221D0 p17613A__5477 (.A1(n_147),
	.A2(m[1]),
	.B1(n_67),
	.B2(n_68),
	.C(n_69),
	.Z(n_114));
   AOI21D0 p18185A__2398 (.A1(n_76),
	.A2(num_computation[5]),
	.B(n_113),
	.ZN(n_130));
   OR2XD1 p13383A__5107 (.A1(n_75),
	.A2(n_88),
	.Z(FE_OFN7_c_col_idx_5));
   AOI21D0 p18395A__6260 (.A1(n_110),
	.A2(FE_PHN24_n_109),
	.B(n_108),
	.ZN(n_111));
   CKND2D0 p18368A__4319 (.A1(n_108),
	.A2(FE_PHN21_num_computated_5),
	.ZN(n_136));
   FA1D0 p18107A__8428 (.A(FE_PHN46_c_col_os_4),
	.B(k[1]),
	.CI(n_21),
	.CO(n_106),
	.S(n_107));
   AOI21D0 p18189A__5526 (.A1(n_61),
	.A2(num_computation[4]),
	.B(n_70),
	.ZN(n_105));
   MAOI22D0 p17929A__6783 (.A1(num_computated[2]),
	.A2(n_103),
	.B1(num_computated[2]),
	.B2(n_103),
	.ZN(n_104));
   AOI221D0 p17815A3685__3680 (.A1(FE_PHN23_num_computated_0),
	.A2(num_computation[0]),
	.B1(FE_PHN26_num_computated_1),
	.B2(n_55),
	.C(n_56),
	.ZN(n_102));
   OAI21D0 p13185A__1617 (.A1(n_87),
	.A2(n_33),
	.B(n_34),
	.ZN(n_118));
   OR2XD1 p13399A__2802 (.A1(n_254),
	.A2(n_52),
	.Z(FE_OFN9_c_col_idx_4));
   OAI221D0 p17709A__1705 (.A1(n_65),
	.A2(n_64),
	.B1(FE_PHN27_c_col_idx_temp_3),
	.B2(n_82),
	.C(n_66),
	.ZN(n_100));
   AOI221D0 p17736A__5122 (.A1(FE_PHN27_c_col_idx_temp_3),
	.A2(k[0]),
	.B1(n_53),
	.B2(k[6]),
	.C(n_54),
	.ZN(n_99));
   MOAI22D0 p18469A__7098 (.A1(n_95),
	.A2(FE_PHN28_c_col_idx_temp_7),
	.B1(n_95),
	.B2(FE_PHN28_c_col_idx_temp_7),
	.ZN(n_96));
   MOAI22D0 p17777A__1881 (.A1(n_90),
	.A2(n_89),
	.B1(n_90),
	.B2(n_89),
	.ZN(n_91));
   NR2D0 p13375A__5115 (.A1(n_87),
	.A2(n_41),
	.ZN(n_88));
   MAOI22D0 p17700A__7482 (.A1(n_85),
	.A2(n_84),
	.B1(n_85),
	.B2(n_84),
	.ZN(n_86));
   MAOI22D0 p17835A__4733 (.A1(n_82),
	.A2(FE_PHN27_c_col_idx_temp_3),
	.B1(n_81),
	.B2(n_80),
	.ZN(n_83));
   MAOI22D0 p17830A__6161 (.A1(n_78),
	.A2(n_77),
	.B1(n_78),
	.B2(n_77),
	.ZN(n_79));
   NR2D0 p18118A__9315 (.A1(n_76),
	.A2(num_computation[5]),
	.ZN(n_113));
   IND2D0 p18451A__9945 (.A1(n_97),
	.B1(u_out_ac_i[7]),
	.ZN(n_122));
   IND2D0 p18415A__2883 (.A1(n_95),
	.B1(FE_PHN28_c_col_idx_temp_7),
	.ZN(n_120));
   NR2D0 p18339A__2346 (.A1(n_110),
	.A2(FE_PHN24_n_109),
	.ZN(n_108));
   NR2D0 p13380A__1666 (.A1(n_57),
	.A2(n_42),
	.ZN(n_75));
   NR2D0 p18724A__5477 (.A1(FE_PHN58_n_71),
	.A2(n_2),
	.ZN(n_177));
   CKND0 Fp18114A (.I(n_76),
	.ZN(n_70));
   CKND2D0 p17629A__2398 (.A1(n_68),
	.A2(n_67),
	.ZN(n_69));
   CKND2D0 p17726A__5107 (.A1(n_65),
	.A2(n_64),
	.ZN(n_66));
   MOAI22D0 p18487A__6260 (.A1(n_62),
	.A2(FE_PHN29_c_col_idx_temp_6),
	.B1(n_62),
	.B2(FE_PHN29_c_col_idx_temp_6),
	.ZN(n_63));
   OA21D0 p18177A__4319 (.A1(n_50),
	.A2(n_49),
	.B(n_61),
	.Z(n_128));
   AOI21D0 p18449A__8428 (.A1(n_59),
	.A2(FE_PHN20_n_32),
	.B(n_58),
	.ZN(n_60));
   CKND0 Fp13166A (.I(n_57),
	.ZN(n_87));
   IND2D0 p18396A__5526 (.A1(n_73),
	.B1(u_out_ac_i[6]),
	.ZN(n_97));
   IND2D0 p18365A__6783 (.A1(n_62),
	.B1(FE_PHN29_c_col_idx_temp_6),
	.ZN(n_95));
   CKND2D0 p18328A__3680 (.A1(n_58),
	.A2(FE_PHN22_num_computated_3),
	.ZN(n_110));
   NR2D0 p17833A__1617 (.A1(FE_PHN26_num_computated_1),
	.A2(n_55),
	.ZN(n_56));
   NR2D0 p17756A__2802 (.A1(n_53),
	.A2(k[6]),
	.ZN(n_54));
   NR2D0 p13392A__1705 (.A1(n_47),
	.A2(n_51),
	.ZN(n_52));
   AOI21D0 p18162A__5122 (.A1(n_23),
	.A2(num_computation[2]),
	.B(n_50),
	.ZN(n_103));
   IND3D0 p18080A__8246 (.A1(num_computation[4]),
	.B1(n_49),
	.B2(n_50),
	.ZN(n_76));
   MOAI22D0 p18524A3686__6131 (.A1(n_43),
	.A2(FE_PHN39_c_col_idx_temp_5),
	.B1(n_43),
	.B2(FE_PHN39_c_col_idx_temp_5),
	.ZN(n_44));
   CKND0 Fp13384A (.I(n_41),
	.ZN(n_42));
   CKND2D0 p18183A__1881 (.A1(n_50),
	.A2(n_49),
	.ZN(n_61));
   CKND2D0 p13383A3688__5115 (.A1(n_40),
	.A2(n_39),
	.ZN(n_138));
   INR2D0 p18288A__7482 (.A1(FE_PHN74_c_row_idx_2),
	.B1(n_19),
	.ZN(n_71));
   CKND2D0 p13388A__4733 (.A1(n_38),
	.A2(n_37),
	.ZN(n_116));
   OAI21D0 p13168A__6161 (.A1(n_27),
	.A2(n_51),
	.B(n_28),
	.ZN(n_57));
   AN2XD1 p13473A__9315 (.A1(n_255),
	.A2(n_51),
	.Z(FE_OFN11_c_col_idx_3));
   AOI21D0 p17750A__9945 (.A1(FE_PHN33_n_17),
	.A2(k[2]),
	.B(n_64),
	.ZN(n_90));
   AOI21D0 p17713A__2883 (.A1(FE_PHN38_n_15),
	.A2(k[3]),
	.B(n_80),
	.ZN(n_65));
   AOI21D0 p17703A__2346 (.A1(FE_PHN36_n_14),
	.A2(k[1]),
	.B(n_89),
	.ZN(n_82));
   AOI21D0 p17778A__1666 (.A1(FE_PHN34_n_16),
	.A2(k[5]),
	.B(n_29),
	.ZN(n_78));
   AOI21D0 p17782A__7410 (.A1(FE_PHN37_n_18),
	.A2(k[4]),
	.B(n_77),
	.ZN(n_81));
   AOI21D0 p17644A__6417 (.A1(FE_PHN43_n_5),
	.A2(m[4]),
	.B(n_30),
	.ZN(n_85));
   AO21D0 p17756A3691__5477 (.A1(FE_PHN44_n_4),
	.A2(m[2]),
	.B(n_67),
	.Z(n_132));
   AOI21D0 p17609A__2398 (.A1(FE_PHN42_n_6),
	.A2(m[3]),
	.B(n_84),
	.ZN(n_68));
   AOI21D0 p17833A3689__5107 (.A1(FE_PHN35_n_0),
	.A2(m[5]),
	.B(n_35),
	.ZN(n_93));
   CKND0 Fp17843A (.I(n_35),
	.ZN(n_124));
   INR2D0 p13356A__6260 (.A1(n_34),
	.B1(n_33),
	.ZN(n_41));
   NR2D0 p18299A__4319 (.A1(n_59),
	.A2(FE_PHN20_n_32),
	.ZN(n_58));
   IND2D0 p18332A3687__8428 (.A1(n_43),
	.B1(FE_PHN39_c_col_idx_temp_5),
	.ZN(n_62));
   IND2D0 p18362A__5526 (.A1(n_45),
	.B1(u_out_ac_i[5]),
	.ZN(n_73));
   MUX2ND0 p18532A__6783 (.I0(FE_PHN41_n_24),
	.I1(FE_PHN27_c_col_idx_temp_3),
	.S(FE_PHN45_c_col_idx_temp_4),
	.ZN(n_31));
   AOI21D0 p18070A__3680 (.A1(num_computation[1]),
	.A2(num_computation[0]),
	.B(n_22),
	.ZN(n_55));
   CKND0 Fp17729A (.I(n_29),
	.ZN(n_53));
   INR2D0 p13360A__1617 (.A1(n_28),
	.B1(n_27),
	.ZN(n_47));
   OAI21D0 p17648A__2802 (.A1(c_row_idx[3]),
	.A2(c_row_idx[4]),
	.B(n_45),
	.ZN(n_147));
   CKND0 Fp18082A (.I(n_22),
	.ZN(n_23));
   CKND0 Fp18131A (.I(n_20),
	.ZN(n_21));
   ND4D0 p18274A__8246 (.A1(FE_PHN76_c_row_idx_0),
	.A2(FE_PHN78_c_row_idx_1),
	.A3(alu_init),
	.A4(in_valid),
	.ZN(n_19));
   CKND2D0 p13343A__7098 (.A1(FE_PHN37_n_18),
	.A2(n_7),
	.ZN(n_40));
   NR2D0 p17586A__6131 (.A1(FE_PHN42_n_6),
	.A2(m[3]),
	.ZN(n_84));
   NR2D0 p17741A__1881 (.A1(FE_PHN33_n_17),
	.A2(k[2]),
	.ZN(n_64));
   NR3D0 p18008A3690__5115 (.A1(num_computation[0]),
	.A2(num_computation[2]),
	.A3(num_computation[1]),
	.ZN(n_50));
   MOAI22D0 p18431A__7482 (.A1(c_col_os[8]),
	.A2(k[5]),
	.B1(c_col_os[8]),
	.B2(k[5]),
	.ZN(n_187));
   MOAI22D0 p13377A__4733 (.A1(c_col_idx_temp[8]),
	.A2(c_col_os[8]),
	.B1(c_col_idx_temp[8]),
	.B2(c_col_os[8]),
	.ZN(n_149));
   NR2D0 p17825A__6161 (.A1(FE_PHN35_n_0),
	.A2(m[5]),
	.ZN(n_35));
   NR2D0 p17734A__9315 (.A1(FE_PHN34_n_16),
	.A2(k[5]),
	.ZN(n_29));
   NR2D0 p17647A__9945 (.A1(FE_PHN43_n_5),
	.A2(m[4]),
	.ZN(n_30));
   CKND2D0 p13274A__2883 (.A1(FE_PHN38_n_15),
	.A2(n_1),
	.ZN(n_38));
   NR2D0 p17634A__2346 (.A1(FE_PHN44_n_4),
	.A2(m[2]),
	.ZN(n_67));
   NR2D0 p17711A__1666 (.A1(FE_PHN36_n_14),
	.A2(k[1]),
	.ZN(n_89));
   NR2D0 p17790A__7410 (.A1(FE_PHN37_n_18),
	.A2(k[4]),
	.ZN(n_77));
   NR2D0 p17689A__6417 (.A1(FE_PHN38_n_15),
	.A2(k[3]),
	.ZN(n_80));
   CKND2D0 p18107A3692__5477 (.A1(FE_PHN32_c_col_os_3),
	.A2(k[0]),
	.ZN(n_20));
   CKND2D0 p13177A__2398 (.A1(FE_PHN46_c_col_os_4),
	.A2(FE_PHN45_c_col_idx_temp_4),
	.ZN(n_28));
   NR2D0 p13166A__5107 (.A1(FE_PHN46_c_col_os_4),
	.A2(FE_PHN45_c_col_idx_temp_4),
	.ZN(n_27));
   NR2D0 p18081A__6260 (.A1(num_computation[1]),
	.A2(num_computation[0]),
	.ZN(n_22));
   CKND2D0 p18319A__4319 (.A1(FE_PHN45_c_col_idx_temp_4),
	.A2(FE_PHN27_c_col_idx_temp_3),
	.ZN(n_43));
   CKND2D0 p13132A__8428 (.A1(FE_PHN32_c_col_os_3),
	.A2(FE_PHN27_c_col_idx_temp_3),
	.ZN(n_51));
   NR2D0 p13216A__5526 (.A1(FE_PHN39_c_col_idx_temp_5),
	.A2(FE_PHN47_c_col_os_5),
	.ZN(n_33));
   IND2D0 p17794A__6783 (.A1(m[1]),
	.B1(c_row_idx[4]),
	.ZN(n_133));
   CKND2D0 p13310A__3680 (.A1(FE_PHN40_c_col_os_6),
	.A2(FE_PHN29_c_col_idx_temp_6),
	.ZN(n_37));
   CKND2D0 p13374A__1617 (.A1(c_col_os[7]),
	.A2(FE_PHN28_c_col_idx_temp_7),
	.ZN(n_39));
   CKND2D0 p13233A__2802 (.A1(FE_PHN47_c_col_os_5),
	.A2(FE_PHN39_c_col_idx_temp_5),
	.ZN(n_34));
   CKND2D0 p18282A__1705 (.A1(FE_PHN23_num_computated_0),
	.A2(FE_PHN26_num_computated_1),
	.ZN(n_59));
   CKND2D0 p17641A__5122 (.A1(FE_PHN19_u_out_ac_i_4),
	.A2(FE_PHN18_u_out_ac_i_3),
	.ZN(n_45));
   CKND0 Fp18292A (.I(FE_PHN23_num_computated_0),
	.ZN(n_12));
   CKND0 Fp18018A (.I(num_computation[0]),
	.ZN(n_9));
   CKND0 Fp18786A (.I(FE_PHN17_rstn),
	.ZN(n_2));
   CKND0 Fp18100A (.I(num_computation[3]),
	.ZN(n_49));
   CKXOR2D0 g2 (.A1(n_122),
	.A2(c_row_idx[8]),
	.Z(n_206));
   CKXOR2D0 g3724 (.A1(n_97),
	.A2(u_out_ac_i[7]),
	.Z(n_207));
   XNR2D0 g3725 (.A1(n_93),
	.A2(n_30),
	.ZN(n_208));
   CKXOR2D0 g3726 (.A1(n_73),
	.A2(u_out_ac_i[6]),
	.Z(n_209));
   CKXOR2D0 g3727 (.A1(n_45),
	.A2(u_out_ac_i[5]),
	.Z(n_210));
   XNR2D0 g3728 (.A1(c_row_idx[3]),
	.A2(m[0]),
	.ZN(n_211));
   INVD12 drc_bufs3729 (.I(FE_PHN44_n_4),
	.ZN(c_row_idx[5]));
   INVD12 drc_bufs3735 (.I(FE_PHN71_n_6),
	.ZN(c_row_idx[6]));
   INVD12 drc_bufs3741 (.I(FE_PHN72_n_5),
	.ZN(c_row_idx[7]));
   CKND12 drc_bufs3747 (.I(FE_PHN31_n_232),
	.ZN(c_row_idx[3]));
   INVD12 drc_bufs3753 (.I(FE_PHN30_n_238),
	.ZN(c_row_idx[4]));
   INVD12 drc_bufs3759 (.I(FE_PHN35_n_0),
	.ZN(c_row_idx[8]));
   INVD12 drc_bufs3765 (.I(FE_PHN48_n_250),
	.ZN(done_flag));
   EDFKCND1 \c_col_os_reg[7]  (.CN(FE_PHN17_rstn),
	.CP(CTS_3),
	.D(FE_PHN53_n_186),
	.E(FE_OFN13_n_190),
	.Q(c_col_os[7]),
	.QN(n_7));
   DFD1 \u_out_ac_j_reg[8]  (.CP(CTS_3),
	.D(FE_PHN62_n_179),
	.Q(c_col_idx_temp[8]),
	.QN(n_16));
   DFXD1 \u_out_ac_j_reg[3]  (.CP(CTS_3),
	.DA(n_177),
	.DB(n_178),
	.Q(c_col_idx_temp[3]),
	.QN(n_24),
	.SA(FE_PHN27_c_col_idx_temp_3));
   EDFKCND1 \num_computated_reg[2]  (.CN(FE_PHN17_rstn),
	.CP(CTS_2),
	.D(n_60),
	.E(FE_OFN13_n_190),
	.Q(num_computated[2]),
	.QN(n_32));
   DFD1 \u_out_ac_j_reg[6]  (.CP(CTS_3),
	.D(n_172),
	.Q(c_col_idx_temp[6]),
	.QN(n_15));
   EDFKCND1 \c_col_os_reg[6]  (.CN(FE_PHN17_rstn),
	.CP(CTS_3),
	.D(FE_PHN55_n_157),
	.E(FE_OFN13_n_190),
	.Q(c_col_os[6]),
	.QN(n_1));
   DFD1 \u_out_ac_j_reg[5]  (.CP(CTS_3),
	.D(n_173),
	.Q(c_col_idx_temp[5]),
	.QN(n_17));
   DFD1 \u_out_ac_j_reg[4]  (.CP(CTS_3),
	.D(n_174),
	.Q(c_col_idx_temp[4]),
	.QN(n_14));
   DFD1 \u_out_ac_j_reg[7]  (.CP(CTS_3),
	.D(n_166),
	.Q(c_col_idx_temp[7]),
	.QN(n_18));
   EDFKCND1 \num_computated_reg[4]  (.CN(FE_PHN17_rstn),
	.CP(CTS_2),
	.D(n_111),
	.E(FE_OFN13_n_190),
	.Q(num_computated[4]),
	.QN(n_109));
   DFD1 \u_out_ac_i_reg[5]  (.CP(CTS_3),
	.D(FE_PHN69_n_171),
	.Q(u_out_ac_i[5]),
	.QN(n_4));
   DFD1 \u_out_ac_i_reg[6]  (.CP(CTS_3),
	.D(FE_PHN68_n_168),
	.Q(u_out_ac_i[6]),
	.QN(n_6));
   DFD1 \u_out_ac_i_reg[7]  (.CP(CTS_3),
	.D(FE_PHN67_n_167),
	.Q(u_out_ac_i[7]),
	.QN(n_5));
   DFXD1 \u_out_ac_i_reg[3]  (.CP(CTS_3),
	.DA(n_175),
	.DB(n_161),
	.Q(u_out_ac_i[3]),
	.QN(n_232),
	.SA(FE_PHN18_u_out_ac_i_3));
   DFD1 \u_out_ac_i_reg[4]  (.CP(CTS_2),
	.D(n_169),
	.Q(u_out_ac_i[4]),
	.QN(n_238));
   DFD1 \u_out_ac_i_reg[8]  (.CP(CTS_3),
	.D(FE_PHN66_n_176),
	.Q(u_out_ac_i[8]),
	.QN(n_0));
   DFXD1 done_flag_reg (.CP(CTS_2),
	.DA(FE_PHN17_rstn),
	.DB(FE_PHN52_done_flag_166),
	.Q(done_flag_166),
	.QN(n_250),
	.SA(FE_PHN65_n_160));
   CKAN2D0 g3804 (.A1(n_51),
	.A2(n_47),
	.Z(n_254));
   IND2D0 g3805 (.A1(FE_PHN32_c_col_os_3),
	.B1(FE_PHN41_n_24),
	.ZN(n_255));
endmodule

