
// Generated by Cadence Genus(TM) Synthesis Solution 21.16-s062_1
// Generated on: Apr 27 2026 20:53:19 EDT (Apr 28 2026 00:53:19 UTC)

// Verification Directory fv/bus_slave_sram_c 

module bus_slave_sram_c(clk, rstn, chip_chc_start, chip_chc_rd,
     chip_chc_rdata, tpu_c_we, tpu_c_addr, tpu_c_din, sc_mem_ctrl,
     sc_cen, sc_wen, sc_addr, sc_din, sc_mem_dout);
  input clk, rstn, chip_chc_start, chip_chc_rd, tpu_c_we, sc_mem_ctrl,
       sc_cen, sc_wen;
  input [8:0] tpu_c_addr, sc_addr;
  input [63:0] tpu_c_din, sc_din;
  output [7:0] chip_chc_rdata;
  output [63:0] sc_mem_dout;
  wire clk, rstn, chip_chc_start, chip_chc_rd, tpu_c_we, sc_mem_ctrl,
       sc_cen, sc_wen;
  wire [8:0] tpu_c_addr, sc_addr;
  wire [63:0] tpu_c_din, sc_din;
  wire [7:0] chip_chc_rdata;
  wire [63:0] sc_mem_dout;
  wire [8:0] u_sram_c_mux_addr;
  wire [63:0] u_sram_c_mux_din;
  wire [63:0] u_sram_c_sram_q;
  wire [11:0] sram_c_addr;
  wire [2:0] u_sram_c_bus_byte_sel_d1;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_153, n_154, n_155, n_156, n_157;
  wire n_158, n_159, n_160, sram_c_re, u_sram_c_mux_cen,
       u_sram_c_mux_wen;
  sram00 u_sram_c_u_sram(.CLK (clk), .CEN (u_sram_c_mux_cen), .WEN
       (u_sram_c_mux_wen), .A (u_sram_c_mux_addr), .D
       (u_sram_c_mux_din), .EMA (3'b10), .RETN (1'b1), .Q
       ({u_sram_c_sram_q[63:8], n_153, n_154, n_155, n_156, n_157,
       n_158, n_159, n_160}));
  CKBD8 Fp16257A1764(.I (u_sram_c_sram_q[62]), .Z (sc_mem_dout[62]));
  CKBD8 Fp16248A1759(.I (u_sram_c_sram_q[36]), .Z (sc_mem_dout[36]));
  CKBD8 Fp16248A1761(.I (u_sram_c_sram_q[35]), .Z (sc_mem_dout[35]));
  CKBD8 Fp16259A1762(.I (u_sram_c_sram_q[34]), .Z (sc_mem_dout[34]));
  CKBD8 Fp16248A1763(.I (u_sram_c_sram_q[33]), .Z (sc_mem_dout[33]));
  CKBD8 Fp16245A1766(.I (u_sram_c_sram_q[32]), .Z (sc_mem_dout[32]));
  CKBD8 Fp16259A1767(.I (u_sram_c_sram_q[31]), .Z (sc_mem_dout[31]));
  CKBD8 Fp16263A1769(.I (u_sram_c_sram_q[30]), .Z (sc_mem_dout[30]));
  CKBD8 Fp16257A1770(.I (u_sram_c_sram_q[29]), .Z (sc_mem_dout[29]));
  CKBD8 Fp16257A1773(.I (u_sram_c_sram_q[28]), .Z (sc_mem_dout[28]));
  CKBD8 Fp16263A1789(.I (u_sram_c_sram_q[27]), .Z (sc_mem_dout[27]));
  CKBD8 Fp16263A1776(.I (u_sram_c_sram_q[26]), .Z (sc_mem_dout[26]));
  CKBD8 Fp16263A1777(.I (u_sram_c_sram_q[25]), .Z (sc_mem_dout[25]));
  CKBD8 Fp16257A1760(.I (u_sram_c_sram_q[63]), .Z (sc_mem_dout[63]));
  CKBD8 Fp16271A1780(.I (u_sram_c_sram_q[24]), .Z (sc_mem_dout[24]));
  CKBD8 Fp16248A1781(.I (u_sram_c_sram_q[23]), .Z (sc_mem_dout[23]));
  CKBD8 Fp16248A(.I (u_sram_c_sram_q[37]), .Z (sc_mem_dout[37]));
  CKBD8 Fp16251A1783(.I (u_sram_c_sram_q[22]), .Z (sc_mem_dout[22]));
  CKBD8 Fp16245A1784(.I (u_sram_c_sram_q[21]), .Z (sc_mem_dout[21]));
  CKBD8 Fp16263A1771(.I (u_sram_c_sram_q[61]), .Z (sc_mem_dout[61]));
  CKBD8 Fp16245A1787(.I (u_sram_c_sram_q[20]), .Z (sc_mem_dout[20]));
  CKBD8 Fp16251A1788(.I (u_sram_c_sram_q[19]), .Z (sc_mem_dout[19]));
  CKBD8 Fp16263A1778(.I (u_sram_c_sram_q[60]), .Z (sc_mem_dout[60]));
  CKBD8 Fp16251A1790(.I (u_sram_c_sram_q[18]), .Z (sc_mem_dout[18]));
  CKBD8 Fp16251A1791(.I (u_sram_c_sram_q[17]), .Z (sc_mem_dout[17]));
  CKBD8 Fp16257A1785(.I (u_sram_c_sram_q[59]), .Z (sc_mem_dout[59]));
  CKBD8 Fp16259A1793(.I (u_sram_c_sram_q[16]), .Z (sc_mem_dout[16]));
  CKBD8 Fp16271A1794(.I (u_sram_c_sram_q[15]), .Z (sc_mem_dout[15]));
  CKBD8 Fp16257A1795(.I (u_sram_c_sram_q[58]), .Z (sc_mem_dout[58]));
  CKBD8 Fp16271A1796(.I (u_sram_c_sram_q[14]), .Z (sc_mem_dout[14]));
  CKBD8 Fp16271A1798(.I (u_sram_c_sram_q[13]), .Z (sc_mem_dout[13]));
  CKBD8 Fp16257A1802(.I (u_sram_c_sram_q[57]), .Z (sc_mem_dout[57]));
  CKBD8 Fp16259A1758(.I (n_159), .Z (sc_mem_dout[1]));
  CKBD8 Fp16271A1803(.I (u_sram_c_sram_q[11]), .Z (sc_mem_dout[11]));
  CKBD8 Fp16263A(.I (u_sram_c_sram_q[56]), .Z (sc_mem_dout[56]));
  CKBD8 Fp16259A1799(.I (u_sram_c_sram_q[10]), .Z (sc_mem_dout[10]));
  CKBD8 Fp16271A(.I (u_sram_c_sram_q[9]), .Z (sc_mem_dout[9]));
  CKBD8 Fp16245A(.I (u_sram_c_sram_q[55]), .Z (sc_mem_dout[55]));
  CKBD8 Fp16259A(.I (u_sram_c_sram_q[8]), .Z (sc_mem_dout[8]));
  CKBD8 Fp16259A1748(.I (n_153), .Z (sc_mem_dout[7]));
  CKBD8 Fp16245A1756(.I (u_sram_c_sram_q[54]), .Z (sc_mem_dout[54]));
  CKBD8 Fp16259A1749(.I (n_154), .Z (sc_mem_dout[6]));
  CKBD8 Fp16259A1751(.I (n_155), .Z (sc_mem_dout[5]));
  CKBD8 Fp16251A1750(.I (u_sram_c_sram_q[53]), .Z (sc_mem_dout[53]));
  CKBD8 Fp16259A1754(.I (n_156), .Z (sc_mem_dout[4]));
  CKBD8 Fp16259A1755(.I (n_157), .Z (sc_mem_dout[3]));
  CKBD8 Fp16251A1765(.I (u_sram_c_sram_q[52]), .Z (sc_mem_dout[52]));
  CKBD8 Fp16248A1757(.I (n_158), .Z (sc_mem_dout[2]));
  CKBD8 Fp16271A1801(.I (u_sram_c_sram_q[12]), .Z (sc_mem_dout[12]));
  CKBD8 Fp16245A1768(.I (u_sram_c_sram_q[51]), .Z (sc_mem_dout[51]));
  CKBD8 Fp16248A1752(.I (n_160), .Z (sc_mem_dout[0]));
  CKBD8 Fp16245A1772(.I (u_sram_c_sram_q[50]), .Z (sc_mem_dout[50]));
  CKBD8 Fp16245A1775(.I (u_sram_c_sram_q[49]), .Z (sc_mem_dout[49]));
  CKBD8 Fp16251A1779(.I (u_sram_c_sram_q[48]), .Z (sc_mem_dout[48]));
  CKBD8 Fp16263A1782(.I (u_sram_c_sram_q[47]), .Z (sc_mem_dout[47]));
  CKBD8 Fp16259A1786(.I (u_sram_c_sram_q[46]), .Z (sc_mem_dout[46]));
  CKBD8 Fp16259A1774(.I (u_sram_c_sram_q[45]), .Z (sc_mem_dout[45]));
  CKBD8 Fp16259A1792(.I (u_sram_c_sram_q[44]), .Z (sc_mem_dout[44]));
  CKBD8 Fp16259A1797(.I (u_sram_c_sram_q[43]), .Z (sc_mem_dout[43]));
  CKBD8 Fp16271A1800(.I (u_sram_c_sram_q[42]), .Z (sc_mem_dout[42]));
  CKBD8 Fp16259A1804(.I (u_sram_c_sram_q[41]), .Z (sc_mem_dout[41]));
  CKBD8 Fp16257A(.I (u_sram_c_sram_q[40]), .Z (sc_mem_dout[40]));
  CKBD8 Fp16251A(.I (u_sram_c_sram_q[39]), .Z (sc_mem_dout[39]));
  CKBD8 Fp16248A1753(.I (u_sram_c_sram_q[38]), .Z (sc_mem_dout[38]));
  DFND1 u_slave_c_chc_rd_s_reg(.CPN (clk), .D (n_41), .Q (sram_c_re),
       .QN (UNCONNECTED));
  DFKCNQD1 \u_sram_c_bus_byte_sel_d1_reg[0] (.CP (clk), .CN (rstn), .D
       (sram_c_addr[0]), .Q (u_sram_c_bus_byte_sel_d1[0]));
  DFKCNQD1 \u_sram_c_bus_byte_sel_d1_reg[1] (.CP (clk), .CN (rstn), .D
       (sram_c_addr[1]), .Q (u_sram_c_bus_byte_sel_d1[1]));
  DFKCNQD1 \u_sram_c_bus_byte_sel_d1_reg[2] (.CP (clk), .CN (rstn), .D
       (sram_c_addr[2]), .Q (u_sram_c_bus_byte_sel_d1[2]));
  ND4D8 p16253A__2398(.A1 (n_71), .A2 (n_84), .A3 (n_82), .A4 (n_81),
       .ZN (chip_chc_rdata[2]));
  ND4D8 p16253A4459__5107(.A1 (n_76), .A2 (n_68), .A3 (n_63), .A4
       (n_61), .ZN (chip_chc_rdata[6]));
  ND4D8 p16253A4460__6260(.A1 (n_59), .A2 (n_73), .A3 (n_86), .A4
       (n_57), .ZN (chip_chc_rdata[7]));
  ND4D8 p16253A4461__4319(.A1 (n_80), .A2 (n_78), .A3 (n_77), .A4
       (n_74), .ZN (chip_chc_rdata[1]));
  ND4D8 p16252A__8428(.A1 (n_56), .A2 (n_85), .A3 (n_83), .A4 (n_79),
       .ZN (chip_chc_rdata[5]));
  ND4D8 p16252A4462__5526(.A1 (n_69), .A2 (n_72), .A3 (n_67), .A4
       (n_65), .ZN (chip_chc_rdata[0]));
  ND4D8 p16252A4463__6783(.A1 (n_55), .A2 (n_75), .A3 (n_66), .A4
       (n_64), .ZN (chip_chc_rdata[4]));
  ND4D8 p16253A4464__3680(.A1 (n_60), .A2 (n_62), .A3 (n_58), .A4
       (n_70), .ZN (chip_chc_rdata[3]));
  AOI22D0 p16250A__1617(.A1 (u_sram_c_sram_q[31]), .A2 (n_49), .B1
       (u_sram_c_sram_q[23]), .B2 (n_51), .ZN (n_86));
  AOI22D0 p16253A4465__2802(.A1 (u_sram_c_sram_q[61]), .A2 (n_50), .B1
       (u_sram_c_sram_q[53]), .B2 (n_48), .ZN (n_85));
  AOI22D0 p16253A4466__1705(.A1 (u_sram_c_sram_q[26]), .A2 (n_49), .B1
       (u_sram_c_sram_q[18]), .B2 (n_51), .ZN (n_84));
  AOI22D0 p16250A4467__5122(.A1 (u_sram_c_sram_q[45]), .A2 (n_54), .B1
       (u_sram_c_sram_q[37]), .B2 (n_52), .ZN (n_83));
  AOI22D0 p16250A4468__8246(.A1 (u_sram_c_sram_q[10]), .A2 (n_53), .B1
       (n_158), .B2 (n_47), .ZN (n_82));
  AOI22D0 p16247A__7098(.A1 (u_sram_c_sram_q[58]), .A2 (n_50), .B1
       (u_sram_c_sram_q[50]), .B2 (n_48), .ZN (n_81));
  AOI22D0 p16261A__6131(.A1 (u_sram_c_sram_q[9]), .A2 (n_53), .B1
       (n_159), .B2 (n_47), .ZN (n_80));
  AOI22D0 p16247A4469__1881(.A1 (u_sram_c_sram_q[29]), .A2 (n_49), .B1
       (u_sram_c_sram_q[21]), .B2 (n_51), .ZN (n_79));
  AOI22D0 p16253A4470__5115(.A1 (u_sram_c_sram_q[25]), .A2 (n_49), .B1
       (u_sram_c_sram_q[17]), .B2 (n_51), .ZN (n_78));
  AOI22D0 p16250A4471__7482(.A1 (u_sram_c_sram_q[41]), .A2 (n_54), .B1
       (u_sram_c_sram_q[33]), .B2 (n_52), .ZN (n_77));
  AOI22D0 p16261A4472__4733(.A1 (u_sram_c_sram_q[14]), .A2 (n_53), .B1
       (n_154), .B2 (n_47), .ZN (n_76));
  AOI22D0 p16253A4473__6161(.A1 (u_sram_c_sram_q[60]), .A2 (n_50), .B1
       (u_sram_c_sram_q[52]), .B2 (n_48), .ZN (n_75));
  AOI22D0 p16247A4474__9315(.A1 (u_sram_c_sram_q[57]), .A2 (n_50), .B1
       (u_sram_c_sram_q[49]), .B2 (n_48), .ZN (n_74));
  AOI22D0 p16253A4475__9945(.A1 (u_sram_c_sram_q[47]), .A2 (n_54), .B1
       (u_sram_c_sram_q[39]), .B2 (n_52), .ZN (n_73));
  AOI22D0 p16253A4476__2883(.A1 (u_sram_c_sram_q[56]), .A2 (n_50), .B1
       (u_sram_c_sram_q[48]), .B2 (n_48), .ZN (n_72));
  AOI22D0 p16261A4477__2346(.A1 (u_sram_c_sram_q[42]), .A2 (n_54), .B1
       (u_sram_c_sram_q[34]), .B2 (n_52), .ZN (n_71));
  AOI22D0 p16247A4478__1666(.A1 (u_sram_c_sram_q[59]), .A2 (n_50), .B1
       (u_sram_c_sram_q[51]), .B2 (n_48), .ZN (n_70));
  AOI22D0 p16261A4479__7410(.A1 (u_sram_c_sram_q[24]), .A2 (n_49), .B1
       (u_sram_c_sram_q[16]), .B2 (n_51), .ZN (n_69));
  AOI22D0 p16253A4480__6417(.A1 (u_sram_c_sram_q[30]), .A2 (n_49), .B1
       (u_sram_c_sram_q[22]), .B2 (n_51), .ZN (n_68));
  AOI22D0 p16250A4481__5477(.A1 (u_sram_c_sram_q[8]), .A2 (n_53), .B1
       (n_160), .B2 (n_47), .ZN (n_67));
  AOI22D0 p16250A4482__2398(.A1 (u_sram_c_sram_q[44]), .A2 (n_54), .B1
       (u_sram_c_sram_q[36]), .B2 (n_52), .ZN (n_66));
  AOI22D0 p16247A4483__5107(.A1 (u_sram_c_sram_q[40]), .A2 (n_54), .B1
       (u_sram_c_sram_q[32]), .B2 (n_52), .ZN (n_65));
  AOI22D0 p16247A4484__6260(.A1 (u_sram_c_sram_q[28]), .A2 (n_49), .B1
       (u_sram_c_sram_q[20]), .B2 (n_51), .ZN (n_64));
  AOI22D0 p16250A4485__4319(.A1 (u_sram_c_sram_q[46]), .A2 (n_54), .B1
       (u_sram_c_sram_q[38]), .B2 (n_52), .ZN (n_63));
  AOI22D0 p16253A4486__8428(.A1 (u_sram_c_sram_q[27]), .A2 (n_49), .B1
       (u_sram_c_sram_q[19]), .B2 (n_51), .ZN (n_62));
  AOI22D0 p16247A4487__5526(.A1 (u_sram_c_sram_q[62]), .A2 (n_50), .B1
       (u_sram_c_sram_q[54]), .B2 (n_48), .ZN (n_61));
  AOI22D0 p16261A4488__6783(.A1 (u_sram_c_sram_q[11]), .A2 (n_53), .B1
       (n_157), .B2 (n_47), .ZN (n_60));
  AOI22D0 p16261A4489__3680(.A1 (u_sram_c_sram_q[15]), .A2 (n_53), .B1
       (n_153), .B2 (n_47), .ZN (n_59));
  AOI22D0 p16250A4490__1617(.A1 (u_sram_c_sram_q[43]), .A2 (n_54), .B1
       (u_sram_c_sram_q[35]), .B2 (n_52), .ZN (n_58));
  AOI22D0 p16247A4491__2802(.A1 (u_sram_c_sram_q[63]), .A2 (n_50), .B1
       (u_sram_c_sram_q[55]), .B2 (n_48), .ZN (n_57));
  AOI22D0 p16261A4492__1705(.A1 (u_sram_c_sram_q[13]), .A2 (n_53), .B1
       (n_155), .B2 (n_47), .ZN (n_56));
  AOI22D0 p16261A4493__5122(.A1 (u_sram_c_sram_q[12]), .A2 (n_53), .B1
       (n_156), .B2 (n_47), .ZN (n_55));
  AO222D0 p10952A__8246(.A1 (sram_c_addr[4]), .A2 (n_39), .B1 (n_38),
       .B2 (tpu_c_addr[1]), .C1 (sc_mem_ctrl), .C2 (sc_addr[1]), .Z
       (u_sram_c_mux_addr[1]));
  NR2D0 p17340A__7098(.A1 (n_45), .A2 (u_sram_c_bus_byte_sel_d1[0]),
       .ZN (n_54));
  NR2D0 p17358A__6131(.A1 (n_43), .A2 (u_sram_c_bus_byte_sel_d1[0]),
       .ZN (n_53));
  NR2D0 p17327A__1881(.A1 (n_45), .A2 (n_42), .ZN (n_52));
  NR2D0 p17327A4494__5115(.A1 (n_46), .A2 (n_42), .ZN (n_51));
  INR2D0 p17321A__7482(.A1 (n_44), .B1 (u_sram_c_bus_byte_sel_d1[0]),
       .ZN (n_50));
  NR2D0 p17340A4495__4733(.A1 (n_46), .A2
       (u_sram_c_bus_byte_sel_d1[0]), .ZN (n_49));
  CKAN2D0 p17368A__6161(.A1 (n_44), .A2 (u_sram_c_bus_byte_sel_d1[0]),
       .Z (n_48));
  NR2D0 p17345A__9315(.A1 (n_43), .A2 (n_42), .ZN (n_47));
  MOAI22D0 p11567A__9945(.A1 (n_40), .A2 (sram_c_re), .B1
       (sc_mem_ctrl), .B2 (sc_cen), .ZN (u_sram_c_mux_cen));
  AO222D0 p10952A4496__2883(.A1 (sram_c_addr[11]), .A2 (n_39), .B1
       (n_38), .B2 (tpu_c_addr[8]), .C1 (sc_mem_ctrl), .C2
       (sc_addr[8]), .Z (u_sram_c_mux_addr[8]));
  AO222D0 p10952A4497__2346(.A1 (sram_c_addr[10]), .A2 (n_39), .B1
       (n_38), .B2 (tpu_c_addr[7]), .C1 (sc_mem_ctrl), .C2
       (sc_addr[7]), .Z (u_sram_c_mux_addr[7]));
  AO222D0 p10952A4498__1666(.A1 (sram_c_addr[9]), .A2 (n_39), .B1
       (n_38), .B2 (tpu_c_addr[6]), .C1 (sc_mem_ctrl), .C2
       (sc_addr[6]), .Z (u_sram_c_mux_addr[6]));
  AO222D0 p10952A4499__7410(.A1 (sram_c_addr[8]), .A2 (n_39), .B1
       (n_38), .B2 (tpu_c_addr[5]), .C1 (sc_mem_ctrl), .C2
       (sc_addr[5]), .Z (u_sram_c_mux_addr[5]));
  AO222D0 p10952A4500__6417(.A1 (sram_c_addr[7]), .A2 (n_39), .B1
       (n_38), .B2 (tpu_c_addr[4]), .C1 (sc_mem_ctrl), .C2
       (sc_addr[4]), .Z (u_sram_c_mux_addr[4]));
  AO222D0 p10952A4501__5477(.A1 (sram_c_addr[6]), .A2 (n_39), .B1
       (n_38), .B2 (tpu_c_addr[3]), .C1 (sc_mem_ctrl), .C2
       (sc_addr[3]), .Z (u_sram_c_mux_addr[3]));
  AO222D0 p10952A4502__2398(.A1 (sram_c_addr[5]), .A2 (n_39), .B1
       (n_38), .B2 (tpu_c_addr[2]), .C1 (sc_mem_ctrl), .C2
       (sc_addr[2]), .Z (u_sram_c_mux_addr[2]));
  AO222D0 p10952A4503__5107(.A1 (sram_c_addr[3]), .A2 (n_39), .B1
       (n_38), .B2 (tpu_c_addr[0]), .C1 (sc_mem_ctrl), .C2
       (sc_addr[0]), .Z (u_sram_c_mux_addr[0]));
  AO22D0 p23968A__6260(.A1 (n_38), .A2 (tpu_c_din[50]), .B1
       (sc_din[50]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[50]));
  AO22D0 p23968A4504__4319(.A1 (n_38), .A2 (tpu_c_din[14]), .B1
       (sc_din[14]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[14]));
  AO22D0 p23968A4505__8428(.A1 (n_38), .A2 (tpu_c_din[13]), .B1
       (sc_din[13]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[13]));
  AO22D0 p23968A4506__5526(.A1 (n_38), .A2 (tpu_c_din[12]), .B1
       (sc_din[12]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[12]));
  AO22D0 p23968A4507__6783(.A1 (n_38), .A2 (tpu_c_din[11]), .B1
       (sc_din[11]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[11]));
  AO22D0 p23968A4508__3680(.A1 (n_38), .A2 (tpu_c_din[10]), .B1
       (sc_din[10]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[10]));
  AO22D0 p23968A4509__1617(.A1 (n_38), .A2 (tpu_c_din[9]), .B1
       (sc_din[9]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[9]));
  AO22D0 p23968A4510__2802(.A1 (n_38), .A2 (tpu_c_din[8]), .B1
       (sc_din[8]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[8]));
  AO22D0 p23968A4511__1705(.A1 (n_38), .A2 (tpu_c_din[63]), .B1
       (sc_din[63]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[63]));
  AO22D0 p23968A4512__5122(.A1 (n_38), .A2 (tpu_c_din[7]), .B1
       (sc_din[7]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[7]));
  AO22D0 p23968A4513__8246(.A1 (n_38), .A2 (tpu_c_din[62]), .B1
       (sc_din[62]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[62]));
  AO22D0 p23968A4514__7098(.A1 (n_38), .A2 (tpu_c_din[6]), .B1
       (sc_din[6]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[6]));
  AO22D0 p23968A4515__6131(.A1 (n_38), .A2 (tpu_c_din[5]), .B1
       (sc_din[5]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[5]));
  AO22D0 p23968A4516__1881(.A1 (n_38), .A2 (tpu_c_din[4]), .B1
       (sc_din[4]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[4]));
  AO22D0 p23968A4517__5115(.A1 (n_38), .A2 (tpu_c_din[61]), .B1
       (sc_din[61]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[61]));
  AO22D0 p23968A4518__7482(.A1 (n_38), .A2 (tpu_c_din[3]), .B1
       (sc_din[3]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[3]));
  AO22D0 p23968A4519__4733(.A1 (n_38), .A2 (tpu_c_din[2]), .B1
       (sc_din[2]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[2]));
  AO22D0 p23968A4520__6161(.A1 (n_38), .A2 (tpu_c_din[60]), .B1
       (sc_din[60]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[60]));
  AO22D0 p23968A4521__9315(.A1 (n_38), .A2 (tpu_c_din[1]), .B1
       (sc_din[1]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[1]));
  AO22D0 p23968A4522__9945(.A1 (n_38), .A2 (tpu_c_din[0]), .B1
       (sc_din[0]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[0]));
  AO22D0 p23968A4523__2883(.A1 (n_38), .A2 (tpu_c_din[59]), .B1
       (sc_din[59]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[59]));
  AO22D0 p23968A4524__2346(.A1 (n_38), .A2 (tpu_c_din[58]), .B1
       (sc_din[58]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[58]));
  AO22D0 p23968A4525__1666(.A1 (n_38), .A2 (tpu_c_din[57]), .B1
       (sc_din[57]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[57]));
  AO22D0 p23968A4526__7410(.A1 (n_38), .A2 (tpu_c_din[56]), .B1
       (sc_din[56]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[56]));
  AO22D0 p23968A4527__6417(.A1 (n_38), .A2 (tpu_c_din[55]), .B1
       (sc_din[55]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[55]));
  AO22D0 p23968A4528__5477(.A1 (n_38), .A2 (tpu_c_din[54]), .B1
       (sc_din[54]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[54]));
  AO22D0 p23968A4529__2398(.A1 (n_38), .A2 (tpu_c_din[53]), .B1
       (sc_din[53]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[53]));
  AO22D0 p23968A4530__5107(.A1 (n_38), .A2 (tpu_c_din[52]), .B1
       (sc_din[52]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[52]));
  AO22D0 p23968A4531__6260(.A1 (n_38), .A2 (tpu_c_din[51]), .B1
       (sc_din[51]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[51]));
  AO22D0 p23968A4532__4319(.A1 (n_38), .A2 (tpu_c_din[15]), .B1
       (sc_din[15]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[15]));
  IND2D0 p17301A__8428(.A1 (u_sram_c_bus_byte_sel_d1[1]), .B1
       (u_sram_c_bus_byte_sel_d1[2]), .ZN (n_46));
  IND2D0 p17301A4533__5526(.A1 (u_sram_c_bus_byte_sel_d1[2]), .B1
       (u_sram_c_bus_byte_sel_d1[1]), .ZN (n_45));
  NR2D0 p17308A__6783(.A1 (u_sram_c_bus_byte_sel_d1[2]), .A2
       (u_sram_c_bus_byte_sel_d1[1]), .ZN (n_44));
  CKND2D0 p17346A__3680(.A1 (u_sram_c_bus_byte_sel_d1[1]), .A2
       (u_sram_c_bus_byte_sel_d1[2]), .ZN (n_43));
  AO22D0 p23968A4534__1617(.A1 (n_38), .A2 (tpu_c_din[49]), .B1
       (sc_din[49]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[49]));
  AO22D0 p23968A4535__2802(.A1 (n_38), .A2 (tpu_c_din[48]), .B1
       (sc_din[48]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[48]));
  AO22D0 p23968A4536__1705(.A1 (n_38), .A2 (tpu_c_din[47]), .B1
       (sc_din[47]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[47]));
  AO22D0 p23968A4537__5122(.A1 (n_38), .A2 (tpu_c_din[46]), .B1
       (sc_din[46]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[46]));
  AO22D0 p23968A4538__8246(.A1 (n_38), .A2 (tpu_c_din[45]), .B1
       (sc_din[45]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[45]));
  AO22D0 p23968A4539__7098(.A1 (n_38), .A2 (tpu_c_din[44]), .B1
       (sc_din[44]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[44]));
  AO22D0 p23968A4540__6131(.A1 (n_38), .A2 (tpu_c_din[43]), .B1
       (sc_din[43]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[43]));
  AO22D0 p23968A4541__1881(.A1 (n_38), .A2 (tpu_c_din[42]), .B1
       (sc_din[42]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[42]));
  AO22D0 p23968A4542__5115(.A1 (n_38), .A2 (tpu_c_din[41]), .B1
       (sc_din[41]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[41]));
  AO22D0 p23968A4543__7482(.A1 (n_38), .A2 (tpu_c_din[40]), .B1
       (sc_din[40]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[40]));
  AO22D0 p23968A4544__4733(.A1 (n_38), .A2 (tpu_c_din[39]), .B1
       (sc_din[39]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[39]));
  AO22D0 p23968A4545__6161(.A1 (n_38), .A2 (tpu_c_din[38]), .B1
       (sc_din[38]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[38]));
  AO22D0 p23968A4546__9315(.A1 (n_38), .A2 (tpu_c_din[37]), .B1
       (sc_din[37]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[37]));
  AO22D0 p23968A4547__9945(.A1 (n_38), .A2 (tpu_c_din[36]), .B1
       (sc_din[36]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[36]));
  AO22D0 p23968A4548__2883(.A1 (n_38), .A2 (tpu_c_din[35]), .B1
       (sc_din[35]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[35]));
  AO22D0 p23968A4549__2346(.A1 (n_38), .A2 (tpu_c_din[34]), .B1
       (sc_din[34]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[34]));
  AO22D0 p23968A4550__1666(.A1 (n_38), .A2 (tpu_c_din[33]), .B1
       (sc_din[33]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[33]));
  AO22D0 p23968A4551__7410(.A1 (n_38), .A2 (tpu_c_din[32]), .B1
       (sc_din[32]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[32]));
  AO22D0 p23968A4552__6417(.A1 (n_38), .A2 (tpu_c_din[31]), .B1
       (sc_din[31]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[31]));
  AO22D0 p23968A4553__5477(.A1 (n_38), .A2 (tpu_c_din[30]), .B1
       (sc_din[30]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[30]));
  AO22D0 p23968A4554__2398(.A1 (n_38), .A2 (tpu_c_din[29]), .B1
       (sc_din[29]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[29]));
  AO22D0 p23968A4555__5107(.A1 (n_38), .A2 (tpu_c_din[28]), .B1
       (sc_din[28]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[28]));
  AO22D0 p23968A4556__6260(.A1 (n_38), .A2 (tpu_c_din[27]), .B1
       (sc_din[27]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[27]));
  AO22D0 p23968A4557__4319(.A1 (n_38), .A2 (tpu_c_din[26]), .B1
       (sc_din[26]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[26]));
  AO22D0 p23968A4558__8428(.A1 (n_38), .A2 (tpu_c_din[25]), .B1
       (sc_din[25]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[25]));
  AO22D0 p23968A4559__5526(.A1 (n_38), .A2 (tpu_c_din[24]), .B1
       (sc_din[24]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[24]));
  AO22D0 p23968A4560__6783(.A1 (n_38), .A2 (tpu_c_din[23]), .B1
       (sc_din[23]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[23]));
  AO22D0 p23968A4561__3680(.A1 (n_38), .A2 (tpu_c_din[22]), .B1
       (sc_din[22]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[22]));
  AO22D0 p23968A4562__1617(.A1 (n_38), .A2 (tpu_c_din[21]), .B1
       (sc_din[21]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[21]));
  AO22D0 p23968A4563__2802(.A1 (n_38), .A2 (tpu_c_din[20]), .B1
       (sc_din[20]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[20]));
  AO22D0 p23968A4564__1705(.A1 (n_38), .A2 (tpu_c_din[19]), .B1
       (sc_din[19]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[19]));
  AO22D0 p23968A4565__5122(.A1 (n_38), .A2 (tpu_c_din[18]), .B1
       (sc_din[18]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[18]));
  AO22D0 p23968A4566__8246(.A1 (n_38), .A2 (tpu_c_din[17]), .B1
       (sc_din[17]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[17]));
  AO22D0 p23968A4567__7098(.A1 (n_38), .A2 (tpu_c_din[16]), .B1
       (sc_din[16]), .B2 (sc_mem_ctrl), .Z (u_sram_c_mux_din[16]));
  CKND0 Fp17347A(.I (u_sram_c_bus_byte_sel_d1[0]), .ZN (n_42));
  IOA21D0 p23977A__6131(.A1 (sc_mem_ctrl), .A2 (sc_wen), .B (n_40), .ZN
       (u_sram_c_mux_wen));
  CKAN2D0 p11708A__1881(.A1 (rstn), .A2 (chip_chc_rd), .Z (n_41));
  CKND0 Fp23736A(.I (n_39), .ZN (n_40));
  NR2D0 p23684A__5115(.A1 (tpu_c_we), .A2 (sc_mem_ctrl), .ZN (n_39));
  CKAN2D1 p23471A__7482(.A1 (n_37), .A2 (tpu_c_we), .Z (n_38));
  CKND0 Fp23470A(.I (sc_mem_ctrl), .ZN (n_37));
  DFND1 \u_slave_c_cnt_c_reg[11] (.CPN (clk), .D (n_36), .Q
       (sram_c_addr[11]), .QN (UNCONNECTED0));
  MOAI22D0 p11614A__4733(.A1 (n_34), .A2 (n_5), .B1 (sram_c_addr[11]),
       .B2 (n_4), .ZN (n_36));
  DFND1 \u_slave_c_cnt_c_reg[10] (.CPN (clk), .D (n_35), .Q
       (sram_c_addr[10]), .QN (UNCONNECTED1));
  MOAI22D0 p11614A2169__6161(.A1 (n_32), .A2 (n_5), .B1
       (sram_c_addr[10]), .B2 (n_4), .ZN (n_35));
  MAOI22D0 p23524A__9315(.A1 (n_31), .A2 (sram_c_addr[11]), .B1 (n_31),
       .B2 (sram_c_addr[11]), .ZN (n_34));
  DFND1 \u_slave_c_cnt_c_reg[9] (.CPN (clk), .D (n_33), .Q
       (sram_c_addr[9]), .QN (UNCONNECTED2));
  MOAI22D0 p11614A2171__9945(.A1 (n_29), .A2 (n_5), .B1
       (sram_c_addr[9]), .B2 (n_4), .ZN (n_33));
  MAOI22D0 p23564A__2883(.A1 (n_28), .A2 (sram_c_addr[10]), .B1 (n_28),
       .B2 (sram_c_addr[10]), .ZN (n_32));
  IND2D0 p23511A__2346(.A1 (n_28), .B1 (sram_c_addr[10]), .ZN (n_31));
  DFND1 \u_slave_c_cnt_c_reg[8] (.CPN (clk), .D (n_30), .Q
       (sram_c_addr[8]), .QN (UNCONNECTED3));
  MOAI22D0 p11614A2173__1666(.A1 (n_27), .A2 (n_5), .B1
       (sram_c_addr[8]), .B2 (n_4), .ZN (n_30));
  MAOI22D0 p23579A__7410(.A1 (n_25), .A2 (sram_c_addr[9]), .B1 (n_25),
       .B2 (sram_c_addr[9]), .ZN (n_29));
  IND2D0 p23464A__6417(.A1 (n_25), .B1 (sram_c_addr[9]), .ZN (n_28));
  DFND1 \u_slave_c_cnt_c_reg[7] (.CPN (clk), .D (n_26), .Q
       (sram_c_addr[7]), .QN (UNCONNECTED4));
  MAOI22D0 p23619A__5477(.A1 (n_22), .A2 (sram_c_addr[8]), .B1 (n_22),
       .B2 (sram_c_addr[8]), .ZN (n_27));
  MOAI22D0 p11614A2175__2398(.A1 (n_23), .A2 (n_5), .B1
       (sram_c_addr[7]), .B2 (n_4), .ZN (n_26));
  IND2D0 p23430A__5107(.A1 (n_22), .B1 (sram_c_addr[8]), .ZN (n_25));
  DFND1 \u_slave_c_cnt_c_reg[6] (.CPN (clk), .D (n_24), .Q
       (sram_c_addr[6]), .QN (UNCONNECTED5));
  MOAI22D0 p11614A2177__6260(.A1 (n_21), .A2 (n_5), .B1
       (sram_c_addr[6]), .B2 (n_4), .ZN (n_24));
  MAOI22D0 p23634A__4319(.A1 (n_19), .A2 (sram_c_addr[7]), .B1 (n_19),
       .B2 (sram_c_addr[7]), .ZN (n_23));
  IND2D0 p23381A__8428(.A1 (n_19), .B1 (sram_c_addr[7]), .ZN (n_22));
  DFND1 \u_slave_c_cnt_c_reg[5] (.CPN (clk), .D (n_20), .Q
       (sram_c_addr[5]), .QN (UNCONNECTED6));
  MAOI22D0 p23674A__5526(.A1 (n_16), .A2 (sram_c_addr[6]), .B1 (n_16),
       .B2 (sram_c_addr[6]), .ZN (n_21));
  MOAI22D0 p11614A2179__6783(.A1 (n_17), .A2 (n_5), .B1
       (sram_c_addr[5]), .B2 (n_4), .ZN (n_20));
  IND2D0 p23347A__3680(.A1 (n_16), .B1 (sram_c_addr[6]), .ZN (n_19));
  DFND1 \u_slave_c_cnt_c_reg[4] (.CPN (clk), .D (n_18), .Q
       (sram_c_addr[4]), .QN (UNCONNECTED7));
  MOAI22D0 p11614A2181__1617(.A1 (n_14), .A2 (n_5), .B1
       (sram_c_addr[4]), .B2 (n_4), .ZN (n_18));
  MAOI22D0 p23689A__2802(.A1 (n_13), .A2 (sram_c_addr[5]), .B1 (n_13),
       .B2 (sram_c_addr[5]), .ZN (n_17));
  IND2D0 p23297A__1705(.A1 (n_13), .B1 (sram_c_addr[5]), .ZN (n_16));
  DFND1 \u_slave_c_cnt_c_reg[3] (.CPN (clk), .D (n_15), .Q
       (sram_c_addr[3]), .QN (UNCONNECTED8));
  MOAI22D0 p11614A2183__5122(.A1 (n_11), .A2 (n_5), .B1
       (sram_c_addr[3]), .B2 (n_4), .ZN (n_15));
  MAOI22D0 p23727A__8246(.A1 (n_10), .A2 (sram_c_addr[4]), .B1 (n_10),
       .B2 (sram_c_addr[4]), .ZN (n_14));
  IND2D0 p23264A__7098(.A1 (n_10), .B1 (sram_c_addr[4]), .ZN (n_13));
  DFND1 \u_slave_c_cnt_c_reg[2] (.CPN (clk), .D (n_12), .Q
       (sram_c_addr[2]), .QN (UNCONNECTED9));
  MOAI22D0 p11614A2185__6131(.A1 (n_9), .A2 (n_5), .B1
       (sram_c_addr[2]), .B2 (n_4), .ZN (n_12));
  MAOI22D0 p23744A__1881(.A1 (n_7), .A2 (sram_c_addr[3]), .B1 (n_7),
       .B2 (sram_c_addr[3]), .ZN (n_11));
  IND2D0 p23214A__5115(.A1 (n_7), .B1 (sram_c_addr[3]), .ZN (n_10));
  DFND1 \u_slave_c_cnt_c_reg[1] (.CPN (clk), .D (n_8), .Q
       (sram_c_addr[1]), .QN (UNCONNECTED10));
  DFND1 \u_slave_c_cnt_c_reg[0] (.CPN (clk), .D (n_6), .Q
       (sram_c_addr[0]), .QN (n_0));
  MAOI22D0 p23781A__7482(.A1 (n_1), .A2 (sram_c_addr[2]), .B1 (n_1),
       .B2 (sram_c_addr[2]), .ZN (n_9));
  MOAI22D0 p11614A2188__4733(.A1 (n_3), .A2 (n_5), .B1
       (sram_c_addr[1]), .B2 (n_4), .ZN (n_8));
  IND2D0 p23180A__6161(.A1 (n_1), .B1 (sram_c_addr[2]), .ZN (n_7));
  MOAI22D0 p11614A2189__9315(.A1 (sram_c_addr[0]), .A2 (n_5), .B1
       (sram_c_addr[0]), .B2 (n_4), .ZN (n_6));
  CKND2D0 p11600A__9945(.A1 (n_2), .A2 (sram_c_re), .ZN (n_5));
  MUX2ND0 p23788A__2883(.I0 (sram_c_addr[0]), .I1 (n_0), .S
       (sram_c_addr[1]), .ZN (n_3));
  INR2D0 p11496A__2346(.A1 (n_2), .B1 (sram_c_re), .ZN (n_4));
  INR2D0 p11457A__1666(.A1 (rstn), .B1 (chip_chc_start), .ZN (n_2));
  CKND2D0 p23163A__7410(.A1 (sram_c_addr[0]), .A2 (sram_c_addr[1]), .ZN
       (n_1));
endmodule

