
// Generated by Cadence Genus(TM) Synthesis Solution 21.16-s062_1
// Generated on: Apr  2 2026 21:17:15 EDT (Apr  3 2026 01:17:15 UTC)

// Verification Directory fv/sram_wrapper_c 

module sram_wrapper_c(clk, rstn, tpu_we, tpu_addr, tpu_din, bus_re,
     bus_addr, bus_dout);
  input clk, rstn, tpu_we, bus_re;
  input [8:0] tpu_addr;
  input [63:0] tpu_din;
  input [11:0] bus_addr;
  output [7:0] bus_dout;
  wire clk, rstn, tpu_we, bus_re;
  wire [8:0] tpu_addr;
  wire [63:0] tpu_din;
  wire [11:0] bus_addr;
  wire [7:0] bus_dout;
  wire [8:0] sram_addr;
  wire [63:0] sram_din;
  wire [63:0] sram_q;
  wire [2:0] bus_byte_sel_d1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, sram_cen;
  sram00 u_sram(.CLK (clk), .CEN (sram_cen), .WEN (n_0), .A
       (sram_addr), .D (sram_din), .EMA (3'b10), .RETN (1'b1), .Q
       ({sram_q[63:8], n_60, n_61, n_62, n_63, n_64, n_65, n_66,
       n_67}));
  ND4D8 p70817A__2398(.A1 (n_43), .A2 (n_30), .A3 (n_41), .A4 (n_40),
       .ZN (bus_dout[2]));
  ND4D8 p70817A1797__5107(.A1 (n_22), .A2 (n_27), .A3 (n_35), .A4
       (n_20), .ZN (bus_dout[6]));
  ND4D8 p70817A1798__6260(.A1 (n_32), .A2 (n_18), .A3 (n_45), .A4
       (n_16), .ZN (bus_dout[7]));
  ND4D8 p70817A1799__4319(.A1 (n_39), .A2 (n_36), .A3 (n_37), .A4
       (n_33), .ZN (bus_dout[1]));
  ND4D8 p70817A1800__8428(.A1 (n_15), .A2 (n_44), .A3 (n_42), .A4
       (n_38), .ZN (bus_dout[5]));
  ND4D8 p70817A1801__5526(.A1 (n_31), .A2 (n_26), .A3 (n_28), .A4
       (n_24), .ZN (bus_dout[0]));
  ND4D8 p70817A1802__6783(.A1 (n_34), .A2 (n_25), .A3 (n_14), .A4
       (n_23), .ZN (bus_dout[4]));
  ND4D8 p70817A1803__3680(.A1 (n_21), .A2 (n_19), .A3 (n_17), .A4
       (n_29), .ZN (bus_dout[3]));
  AOI22D0 p70812A__1617(.A1 (sram_q[23]), .A2 (n_6), .B1 (sram_q[31]),
       .B2 (n_9), .ZN (n_45));
  AOI22D0 p70816A__2802(.A1 (sram_q[37]), .A2 (n_8), .B1 (sram_q[45]),
       .B2 (n_7), .ZN (n_44));
  AOI22D0 p70824A__1705(.A1 (sram_q[50]), .A2 (n_10), .B1 (sram_q[58]),
       .B2 (n_13), .ZN (n_43));
  AOI22D0 p70812A1804__5122(.A1 (sram_q[21]), .A2 (n_6), .B1
       (sram_q[29]), .B2 (n_9), .ZN (n_42));
  AOI22D0 p70812A1805__8246(.A1 (sram_q[34]), .A2 (n_8), .B1
       (sram_q[42]), .B2 (n_7), .ZN (n_41));
  AOI22D0 p70810A__7098(.A1 (n_65), .A2 (n_12), .B1 (sram_q[10]), .B2
       (n_11), .ZN (n_40));
  AOI22D0 p70824A1806__6131(.A1 (sram_q[33]), .A2 (n_8), .B1
       (sram_q[41]), .B2 (n_7), .ZN (n_39));
  AOI22D0 p70810A1807__1881(.A1 (n_62), .A2 (n_12), .B1 (sram_q[13]),
       .B2 (n_11), .ZN (n_38));
  AOI22D0 p70812A1808__5115(.A1 (sram_q[17]), .A2 (n_6), .B1
       (sram_q[25]), .B2 (n_9), .ZN (n_37));
  AOI22D0 p70816A1809__7482(.A1 (sram_q[49]), .A2 (n_10), .B1
       (sram_q[57]), .B2 (n_13), .ZN (n_36));
  AOI22D0 p70812A1810__4733(.A1 (n_61), .A2 (n_12), .B1 (sram_q[14]),
       .B2 (n_11), .ZN (n_35));
  AOI22D0 p70824A1811__6161(.A1 (sram_q[20]), .A2 (n_6), .B1
       (sram_q[28]), .B2 (n_9), .ZN (n_34));
  AOI22D0 p70810A1812__9315(.A1 (n_66), .A2 (n_12), .B1 (sram_q[9]),
       .B2 (n_11), .ZN (n_33));
  AOI22D0 p70824A1813__9945(.A1 (sram_q[55]), .A2 (n_10), .B1
       (sram_q[63]), .B2 (n_13), .ZN (n_32));
  AOI22D0 p70824A1814__2883(.A1 (sram_q[32]), .A2 (n_8), .B1
       (sram_q[40]), .B2 (n_7), .ZN (n_31));
  AOI22D0 p70816A1815__2346(.A1 (sram_q[18]), .A2 (n_6), .B1
       (sram_q[26]), .B2 (n_9), .ZN (n_30));
  AOI22D0 p70810A1816__1666(.A1 (n_64), .A2 (n_12), .B1 (sram_q[11]),
       .B2 (n_11), .ZN (n_29));
  AOI22D0 p70812A1817__7410(.A1 (sram_q[16]), .A2 (n_6), .B1
       (sram_q[24]), .B2 (n_9), .ZN (n_28));
  AOI22D0 p70816A1818__6417(.A1 (sram_q[22]), .A2 (n_6), .B1
       (sram_q[30]), .B2 (n_9), .ZN (n_27));
  AOI22D0 p70816A1819__5477(.A1 (sram_q[48]), .A2 (n_10), .B1
       (sram_q[56]), .B2 (n_13), .ZN (n_26));
  AOI22D0 p70816A1820__2398(.A1 (sram_q[52]), .A2 (n_10), .B1
       (sram_q[60]), .B2 (n_13), .ZN (n_25));
  AOI22D0 p70810A1821__5107(.A1 (n_67), .A2 (n_12), .B1 (sram_q[8]),
       .B2 (n_11), .ZN (n_24));
  AOI22D0 p70810A1822__6260(.A1 (sram_q[36]), .A2 (n_8), .B1
       (sram_q[44]), .B2 (n_7), .ZN (n_23));
  AOI22D0 p70824A1823__4319(.A1 (sram_q[54]), .A2 (n_10), .B1
       (sram_q[62]), .B2 (n_13), .ZN (n_22));
  AOI22D0 p70824A1824__8428(.A1 (sram_q[51]), .A2 (n_10), .B1
       (sram_q[59]), .B2 (n_13), .ZN (n_21));
  AOI22D0 p70810A1825__5526(.A1 (sram_q[38]), .A2 (n_8), .B1
       (sram_q[46]), .B2 (n_7), .ZN (n_20));
  AOI22D0 p70816A1826__6783(.A1 (sram_q[35]), .A2 (n_8), .B1
       (sram_q[43]), .B2 (n_7), .ZN (n_19));
  AOI22D0 p70816A1827__3680(.A1 (sram_q[39]), .A2 (n_8), .B1
       (sram_q[47]), .B2 (n_7), .ZN (n_18));
  AOI22D0 p70812A1828__1617(.A1 (sram_q[19]), .A2 (n_6), .B1
       (sram_q[27]), .B2 (n_9), .ZN (n_17));
  AOI22D0 p70810A1829__2802(.A1 (n_60), .A2 (n_12), .B1 (sram_q[15]),
       .B2 (n_11), .ZN (n_16));
  AOI22D0 p70824A1830__1705(.A1 (sram_q[53]), .A2 (n_10), .B1
       (sram_q[61]), .B2 (n_13), .ZN (n_15));
  AOI22D0 p70812A1831__5122(.A1 (n_63), .A2 (n_12), .B1 (sram_q[12]),
       .B2 (n_11), .ZN (n_14));
  NR2D0 p71871A__8246(.A1 (n_2), .A2 (n_1), .ZN (n_13));
  INR2D0 p71849A__7098(.A1 (n_5), .B1 (bus_byte_sel_d1[0]), .ZN (n_12));
  CKAN2D0 p71898A__6131(.A1 (n_5), .A2 (bus_byte_sel_d1[0]), .Z (n_11));
  NR2D0 p71884A__1881(.A1 (n_2), .A2 (bus_byte_sel_d1[0]), .ZN (n_10));
  NR2D0 p71849A1832__5115(.A1 (n_3), .A2 (n_1), .ZN (n_9));
  NR2D0 p71859A__7482(.A1 (n_4), .A2 (bus_byte_sel_d1[0]), .ZN (n_8));
  NR2D0 p71846A__4733(.A1 (n_4), .A2 (n_1), .ZN (n_7));
  NR2D0 p71862A__6161(.A1 (n_3), .A2 (bus_byte_sel_d1[0]), .ZN (n_6));
  NR2D0 p71824A__9315(.A1 (bus_byte_sel_d1[2]), .A2
       (bus_byte_sel_d1[1]), .ZN (n_5));
  IND2D0 p71822A__9945(.A1 (bus_byte_sel_d1[1]), .B1
       (bus_byte_sel_d1[2]), .ZN (n_4));
  IND2D0 p71825A__2883(.A1 (bus_byte_sel_d1[2]), .B1
       (bus_byte_sel_d1[1]), .ZN (n_3));
  CKND2D0 p71861A__2346(.A1 (bus_byte_sel_d1[1]), .A2
       (bus_byte_sel_d1[2]), .ZN (n_2));
  DFCNQD1 \bus_byte_sel_d1_reg[2] (.CDN (rstn), .CP (clk), .D
       (bus_addr[2]), .Q (bus_byte_sel_d1[2]));
  DFCNQD1 \bus_byte_sel_d1_reg[1] (.CDN (rstn), .CP (clk), .D
       (bus_addr[1]), .Q (bus_byte_sel_d1[1]));
  AO22D0 p96144A__1666(.A1 (n_0), .A2 (bus_addr[8]), .B1 (tpu_addr[5]),
       .B2 (tpu_we), .Z (sram_addr[5]));
  AO22D0 p96144A1087__7410(.A1 (n_0), .A2 (bus_addr[10]), .B1
       (tpu_addr[7]), .B2 (tpu_we), .Z (sram_addr[7]));
  AO22D0 p96144A1088__6417(.A1 (n_0), .A2 (bus_addr[11]), .B1
       (tpu_addr[8]), .B2 (tpu_we), .Z (sram_addr[8]));
  AO22D0 p96144A1089__5477(.A1 (n_0), .A2 (bus_addr[5]), .B1
       (tpu_addr[2]), .B2 (tpu_we), .Z (sram_addr[2]));
  AO22D0 p96144A1090__2398(.A1 (n_0), .A2 (bus_addr[3]), .B1
       (tpu_addr[0]), .B2 (tpu_we), .Z (sram_addr[0]));
  AO22D0 p96144A1091__5107(.A1 (n_0), .A2 (bus_addr[7]), .B1
       (tpu_addr[4]), .B2 (tpu_we), .Z (sram_addr[4]));
  AO22D0 p96144A1092__6260(.A1 (n_0), .A2 (bus_addr[4]), .B1
       (tpu_addr[1]), .B2 (tpu_we), .Z (sram_addr[1]));
  AO22D0 p96144A1093__4319(.A1 (n_0), .A2 (bus_addr[9]), .B1
       (tpu_addr[6]), .B2 (tpu_we), .Z (sram_addr[6]));
  AO22D0 p96144A1094__8428(.A1 (n_0), .A2 (bus_addr[6]), .B1
       (tpu_addr[3]), .B2 (tpu_we), .Z (sram_addr[3]));
  CKAN2D0 p96447A__5526(.A1 (tpu_we), .A2 (tpu_din[15]), .Z
       (sram_din[15]));
  CKAN2D0 p96447A1095__6783(.A1 (tpu_we), .A2 (tpu_din[24]), .Z
       (sram_din[24]));
  CKAN2D0 p96447A1096__3680(.A1 (tpu_we), .A2 (tpu_din[23]), .Z
       (sram_din[23]));
  CKAN2D0 p96447A1097__1617(.A1 (tpu_we), .A2 (tpu_din[55]), .Z
       (sram_din[55]));
  CKAN2D0 p96447A1098__2802(.A1 (tpu_we), .A2 (tpu_din[22]), .Z
       (sram_din[22]));
  CKAN2D0 p96447A1099__1705(.A1 (tpu_we), .A2 (tpu_din[21]), .Z
       (sram_din[21]));
  CKAN2D0 p96447A1100__5122(.A1 (tpu_we), .A2 (tpu_din[54]), .Z
       (sram_din[54]));
  CKAN2D0 p96447A1101__8246(.A1 (tpu_we), .A2 (tpu_din[20]), .Z
       (sram_din[20]));
  CKAN2D0 p96447A1102__7098(.A1 (tpu_we), .A2 (tpu_din[19]), .Z
       (sram_din[19]));
  CKAN2D0 p96447A1103__6131(.A1 (tpu_we), .A2 (tpu_din[53]), .Z
       (sram_din[53]));
  CKAN2D0 p96447A1104__1881(.A1 (tpu_we), .A2 (tpu_din[18]), .Z
       (sram_din[18]));
  CKAN2D0 p96447A1105__5115(.A1 (tpu_we), .A2 (tpu_din[10]), .Z
       (sram_din[10]));
  CKAN2D0 p96447A1106__7482(.A1 (tpu_we), .A2 (tpu_din[17]), .Z
       (sram_din[17]));
  CKAN2D0 p96447A1107__4733(.A1 (tpu_we), .A2 (tpu_din[52]), .Z
       (sram_din[52]));
  CKAN2D0 p96447A1108__6161(.A1 (tpu_we), .A2 (tpu_din[12]), .Z
       (sram_din[12]));
  CKAN2D0 p96447A1109__9315(.A1 (tpu_we), .A2 (tpu_din[16]), .Z
       (sram_din[16]));
  CKAN2D0 p96447A1110__9945(.A1 (tpu_we), .A2 (tpu_din[56]), .Z
       (sram_din[56]));
  CKAN2D0 p96447A1111__2883(.A1 (tpu_we), .A2 (tpu_din[51]), .Z
       (sram_din[51]));
  CKAN2D0 p96447A1112__2346(.A1 (tpu_we), .A2 (tpu_din[14]), .Z
       (sram_din[14]));
  CKAN2D0 p96447A1113__1666(.A1 (tpu_we), .A2 (tpu_din[13]), .Z
       (sram_din[13]));
  CKAN2D0 p96447A1114__7410(.A1 (tpu_we), .A2 (tpu_din[50]), .Z
       (sram_din[50]));
  CKAN2D0 p96447A1115__6417(.A1 (tpu_we), .A2 (tpu_din[11]), .Z
       (sram_din[11]));
  CKAN2D0 p96447A1116__5477(.A1 (tpu_we), .A2 (tpu_din[49]), .Z
       (sram_din[49]));
  CKAN2D0 p96447A1117__2398(.A1 (tpu_we), .A2 (tpu_din[9]), .Z
       (sram_din[9]));
  CKAN2D0 p96447A1118__5107(.A1 (tpu_we), .A2 (tpu_din[48]), .Z
       (sram_din[48]));
  CKAN2D0 p96447A1119__6260(.A1 (tpu_we), .A2 (tpu_din[8]), .Z
       (sram_din[8]));
  CKAN2D0 p96447A1120__4319(.A1 (tpu_we), .A2 (tpu_din[7]), .Z
       (sram_din[7]));
  CKAN2D0 p96447A1121__8428(.A1 (tpu_we), .A2 (tpu_din[47]), .Z
       (sram_din[47]));
  CKAN2D0 p96447A1122__5526(.A1 (tpu_we), .A2 (tpu_din[6]), .Z
       (sram_din[6]));
  CKAN2D0 p96447A1123__6783(.A1 (tpu_we), .A2 (tpu_din[5]), .Z
       (sram_din[5]));
  CKAN2D0 p96447A1124__3680(.A1 (tpu_we), .A2 (tpu_din[46]), .Z
       (sram_din[46]));
  CKAN2D0 p96447A1125__1617(.A1 (tpu_we), .A2 (tpu_din[4]), .Z
       (sram_din[4]));
  CKAN2D0 p96447A1126__2802(.A1 (tpu_we), .A2 (tpu_din[62]), .Z
       (sram_din[62]));
  CKAN2D0 p96447A1127__1705(.A1 (tpu_we), .A2 (tpu_din[45]), .Z
       (sram_din[45]));
  CKAN2D0 p96447A1128__5122(.A1 (tpu_we), .A2 (tpu_din[2]), .Z
       (sram_din[2]));
  CKAN2D0 p96447A1129__8246(.A1 (tpu_we), .A2 (tpu_din[1]), .Z
       (sram_din[1]));
  CKAN2D0 p96447A1130__7098(.A1 (tpu_we), .A2 (tpu_din[44]), .Z
       (sram_din[44]));
  CKAN2D0 p96447A1131__6131(.A1 (tpu_we), .A2 (tpu_din[0]), .Z
       (sram_din[0]));
  CKAN2D0 p96447A1132__1881(.A1 (tpu_we), .A2 (tpu_din[43]), .Z
       (sram_din[43]));
  CKAN2D0 p96447A1133__5115(.A1 (tpu_we), .A2 (tpu_din[42]), .Z
       (sram_din[42]));
  CKAN2D0 p96447A1134__7482(.A1 (tpu_we), .A2 (tpu_din[41]), .Z
       (sram_din[41]));
  CKAN2D0 p96447A1135__4733(.A1 (tpu_we), .A2 (tpu_din[30]), .Z
       (sram_din[30]));
  NR2D0 p96407A__6161(.A1 (tpu_we), .A2 (bus_re), .ZN (sram_cen));
  CKAN2D0 p96447A1136__9315(.A1 (tpu_we), .A2 (tpu_din[40]), .Z
       (sram_din[40]));
  CKAN2D0 p96447A1137__9945(.A1 (tpu_we), .A2 (tpu_din[39]), .Z
       (sram_din[39]));
  CKAN2D0 p96447A1138__2883(.A1 (tpu_we), .A2 (tpu_din[63]), .Z
       (sram_din[63]));
  CKAN2D0 p96447A1139__2346(.A1 (tpu_we), .A2 (tpu_din[38]), .Z
       (sram_din[38]));
  CKAN2D0 p96447A1140__1666(.A1 (tpu_we), .A2 (tpu_din[37]), .Z
       (sram_din[37]));
  CKAN2D0 p96447A1141__7410(.A1 (tpu_we), .A2 (tpu_din[3]), .Z
       (sram_din[3]));
  CKAN2D0 p96447A1142__6417(.A1 (tpu_we), .A2 (tpu_din[36]), .Z
       (sram_din[36]));
  CKAN2D0 p96447A1143__5477(.A1 (tpu_we), .A2 (tpu_din[35]), .Z
       (sram_din[35]));
  CKAN2D0 p96447A1144__2398(.A1 (tpu_we), .A2 (tpu_din[61]), .Z
       (sram_din[61]));
  CKAN2D0 p96447A1145__5107(.A1 (tpu_we), .A2 (tpu_din[34]), .Z
       (sram_din[34]));
  CKAN2D0 p96447A1146__6260(.A1 (tpu_we), .A2 (tpu_din[33]), .Z
       (sram_din[33]));
  CKAN2D0 p96447A1147__4319(.A1 (tpu_we), .A2 (tpu_din[60]), .Z
       (sram_din[60]));
  CKAN2D0 p96447A1148__8428(.A1 (tpu_we), .A2 (tpu_din[32]), .Z
       (sram_din[32]));
  CKAN2D0 p96447A1149__5526(.A1 (tpu_we), .A2 (tpu_din[31]), .Z
       (sram_din[31]));
  CKAN2D0 p96447A1150__6783(.A1 (tpu_we), .A2 (tpu_din[59]), .Z
       (sram_din[59]));
  CKAN2D0 p96447A1151__3680(.A1 (tpu_we), .A2 (tpu_din[29]), .Z
       (sram_din[29]));
  CKAN2D0 p96447A1152__1617(.A1 (tpu_we), .A2 (tpu_din[58]), .Z
       (sram_din[58]));
  CKAN2D0 p96447A1153__2802(.A1 (tpu_we), .A2 (tpu_din[28]), .Z
       (sram_din[28]));
  CKAN2D0 p96447A1154__1705(.A1 (tpu_we), .A2 (tpu_din[27]), .Z
       (sram_din[27]));
  CKAN2D0 p96447A1155__5122(.A1 (tpu_we), .A2 (tpu_din[57]), .Z
       (sram_din[57]));
  CKAN2D0 p96447A1156__8246(.A1 (tpu_we), .A2 (tpu_din[26]), .Z
       (sram_din[26]));
  CKAN2D0 p96447A1157__7098(.A1 (tpu_we), .A2 (tpu_din[25]), .Z
       (sram_din[25]));
  CKND0 Fp96144A1836(.I (tpu_we), .ZN (n_0));
  DFCND1 \bus_byte_sel_d1_reg[0] (.CDN (rstn), .CP (clk), .D
       (bus_addr[0]), .Q (bus_byte_sel_d1[0]), .QN (n_1));
endmodule

