/*
###############################################################
#  Generated by:      Cadence Innovus 21.16-s078_1
#  OS:                Linux x86_64(Host ID cadpc15)
#  Generated on:      Thu Apr  2 21:37:00 2026
#  Design:            sram_wrapper_c
#  Command:           write_netlist ../output/sram_wrapper_c.functpg.v -include_pg_ports
###############################################################
*/
module DEL015 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module DEL01 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module DEL0 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module BUFFD2 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module CKBD0 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module CKBD1 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module BUFFD1 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module DEL1 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module DEL005 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module CKBD2 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module DEL2 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module CKND6 (
	I, 
	ZN, 
	VSS, 
	VDD);
   input I;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module CKND1 (
	I, 
	ZN, 
	VSS, 
	VDD);
   input I;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module TIEL (
	ZN, 
	VSS, 
	VDD);
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module TIEH (
	Z, 
	VSS, 
	VDD);
   output Z;
   inout VSS;
   inout VDD;
endmodule

module BUFFD16 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module BUFFD12 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module sram00 (
	Q, 
	CLK, 
	CEN, 
	WEN, 
	A, 
	D, 
	EMA, 
	RETN, 
	VSS, 
	VDD);
   output [63:0] Q;
   input CLK;
   input CEN;
   input WEN;
   input [8:0] A;
   input [63:0] D;
   input [2:0] EMA;
   input RETN;
   inout VSS;
   inout VDD;
endmodule

module ND4D1 (
	A1, 
	A2, 
	A3, 
	A4, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input A3;
   input A4;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module AOI22D0 (
	A1, 
	A2, 
	B1, 
	B2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input B1;
   input B2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module AOI22D1 (
	A1, 
	A2, 
	B1, 
	B2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input B1;
   input B2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module NR2D2 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module INR2D0 (
	A1, 
	B1, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input B1;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module CKAN2D0 (
	A1, 
	A2, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module NR2XD1 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module NR2D1 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module NR2D0 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module IND2D0 (
	A1, 
	B1, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input B1;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module CKND2D0 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module DFCNQD1 (
	CDN, 
	CP, 
	D, 
	Q, 
	VSS, 
	VDD);
   input CDN;
   input CP;
   input D;
   output Q;
   inout VSS;
   inout VDD;
endmodule

module AO22D0 (
	A1, 
	A2, 
	B1, 
	B2, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input B1;
   input B2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module AN2XD1 (
	A1, 
	A2, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module AN2D2 (
	A1, 
	A2, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module CKND0 (
	I, 
	ZN, 
	VSS, 
	VDD);
   input I;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module DFCND1 (
	CDN, 
	CP, 
	D, 
	Q, 
	QN, 
	VSS, 
	VDD);
   input CDN;
   input CP;
   input D;
   output Q;
   output QN;
   inout VSS;
   inout VDD;
endmodule

// Generated by Cadence Genus(TM) Synthesis Solution 21.16-s062_1
// Generated on: Apr  2 2026 21:17:15 EDT (Apr  3 2026 01:17:15 UTC)
// Verification Directory fv/sram_wrapper_c 
module sram_wrapper_c (
	clk, 
	rstn, 
	tpu_we, 
	tpu_addr, 
	tpu_din, 
	bus_re, 
	bus_addr, 
	bus_dout, 
	DVDD, 
	DVSS);
   input clk;
   input rstn;
   input tpu_we;
   input [8:0] tpu_addr;
   input [63:0] tpu_din;
   input bus_re;
   input [11:0] bus_addr;
   output [7:0] bus_dout;
   inout DVDD;
   inout DVSS;

   // Internal wires
   wire FE_PHN235_sram_din_18;
   wire FE_PHN234_sram_din_13;
   wire FE_PHN233_sram_din_1;
   wire FE_PHN232_sram_din_8;
   wire FE_PHN231_sram_din_9;
   wire FE_PHN230_sram_din_3;
   wire FE_PHN229_sram_din_5;
   wire FE_PHN228_sram_din_4;
   wire FE_PHN227_sram_din_11;
   wire FE_PHN226_sram_din_10;
   wire FE_PHN225_sram_din_0;
   wire FE_PHN224_sram_din_12;
   wire FE_PHN223_sram_din_6;
   wire FE_PHN222_sram_din_2;
   wire FE_PHN221_sram_din_33;
   wire FE_PHN220_sram_din_35;
   wire FE_PHN219_sram_din_34;
   wire FE_PHN218_sram_din_42;
   wire FE_PHN217_sram_din_47;
   wire FE_PHN216_sram_din_37;
   wire FE_PHN215_sram_din_49;
   wire FE_PHN214_sram_din_32;
   wire FE_PHN213_sram_din_43;
   wire FE_PHN212_sram_din_38;
   wire FE_PHN211_sram_din_50;
   wire FE_PHN210_sram_din_41;
   wire FE_PHN209_sram_din_45;
   wire FE_PHN208_sram_din_46;
   wire FE_PHN207_sram_addr_2;
   wire FE_PHN206_sram_din_48;
   wire FE_PHN205_sram_addr_7;
   wire FE_PHN204_sram_addr_8;
   wire FE_PHN203_sram_din_36;
   wire FE_PHN202_sram_din_53;
   wire FE_PHN201_sram_din_51;
   wire FE_PHN200_sram_din_62;
   wire FE_PHN199_sram_din_54;
   wire FE_PHN198_sram_din_52;
   wire FE_PHN197_sram_din_55;
   wire FE_PHN196_sram_din_60;
   wire FE_PHN195_sram_din_7;
   wire FE_PHN194_tpu_we;
   wire FE_PHN193_bus_addr_0;
   wire FE_PHN192_bus_addr_5;
   wire FE_PHN191_bus_addr_10;
   wire FE_PHN190_bus_addr_11;
   wire FE_PHN189_bus_addr_2;
   wire FE_PHN188_bus_addr_1;
   wire FE_PDN16_n_16;
   wire FE_PHN187_tpu_din_18;
   wire FE_PHN186_sram_din_1;
   wire FE_PHN185_sram_din_8;
   wire FE_PHN184_sram_din_0;
   wire FE_PHN183_sram_din_19;
   wire FE_PHN182_sram_din_20;
   wire FE_PHN181_sram_din_21;
   wire FE_PHN180_bus_addr_2;
   wire FE_PHN179_tpu_we;
   wire FE_PHN178_sram_din_11;
   wire FE_PHN177_sram_din_9;
   wire FE_PHN176_sram_din_10;
   wire FE_PHN175_sram_din_8;
   wire FE_PHN174_sram_din_0;
   wire FE_PHN173_sram_din_1;
   wire FE_PHN172_sram_din_12;
   wire FE_PHN171_sram_din_13;
   wire FE_PHN170_sram_din_4;
   wire FE_PHN169_sram_din_3;
   wire FE_PHN168_sram_din_5;
   wire FE_PHN167_sram_din_33;
   wire FE_PHN166_sram_din_32;
   wire FE_PHN165_sram_din_35;
   wire FE_PHN164_sram_din_34;
   wire FE_PHN163_sram_din_37;
   wire FE_PHN162_sram_din_38;
   wire FE_PHN161_sram_din_36;
   wire FE_PHN160_sram_din_31;
   wire FE_PHN159_sram_din_16;
   wire FE_PHN158_sram_din_28;
   wire FE_PHN157_sram_din_22;
   wire FE_PHN156_sram_din_23;
   wire FE_PHN155_sram_din_24;
   wire FE_PHN154_sram_din_25;
   wire FE_PHN153_sram_din_26;
   wire FE_PHN152_sram_din_29;
   wire FE_PHN151_sram_din_27;
   wire FE_PHN150_sram_din_14;
   wire FE_PHN149_sram_din_15;
   wire FE_PHN148_sram_din_44;
   wire FE_PHN147_sram_addr_4;
   wire FE_PHN146_sram_din_41;
   wire FE_PHN145_bus_addr_1;
   wire FE_PHN144_sram_din_39;
   wire FE_PHN143_sram_din_49;
   wire FE_PHN142_bus_addr_0;
   wire FE_PHN141_sram_din_40;
   wire FE_PHN140_sram_din_42;
   wire FE_PHN139_sram_din_47;
   wire FE_PHN138_sram_din_43;
   wire FE_PHN137_sram_addr_0;
   wire FE_PHN136_sram_din_58;
   wire FE_PHN135_sram_din_56;
   wire FE_PHN134_sram_din_59;
   wire FE_PHN133_sram_din_57;
   wire FE_PHN132_sram_din_61;
   wire FE_PHN131_sram_din_63;
   wire FE_PHN130_sram_addr_1;
   wire FE_PHN129_sram_din_45;
   wire FE_PHN128_sram_din_50;
   wire FE_PHN127_sram_din_48;
   wire FE_PHN126_sram_din_51;
   wire FE_PHN125_sram_din_46;
   wire FE_PHN124_sram_din_52;
   wire FE_PHN123_sram_addr_6;
   wire FE_PHN122_sram_din_62;
   wire FE_PHN121_sram_din_53;
   wire FE_PHN120_sram_din_60;
   wire FE_PHN119_sram_din_54;
   wire FE_PHN118_sram_addr_5;
   wire FE_PHN117_sram_din_55;
   wire FE_PHN116_sram_addr_2;
   wire FE_PHN115_sram_addr_3;
   wire FE_PHN114_sram_addr_7;
   wire FE_PHN113_sram_addr_8;
   wire FE_PHN112_sram_cen;
   wire FE_PHN111_sram_din_30;
   wire FE_PHN110_tpu_we;
   wire FE_PHN109_bus_addr_2;
   wire FE_PHN108_rstn;
   wire FE_PHN107_sram_din_7;
   wire FE_PHN106_sram_din_5;
   wire FE_PHN105_sram_din_2;
   wire FE_PHN104_sram_din_3;
   wire FE_PHN103_sram_din_4;
   wire FE_PHN102_sram_din_6;
   wire FE_PHN101_sram_din_0;
   wire FE_PHN100_sram_din_11;
   wire FE_PHN99_sram_din_1;
   wire FE_PHN98_sram_din_8;
   wire FE_PHN97_sram_din_9;
   wire FE_PHN96_sram_din_13;
   wire FE_PHN95_sram_din_10;
   wire FE_PHN94_sram_din_12;
   wire FE_PHN93_sram_din_33;
   wire FE_PHN92_sram_din_32;
   wire FE_PHN91_sram_din_35;
   wire FE_PHN90_sram_din_34;
   wire FE_PHN89_sram_din_37;
   wire FE_PHN88_sram_din_39;
   wire FE_PHN87_sram_din_41;
   wire FE_PHN86_sram_din_38;
   wire FE_PHN85_sram_din_40;
   wire FE_PHN84_sram_din_42;
   wire FE_PHN83_sram_din_44;
   wire FE_PHN82_sram_din_43;
   wire FE_PHN81_sram_din_36;
   wire FE_PHN80_sram_addr_6;
   wire FE_PHN79_sram_addr_4;
   wire FE_PHN78_sram_addr_0;
   wire FE_PHN77_sram_addr_2;
   wire FE_PHN76_sram_addr_5;
   wire FE_PHN75_sram_addr_1;
   wire FE_PHN74_sram_addr_3;
   wire FE_PHN73_sram_addr_7;
   wire FE_PHN72_sram_addr_8;
   wire FE_PHN71_sram_din_45;
   wire FE_PHN70_sram_din_47;
   wire FE_PHN69_sram_din_46;
   wire FE_PHN68_sram_din_49;
   wire FE_PHN67_sram_din_48;
   wire FE_PHN66_sram_din_50;
   wire FE_PHN65_sram_din_53;
   wire FE_PHN64_sram_din_52;
   wire FE_PHN63_sram_din_51;
   wire FE_PHN62_sram_din_54;
   wire FE_PHN61_sram_din_62;
   wire FE_PHN60_sram_din_60;
   wire FE_PHN59_sram_din_56;
   wire FE_PHN58_sram_din_61;
   wire FE_PHN57_sram_din_63;
   wire FE_PHN56_sram_din_59;
   wire FE_PHN55_sram_din_57;
   wire FE_PHN54_FE_OFN10_bus_dout_5;
   wire FE_PHN53_FE_OFN11_bus_dout_4;
   wire FE_PHN52_sram_din_55;
   wire FE_PHN51_rstn;
   wire FE_PHN50_FE_OFN13_bus_dout_2;
   wire FE_PHN49_FE_OFN12_bus_dout_3;
   wire FE_PHN48_FE_OFN15_bus_dout_0;
   wire FE_PHN47_FE_OFN9_bus_dout_6;
   wire FE_PHN46_FE_OFN14_bus_dout_1;
   wire FE_PHN45_n_38;
   wire FE_PHN44_n_14;
   wire FE_PHN43_FE_OFN8_bus_dout_7;
   wire FE_PHN42_sram_din_58;
   wire FE_PHN41_sram_cen;
   wire FE_PHN40_tpu_we;
   wire FE_PHN39_tpu_din_17;
   wire FE_PHN38_bus_byte_sel_d1_2;
   wire FE_PHN37_bus_byte_sel_d1_1;
   wire FE_PHN36_bus_byte_sel_d1_0;
   wire FE_PHN35_tpu_din_18;
   wire FE_PHN34_tpu_din_31;
   wire FE_PHN33_tpu_din_20;
   wire FE_PHN32_tpu_din_16;
   wire FE_PHN31_tpu_din_19;
   wire FE_PHN30_tpu_din_21;
   wire FE_PHN29_tpu_din_28;
   wire FE_PHN28_tpu_din_22;
   wire FE_PHN27_tpu_din_23;
   wire FE_PHN26_tpu_din_24;
   wire FE_PHN25_tpu_din_25;
   wire FE_PHN24_bus_addr_0;
   wire FE_PHN23_bus_addr_2;
   wire FE_PHN22_bus_addr_1;
   wire FE_PHN21_tpu_din_26;
   wire FE_PHN20_tpu_din_14;
   wire FE_PHN19_tpu_din_29;
   wire FE_PHN18_tpu_din_15;
   wire FE_PHN17_tpu_din_27;
   wire FE_PHN16_tpu_din_30;
   wire CTS_2;
   wire CTS_1;
   wire LTIELO_NET;
   wire LTIEHI_NET;
   wire FE_OFN15_bus_dout_0;
   wire FE_OFN14_bus_dout_1;
   wire FE_OFN13_bus_dout_2;
   wire FE_OFN12_bus_dout_3;
   wire FE_OFN11_bus_dout_4;
   wire FE_OFN10_bus_dout_5;
   wire FE_OFN9_bus_dout_6;
   wire FE_OFN8_bus_dout_7;
   wire FE_OFN7_n_43;
   wire FE_OFN6_n_36;
   wire FE_OFN5_n_32;
   wire FE_OFN4_n_26;
   wire FE_OFN3_n_25;
   wire FE_OFN2_n_22;
   wire FE_OFN1_n_21;
   wire FE_OFN0_n_15;
   wire [8:0] sram_addr;
   wire [63:0] sram_din;
   wire [63:0] sram_q;
   wire [2:0] bus_byte_sel_d1;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire sram_cen;

   // Module instantiations
   DEL015 FE_PHC235_sram_din_18 (
	.I(sram_din[18]),
	.Z(FE_PHN235_sram_din_18), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC234_sram_din_13 (
	.I(FE_PHN171_sram_din_13),
	.Z(FE_PHN234_sram_din_13), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC233_sram_din_1 (
	.I(FE_PHN233_sram_din_1),
	.Z(FE_PHN186_sram_din_1), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC232_sram_din_8 (
	.I(FE_PHN185_sram_din_8),
	.Z(FE_PHN232_sram_din_8), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC231_sram_din_9 (
	.I(FE_PHN231_sram_din_9),
	.Z(FE_PHN177_sram_din_9), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC230_sram_din_3 (
	.I(FE_PHN230_sram_din_3),
	.Z(FE_PHN169_sram_din_3), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC229_sram_din_5 (
	.I(FE_PHN229_sram_din_5),
	.Z(FE_PHN168_sram_din_5), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC228_sram_din_4 (
	.I(FE_PHN228_sram_din_4),
	.Z(FE_PHN170_sram_din_4), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC227_sram_din_11 (
	.I(FE_PHN227_sram_din_11),
	.Z(FE_PHN178_sram_din_11), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC226_sram_din_10 (
	.I(FE_PHN226_sram_din_10),
	.Z(FE_PHN176_sram_din_10), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC225_sram_din_0 (
	.I(FE_PHN225_sram_din_0),
	.Z(FE_PHN184_sram_din_0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC224_sram_din_12 (
	.I(FE_PHN224_sram_din_12),
	.Z(FE_PHN172_sram_din_12), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC223_sram_din_6 (
	.I(FE_PHN102_sram_din_6),
	.Z(FE_PHN223_sram_din_6), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC222_sram_din_2 (
	.I(FE_PHN105_sram_din_2),
	.Z(FE_PHN222_sram_din_2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC221_sram_din_33 (
	.I(FE_PHN221_sram_din_33),
	.Z(sram_din[33]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC220_sram_din_35 (
	.I(FE_PHN220_sram_din_35),
	.Z(sram_din[35]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC219_sram_din_34 (
	.I(FE_PHN219_sram_din_34),
	.Z(sram_din[34]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD2 FE_PHC218_sram_din_42 (
	.I(FE_PHN218_sram_din_42),
	.Z(sram_din[42]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC217_sram_din_47 (
	.I(FE_PHN217_sram_din_47),
	.Z(sram_din[47]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC216_sram_din_37 (
	.I(FE_PHN216_sram_din_37),
	.Z(sram_din[37]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC215_sram_din_49 (
	.I(FE_PHN143_sram_din_49),
	.Z(FE_PHN215_sram_din_49), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC214_sram_din_32 (
	.I(FE_PHN214_sram_din_32),
	.Z(sram_din[32]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC213_sram_din_43 (
	.I(FE_PHN213_sram_din_43),
	.Z(sram_din[43]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC212_sram_din_38 (
	.I(FE_PHN212_sram_din_38),
	.Z(sram_din[38]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC211_sram_din_50 (
	.I(FE_PHN211_sram_din_50),
	.Z(FE_PHN128_sram_din_50), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD0 FE_PHC210_sram_din_41 (
	.I(FE_PHN210_sram_din_41),
	.Z(sram_din[41]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC209_sram_din_45 (
	.I(FE_PHN209_sram_din_45),
	.Z(sram_din[45]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC208_sram_din_46 (
	.I(FE_PHN125_sram_din_46),
	.Z(FE_PHN208_sram_din_46), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC207_sram_addr_2 (
	.I(FE_PHN207_sram_addr_2),
	.Z(FE_PHN116_sram_addr_2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC206_sram_din_48 (
	.I(FE_PHN127_sram_din_48),
	.Z(FE_PHN206_sram_din_48), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC205_sram_addr_7 (
	.I(FE_PHN205_sram_addr_7),
	.Z(FE_PHN114_sram_addr_7), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC204_sram_addr_8 (
	.I(FE_PHN204_sram_addr_8),
	.Z(FE_PHN113_sram_addr_8), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC203_sram_din_36 (
	.I(sram_din[36]),
	.Z(FE_PHN203_sram_din_36), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC202_sram_din_53 (
	.I(FE_PHN202_sram_din_53),
	.Z(sram_din[53]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC201_sram_din_51 (
	.I(FE_PHN201_sram_din_51),
	.Z(sram_din[51]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC200_sram_din_62 (
	.I(sram_din[62]),
	.Z(FE_PHN200_sram_din_62), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC199_sram_din_54 (
	.I(sram_din[54]),
	.Z(FE_PHN199_sram_din_54), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC198_sram_din_52 (
	.I(sram_din[52]),
	.Z(FE_PHN198_sram_din_52), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC197_sram_din_55 (
	.I(FE_PHN197_sram_din_55),
	.Z(sram_din[55]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC196_sram_din_60 (
	.I(sram_din[60]),
	.Z(FE_PHN196_sram_din_60), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD2 FE_PHC195_sram_din_7 (
	.I(FE_PHN195_sram_din_7),
	.Z(FE_PHN107_sram_din_7), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD0 FE_PHC194_tpu_we (
	.I(tpu_we),
	.Z(FE_PHN194_tpu_we), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC193_bus_addr_0 (
	.I(bus_addr[0]),
	.Z(FE_PHN193_bus_addr_0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC192_bus_addr_5 (
	.I(bus_addr[5]),
	.Z(FE_PHN192_bus_addr_5), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC191_bus_addr_10 (
	.I(bus_addr[10]),
	.Z(FE_PHN191_bus_addr_10), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC190_bus_addr_11 (
	.I(bus_addr[11]),
	.Z(FE_PHN190_bus_addr_11), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC189_bus_addr_2 (
	.I(bus_addr[2]),
	.Z(FE_PHN189_bus_addr_2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD1 FE_PHC188_bus_addr_1 (
	.I(bus_addr[1]),
	.Z(FE_PHN188_bus_addr_1), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD0 FE_PDC16_n_16 (
	.I(n_16),
	.Z(FE_PDN16_n_16), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC187_tpu_din_18 (
	.I(tpu_din[18]),
	.Z(FE_PHN187_tpu_din_18), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD1 FE_PHC186_sram_din_1 (
	.I(FE_PHN173_sram_din_1),
	.Z(FE_PHN233_sram_din_1), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD1 FE_PHC185_sram_din_8 (
	.I(FE_PHN175_sram_din_8),
	.Z(FE_PHN185_sram_din_8), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD1 FE_PHC184_sram_din_0 (
	.I(FE_PHN174_sram_din_0),
	.Z(FE_PHN225_sram_din_0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC183_sram_din_19 (
	.I(sram_din[19]),
	.Z(FE_PHN183_sram_din_19), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC182_sram_din_20 (
	.I(sram_din[20]),
	.Z(FE_PHN182_sram_din_20), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC181_sram_din_21 (
	.I(sram_din[21]),
	.Z(FE_PHN181_sram_din_21), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD1 FE_PHC180_bus_addr_2 (
	.I(FE_PHN189_bus_addr_2),
	.Z(FE_PHN180_bus_addr_2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC179_tpu_we (
	.I(FE_PHN194_tpu_we),
	.Z(FE_PHN179_tpu_we), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD0 FE_PHC178_sram_din_11 (
	.I(FE_PHN100_sram_din_11),
	.Z(FE_PHN227_sram_din_11), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD0 FE_PHC177_sram_din_9 (
	.I(FE_PHN97_sram_din_9),
	.Z(FE_PHN231_sram_din_9), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD0 FE_PHC176_sram_din_10 (
	.I(FE_PHN95_sram_din_10),
	.Z(FE_PHN226_sram_din_10), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL005 FE_PHC175_sram_din_8 (
	.I(FE_PHN98_sram_din_8),
	.Z(FE_PHN175_sram_din_8), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD0 FE_PHC174_sram_din_0 (
	.I(FE_PHN101_sram_din_0),
	.Z(FE_PHN174_sram_din_0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD0 FE_PHC173_sram_din_1 (
	.I(FE_PHN99_sram_din_1),
	.Z(FE_PHN173_sram_din_1), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD0 FE_PHC172_sram_din_12 (
	.I(FE_PHN94_sram_din_12),
	.Z(FE_PHN224_sram_din_12), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL01 FE_PHC171_sram_din_13 (
	.I(FE_PHN96_sram_din_13),
	.Z(FE_PHN171_sram_din_13), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD0 FE_PHC170_sram_din_4 (
	.I(FE_PHN103_sram_din_4),
	.Z(FE_PHN228_sram_din_4), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD0 FE_PHC169_sram_din_3 (
	.I(FE_PHN104_sram_din_3),
	.Z(FE_PHN230_sram_din_3), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD0 FE_PHC168_sram_din_5 (
	.I(FE_PHN106_sram_din_5),
	.Z(FE_PHN229_sram_din_5), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC167_sram_din_33 (
	.I(FE_PHN93_sram_din_33),
	.Z(FE_PHN167_sram_din_33), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC166_sram_din_32 (
	.I(FE_PHN92_sram_din_32),
	.Z(FE_PHN166_sram_din_32), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC165_sram_din_35 (
	.I(FE_PHN91_sram_din_35),
	.Z(FE_PHN165_sram_din_35), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC164_sram_din_34 (
	.I(FE_PHN90_sram_din_34),
	.Z(FE_PHN164_sram_din_34), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC163_sram_din_37 (
	.I(FE_PHN89_sram_din_37),
	.Z(FE_PHN163_sram_din_37), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC162_sram_din_38 (
	.I(FE_PHN86_sram_din_38),
	.Z(FE_PHN162_sram_din_38), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC161_sram_din_36 (
	.I(FE_PHN81_sram_din_36),
	.Z(FE_PHN161_sram_din_36), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC160_sram_din_31 (
	.I(sram_din[31]),
	.Z(FE_PHN160_sram_din_31), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC159_sram_din_16 (
	.I(sram_din[16]),
	.Z(FE_PHN159_sram_din_16), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC158_sram_din_28 (
	.I(sram_din[28]),
	.Z(FE_PHN158_sram_din_28), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC157_sram_din_22 (
	.I(sram_din[22]),
	.Z(FE_PHN157_sram_din_22), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC156_sram_din_23 (
	.I(sram_din[23]),
	.Z(FE_PHN156_sram_din_23), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC155_sram_din_24 (
	.I(sram_din[24]),
	.Z(FE_PHN155_sram_din_24), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC154_sram_din_25 (
	.I(sram_din[25]),
	.Z(FE_PHN154_sram_din_25), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC153_sram_din_26 (
	.I(sram_din[26]),
	.Z(FE_PHN153_sram_din_26), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC152_sram_din_29 (
	.I(sram_din[29]),
	.Z(FE_PHN152_sram_din_29), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC151_sram_din_27 (
	.I(sram_din[27]),
	.Z(FE_PHN151_sram_din_27), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC150_sram_din_14 (
	.I(sram_din[14]),
	.Z(FE_PHN150_sram_din_14), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC149_sram_din_15 (
	.I(sram_din[15]),
	.Z(FE_PHN149_sram_din_15), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC148_sram_din_44 (
	.I(sram_din[44]),
	.Z(FE_PHN148_sram_din_44), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC147_sram_addr_4 (
	.I(sram_addr[4]),
	.Z(FE_PHN147_sram_addr_4), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC146_sram_din_41 (
	.I(sram_din[41]),
	.Z(FE_PHN146_sram_din_41), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC145_bus_addr_1 (
	.I(FE_PHN22_bus_addr_1),
	.Z(FE_PHN145_bus_addr_1), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC144_sram_din_39 (
	.I(sram_din[39]),
	.Z(FE_PHN144_sram_din_39), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC143_sram_din_49 (
	.I(sram_din[49]),
	.Z(FE_PHN143_sram_din_49), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC142_bus_addr_0 (
	.I(FE_PHN24_bus_addr_0),
	.Z(FE_PHN142_bus_addr_0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC141_sram_din_40 (
	.I(sram_din[40]),
	.Z(FE_PHN141_sram_din_40), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC140_sram_din_42 (
	.I(sram_din[42]),
	.Z(FE_PHN140_sram_din_42), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC139_sram_din_47 (
	.I(sram_din[47]),
	.Z(FE_PHN139_sram_din_47), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC138_sram_din_43 (
	.I(sram_din[43]),
	.Z(FE_PHN138_sram_din_43), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC137_sram_addr_0 (
	.I(sram_addr[0]),
	.Z(FE_PHN137_sram_addr_0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC136_sram_din_58 (
	.I(sram_din[58]),
	.Z(FE_PHN136_sram_din_58), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC135_sram_din_56 (
	.I(sram_din[56]),
	.Z(FE_PHN135_sram_din_56), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC134_sram_din_59 (
	.I(sram_din[59]),
	.Z(FE_PHN134_sram_din_59), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC133_sram_din_57 (
	.I(sram_din[57]),
	.Z(FE_PHN133_sram_din_57), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC132_sram_din_61 (
	.I(sram_din[61]),
	.Z(FE_PHN132_sram_din_61), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC131_sram_din_63 (
	.I(sram_din[63]),
	.Z(FE_PHN131_sram_din_63), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC130_sram_addr_1 (
	.I(sram_addr[1]),
	.Z(FE_PHN130_sram_addr_1), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC129_sram_din_45 (
	.I(sram_din[45]),
	.Z(FE_PHN129_sram_din_45), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC128_sram_din_50 (
	.I(sram_din[50]),
	.Z(FE_PHN211_sram_din_50), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC127_sram_din_48 (
	.I(sram_din[48]),
	.Z(FE_PHN127_sram_din_48), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC126_sram_din_51 (
	.I(sram_din[51]),
	.Z(FE_PHN126_sram_din_51), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC125_sram_din_46 (
	.I(sram_din[46]),
	.Z(FE_PHN125_sram_din_46), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC124_sram_din_52 (
	.I(FE_PHN198_sram_din_52),
	.Z(FE_PHN124_sram_din_52), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC123_sram_addr_6 (
	.I(sram_addr[6]),
	.Z(FE_PHN123_sram_addr_6), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC122_sram_din_62 (
	.I(FE_PHN200_sram_din_62),
	.Z(FE_PHN122_sram_din_62), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC121_sram_din_53 (
	.I(sram_din[53]),
	.Z(FE_PHN121_sram_din_53), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC120_sram_din_60 (
	.I(FE_PHN196_sram_din_60),
	.Z(FE_PHN120_sram_din_60), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC119_sram_din_54 (
	.I(FE_PHN199_sram_din_54),
	.Z(FE_PHN119_sram_din_54), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC118_sram_addr_5 (
	.I(sram_addr[5]),
	.Z(FE_PHN118_sram_addr_5), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC117_sram_din_55 (
	.I(sram_din[55]),
	.Z(FE_PHN117_sram_din_55), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC116_sram_addr_2 (
	.I(sram_addr[2]),
	.Z(FE_PHN207_sram_addr_2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC115_sram_addr_3 (
	.I(sram_addr[3]),
	.Z(FE_PHN115_sram_addr_3), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC114_sram_addr_7 (
	.I(sram_addr[7]),
	.Z(FE_PHN205_sram_addr_7), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL015 FE_PHC113_sram_addr_8 (
	.I(sram_addr[8]),
	.Z(FE_PHN204_sram_addr_8), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC112_sram_cen (
	.I(sram_cen),
	.Z(FE_PHN112_sram_cen), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC111_sram_din_30 (
	.I(sram_din[30]),
	.Z(FE_PHN111_sram_din_30), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD1 FE_PHC110_tpu_we (
	.I(tpu_we),
	.Z(FE_PHN110_tpu_we), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD0 FE_PHC109_bus_addr_2 (
	.I(FE_PHN180_bus_addr_2),
	.Z(FE_PHN109_bus_addr_2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC108_rstn (
	.I(rstn),
	.Z(FE_PHN108_rstn), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD2 FE_PHC107_sram_din_7 (
	.I(sram_din[7]),
	.Z(FE_PHN195_sram_din_7), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC106_sram_din_5 (
	.I(sram_din[5]),
	.Z(FE_PHN106_sram_din_5), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC105_sram_din_2 (
	.I(sram_din[2]),
	.Z(FE_PHN105_sram_din_2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC104_sram_din_3 (
	.I(sram_din[3]),
	.Z(FE_PHN104_sram_din_3), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC103_sram_din_4 (
	.I(sram_din[4]),
	.Z(FE_PHN103_sram_din_4), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC102_sram_din_6 (
	.I(sram_din[6]),
	.Z(FE_PHN102_sram_din_6), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC101_sram_din_0 (
	.I(sram_din[0]),
	.Z(FE_PHN101_sram_din_0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC100_sram_din_11 (
	.I(sram_din[11]),
	.Z(FE_PHN100_sram_din_11), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC99_sram_din_1 (
	.I(sram_din[1]),
	.Z(FE_PHN99_sram_din_1), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC98_sram_din_8 (
	.I(sram_din[8]),
	.Z(FE_PHN98_sram_din_8), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC97_sram_din_9 (
	.I(sram_din[9]),
	.Z(FE_PHN97_sram_din_9), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC96_sram_din_13 (
	.I(sram_din[13]),
	.Z(FE_PHN96_sram_din_13), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC95_sram_din_10 (
	.I(sram_din[10]),
	.Z(FE_PHN95_sram_din_10), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC94_sram_din_12 (
	.I(sram_din[12]),
	.Z(FE_PHN94_sram_din_12), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC93_sram_din_33 (
	.I(sram_din[33]),
	.Z(FE_PHN93_sram_din_33), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC92_sram_din_32 (
	.I(sram_din[32]),
	.Z(FE_PHN92_sram_din_32), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC91_sram_din_35 (
	.I(sram_din[35]),
	.Z(FE_PHN91_sram_din_35), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC90_sram_din_34 (
	.I(sram_din[34]),
	.Z(FE_PHN90_sram_din_34), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC89_sram_din_37 (
	.I(sram_din[37]),
	.Z(FE_PHN89_sram_din_37), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC88_sram_din_39 (
	.I(FE_PHN144_sram_din_39),
	.Z(FE_PHN88_sram_din_39), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC87_sram_din_41 (
	.I(FE_PHN146_sram_din_41),
	.Z(FE_PHN87_sram_din_41), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC86_sram_din_38 (
	.I(sram_din[38]),
	.Z(FE_PHN86_sram_din_38), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC85_sram_din_40 (
	.I(FE_PHN141_sram_din_40),
	.Z(FE_PHN85_sram_din_40), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC84_sram_din_42 (
	.I(FE_PHN140_sram_din_42),
	.Z(FE_PHN84_sram_din_42), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC83_sram_din_44 (
	.I(FE_PHN148_sram_din_44),
	.Z(FE_PHN83_sram_din_44), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC82_sram_din_43 (
	.I(FE_PHN138_sram_din_43),
	.Z(FE_PHN82_sram_din_43), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC81_sram_din_36 (
	.I(FE_PHN203_sram_din_36),
	.Z(FE_PHN81_sram_din_36), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC80_sram_addr_6 (
	.I(FE_PHN123_sram_addr_6),
	.Z(FE_PHN80_sram_addr_6), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC79_sram_addr_4 (
	.I(FE_PHN147_sram_addr_4),
	.Z(FE_PHN79_sram_addr_4), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC78_sram_addr_0 (
	.I(FE_PHN137_sram_addr_0),
	.Z(FE_PHN78_sram_addr_0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC77_sram_addr_2 (
	.I(FE_PHN116_sram_addr_2),
	.Z(FE_PHN77_sram_addr_2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC76_sram_addr_5 (
	.I(FE_PHN118_sram_addr_5),
	.Z(FE_PHN76_sram_addr_5), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC75_sram_addr_1 (
	.I(FE_PHN130_sram_addr_1),
	.Z(FE_PHN75_sram_addr_1), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC74_sram_addr_3 (
	.I(FE_PHN115_sram_addr_3),
	.Z(FE_PHN74_sram_addr_3), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC73_sram_addr_7 (
	.I(FE_PHN114_sram_addr_7),
	.Z(FE_PHN73_sram_addr_7), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC72_sram_addr_8 (
	.I(FE_PHN113_sram_addr_8),
	.Z(FE_PHN72_sram_addr_8), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC71_sram_din_45 (
	.I(FE_PHN129_sram_din_45),
	.Z(FE_PHN71_sram_din_45), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC70_sram_din_47 (
	.I(FE_PHN139_sram_din_47),
	.Z(FE_PHN70_sram_din_47), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC69_sram_din_46 (
	.I(FE_PHN208_sram_din_46),
	.Z(FE_PHN69_sram_din_46), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC68_sram_din_49 (
	.I(FE_PHN215_sram_din_49),
	.Z(FE_PHN68_sram_din_49), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC67_sram_din_48 (
	.I(FE_PHN206_sram_din_48),
	.Z(FE_PHN67_sram_din_48), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC66_sram_din_50 (
	.I(FE_PHN128_sram_din_50),
	.Z(FE_PHN66_sram_din_50), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC65_sram_din_53 (
	.I(FE_PHN121_sram_din_53),
	.Z(FE_PHN65_sram_din_53), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC64_sram_din_52 (
	.I(FE_PHN124_sram_din_52),
	.Z(FE_PHN64_sram_din_52), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC63_sram_din_51 (
	.I(FE_PHN126_sram_din_51),
	.Z(FE_PHN63_sram_din_51), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC62_sram_din_54 (
	.I(FE_PHN119_sram_din_54),
	.Z(FE_PHN62_sram_din_54), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC61_sram_din_62 (
	.I(FE_PHN122_sram_din_62),
	.Z(FE_PHN61_sram_din_62), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC60_sram_din_60 (
	.I(FE_PHN120_sram_din_60),
	.Z(FE_PHN60_sram_din_60), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC59_sram_din_56 (
	.I(FE_PHN135_sram_din_56),
	.Z(FE_PHN59_sram_din_56), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC58_sram_din_61 (
	.I(FE_PHN132_sram_din_61),
	.Z(FE_PHN58_sram_din_61), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC57_sram_din_63 (
	.I(FE_PHN131_sram_din_63),
	.Z(FE_PHN57_sram_din_63), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC56_sram_din_59 (
	.I(FE_PHN134_sram_din_59),
	.Z(FE_PHN56_sram_din_59), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC55_sram_din_57 (
	.I(FE_PHN133_sram_din_57),
	.Z(FE_PHN55_sram_din_57), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC54_FE_OFN10_bus_dout_5 (
	.I(FE_OFN10_bus_dout_5),
	.Z(FE_PHN54_FE_OFN10_bus_dout_5), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC53_FE_OFN11_bus_dout_4 (
	.I(FE_OFN11_bus_dout_4),
	.Z(FE_PHN53_FE_OFN11_bus_dout_4), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC52_sram_din_55 (
	.I(FE_PHN117_sram_din_55),
	.Z(FE_PHN52_sram_din_55), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC51_rstn (
	.I(rstn),
	.Z(FE_PHN51_rstn), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC50_FE_OFN13_bus_dout_2 (
	.I(FE_OFN13_bus_dout_2),
	.Z(FE_PHN50_FE_OFN13_bus_dout_2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC49_FE_OFN12_bus_dout_3 (
	.I(FE_OFN12_bus_dout_3),
	.Z(FE_PHN49_FE_OFN12_bus_dout_3), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC48_FE_OFN15_bus_dout_0 (
	.I(FE_OFN15_bus_dout_0),
	.Z(FE_PHN48_FE_OFN15_bus_dout_0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC47_FE_OFN9_bus_dout_6 (
	.I(FE_OFN9_bus_dout_6),
	.Z(FE_PHN47_FE_OFN9_bus_dout_6), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC46_FE_OFN14_bus_dout_1 (
	.I(FE_OFN14_bus_dout_1),
	.Z(FE_PHN46_FE_OFN14_bus_dout_1), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC45_n_38 (
	.I(n_38),
	.Z(FE_PHN45_n_38), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC44_n_14 (
	.I(n_14),
	.Z(FE_PHN44_n_14), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC43_FE_OFN8_bus_dout_7 (
	.I(FE_OFN8_bus_dout_7),
	.Z(FE_PHN43_FE_OFN8_bus_dout_7), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC42_sram_din_58 (
	.I(FE_PHN136_sram_din_58),
	.Z(FE_PHN42_sram_din_58), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC41_sram_cen (
	.I(FE_PHN112_sram_cen),
	.Z(FE_PHN41_sram_cen), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD2 FE_PHC40_tpu_we (
	.I(FE_PHN179_tpu_we),
	.Z(FE_PHN40_tpu_we), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL2 FE_PHC39_tpu_din_17 (
	.I(tpu_din[17]),
	.Z(FE_PHN39_tpu_din_17), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC38_bus_byte_sel_d1_2 (
	.I(bus_byte_sel_d1[2]),
	.Z(FE_PHN38_bus_byte_sel_d1_2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC37_bus_byte_sel_d1_1 (
	.I(bus_byte_sel_d1[1]),
	.Z(FE_PHN37_bus_byte_sel_d1_1), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC36_bus_byte_sel_d1_0 (
	.I(bus_byte_sel_d1[0]),
	.Z(FE_PHN36_bus_byte_sel_d1_0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC35_tpu_din_18 (
	.I(FE_PHN187_tpu_din_18),
	.Z(FE_PHN35_tpu_din_18), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC34_tpu_din_31 (
	.I(tpu_din[31]),
	.Z(FE_PHN34_tpu_din_31), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC33_tpu_din_20 (
	.I(tpu_din[20]),
	.Z(FE_PHN33_tpu_din_20), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC32_tpu_din_16 (
	.I(tpu_din[16]),
	.Z(FE_PHN32_tpu_din_16), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC31_tpu_din_19 (
	.I(tpu_din[19]),
	.Z(FE_PHN31_tpu_din_19), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC30_tpu_din_21 (
	.I(tpu_din[21]),
	.Z(FE_PHN30_tpu_din_21), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC29_tpu_din_28 (
	.I(tpu_din[28]),
	.Z(FE_PHN29_tpu_din_28), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC28_tpu_din_22 (
	.I(tpu_din[22]),
	.Z(FE_PHN28_tpu_din_22), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC27_tpu_din_23 (
	.I(tpu_din[23]),
	.Z(FE_PHN27_tpu_din_23), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC26_tpu_din_24 (
	.I(tpu_din[24]),
	.Z(FE_PHN26_tpu_din_24), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC25_tpu_din_25 (
	.I(tpu_din[25]),
	.Z(FE_PHN25_tpu_din_25), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC24_bus_addr_0 (
	.I(FE_PHN193_bus_addr_0),
	.Z(FE_PHN24_bus_addr_0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC23_bus_addr_2 (
	.I(FE_PHN109_bus_addr_2),
	.Z(FE_PHN23_bus_addr_2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC22_bus_addr_1 (
	.I(FE_PHN188_bus_addr_1),
	.Z(FE_PHN22_bus_addr_1), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC21_tpu_din_26 (
	.I(tpu_din[26]),
	.Z(FE_PHN21_tpu_din_26), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC20_tpu_din_14 (
	.I(tpu_din[14]),
	.Z(FE_PHN20_tpu_din_14), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC19_tpu_din_29 (
	.I(tpu_din[29]),
	.Z(FE_PHN19_tpu_din_29), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC18_tpu_din_15 (
	.I(tpu_din[15]),
	.Z(FE_PHN18_tpu_din_15), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC17_tpu_din_27 (
	.I(tpu_din[27]),
	.Z(FE_PHN17_tpu_din_27), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC16_tpu_din_30 (
	.I(tpu_din[30]),
	.Z(FE_PHN16_tpu_din_30), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKND6 CTS_ccl_a_inv_00001 (
	.I(CTS_2),
	.ZN(CTS_1), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKND1 CTS_cmf_inv_00047 (
	.I(clk),
	.ZN(CTS_2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   TIEL LTIELO (
	.ZN(LTIELO_NET), 
	.VSS(DVSS), 
	.VDD(DVDD));
   TIEH LTIEHI (
	.Z(LTIEHI_NET), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD16 FE_OFC15_bus_dout_0 (
	.I(FE_PHN48_FE_OFN15_bus_dout_0),
	.Z(bus_dout[0]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD16 FE_OFC14_bus_dout_1 (
	.I(FE_PHN46_FE_OFN14_bus_dout_1),
	.Z(bus_dout[1]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD12 FE_OFC13_bus_dout_2 (
	.I(FE_PHN50_FE_OFN13_bus_dout_2),
	.Z(bus_dout[2]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD16 FE_OFC12_bus_dout_3 (
	.I(FE_PHN49_FE_OFN12_bus_dout_3),
	.Z(bus_dout[3]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD12 FE_OFC11_bus_dout_4 (
	.I(FE_PHN53_FE_OFN11_bus_dout_4),
	.Z(bus_dout[4]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD12 FE_OFC10_bus_dout_5 (
	.I(FE_PHN54_FE_OFN10_bus_dout_5),
	.Z(bus_dout[5]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD12 FE_OFC9_bus_dout_6 (
	.I(FE_PHN47_FE_OFN9_bus_dout_6),
	.Z(bus_dout[6]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD16 FE_OFC8_bus_dout_7 (
	.I(FE_PHN43_FE_OFN8_bus_dout_7),
	.Z(bus_dout[7]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD1 FE_OFC7_n_43 (
	.I(n_43),
	.Z(FE_OFN7_n_43), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD1 FE_OFC6_n_36 (
	.I(n_36),
	.Z(FE_OFN6_n_36), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD0 FE_OFC5_n_32 (
	.I(n_32),
	.Z(FE_OFN5_n_32), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD1 FE_OFC4_n_26 (
	.I(n_26),
	.Z(FE_OFN4_n_26), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD1 FE_OFC3_n_25 (
	.I(n_25),
	.Z(FE_OFN3_n_25), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD1 FE_OFC2_n_22 (
	.I(n_22),
	.Z(FE_OFN2_n_22), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD1 FE_OFC1_n_21 (
	.I(n_21),
	.Z(FE_OFN1_n_21), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD2 FE_OFC0_n_15 (
	.I(n_15),
	.Z(FE_OFN0_n_15), 
	.VSS(DVSS), 
	.VDD(DVDD));
   sram00 u_sram (
	.Q({ sram_q[63],
		sram_q[62],
		sram_q[61],
		sram_q[60],
		sram_q[59],
		sram_q[58],
		sram_q[57],
		sram_q[56],
		sram_q[55],
		sram_q[54],
		sram_q[53],
		sram_q[52],
		sram_q[51],
		sram_q[50],
		sram_q[49],
		sram_q[48],
		sram_q[47],
		sram_q[46],
		sram_q[45],
		sram_q[44],
		sram_q[43],
		sram_q[42],
		sram_q[41],
		sram_q[40],
		sram_q[39],
		sram_q[38],
		sram_q[37],
		sram_q[36],
		sram_q[35],
		sram_q[34],
		sram_q[33],
		sram_q[32],
		sram_q[31],
		sram_q[30],
		sram_q[29],
		sram_q[28],
		sram_q[27],
		sram_q[26],
		sram_q[25],
		sram_q[24],
		sram_q[23],
		sram_q[22],
		sram_q[21],
		sram_q[20],
		sram_q[19],
		sram_q[18],
		sram_q[17],
		sram_q[16],
		sram_q[15],
		sram_q[14],
		sram_q[13],
		sram_q[12],
		sram_q[11],
		sram_q[10],
		sram_q[9],
		sram_q[8],
		n_60,
		n_61,
		n_62,
		n_63,
		n_64,
		n_65,
		n_66,
		n_67 }),
	.CLK(CTS_1),
	.CEN(FE_PHN41_sram_cen),
	.WEN(n_0),
	.A({ FE_PHN72_sram_addr_8,
		FE_PHN73_sram_addr_7,
		FE_PHN80_sram_addr_6,
		FE_PHN76_sram_addr_5,
		FE_PHN79_sram_addr_4,
		FE_PHN74_sram_addr_3,
		FE_PHN77_sram_addr_2,
		FE_PHN75_sram_addr_1,
		FE_PHN78_sram_addr_0 }),
	.D({ FE_PHN57_sram_din_63,
		FE_PHN61_sram_din_62,
		FE_PHN58_sram_din_61,
		FE_PHN60_sram_din_60,
		FE_PHN56_sram_din_59,
		FE_PHN42_sram_din_58,
		FE_PHN55_sram_din_57,
		FE_PHN59_sram_din_56,
		FE_PHN52_sram_din_55,
		FE_PHN62_sram_din_54,
		FE_PHN65_sram_din_53,
		FE_PHN64_sram_din_52,
		FE_PHN63_sram_din_51,
		FE_PHN66_sram_din_50,
		FE_PHN68_sram_din_49,
		FE_PHN67_sram_din_48,
		FE_PHN70_sram_din_47,
		FE_PHN69_sram_din_46,
		FE_PHN71_sram_din_45,
		FE_PHN83_sram_din_44,
		FE_PHN82_sram_din_43,
		FE_PHN84_sram_din_42,
		FE_PHN87_sram_din_41,
		FE_PHN85_sram_din_40,
		FE_PHN88_sram_din_39,
		FE_PHN162_sram_din_38,
		FE_PHN163_sram_din_37,
		FE_PHN161_sram_din_36,
		FE_PHN165_sram_din_35,
		FE_PHN164_sram_din_34,
		FE_PHN167_sram_din_33,
		FE_PHN166_sram_din_32,
		FE_PHN160_sram_din_31,
		FE_PHN111_sram_din_30,
		FE_PHN152_sram_din_29,
		FE_PHN158_sram_din_28,
		FE_PHN151_sram_din_27,
		FE_PHN153_sram_din_26,
		FE_PHN154_sram_din_25,
		FE_PHN155_sram_din_24,
		FE_PHN156_sram_din_23,
		FE_PHN157_sram_din_22,
		FE_PHN181_sram_din_21,
		FE_PHN182_sram_din_20,
		FE_PHN183_sram_din_19,
		FE_PHN235_sram_din_18,
		sram_din[17],
		FE_PHN159_sram_din_16,
		FE_PHN149_sram_din_15,
		FE_PHN150_sram_din_14,
		FE_PHN234_sram_din_13,
		FE_PHN172_sram_din_12,
		FE_PHN178_sram_din_11,
		FE_PHN176_sram_din_10,
		FE_PHN177_sram_din_9,
		FE_PHN232_sram_din_8,
		FE_PHN107_sram_din_7,
		FE_PHN223_sram_din_6,
		FE_PHN168_sram_din_5,
		FE_PHN170_sram_din_4,
		FE_PHN169_sram_din_3,
		FE_PHN222_sram_din_2,
		FE_PHN186_sram_din_1,
		FE_PHN184_sram_din_0 }),
	.EMA({ LTIELO_NET,
		LTIEHI_NET,
		LTIELO_NET }),
	.RETN(LTIEHI_NET), 
	.VSS(DVSS), 
	.VDD(DVDD));
   ND4D1 p70817A__2398 (
	.A1(FE_OFN7_n_43),
	.A2(n_30),
	.A3(n_41),
	.A4(n_40),
	.ZN(FE_OFN13_bus_dout_2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   ND4D1 p70817A1797__5107 (
	.A1(FE_OFN2_n_22),
	.A2(n_27),
	.A3(n_35),
	.A4(n_20),
	.ZN(FE_OFN9_bus_dout_6), 
	.VSS(DVSS), 
	.VDD(DVDD));
   ND4D1 p70817A1798__6260 (
	.A1(FE_OFN5_n_32),
	.A2(n_18),
	.A3(n_45),
	.A4(FE_PDN16_n_16),
	.ZN(FE_OFN8_bus_dout_7), 
	.VSS(DVSS), 
	.VDD(DVDD));
   ND4D1 p70817A1799__4319 (
	.A1(n_39),
	.A2(FE_OFN6_n_36),
	.A3(n_37),
	.A4(n_33),
	.ZN(FE_OFN14_bus_dout_1), 
	.VSS(DVSS), 
	.VDD(DVDD));
   ND4D1 p70817A1800__8428 (
	.A1(FE_OFN0_n_15),
	.A2(n_44),
	.A3(n_42),
	.A4(FE_PHN45_n_38),
	.ZN(FE_OFN10_bus_dout_5), 
	.VSS(DVSS), 
	.VDD(DVDD));
   ND4D1 p70817A1801__5526 (
	.A1(n_31),
	.A2(FE_OFN4_n_26),
	.A3(n_28),
	.A4(n_24),
	.ZN(FE_OFN15_bus_dout_0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   ND4D1 p70817A1802__6783 (
	.A1(n_34),
	.A2(FE_OFN3_n_25),
	.A3(FE_PHN44_n_14),
	.A4(n_23),
	.ZN(FE_OFN11_bus_dout_4), 
	.VSS(DVSS), 
	.VDD(DVDD));
   ND4D1 p70817A1803__3680 (
	.A1(FE_OFN1_n_21),
	.A2(n_19),
	.A3(n_17),
	.A4(n_29),
	.ZN(FE_OFN12_bus_dout_3), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70812A__1617 (
	.A1(sram_q[23]),
	.A2(n_6),
	.B1(sram_q[31]),
	.B2(n_9),
	.ZN(n_45), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D1 p70816A__2802 (
	.A1(sram_q[37]),
	.A2(n_8),
	.B1(sram_q[45]),
	.B2(n_7),
	.ZN(n_44), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70824A__1705 (
	.A1(sram_q[50]),
	.A2(n_10),
	.B1(sram_q[58]),
	.B2(n_13),
	.ZN(n_43), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70812A1804__5122 (
	.A1(sram_q[21]),
	.A2(n_6),
	.B1(sram_q[29]),
	.B2(n_9),
	.ZN(n_42), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D1 p70812A1805__8246 (
	.A1(sram_q[34]),
	.A2(n_8),
	.B1(sram_q[42]),
	.B2(n_7),
	.ZN(n_41), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D1 p70810A__7098 (
	.A1(n_65),
	.A2(n_12),
	.B1(sram_q[10]),
	.B2(n_11),
	.ZN(n_40), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D1 p70824A1806__6131 (
	.A1(sram_q[33]),
	.A2(n_8),
	.B1(sram_q[41]),
	.B2(n_7),
	.ZN(n_39), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70810A1807__1881 (
	.A1(n_62),
	.A2(n_12),
	.B1(sram_q[13]),
	.B2(n_11),
	.ZN(n_38), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70812A1808__5115 (
	.A1(sram_q[17]),
	.A2(n_6),
	.B1(sram_q[25]),
	.B2(n_9),
	.ZN(n_37), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70816A1809__7482 (
	.A1(sram_q[49]),
	.A2(n_10),
	.B1(sram_q[57]),
	.B2(n_13),
	.ZN(n_36), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D1 p70812A1810__4733 (
	.A1(n_61),
	.A2(n_12),
	.B1(sram_q[14]),
	.B2(n_11),
	.ZN(n_35), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70824A1811__6161 (
	.A1(sram_q[20]),
	.A2(n_6),
	.B1(sram_q[28]),
	.B2(n_9),
	.ZN(n_34), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70810A1812__9315 (
	.A1(n_66),
	.A2(n_12),
	.B1(sram_q[9]),
	.B2(n_11),
	.ZN(n_33), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70824A1813__9945 (
	.A1(sram_q[55]),
	.A2(n_10),
	.B1(sram_q[63]),
	.B2(n_13),
	.ZN(n_32), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D1 p70824A1814__2883 (
	.A1(sram_q[32]),
	.A2(n_8),
	.B1(sram_q[40]),
	.B2(n_7),
	.ZN(n_31), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70816A1815__2346 (
	.A1(sram_q[18]),
	.A2(n_6),
	.B1(sram_q[26]),
	.B2(n_9),
	.ZN(n_30), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D1 p70810A1816__1666 (
	.A1(n_64),
	.A2(n_12),
	.B1(sram_q[11]),
	.B2(n_11),
	.ZN(n_29), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70812A1817__7410 (
	.A1(sram_q[16]),
	.A2(n_6),
	.B1(sram_q[24]),
	.B2(n_9),
	.ZN(n_28), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70816A1818__6417 (
	.A1(sram_q[22]),
	.A2(n_6),
	.B1(sram_q[30]),
	.B2(n_9),
	.ZN(n_27), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70816A1819__5477 (
	.A1(sram_q[48]),
	.A2(n_10),
	.B1(sram_q[56]),
	.B2(n_13),
	.ZN(n_26), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70816A1820__2398 (
	.A1(sram_q[52]),
	.A2(n_10),
	.B1(sram_q[60]),
	.B2(n_13),
	.ZN(n_25), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70810A1821__5107 (
	.A1(n_67),
	.A2(n_12),
	.B1(sram_q[8]),
	.B2(n_11),
	.ZN(n_24), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D1 p70810A1822__6260 (
	.A1(sram_q[36]),
	.A2(n_8),
	.B1(sram_q[44]),
	.B2(n_7),
	.ZN(n_23), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70824A1823__4319 (
	.A1(sram_q[54]),
	.A2(n_10),
	.B1(sram_q[62]),
	.B2(n_13),
	.ZN(n_22), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70824A1824__8428 (
	.A1(sram_q[51]),
	.A2(n_10),
	.B1(sram_q[59]),
	.B2(n_13),
	.ZN(n_21), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D1 p70810A1825__5526 (
	.A1(sram_q[38]),
	.A2(n_8),
	.B1(sram_q[46]),
	.B2(n_7),
	.ZN(n_20), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D1 p70816A1826__6783 (
	.A1(sram_q[35]),
	.A2(n_8),
	.B1(sram_q[43]),
	.B2(n_7),
	.ZN(n_19), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D1 p70816A1827__3680 (
	.A1(sram_q[39]),
	.A2(n_8),
	.B1(sram_q[47]),
	.B2(n_7),
	.ZN(n_18), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70812A1828__1617 (
	.A1(sram_q[19]),
	.A2(n_6),
	.B1(sram_q[27]),
	.B2(n_9),
	.ZN(n_17), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70810A1829__2802 (
	.A1(n_60),
	.A2(n_12),
	.B1(sram_q[15]),
	.B2(n_11),
	.ZN(n_16), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70824A1830__1705 (
	.A1(sram_q[53]),
	.A2(n_10),
	.B1(sram_q[61]),
	.B2(n_13),
	.ZN(n_15), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI22D0 p70812A1831__5122 (
	.A1(n_63),
	.A2(n_12),
	.B1(sram_q[12]),
	.B2(n_11),
	.ZN(n_14), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2D2 p71871A__8246 (
	.A1(n_2),
	.A2(n_1),
	.ZN(n_13), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INR2D0 p71849A__7098 (
	.A1(n_5),
	.B1(FE_PHN36_bus_byte_sel_d1_0),
	.ZN(n_12), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p71898A__6131 (
	.A1(n_5),
	.A2(FE_PHN36_bus_byte_sel_d1_0),
	.Z(n_11), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2XD1 p71884A__1881 (
	.A1(n_2),
	.A2(FE_PHN36_bus_byte_sel_d1_0),
	.ZN(n_10), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2D1 p71849A1832__5115 (
	.A1(n_3),
	.A2(n_1),
	.ZN(n_9), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2D1 p71859A__7482 (
	.A1(n_4),
	.A2(FE_PHN36_bus_byte_sel_d1_0),
	.ZN(n_8), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2D1 p71846A__4733 (
	.A1(n_4),
	.A2(n_1),
	.ZN(n_7), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2D1 p71862A__6161 (
	.A1(n_3),
	.A2(FE_PHN36_bus_byte_sel_d1_0),
	.ZN(n_6), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2D0 p71824A__9315 (
	.A1(FE_PHN38_bus_byte_sel_d1_2),
	.A2(FE_PHN37_bus_byte_sel_d1_1),
	.ZN(n_5), 
	.VSS(DVSS), 
	.VDD(DVDD));
   IND2D0 p71822A__9945 (
	.A1(FE_PHN37_bus_byte_sel_d1_1),
	.B1(FE_PHN38_bus_byte_sel_d1_2),
	.ZN(n_4), 
	.VSS(DVSS), 
	.VDD(DVDD));
   IND2D0 p71825A__2883 (
	.A1(FE_PHN38_bus_byte_sel_d1_2),
	.B1(FE_PHN37_bus_byte_sel_d1_1),
	.ZN(n_3), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKND2D0 p71861A__2346 (
	.A1(FE_PHN37_bus_byte_sel_d1_1),
	.A2(FE_PHN38_bus_byte_sel_d1_2),
	.ZN(n_2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DFCNQD1 \bus_byte_sel_d1_reg[2]  (
	.CDN(FE_PHN51_rstn),
	.CP(CTS_1),
	.D(FE_PHN23_bus_addr_2),
	.Q(bus_byte_sel_d1[2]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DFCNQD1 \bus_byte_sel_d1_reg[1]  (
	.CDN(FE_PHN51_rstn),
	.CP(CTS_1),
	.D(FE_PHN145_bus_addr_1),
	.Q(bus_byte_sel_d1[1]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AO22D0 p96144A__1666 (
	.A1(n_0),
	.A2(bus_addr[8]),
	.B1(tpu_addr[5]),
	.B2(FE_PHN40_tpu_we),
	.Z(sram_addr[5]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AO22D0 p96144A1087__7410 (
	.A1(n_0),
	.A2(FE_PHN191_bus_addr_10),
	.B1(tpu_addr[7]),
	.B2(FE_PHN40_tpu_we),
	.Z(sram_addr[7]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AO22D0 p96144A1088__6417 (
	.A1(n_0),
	.A2(FE_PHN190_bus_addr_11),
	.B1(tpu_addr[8]),
	.B2(FE_PHN40_tpu_we),
	.Z(sram_addr[8]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AO22D0 p96144A1089__5477 (
	.A1(n_0),
	.A2(FE_PHN192_bus_addr_5),
	.B1(tpu_addr[2]),
	.B2(FE_PHN40_tpu_we),
	.Z(sram_addr[2]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AO22D0 p96144A1090__2398 (
	.A1(n_0),
	.A2(bus_addr[3]),
	.B1(tpu_addr[0]),
	.B2(FE_PHN40_tpu_we),
	.Z(sram_addr[0]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AO22D0 p96144A1091__5107 (
	.A1(n_0),
	.A2(bus_addr[7]),
	.B1(tpu_addr[4]),
	.B2(FE_PHN40_tpu_we),
	.Z(sram_addr[4]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AO22D0 p96144A1092__6260 (
	.A1(n_0),
	.A2(bus_addr[4]),
	.B1(tpu_addr[1]),
	.B2(FE_PHN40_tpu_we),
	.Z(sram_addr[1]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AO22D0 p96144A1093__4319 (
	.A1(n_0),
	.A2(bus_addr[9]),
	.B1(tpu_addr[6]),
	.B2(FE_PHN40_tpu_we),
	.Z(sram_addr[6]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AO22D0 p96144A1094__8428 (
	.A1(n_0),
	.A2(bus_addr[6]),
	.B1(tpu_addr[3]),
	.B2(FE_PHN40_tpu_we),
	.Z(sram_addr[3]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AN2XD1 p96447A__5526 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN18_tpu_din_15),
	.Z(sram_din[15]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1095__6783 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN26_tpu_din_24),
	.Z(sram_din[24]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1096__3680 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN27_tpu_din_23),
	.Z(sram_din[23]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1097__1617 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[55]),
	.Z(FE_PHN197_sram_din_55), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1098__2802 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN28_tpu_din_22),
	.Z(sram_din[22]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1099__1705 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN30_tpu_din_21),
	.Z(sram_din[21]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1100__5122 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[54]),
	.Z(sram_din[54]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1101__8246 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN33_tpu_din_20),
	.Z(sram_din[20]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1102__7098 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN31_tpu_din_19),
	.Z(sram_din[19]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1103__6131 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[53]),
	.Z(FE_PHN202_sram_din_53), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1104__1881 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN35_tpu_din_18),
	.Z(sram_din[18]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AN2XD1 p96447A1105__5115 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[10]),
	.Z(sram_din[10]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1106__7482 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN39_tpu_din_17),
	.Z(sram_din[17]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1107__4733 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[52]),
	.Z(sram_din[52]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AN2XD1 p96447A1108__6161 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[12]),
	.Z(sram_din[12]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1109__9315 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN32_tpu_din_16),
	.Z(sram_din[16]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1110__9945 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[56]),
	.Z(sram_din[56]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1111__2883 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[51]),
	.Z(FE_PHN201_sram_din_51), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AN2XD1 p96447A1112__2346 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN20_tpu_din_14),
	.Z(sram_din[14]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AN2XD1 p96447A1113__1666 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[13]),
	.Z(sram_din[13]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1114__7410 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[50]),
	.Z(sram_din[50]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AN2XD1 p96447A1115__6417 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[11]),
	.Z(sram_din[11]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1116__5477 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[49]),
	.Z(sram_din[49]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AN2XD1 p96447A1117__2398 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[9]),
	.Z(sram_din[9]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1118__5107 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[48]),
	.Z(sram_din[48]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AN2XD1 p96447A1119__6260 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[8]),
	.Z(sram_din[8]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AN2XD1 p96447A1120__4319 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[7]),
	.Z(sram_din[7]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1121__8428 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[47]),
	.Z(FE_PHN217_sram_din_47), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AN2XD1 p96447A1122__5526 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[6]),
	.Z(sram_din[6]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AN2XD1 p96447A1123__6783 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[5]),
	.Z(sram_din[5]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1124__3680 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[46]),
	.Z(sram_din[46]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AN2XD1 p96447A1125__1617 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[4]),
	.Z(sram_din[4]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1126__2802 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[62]),
	.Z(sram_din[62]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1127__1705 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[45]),
	.Z(FE_PHN209_sram_din_45), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AN2XD1 p96447A1128__5122 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[2]),
	.Z(sram_din[2]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AN2XD1 p96447A1129__8246 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[1]),
	.Z(sram_din[1]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1130__7098 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[44]),
	.Z(sram_din[44]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AN2XD1 p96447A1131__6131 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[0]),
	.Z(sram_din[0]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1132__1881 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[43]),
	.Z(FE_PHN213_sram_din_43), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1133__5115 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[42]),
	.Z(FE_PHN218_sram_din_42), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1134__7482 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[41]),
	.Z(FE_PHN210_sram_din_41), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1135__4733 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN16_tpu_din_30),
	.Z(sram_din[30]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2D0 p96407A__6161 (
	.A1(FE_PHN40_tpu_we),
	.A2(bus_re),
	.ZN(sram_cen), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1136__9315 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[40]),
	.Z(sram_din[40]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1137__9945 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[39]),
	.Z(sram_din[39]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1138__2883 (
	.A1(FE_PHN110_tpu_we),
	.A2(tpu_din[63]),
	.Z(sram_din[63]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1139__2346 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[38]),
	.Z(FE_PHN212_sram_din_38), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1140__1666 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[37]),
	.Z(FE_PHN216_sram_din_37), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AN2XD1 p96447A1141__7410 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[3]),
	.Z(sram_din[3]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AN2D2 p96447A1142__6417 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[36]),
	.Z(sram_din[36]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1143__5477 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[35]),
	.Z(FE_PHN220_sram_din_35), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1144__2398 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[61]),
	.Z(sram_din[61]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1145__5107 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[34]),
	.Z(FE_PHN219_sram_din_34), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1146__6260 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[33]),
	.Z(FE_PHN221_sram_din_33), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1147__4319 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[60]),
	.Z(sram_din[60]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1148__8428 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[32]),
	.Z(FE_PHN214_sram_din_32), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1149__5526 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN34_tpu_din_31),
	.Z(sram_din[31]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1150__6783 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[59]),
	.Z(sram_din[59]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1151__3680 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN19_tpu_din_29),
	.Z(sram_din[29]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1152__1617 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[58]),
	.Z(sram_din[58]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1153__2802 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN29_tpu_din_28),
	.Z(sram_din[28]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1154__1705 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN17_tpu_din_27),
	.Z(sram_din[27]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1155__5122 (
	.A1(FE_PHN40_tpu_we),
	.A2(tpu_din[57]),
	.Z(sram_din[57]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1156__8246 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN21_tpu_din_26),
	.Z(sram_din[26]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKAN2D0 p96447A1157__7098 (
	.A1(FE_PHN40_tpu_we),
	.A2(FE_PHN25_tpu_din_25),
	.Z(sram_din[25]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKND0 Fp96144A1836 (
	.I(FE_PHN40_tpu_we),
	.ZN(n_0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DFCND1 \bus_byte_sel_d1_reg[0]  (
	.CDN(FE_PHN108_rstn),
	.CP(CTS_1),
	.D(FE_PHN142_bus_addr_0),
	.Q(bus_byte_sel_d1[0]),
	.QN(n_1), 
	.VSS(DVSS), 
	.VDD(DVDD));
endmodule

