
// Generated by Cadence Genus(TM) Synthesis Solution 21.16-s062_1
// Generated on: Mar 22 2026 14:07:19 EDT (Mar 22 2026 18:07:19 UTC)

// Verification Directory fv/output_idx_controller 

module output_idx_controller(clk, rstn, alu_init, in_valid, row_idx,
     num_computation, m, k, c_row_idx, c_col_idx, done_flag);
  input clk, rstn, alu_init, in_valid;
  input [2:0] row_idx;
  input [6:0] num_computation, m, k;
  output [8:0] c_row_idx, c_col_idx;
  output done_flag;
  wire clk, rstn, alu_init, in_valid;
  wire [2:0] row_idx;
  wire [6:0] num_computation, m, k;
  wire [8:0] c_row_idx, c_col_idx;
  wire done_flag;
  wire [8:0] c_col_os;
  wire [6:0] num_computated;
  wire [8:0] c_col_idx_temp;
  wire [8:0] u_out_ac_i;
  wire done_flag_166, n_0, n_1, n_2, n_4, n_5, n_6, n_7;
  wire n_9, n_12, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_47;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_73;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_93, n_95, n_96, n_97, n_99, n_100, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_206, n_207, n_208, n_209, n_210;
  wire n_211, n_232, n_238, n_250, n_254, n_255;
  assign c_col_idx[0] = 1'b0;
  assign c_col_idx[1] = 1'b0;
  assign c_col_idx[2] = 1'b0;
  assign c_row_idx[0] = row_idx[0];
  assign c_row_idx[1] = row_idx[1];
  assign c_row_idx[2] = row_idx[2];
  EDFKCNQD1 \c_col_os_reg[8] (.CP (clk), .CN (rstn), .D (n_189), .E
       (n_190), .Q (c_col_os[8]));
  MOAI22D0 p18291A__2398(.A1 (n_188), .A2 (n_187), .B1 (n_188), .B2
       (n_187), .ZN (n_189));
  DFKCNQD1 \num_computated_reg[5] (.CP (clk), .CN (rstn), .D (n_185),
       .Q (num_computated[5]));
  DFKCNQD1 \num_computated_reg[1] (.CP (clk), .CN (rstn), .D (n_182),
       .Q (num_computated[1]));
  DFKCNQD1 \num_computated_reg[3] (.CP (clk), .CN (rstn), .D (n_184),
       .Q (num_computated[3]));
  DFKCNQD1 \c_col_os_reg[3] (.CP (clk), .CN (rstn), .D (n_181), .Q
       (c_col_os[3]));
  DFKCNQD1 \num_computated_reg[0] (.CP (clk), .CN (rstn), .D (n_180),
       .Q (num_computated[0]));
  FA1D0 p18250A__5107(.A (c_col_os[7]), .B (k[4]), .CI (n_156), .CO
       (n_188), .S (n_186));
  IOA21D0 p18246A3671__6260(.A1 (n_183), .A2 (num_computated[5]), .B
       (n_163), .ZN (n_185));
  IOA21D0 p18246A3670__4319(.A1 (n_183), .A2 (num_computated[3]), .B
       (n_165), .ZN (n_184));
  IOA21D0 p18246A3669__8428(.A1 (n_183), .A2 (num_computated[1]), .B
       (n_164), .ZN (n_182));
  IOA21D0 p18246A__5526(.A1 (n_183), .A2 (c_col_os[3]), .B (n_162), .ZN
       (n_181));
  EDFKCNQD1 \num_computated_reg[6] (.CP (clk), .CN (rstn), .D (n_137),
       .E (n_190), .Q (num_computated[6]));
  EDFKCNQD1 \c_col_os_reg[5] (.CP (clk), .CN (rstn), .D (n_145), .E
       (n_190), .Q (c_col_os[5]));
  EDFKCNQD1 \c_col_os_reg[4] (.CP (clk), .CN (rstn), .D (n_107), .E
       (n_190), .Q (c_col_os[4]));
  MUX2ND0 p18240A__6783(.I0 (n_183), .I1 (n_190), .S
       (num_computated[0]), .ZN (n_180));
  AO22D0 p18289A3679__3680(.A1 (n_178), .A2 (n_121), .B1 (n_177), .B2
       (c_col_idx_temp[8]), .Z (n_179));
  MOAI22D0 p18332A3678__1617(.A1 (n_170), .A2 (n_206), .B1 (n_175), .B2
       (u_out_ac_i[8]), .ZN (n_176));
  AO22D0 p18289A3680__2802(.A1 (n_178), .A2 (n_31), .B1 (n_177), .B2
       (c_col_idx_temp[4]), .Z (n_174));
  AO22D0 p18289A3681__1705(.A1 (n_178), .A2 (n_44), .B1 (n_177), .B2
       (c_col_idx_temp[5]), .Z (n_173));
  AO22D0 p18289A3682__5122(.A1 (n_178), .A2 (n_63), .B1 (n_177), .B2
       (c_col_idx_temp[6]), .Z (n_172));
  MOAI22D0 p18332A3683__8246(.A1 (n_170), .A2 (n_210), .B1 (n_175), .B2
       (u_out_ac_i[5]), .ZN (n_171));
  MOAI22D0 p18332A__7098(.A1 (n_170), .A2 (n_147), .B1 (n_175), .B2
       (u_out_ac_i[4]), .ZN (n_169));
  MOAI22D0 p18332A3676__6131(.A1 (n_170), .A2 (n_209), .B1 (n_175), .B2
       (u_out_ac_i[6]), .ZN (n_168));
  MOAI22D0 p18332A3677__1881(.A1 (n_170), .A2 (n_207), .B1 (n_175), .B2
       (u_out_ac_i[7]), .ZN (n_167));
  AO22D0 p18289A__5115(.A1 (n_178), .A2 (n_96), .B1 (n_177), .B2
       (c_col_idx_temp[7]), .Z (n_166));
  OAI211D0 p18222A__7482(.A1 (num_computated[3]), .A2 (n_58), .B
       (n_190), .C (n_110), .ZN (n_165));
  OAI211D0 p18222A3674__4733(.A1 (num_computated[0]), .A2
       (num_computated[1]), .B (n_190), .C (n_59), .ZN (n_164));
  OAI211D0 p18222A3675__6161(.A1 (num_computated[5]), .A2 (n_108), .B
       (n_190), .C (n_136), .ZN (n_163));
  OAI211D0 p18221A__9315(.A1 (k[0]), .A2 (c_col_os[3]), .B (n_190), .C
       (n_20), .ZN (n_162));
  CKND0 Fp18296A(.I (n_170), .ZN (n_161));
  OAI31D0 p18260A__9945(.A1 (n_155), .A2 (n_158), .A3 (n_159), .B
       (rstn), .ZN (n_160));
  CKND0 Fp18200A(.I (n_190), .ZN (n_183));
  IND3D0 p18227A__2883(.A1 (n_159), .B1 (rstn), .B2 (n_158), .ZN
       (n_170));
  NR2D0 p18251A__2346(.A1 (n_154), .A2 (n_177), .ZN (n_178));
  FA1D0 p18212A__1666(.A (c_col_os[6]), .B (k[3]), .CI (n_144), .CO
       (n_156), .S (n_157));
  INR3D0 p17878A__7410(.A1 (n_155), .B1 (n_158), .B2 (n_159), .ZN
       (n_190));
  CKND0 Fp18257A(.I (n_154), .ZN (n_175));
  CKND2D0 p18258A__6417(.A1 (n_159), .A2 (rstn), .ZN (n_154));
  OAI211D0 p17867A__5477(.A1 (m[6]), .A2 (n_124), .B (n_148), .C
       (n_125), .ZN (n_158));
  OR2D8 p13248A__2398(.A1 (n_151), .A2 (n_152), .Z (c_col_idx[8]));
  ND4D0 p17946A__5107(.A1 (n_143), .A2 (n_131), .A3 (n_127), .A4
       (n_115), .ZN (n_155));
  OAI211D0 p17850A__6260(.A1 (k[0]), .A2 (c_col_idx_temp[3]), .B
       (n_142), .C (n_71), .ZN (n_159));
  NR2D0 p13239A__4319(.A1 (n_150), .A2 (n_149), .ZN (n_152));
  CKAN2D0 p13247A__8428(.A1 (n_150), .A2 (n_149), .Z (n_151));
  AOI221D0 p17717A__5526(.A1 (n_132), .A2 (n_133), .B1 (n_147), .B2
       (m[1]), .C (n_134), .ZN (n_148));
  OR2D8 p13293A__6783(.A1 (n_141), .A2 (n_139), .Z (c_col_idx[7]));
  FA1D0 p18170A__3680(.A (c_col_os[5]), .B (k[2]), .CI (n_106), .CO
       (n_144), .S (n_145));
  IOA21D0 p13222A__1617(.A1 (n_140), .A2 (n_40), .B (n_39), .ZN
       (n_150));
  AOI221D0 p17922A__2802(.A1 (n_12), .A2 (n_9), .B1
       (num_computated[3]), .B2 (n_128), .C (n_129), .ZN (n_143));
  AN4D0 p17815A__1705(.A1 (n_126), .A2 (n_79), .A3 (n_99), .A4 (n_83),
       .Z (n_142));
  CKAN2D0 p13290A__5122(.A1 (n_140), .A2 (n_138), .Z (n_141));
  NR2D0 p13282A__8246(.A1 (n_140), .A2 (n_138), .ZN (n_139));
  MOAI22D0 p18366A__7098(.A1 (n_136), .A2 (num_computated[6]), .B1
       (n_136), .B2 (num_computated[6]), .ZN (n_137));
  OR2D8 p13336A__6131(.A1 (n_117), .A2 (n_119), .Z (c_col_idx[6]));
  OAI211D0 p17705A__1881(.A1 (n_133), .A2 (n_132), .B (n_114), .C
       (n_86), .ZN (n_134));
  MAOI22D0 p18007A__5115(.A1 (num_computated[5]), .A2 (n_130), .B1
       (num_computated[5]), .B2 (n_130), .ZN (n_131));
  OAI211D0 p17928A__7482(.A1 (n_128), .A2 (num_computated[3]), .B
       (n_102), .C (n_104), .ZN (n_129));
  IOA21D0 p13197A__4733(.A1 (n_118), .A2 (n_38), .B (n_37), .ZN
       (n_140));
  MUX2ND0 p18008A__6161(.I0 (n_109), .I1 (num_computated[4]), .S
       (n_105), .ZN (n_127));
  AOI211D0 p17772A__9315(.A1 (n_81), .A2 (n_80), .B (n_100), .C (n_91),
       .ZN (n_126));
  AOI211D0 p17875A__9945(.A1 (n_124), .A2 (m[6]), .B (n_208), .C
       (n_211), .ZN (n_125));
  MOAI22D0 p18432A__2346(.A1 (n_120), .A2 (c_col_idx_temp[8]), .B1
       (n_120), .B2 (c_col_idx_temp[8]), .ZN (n_121));
  CKAN2D0 p13327A__1666(.A1 (n_118), .A2 (n_116), .Z (n_119));
  NR2D0 p13336A3684__7410(.A1 (n_118), .A2 (n_116), .ZN (n_117));
  XNR3D0 p17951A__6417(.A1 (n_113), .A2 (num_computation[6]), .A3
       (num_computated[6]), .ZN (n_115));
  OA221D0 p17613A__5477(.A1 (n_147), .A2 (m[1]), .B1 (n_67), .B2
       (n_68), .C (n_69), .Z (n_114));
  AOI21D0 p18185A__2398(.A1 (n_76), .A2 (num_computation[5]), .B
       (n_113), .ZN (n_130));
  OR2D8 p13383A__5107(.A1 (n_75), .A2 (n_88), .Z (c_col_idx[5]));
  AOI21D0 p18395A__6260(.A1 (n_110), .A2 (n_109), .B (n_108), .ZN
       (n_111));
  CKND2D0 p18368A__4319(.A1 (n_108), .A2 (num_computated[5]), .ZN
       (n_136));
  FA1D0 p18107A__8428(.A (c_col_os[4]), .B (k[1]), .CI (n_21), .CO
       (n_106), .S (n_107));
  AOI21D0 p18189A__5526(.A1 (n_61), .A2 (num_computation[4]), .B
       (n_70), .ZN (n_105));
  MAOI22D0 p17929A__6783(.A1 (num_computated[2]), .A2 (n_103), .B1
       (num_computated[2]), .B2 (n_103), .ZN (n_104));
  AOI221D0 p17815A3685__3680(.A1 (num_computated[0]), .A2
       (num_computation[0]), .B1 (num_computated[1]), .B2 (n_55), .C
       (n_56), .ZN (n_102));
  OAI21D0 p13185A__1617(.A1 (n_87), .A2 (n_33), .B (n_34), .ZN (n_118));
  OR2D8 p13399A__2802(.A1 (n_254), .A2 (n_52), .Z (c_col_idx[4]));
  OAI221D0 p17709A__1705(.A1 (n_65), .A2 (n_64), .B1
       (c_col_idx_temp[3]), .B2 (n_82), .C (n_66), .ZN (n_100));
  AOI221D0 p17736A__5122(.A1 (c_col_idx_temp[3]), .A2 (k[0]), .B1
       (n_53), .B2 (k[6]), .C (n_54), .ZN (n_99));
  MOAI22D0 p18469A__7098(.A1 (n_95), .A2 (c_col_idx_temp[7]), .B1
       (n_95), .B2 (c_col_idx_temp[7]), .ZN (n_96));
  MOAI22D0 p17777A__1881(.A1 (n_90), .A2 (n_89), .B1 (n_90), .B2
       (n_89), .ZN (n_91));
  NR2D0 p13375A__5115(.A1 (n_87), .A2 (n_41), .ZN (n_88));
  MAOI22D0 p17700A__7482(.A1 (n_85), .A2 (n_84), .B1 (n_85), .B2
       (n_84), .ZN (n_86));
  MAOI22D0 p17835A__4733(.A1 (n_82), .A2 (c_col_idx_temp[3]), .B1
       (n_81), .B2 (n_80), .ZN (n_83));
  MAOI22D0 p17830A__6161(.A1 (n_78), .A2 (n_77), .B1 (n_78), .B2
       (n_77), .ZN (n_79));
  NR2D0 p18118A__9315(.A1 (n_76), .A2 (num_computation[5]), .ZN
       (n_113));
  IND2D0 p18451A__9945(.A1 (n_97), .B1 (u_out_ac_i[7]), .ZN (n_122));
  IND2D0 p18415A__2883(.A1 (n_95), .B1 (c_col_idx_temp[7]), .ZN
       (n_120));
  NR2D0 p18339A__2346(.A1 (n_110), .A2 (n_109), .ZN (n_108));
  NR2D0 p13380A__1666(.A1 (n_57), .A2 (n_42), .ZN (n_75));
  NR2D0 p18724A__5477(.A1 (n_71), .A2 (n_2), .ZN (n_177));
  CKND0 Fp18114A(.I (n_76), .ZN (n_70));
  CKND2D0 p17629A__2398(.A1 (n_68), .A2 (n_67), .ZN (n_69));
  CKND2D0 p17726A__5107(.A1 (n_65), .A2 (n_64), .ZN (n_66));
  MOAI22D0 p18487A__6260(.A1 (n_62), .A2 (c_col_idx_temp[6]), .B1
       (n_62), .B2 (c_col_idx_temp[6]), .ZN (n_63));
  OA21D0 p18177A__4319(.A1 (n_50), .A2 (n_49), .B (n_61), .Z (n_128));
  AOI21D0 p18449A__8428(.A1 (n_59), .A2 (n_32), .B (n_58), .ZN (n_60));
  CKND0 Fp13166A(.I (n_57), .ZN (n_87));
  IND2D0 p18396A__5526(.A1 (n_73), .B1 (u_out_ac_i[6]), .ZN (n_97));
  IND2D0 p18365A__6783(.A1 (n_62), .B1 (c_col_idx_temp[6]), .ZN (n_95));
  CKND2D0 p18328A__3680(.A1 (n_58), .A2 (num_computated[3]), .ZN
       (n_110));
  NR2D0 p17833A__1617(.A1 (num_computated[1]), .A2 (n_55), .ZN (n_56));
  NR2D0 p17756A__2802(.A1 (n_53), .A2 (k[6]), .ZN (n_54));
  NR2D0 p13392A__1705(.A1 (n_47), .A2 (n_51), .ZN (n_52));
  AOI21D0 p18162A__5122(.A1 (n_23), .A2 (num_computation[2]), .B
       (n_50), .ZN (n_103));
  IND3D0 p18080A__8246(.A1 (num_computation[4]), .B1 (n_49), .B2
       (n_50), .ZN (n_76));
  MOAI22D0 p18524A3686__6131(.A1 (n_43), .A2 (c_col_idx_temp[5]), .B1
       (n_43), .B2 (c_col_idx_temp[5]), .ZN (n_44));
  CKND0 Fp13384A(.I (n_41), .ZN (n_42));
  CKND2D0 p18183A__1881(.A1 (n_50), .A2 (n_49), .ZN (n_61));
  CKND2D0 p13383A3688__5115(.A1 (n_40), .A2 (n_39), .ZN (n_138));
  INR2D0 p18288A__7482(.A1 (row_idx[2]), .B1 (n_19), .ZN (n_71));
  CKND2D0 p13388A__4733(.A1 (n_38), .A2 (n_37), .ZN (n_116));
  OAI21D0 p13168A__6161(.A1 (n_27), .A2 (n_51), .B (n_28), .ZN (n_57));
  AN2D8 p13473A__9315(.A1 (n_255), .A2 (n_51), .Z (c_col_idx[3]));
  AOI21D0 p17750A__9945(.A1 (n_17), .A2 (k[2]), .B (n_64), .ZN (n_90));
  AOI21D0 p17713A__2883(.A1 (n_15), .A2 (k[3]), .B (n_80), .ZN (n_65));
  AOI21D0 p17703A__2346(.A1 (n_14), .A2 (k[1]), .B (n_89), .ZN (n_82));
  AOI21D0 p17778A__1666(.A1 (n_16), .A2 (k[5]), .B (n_29), .ZN (n_78));
  AOI21D0 p17782A__7410(.A1 (n_18), .A2 (k[4]), .B (n_77), .ZN (n_81));
  AOI21D0 p17644A__6417(.A1 (n_5), .A2 (m[4]), .B (n_30), .ZN (n_85));
  AO21D0 p17756A3691__5477(.A1 (n_4), .A2 (m[2]), .B (n_67), .Z
       (n_132));
  AOI21D0 p17609A__2398(.A1 (n_6), .A2 (m[3]), .B (n_84), .ZN (n_68));
  AOI21D0 p17833A3689__5107(.A1 (n_0), .A2 (m[5]), .B (n_35), .ZN
       (n_93));
  CKND0 Fp17843A(.I (n_35), .ZN (n_124));
  INR2D0 p13356A__6260(.A1 (n_34), .B1 (n_33), .ZN (n_41));
  NR2D0 p18299A__4319(.A1 (n_59), .A2 (n_32), .ZN (n_58));
  IND2D0 p18332A3687__8428(.A1 (n_43), .B1 (c_col_idx_temp[5]), .ZN
       (n_62));
  IND2D0 p18362A__5526(.A1 (n_45), .B1 (u_out_ac_i[5]), .ZN (n_73));
  MUX2ND0 p18532A__6783(.I0 (n_24), .I1 (c_col_idx_temp[3]), .S
       (c_col_idx_temp[4]), .ZN (n_31));
  AOI21D0 p18070A__3680(.A1 (num_computation[1]), .A2
       (num_computation[0]), .B (n_22), .ZN (n_55));
  CKND0 Fp17729A(.I (n_29), .ZN (n_53));
  INR2D0 p13360A__1617(.A1 (n_28), .B1 (n_27), .ZN (n_47));
  OAI21D0 p17648A__2802(.A1 (c_row_idx[3]), .A2 (c_row_idx[4]), .B
       (n_45), .ZN (n_147));
  CKND0 Fp18082A(.I (n_22), .ZN (n_23));
  CKND0 Fp18131A(.I (n_20), .ZN (n_21));
  ND4D0 p18274A__8246(.A1 (row_idx[0]), .A2 (row_idx[1]), .A3
       (alu_init), .A4 (in_valid), .ZN (n_19));
  CKND2D0 p13343A__7098(.A1 (n_18), .A2 (n_7), .ZN (n_40));
  NR2D0 p17586A__6131(.A1 (n_6), .A2 (m[3]), .ZN (n_84));
  NR2D0 p17741A__1881(.A1 (n_17), .A2 (k[2]), .ZN (n_64));
  NR3D0 p18008A3690__5115(.A1 (num_computation[0]), .A2
       (num_computation[2]), .A3 (num_computation[1]), .ZN (n_50));
  MOAI22D0 p18431A__7482(.A1 (c_col_os[8]), .A2 (k[5]), .B1
       (c_col_os[8]), .B2 (k[5]), .ZN (n_187));
  MOAI22D0 p13377A__4733(.A1 (c_col_idx_temp[8]), .A2 (c_col_os[8]),
       .B1 (c_col_idx_temp[8]), .B2 (c_col_os[8]), .ZN (n_149));
  NR2D0 p17825A__6161(.A1 (n_0), .A2 (m[5]), .ZN (n_35));
  NR2D0 p17734A__9315(.A1 (n_16), .A2 (k[5]), .ZN (n_29));
  NR2D0 p17647A__9945(.A1 (n_5), .A2 (m[4]), .ZN (n_30));
  CKND2D0 p13274A__2883(.A1 (n_15), .A2 (n_1), .ZN (n_38));
  NR2D0 p17634A__2346(.A1 (n_4), .A2 (m[2]), .ZN (n_67));
  NR2D0 p17711A__1666(.A1 (n_14), .A2 (k[1]), .ZN (n_89));
  NR2D0 p17790A__7410(.A1 (n_18), .A2 (k[4]), .ZN (n_77));
  NR2D0 p17689A__6417(.A1 (n_15), .A2 (k[3]), .ZN (n_80));
  CKND2D0 p18107A3692__5477(.A1 (c_col_os[3]), .A2 (k[0]), .ZN (n_20));
  CKND2D0 p13177A__2398(.A1 (c_col_os[4]), .A2 (c_col_idx_temp[4]), .ZN
       (n_28));
  NR2D0 p13166A__5107(.A1 (c_col_os[4]), .A2 (c_col_idx_temp[4]), .ZN
       (n_27));
  NR2D0 p18081A__6260(.A1 (num_computation[1]), .A2
       (num_computation[0]), .ZN (n_22));
  CKND2D0 p18319A__4319(.A1 (c_col_idx_temp[4]), .A2
       (c_col_idx_temp[3]), .ZN (n_43));
  CKND2D0 p13132A__8428(.A1 (c_col_os[3]), .A2 (c_col_idx_temp[3]), .ZN
       (n_51));
  NR2D0 p13216A__5526(.A1 (c_col_idx_temp[5]), .A2 (c_col_os[5]), .ZN
       (n_33));
  IND2D0 p17794A__6783(.A1 (m[1]), .B1 (c_row_idx[4]), .ZN (n_133));
  CKND2D0 p13310A__3680(.A1 (c_col_os[6]), .A2 (c_col_idx_temp[6]), .ZN
       (n_37));
  CKND2D0 p13374A__1617(.A1 (c_col_os[7]), .A2 (c_col_idx_temp[7]), .ZN
       (n_39));
  CKND2D0 p13233A__2802(.A1 (c_col_os[5]), .A2 (c_col_idx_temp[5]), .ZN
       (n_34));
  CKND2D0 p18282A__1705(.A1 (num_computated[0]), .A2
       (num_computated[1]), .ZN (n_59));
  CKND2D0 p17641A__5122(.A1 (u_out_ac_i[4]), .A2 (u_out_ac_i[3]), .ZN
       (n_45));
  CKND0 Fp18292A(.I (num_computated[0]), .ZN (n_12));
  CKND0 Fp18018A(.I (num_computation[0]), .ZN (n_9));
  CKND0 Fp18786A(.I (rstn), .ZN (n_2));
  CKND0 Fp18100A(.I (num_computation[3]), .ZN (n_49));
  CKXOR2D0 g2(.A1 (n_122), .A2 (c_row_idx[8]), .Z (n_206));
  CKXOR2D0 g3724(.A1 (n_97), .A2 (u_out_ac_i[7]), .Z (n_207));
  XNR2D0 g3725(.A1 (n_93), .A2 (n_30), .ZN (n_208));
  CKXOR2D0 g3726(.A1 (n_73), .A2 (u_out_ac_i[6]), .Z (n_209));
  CKXOR2D0 g3727(.A1 (n_45), .A2 (u_out_ac_i[5]), .Z (n_210));
  XNR2D0 g3728(.A1 (c_row_idx[3]), .A2 (m[0]), .ZN (n_211));
  CKND8 drc_bufs3729(.I (n_4), .ZN (c_row_idx[5]));
  CKND8 drc_bufs3735(.I (n_6), .ZN (c_row_idx[6]));
  CKND8 drc_bufs3741(.I (n_5), .ZN (c_row_idx[7]));
  CKND8 drc_bufs3747(.I (n_232), .ZN (c_row_idx[3]));
  CKND8 drc_bufs3753(.I (n_238), .ZN (c_row_idx[4]));
  CKND8 drc_bufs3759(.I (n_0), .ZN (c_row_idx[8]));
  CKND8 drc_bufs3765(.I (n_250), .ZN (done_flag));
  EDFKCND1 \c_col_os_reg[7] (.CP (clk), .CN (rstn), .D (n_186), .E
       (n_190), .Q (c_col_os[7]), .QN (n_7));
  DFD1 \u_out_ac_j_reg[8] (.CP (clk), .D (n_179), .Q
       (c_col_idx_temp[8]), .QN (n_16));
  DFXD1 \u_out_ac_j_reg[3] (.CP (clk), .DA (n_177), .DB (n_178), .SA
       (c_col_idx_temp[3]), .Q (c_col_idx_temp[3]), .QN (n_24));
  EDFKCND1 \num_computated_reg[2] (.CP (clk), .CN (rstn), .D (n_60), .E
       (n_190), .Q (num_computated[2]), .QN (n_32));
  DFD1 \u_out_ac_j_reg[6] (.CP (clk), .D (n_172), .Q
       (c_col_idx_temp[6]), .QN (n_15));
  EDFKCND1 \c_col_os_reg[6] (.CP (clk), .CN (rstn), .D (n_157), .E
       (n_190), .Q (c_col_os[6]), .QN (n_1));
  DFD1 \u_out_ac_j_reg[5] (.CP (clk), .D (n_173), .Q
       (c_col_idx_temp[5]), .QN (n_17));
  DFD1 \u_out_ac_j_reg[4] (.CP (clk), .D (n_174), .Q
       (c_col_idx_temp[4]), .QN (n_14));
  DFD1 \u_out_ac_j_reg[7] (.CP (clk), .D (n_166), .Q
       (c_col_idx_temp[7]), .QN (n_18));
  EDFKCND1 \num_computated_reg[4] (.CP (clk), .CN (rstn), .D (n_111),
       .E (n_190), .Q (num_computated[4]), .QN (n_109));
  DFD1 \u_out_ac_i_reg[5] (.CP (clk), .D (n_171), .Q (u_out_ac_i[5]),
       .QN (n_4));
  DFD1 \u_out_ac_i_reg[6] (.CP (clk), .D (n_168), .Q (u_out_ac_i[6]),
       .QN (n_6));
  DFD1 \u_out_ac_i_reg[7] (.CP (clk), .D (n_167), .Q (u_out_ac_i[7]),
       .QN (n_5));
  DFXD1 \u_out_ac_i_reg[3] (.CP (clk), .DA (n_175), .DB (n_161), .SA
       (u_out_ac_i[3]), .Q (u_out_ac_i[3]), .QN (n_232));
  DFD1 \u_out_ac_i_reg[4] (.CP (clk), .D (n_169), .Q (u_out_ac_i[4]),
       .QN (n_238));
  DFD1 \u_out_ac_i_reg[8] (.CP (clk), .D (n_176), .Q (u_out_ac_i[8]),
       .QN (n_0));
  DFXD1 done_flag_reg(.CP (clk), .DA (rstn), .DB (done_flag_166), .SA
       (n_160), .Q (done_flag_166), .QN (n_250));
  CKAN2D0 g3804(.A1 (n_51), .A2 (n_47), .Z (n_254));
  IND2D0 g3805(.A1 (c_col_os[3]), .B1 (n_24), .ZN (n_255));
endmodule

