
// Generated by Cadence Genus(TM) Synthesis Solution 21.16-s062_1
// Generated on: Apr  2 2026 20:22:56 EDT (Apr  3 2026 00:22:56 UTC)

// Verification Directory fv/bus_slave_c 

module bus_slave_c(BUS_CLK, BUS_RST_N, CHC_START, CHC_RD, CHC_RDATA,
     sram_c_re, sram_c_addr, sram_c_dout, debug_cnt_c);
  input BUS_CLK, BUS_RST_N, CHC_START, CHC_RD;
  input [7:0] sram_c_dout;
  output [7:0] CHC_RDATA;
  output sram_c_re;
  output [11:0] sram_c_addr, debug_cnt_c;
  wire BUS_CLK, BUS_RST_N, CHC_START, CHC_RD;
  wire [7:0] sram_c_dout;
  wire [7:0] CHC_RDATA;
  wire sram_c_re;
  wire [11:0] sram_c_addr, debug_cnt_c;
  wire [11:0] cnt_c;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire n_0, n_3, n_6, n_18, n_20, n_35, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_57;
  wire n_58, n_60, n_61, n_62, n_63, n_64, n_65, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_92, n_106, n_107, n_108;
  wire n_109, n_110, n_111;
  assign debug_cnt_c[0] = sram_c_addr[0];
  assign debug_cnt_c[1] = sram_c_addr[1];
  assign debug_cnt_c[2] = sram_c_addr[2];
  assign debug_cnt_c[3] = sram_c_addr[3];
  assign debug_cnt_c[4] = sram_c_addr[4];
  assign debug_cnt_c[5] = sram_c_addr[5];
  assign debug_cnt_c[6] = sram_c_addr[6];
  assign debug_cnt_c[7] = sram_c_addr[7];
  assign debug_cnt_c[8] = sram_c_addr[8];
  assign debug_cnt_c[9] = sram_c_addr[9];
  assign debug_cnt_c[10] = sram_c_addr[10];
  assign debug_cnt_c[11] = sram_c_addr[11];
  assign CHC_RDATA[0] = sram_c_dout[0];
  assign CHC_RDATA[1] = sram_c_dout[1];
  assign CHC_RDATA[2] = sram_c_dout[2];
  assign CHC_RDATA[3] = sram_c_dout[3];
  assign CHC_RDATA[4] = sram_c_dout[4];
  assign CHC_RDATA[5] = sram_c_dout[5];
  assign CHC_RDATA[6] = sram_c_dout[6];
  assign CHC_RDATA[7] = sram_c_dout[7];
  DFNCND1 \cnt_c_reg[11] (.CDN (BUS_RST_N), .CPN (BUS_CLK), .D (n_92),
       .Q (cnt_c[11]), .QN (UNCONNECTED));
  NR2D0 p95792A__2398(.A1 (n_106), .A2 (CHC_START), .ZN (n_92));
  DFNCND1 \cnt_c_reg[10] (.CDN (BUS_RST_N), .CPN (BUS_CLK), .D (n_89),
       .Q (cnt_c[10]), .QN (n_18));
  NR2D0 p95821A__6260(.A1 (n_87), .A2 (CHC_START), .ZN (n_89));
  DFNCND1 \cnt_c_reg[9] (.CDN (BUS_RST_N), .CPN (BUS_CLK), .D (n_88),
       .Q (cnt_c[9]), .QN (UNCONNECTED0));
  DFNCND1 \cnt_c_reg[8] (.CDN (BUS_RST_N), .CPN (BUS_CLK), .D (n_84),
       .Q (cnt_c[8]), .QN (n_20));
  AOI21D0 p95850A__4319(.A1 (n_82), .A2 (n_55), .B (CHC_START), .ZN
       (n_88));
  AOI32D0 p95810A__8428(.A1 (n_85), .A2 (n_79), .A3 (sram_c_re), .B1
       (cnt_c[10]), .B2 (n_35), .ZN (n_87));
  MOAI22D0 p95771A__5526(.A1 (n_85), .A2 (cnt_c[11]), .B1 (n_85), .B2
       (cnt_c[11]), .ZN (n_86));
  NR2D0 p95879A__6783(.A1 (n_107), .A2 (CHC_START), .ZN (n_84));
  DFNCND1 \cnt_c_reg[7] (.CDN (BUS_RST_N), .CPN (BUS_CLK), .D (n_80),
       .Q (cnt_c[7]), .QN (UNCONNECTED1));
  OAI211D0 p95856A306__1617(.A1 (cnt_c[9]), .A2 (n_76), .B (n_81), .C
       (sram_c_re), .ZN (n_82));
  DFNCND1 \cnt_c_reg[6] (.CDN (BUS_RST_N), .CPN (BUS_CLK), .D (n_78),
       .Q (cnt_c[6]), .QN (n_3));
  OR2D0 p95752A__2802(.A1 (n_81), .A2 (n_18), .Z (n_85));
  AOI21D0 p95906A__1705(.A1 (n_75), .A2 (n_54), .B (CHC_START), .ZN
       (n_80));
  CKND2D0 p95856A__5122(.A1 (n_81), .A2 (n_18), .ZN (n_79));
  NR2D0 p95934A__8246(.A1 (n_108), .A2 (CHC_START), .ZN (n_78));
  DFNCND1 \cnt_c_reg[5] (.CDN (BUS_RST_N), .CPN (BUS_CLK), .D (n_72),
       .Q (cnt_c[5]), .QN (UNCONNECTED2));
  AOI21D0 p95858A__7098(.A1 (n_74), .A2 (n_20), .B (n_76), .ZN (n_77));
  CKND2D0 p95742A__6131(.A1 (n_76), .A2 (cnt_c[9]), .ZN (n_81));
  DFNCND1 \cnt_c_reg[4] (.CDN (BUS_RST_N), .CPN (BUS_CLK), .D (n_71),
       .Q (cnt_c[4]), .QN (n_0));
  OAI211D0 p95912A__1881(.A1 (cnt_c[7]), .A2 (n_70), .B (n_74), .C
       (sram_c_re), .ZN (n_75));
  AOI21D0 p95962A__7482(.A1 (n_68), .A2 (n_47), .B (CHC_START), .ZN
       (n_72));
  NR2D0 p95716A__4733(.A1 (n_74), .A2 (n_20), .ZN (n_76));
  NR2D0 p95991A__6161(.A1 (n_109), .A2 (CHC_START), .ZN (n_71));
  CKND2D0 p95705A__9315(.A1 (n_70), .A2 (cnt_c[7]), .ZN (n_74));
  AOI21D0 p95914A__9945(.A1 (n_67), .A2 (n_3), .B (n_70), .ZN (n_69));
  DFNCND1 \cnt_c_reg[3] (.CDN (BUS_RST_N), .CPN (BUS_CLK), .D (n_65),
       .Q (cnt_c[3]), .QN (UNCONNECTED3));
  OAI211D0 p95969A__2883(.A1 (cnt_c[5]), .A2 (n_63), .B (n_67), .C
       (sram_c_re), .ZN (n_68));
  DFNCND1 \cnt_c_reg[2] (.CDN (BUS_RST_N), .CPN (BUS_CLK), .D (n_64),
       .Q (cnt_c[2]), .QN (n_6));
  NR2D0 p95679A__1666(.A1 (n_67), .A2 (n_3), .ZN (n_70));
  AOI21D0 p96017A__7410(.A1 (n_61), .A2 (n_52), .B (CHC_START), .ZN
       (n_65));
  DFNCND1 \cnt_c_reg[0] (.CDN (BUS_RST_N), .CPN (BUS_CLK), .D (n_57),
       .Q (cnt_c[0]), .QN (UNCONNECTED4));
  NR2D0 p96050A__6417(.A1 (n_110), .A2 (CHC_START), .ZN (n_64));
  DFNCND1 \cnt_c_reg[1] (.CDN (BUS_RST_N), .CPN (BUS_CLK), .D (n_58),
       .Q (cnt_c[1]), .QN (UNCONNECTED5));
  CKND2D0 p95668A__5477(.A1 (n_63), .A2 (cnt_c[5]), .ZN (n_67));
  AOI21D0 p95971A__2398(.A1 (n_60), .A2 (n_0), .B (n_63), .ZN (n_62));
  OAI211D0 p96026A__5107(.A1 (cnt_c[3]), .A2 (n_48), .B (n_60), .C
       (sram_c_re), .ZN (n_61));
  AOI21D0 p96073A__4319(.A1 (n_51), .A2 (n_53), .B (CHC_START), .ZN
       (n_58));
  NR2D0 p96118A__8428(.A1 (n_111), .A2 (CHC_START), .ZN (n_57));
  NR2D0 p95642A__5526(.A1 (n_60), .A2 (n_0), .ZN (n_63));
  CKND2D0 p96142A317__3680(.A1 (cnt_c[9]), .A2 (n_35), .ZN (n_55));
  CKND2D0 p96142A316__1617(.A1 (cnt_c[7]), .A2 (n_35), .ZN (n_54));
  CKND2D0 p96142A315__2802(.A1 (cnt_c[1]), .A2 (n_35), .ZN (n_53));
  CKND2D0 p96142A318__1705(.A1 (cnt_c[3]), .A2 (n_35), .ZN (n_52));
  OAI211D0 p96082A__5122(.A1 (cnt_c[1]), .A2 (cnt_c[0]), .B (n_49), .C
       (sram_c_re), .ZN (n_51));
  AOI21D0 p96028A__8246(.A1 (n_49), .A2 (n_6), .B (n_48), .ZN (n_50));
  CKND2D0 p96142A__7098(.A1 (cnt_c[5]), .A2 (n_35), .ZN (n_47));
  CKND2D0 p95632A__6131(.A1 (n_48), .A2 (cnt_c[3]), .ZN (n_60));
  NR2D0 p95604A__1881(.A1 (n_49), .A2 (n_6), .ZN (n_48));
  CKND8 p23609A(.I (n_35), .ZN (sram_c_re));
  CKND2D0 p95591A__5115(.A1 (cnt_c[0]), .A2 (cnt_c[1]), .ZN (n_49));
  DFNCND1 chc_rd_s_reg(.CDN (BUS_RST_N), .CPN (BUS_CLK), .D (CHC_RD),
       .Q (UNCONNECTED6), .QN (n_35));
  BUFFD16 Fp45940A353(.I (cnt_c[0]), .Z (sram_c_addr[0]));
  BUFFD16 Fp46319A349(.I (cnt_c[9]), .Z (sram_c_addr[9]));
  BUFFD16 Fp45967A(.I (cnt_c[2]), .Z (sram_c_addr[2]));
  BUFFD16 Fp46247A336(.I (cnt_c[8]), .Z (sram_c_addr[8]));
  BUFFD16 Fp46438A(.I (cnt_c[11]), .Z (sram_c_addr[11]));
  BUFFD16 Fp46154A(.I (cnt_c[6]), .Z (sram_c_addr[6]));
  BUFFD16 Fp45947A(.I (cnt_c[1]), .Z (sram_c_addr[1]));
  BUFFD16 Fp46133A339(.I (cnt_c[5]), .Z (sram_c_addr[5]));
  BUFFD16 Fp46337A(.I (cnt_c[10]), .Z (sram_c_addr[10]));
  BUFFD16 Fp46040A346(.I (cnt_c[3]), .Z (sram_c_addr[3]));
  BUFFD16 Fp46060A333(.I (cnt_c[4]), .Z (sram_c_addr[4]));
  BUFFD16 Fp46226A(.I (cnt_c[7]), .Z (sram_c_addr[7]));
  MUX2ND0 g2(.I0 (cnt_c[11]), .I1 (n_86), .S (sram_c_re), .ZN (n_106));
  MUX2ND0 g367(.I0 (cnt_c[8]), .I1 (n_77), .S (sram_c_re), .ZN (n_107));
  MUX2ND0 g368(.I0 (cnt_c[6]), .I1 (n_69), .S (sram_c_re), .ZN (n_108));
  MUX2ND0 g369(.I0 (cnt_c[4]), .I1 (n_62), .S (sram_c_re), .ZN (n_109));
  MUX2ND0 g370(.I0 (cnt_c[2]), .I1 (n_50), .S (sram_c_re), .ZN (n_110));
  XNR2D0 g371(.A1 (cnt_c[0]), .A2 (sram_c_re), .ZN (n_111));
endmodule

