/*
###############################################################
#  Generated by:      Cadence Innovus 21.16-s078_1
#  OS:                Linux x86_64(Host ID cadpc15)
#  Generated on:      Thu Apr  2 21:19:50 2026
#  Design:            bus_slave_c
#  Command:           write_netlist ../output/bus_slave_c.functpg.v -include_pg_ports
###############################################################
*/
module CKBD0 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module BUFFD1 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module DEL2 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module DEL1 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module DEL0 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module CKND6 (
	I, 
	ZN, 
	VSS, 
	VDD);
   input I;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module CKND1 (
	I, 
	ZN, 
	VSS, 
	VDD);
   input I;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module BUFFD12 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module CKBD12 (
	I, 
	Z, 
	VSS, 
	VDD);
   input I;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module INVD12 (
	I, 
	ZN, 
	VSS, 
	VDD);
   input I;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module INVD1 (
	I, 
	ZN, 
	VSS, 
	VDD);
   input I;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module DFNCND1 (
	CDN, 
	CPN, 
	D, 
	Q, 
	QN, 
	VSS, 
	VDD);
   input CDN;
   input CPN;
   input D;
   output Q;
   output QN;
   inout VSS;
   inout VDD;
endmodule

module NR2D0 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module AOI21D0 (
	A1, 
	A2, 
	B, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input B;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module AOI32D0 (
	A1, 
	A2, 
	A3, 
	B1, 
	B2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input A3;
   input B1;
   input B2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module MOAI22D0 (
	A1, 
	A2, 
	B1, 
	B2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input B1;
   input B2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module OAI211D0 (
	A1, 
	A2, 
	B, 
	C, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   input B;
   input C;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module OR2D0 (
	A1, 
	A2, 
	Z, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output Z;
   inout VSS;
   inout VDD;
endmodule

module CKND2D0 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module NR2XD0 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module NR2D1 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module MUX2ND0 (
	I0, 
	I1, 
	S, 
	ZN, 
	VSS, 
	VDD);
   input I0;
   input I1;
   input S;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

module XNR2D0 (
	A1, 
	A2, 
	ZN, 
	VSS, 
	VDD);
   input A1;
   input A2;
   output ZN;
   inout VSS;
   inout VDD;
endmodule

// Generated by Cadence Genus(TM) Synthesis Solution 21.16-s062_1
// Generated on: Apr  2 2026 20:22:56 EDT (Apr  3 2026 00:22:56 UTC)
// Verification Directory fv/bus_slave_c 
module bus_slave_c (
	BUS_CLK, 
	BUS_RST_N, 
	CHC_START, 
	CHC_RD, 
	CHC_RDATA, 
	sram_c_re, 
	sram_c_addr, 
	sram_c_dout, 
	debug_cnt_c, 
	DVDD, 
	DVSS);
   input BUS_CLK;
   input BUS_RST_N;
   input CHC_START;
   input CHC_RD;
   output [7:0] CHC_RDATA;
   output sram_c_re;
   output [11:0] sram_c_addr;
   input [7:0] sram_c_dout;
   output [11:0] debug_cnt_c;
   inout DVDD;
   inout DVSS;

   // Internal wires
   wire FE_PDN36_n_58;
   wire FE_PDN35_n_65;
   wire FE_PHN80_BUS_RST_N;
   wire FE_PHN79_FE_OFN12_debug_cnt_c_7;
   wire FE_PHN78_n_78;
   wire FE_PHN77_n_84;
   wire FE_PHN76_n_89;
   wire FE_PHN75_n_72;
   wire FE_PHN74_n_65;
   wire FE_PHN73_n_92;
   wire FE_PHN72_n_58;
   wire FE_PHN71_n_64;
   wire FE_PHN70_n_71;
   wire FE_PHN69_n_78;
   wire FE_PHN68_BUS_RST_N;
   wire FE_PHN67_FE_OFN32_debug_cnt_c_0;
   wire FE_PHN66_CHC_START;
   wire FE_PHN65_n_35;
   wire FE_PHN64_FE_OFN6_debug_cnt_c_9;
   wire FE_PHN63_CHC_RD;
   wire FE_PHN62_FE_OFN12_debug_cnt_c_7;
   wire FE_PHN61_n_20;
   wire FE_PHN60_BUS_RST_N;
   wire FE_PHN59_BUS_RST_N;
   wire FE_PHN58_BUS_RST_N;
   wire FE_PHN57_BUS_RST_N;
   wire FE_PHN56_BUS_RST_N;
   wire FE_PHN55_BUS_RST_N;
   wire FE_PHN54_n_92;
   wire FE_PHN53_n_89;
   wire FE_PHN52_n_88;
   wire FE_PHN51_n_80;
   wire FE_PHN50_n_84;
   wire FE_PHN49_n_78;
   wire FE_PHN48_n_72;
   wire FE_PHN47_n_70;
   wire FE_PHN46_n_71;
   wire FE_PHN45_n_67;
   wire FE_PHN44_n_64;
   wire FE_PHN43_BUS_RST_N;
   wire FE_PHN42_CHC_RD;
   wire FE_PHN41_FE_OFN24_debug_cnt_c_3;
   wire FE_PHN40_FE_OFN32_debug_cnt_c_0;
   wire FE_PHN39_FE_OFN30_debug_cnt_c_1;
   wire FE_PHN38_n_35;
   wire FE_PHN37_n_0;
   wire FE_PHN36_n_6;
   wire FE_PHN35_CHC_START;
   wire CTS_2;
   wire CTS_1;
   wire FE_RN_8;
   wire FE_RN_7;
   wire FE_OFN32_debug_cnt_c_0;
   wire FE_OFN30_debug_cnt_c_1;
   wire FE_RN_6;
   wire FE_OFN28_debug_cnt_c_2;
   wire FE_OFN27_debug_cnt_c_2;
   wire FE_OFN25_debug_cnt_c_3;
   wire FE_OFN24_debug_cnt_c_3;
   wire FE_RN_5;
   wire FE_OFN22_debug_cnt_c_4;
   wire FE_OFN21_debug_cnt_c_4;
   wire FE_RN_4;
   wire FE_OFN19_debug_cnt_c_5;
   wire FE_OFN18_debug_cnt_c_5;
   wire FE_OFN16_debug_cnt_c_6;
   wire FE_OFN15_debug_cnt_c_6;
   wire FE_OFN13_debug_cnt_c_7;
   wire FE_OFN12_debug_cnt_c_7;
   wire FE_RN_3;
   wire FE_OFN10_debug_cnt_c_8;
   wire FE_OFN9_debug_cnt_c_8;
   wire FE_RN_2;
   wire FE_OFN7_debug_cnt_c_9;
   wire FE_OFN6_debug_cnt_c_9;
   wire FE_OFN4_debug_cnt_c_10;
   wire FE_OFN3_debug_cnt_c_10;
   wire FE_RN_1;
   wire FE_OFN1_debug_cnt_c_11;
   wire [11:0] cnt_c;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire n_0;
   wire n_3;
   wire n_6;
   wire n_18;
   wire n_20;
   wire n_35;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_57;
   wire n_58;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_92;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;

   assign FE_RN_7 = sram_c_addr[0] ;
   assign debug_cnt_c[1] = FE_RN_8 ;
   assign debug_cnt_c[2] = FE_RN_6 ;
   assign debug_cnt_c[4] = FE_RN_5 ;
   assign debug_cnt_c[5] = FE_RN_4 ;
   assign debug_cnt_c[8] = FE_RN_3 ;
   assign debug_cnt_c[9] = FE_RN_2 ;
   assign debug_cnt_c[11] = FE_RN_1 ;
   assign CHC_RDATA[0] = sram_c_dout[0] ;
   assign CHC_RDATA[1] = sram_c_dout[1] ;
   assign CHC_RDATA[2] = sram_c_dout[2] ;
   assign CHC_RDATA[3] = sram_c_dout[3] ;
   assign CHC_RDATA[4] = sram_c_dout[4] ;
   assign CHC_RDATA[5] = sram_c_dout[5] ;
   assign CHC_RDATA[6] = sram_c_dout[6] ;
   assign CHC_RDATA[7] = sram_c_dout[7] ;

   // Module instantiations
   CKBD0 FE_PDC36_n_58 (
	.I(n_58),
	.Z(FE_PDN36_n_58), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD0 FE_PDC35_n_65 (
	.I(n_65),
	.Z(FE_PDN35_n_65), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD1 FE_PHC80_BUS_RST_N (
	.I(BUS_RST_N),
	.Z(FE_PHN80_BUS_RST_N), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD1 FE_PHC79_FE_OFN12_debug_cnt_c_7 (
	.I(FE_OFN12_debug_cnt_c_7),
	.Z(FE_PHN79_FE_OFN12_debug_cnt_c_7), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD1 FE_PHC78_n_78 (
	.I(n_78),
	.Z(FE_PHN78_n_78), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL2 FE_PHC77_n_84 (
	.I(n_84),
	.Z(FE_PHN77_n_84), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL2 FE_PHC76_n_89 (
	.I(n_89),
	.Z(FE_PHN76_n_89), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC75_n_72 (
	.I(FE_PHN75_n_72),
	.Z(FE_PHN48_n_72), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC74_n_65 (
	.I(FE_PDN35_n_65),
	.Z(FE_PHN74_n_65), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC73_n_92 (
	.I(n_92),
	.Z(FE_PHN73_n_92), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC72_n_58 (
	.I(FE_PDN36_n_58),
	.Z(FE_PHN72_n_58), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC71_n_64 (
	.I(n_64),
	.Z(FE_PHN71_n_64), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC70_n_71 (
	.I(n_71),
	.Z(FE_PHN70_n_71), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC69_n_78 (
	.I(FE_PHN78_n_78),
	.Z(FE_PHN69_n_78), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL0 FE_PHC68_BUS_RST_N (
	.I(FE_PHN80_BUS_RST_N),
	.Z(FE_PHN68_BUS_RST_N), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC67_FE_OFN32_debug_cnt_c_0 (
	.I(FE_OFN32_debug_cnt_c_0),
	.Z(FE_PHN67_FE_OFN32_debug_cnt_c_0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC66_CHC_START (
	.I(CHC_START),
	.Z(FE_PHN66_CHC_START), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC65_n_35 (
	.I(n_35),
	.Z(FE_PHN65_n_35), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL2 FE_PHC64_FE_OFN6_debug_cnt_c_9 (
	.I(FE_PHN64_FE_OFN6_debug_cnt_c_9),
	.Z(FE_OFN6_debug_cnt_c_9), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC63_CHC_RD (
	.I(CHC_RD),
	.Z(FE_PHN63_CHC_RD), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC62_FE_OFN12_debug_cnt_c_7 (
	.I(FE_PHN79_FE_OFN12_debug_cnt_c_7),
	.Z(FE_PHN62_FE_OFN12_debug_cnt_c_7), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC61_n_20 (
	.I(FE_PHN61_n_20),
	.Z(n_20), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC60_BUS_RST_N (
	.I(FE_PHN68_BUS_RST_N),
	.Z(FE_PHN60_BUS_RST_N), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC59_BUS_RST_N (
	.I(FE_PHN68_BUS_RST_N),
	.Z(FE_PHN59_BUS_RST_N), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC58_BUS_RST_N (
	.I(FE_PHN68_BUS_RST_N),
	.Z(FE_PHN58_BUS_RST_N), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC57_BUS_RST_N (
	.I(FE_PHN68_BUS_RST_N),
	.Z(FE_PHN57_BUS_RST_N), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC56_BUS_RST_N (
	.I(FE_PHN68_BUS_RST_N),
	.Z(FE_PHN56_BUS_RST_N), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC55_BUS_RST_N (
	.I(FE_PHN68_BUS_RST_N),
	.Z(FE_PHN55_BUS_RST_N), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC54_n_92 (
	.I(FE_PHN73_n_92),
	.Z(FE_PHN54_n_92), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC53_n_89 (
	.I(FE_PHN76_n_89),
	.Z(FE_PHN53_n_89), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC52_n_88 (
	.I(n_88),
	.Z(FE_PHN52_n_88), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC51_n_80 (
	.I(n_80),
	.Z(FE_PHN51_n_80), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC50_n_84 (
	.I(FE_PHN77_n_84),
	.Z(FE_PHN50_n_84), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC49_n_78 (
	.I(FE_PHN69_n_78),
	.Z(FE_PHN49_n_78), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC48_n_72 (
	.I(n_72),
	.Z(FE_PHN75_n_72), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC47_n_70 (
	.I(n_70),
	.Z(FE_PHN47_n_70), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC46_n_71 (
	.I(FE_PHN70_n_71),
	.Z(FE_PHN46_n_71), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC45_n_67 (
	.I(n_67),
	.Z(FE_PHN45_n_67), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC44_n_64 (
	.I(FE_PHN71_n_64),
	.Z(FE_PHN44_n_64), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC43_BUS_RST_N (
	.I(FE_PHN68_BUS_RST_N),
	.Z(FE_PHN43_BUS_RST_N), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC42_CHC_RD (
	.I(FE_PHN63_CHC_RD),
	.Z(FE_PHN42_CHC_RD), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC41_FE_OFN24_debug_cnt_c_3 (
	.I(FE_OFN24_debug_cnt_c_3),
	.Z(FE_PHN41_FE_OFN24_debug_cnt_c_3), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC40_FE_OFN32_debug_cnt_c_0 (
	.I(FE_PHN67_FE_OFN32_debug_cnt_c_0),
	.Z(FE_PHN40_FE_OFN32_debug_cnt_c_0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC39_FE_OFN30_debug_cnt_c_1 (
	.I(FE_OFN30_debug_cnt_c_1),
	.Z(FE_PHN39_FE_OFN30_debug_cnt_c_1), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC38_n_35 (
	.I(FE_PHN65_n_35),
	.Z(FE_PHN38_n_35), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC37_n_0 (
	.I(n_0),
	.Z(FE_PHN37_n_0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC36_n_6 (
	.I(n_6),
	.Z(FE_PHN36_n_6), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DEL1 FE_PHC35_CHC_START (
	.I(FE_PHN66_CHC_START),
	.Z(FE_PHN35_CHC_START), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKND6 CTS_ccl_a_inv_00001 (
	.I(CTS_2),
	.ZN(CTS_1), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKND1 CTS_cmf_inv_00047 (
	.I(BUS_CLK),
	.ZN(CTS_2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD12 FE_OFC34_debug_cnt_c_1 (
	.I(debug_cnt_c[1]),
	.Z(sram_c_addr[1]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD12 FE_OFC33_debug_cnt_c_0 (
	.I(FE_RN_7),
	.Z(debug_cnt_c[0]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD12 FE_OFC32_debug_cnt_c_0 (
	.I(FE_PHN40_FE_OFN32_debug_cnt_c_0),
	.Z(sram_c_addr[0]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKBD12 FE_OFC30_debug_cnt_c_1 (
	.I(FE_PHN39_FE_OFN30_debug_cnt_c_1),
	.Z(FE_RN_8), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC29_debug_cnt_c_2 (
	.I(FE_OFN28_debug_cnt_c_2),
	.ZN(sram_c_addr[2]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC28_debug_cnt_c_2 (
	.I(FE_OFN28_debug_cnt_c_2),
	.ZN(FE_RN_6), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD1 FE_OFC27_debug_cnt_c_2 (
	.I(FE_OFN27_debug_cnt_c_2),
	.ZN(FE_OFN28_debug_cnt_c_2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC26_debug_cnt_c_3 (
	.I(FE_OFN25_debug_cnt_c_3),
	.ZN(debug_cnt_c[3]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC25_debug_cnt_c_3 (
	.I(FE_OFN25_debug_cnt_c_3),
	.ZN(sram_c_addr[3]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD1 FE_OFC24_debug_cnt_c_3 (
	.I(FE_PHN41_FE_OFN24_debug_cnt_c_3),
	.ZN(FE_OFN25_debug_cnt_c_3), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC23_debug_cnt_c_4 (
	.I(FE_OFN22_debug_cnt_c_4),
	.ZN(sram_c_addr[4]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC22_debug_cnt_c_4 (
	.I(FE_OFN22_debug_cnt_c_4),
	.ZN(FE_RN_5), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD1 FE_OFC21_debug_cnt_c_4 (
	.I(FE_OFN21_debug_cnt_c_4),
	.ZN(FE_OFN22_debug_cnt_c_4), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC20_debug_cnt_c_5 (
	.I(FE_OFN19_debug_cnt_c_5),
	.ZN(sram_c_addr[5]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC19_debug_cnt_c_5 (
	.I(FE_OFN19_debug_cnt_c_5),
	.ZN(FE_RN_4), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD1 FE_OFC18_debug_cnt_c_5 (
	.I(FE_OFN18_debug_cnt_c_5),
	.ZN(FE_OFN19_debug_cnt_c_5), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC17_debug_cnt_c_6 (
	.I(FE_OFN16_debug_cnt_c_6),
	.ZN(debug_cnt_c[6]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC16_debug_cnt_c_6 (
	.I(FE_OFN16_debug_cnt_c_6),
	.ZN(sram_c_addr[6]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD1 FE_OFC15_debug_cnt_c_6 (
	.I(FE_OFN15_debug_cnt_c_6),
	.ZN(FE_OFN16_debug_cnt_c_6), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC14_debug_cnt_c_7 (
	.I(FE_OFN13_debug_cnt_c_7),
	.ZN(debug_cnt_c[7]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC13_debug_cnt_c_7 (
	.I(FE_OFN13_debug_cnt_c_7),
	.ZN(sram_c_addr[7]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD1 FE_OFC12_debug_cnt_c_7 (
	.I(FE_PHN62_FE_OFN12_debug_cnt_c_7),
	.ZN(FE_OFN13_debug_cnt_c_7), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC11_debug_cnt_c_8 (
	.I(FE_OFN10_debug_cnt_c_8),
	.ZN(sram_c_addr[8]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC10_debug_cnt_c_8 (
	.I(FE_OFN10_debug_cnt_c_8),
	.ZN(FE_RN_3), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD1 FE_OFC9_debug_cnt_c_8 (
	.I(FE_OFN9_debug_cnt_c_8),
	.ZN(FE_OFN10_debug_cnt_c_8), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC8_debug_cnt_c_9 (
	.I(FE_OFN7_debug_cnt_c_9),
	.ZN(sram_c_addr[9]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC7_debug_cnt_c_9 (
	.I(FE_OFN7_debug_cnt_c_9),
	.ZN(FE_RN_2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD1 FE_OFC6_debug_cnt_c_9 (
	.I(FE_OFN6_debug_cnt_c_9),
	.ZN(FE_OFN7_debug_cnt_c_9), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC5_debug_cnt_c_10 (
	.I(FE_OFN4_debug_cnt_c_10),
	.ZN(debug_cnt_c[10]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 FE_OFC4_debug_cnt_c_10 (
	.I(FE_OFN4_debug_cnt_c_10),
	.ZN(sram_c_addr[10]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD1 FE_OFC3_debug_cnt_c_10 (
	.I(FE_OFN3_debug_cnt_c_10),
	.ZN(FE_OFN4_debug_cnt_c_10), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD12 FE_OFC2_debug_cnt_c_11 (
	.I(debug_cnt_c[11]),
	.Z(sram_c_addr[11]), 
	.VSS(DVSS), 
	.VDD(DVDD));
   BUFFD12 FE_OFC1_debug_cnt_c_11 (
	.I(FE_OFN1_debug_cnt_c_11),
	.Z(FE_RN_1), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DFNCND1 \cnt_c_reg[11]  (
	.CDN(FE_PHN57_BUS_RST_N),
	.CPN(CTS_1),
	.D(FE_PHN54_n_92),
	.Q(FE_OFN1_debug_cnt_c_11),
	.QN(UNCONNECTED), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2D0 p95792A__2398 (
	.A1(n_106),
	.A2(FE_PHN35_CHC_START),
	.ZN(n_92), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DFNCND1 \cnt_c_reg[10]  (
	.CDN(FE_PHN59_BUS_RST_N),
	.CPN(CTS_1),
	.D(FE_PHN53_n_89),
	.Q(FE_OFN3_debug_cnt_c_10),
	.QN(n_18), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2D0 p95821A__6260 (
	.A1(n_87),
	.A2(FE_PHN35_CHC_START),
	.ZN(n_89), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DFNCND1 \cnt_c_reg[9]  (
	.CDN(FE_PHN60_BUS_RST_N),
	.CPN(CTS_1),
	.D(FE_PHN52_n_88),
	.Q(FE_PHN64_FE_OFN6_debug_cnt_c_9),
	.QN(UNCONNECTED0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DFNCND1 \cnt_c_reg[8]  (
	.CDN(FE_PHN58_BUS_RST_N),
	.CPN(CTS_1),
	.D(FE_PHN50_n_84),
	.Q(FE_OFN9_debug_cnt_c_8),
	.QN(FE_PHN61_n_20), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI21D0 p95850A__4319 (
	.A1(n_82),
	.A2(n_55),
	.B(FE_PHN35_CHC_START),
	.ZN(n_88), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI32D0 p95810A__8428 (
	.A1(n_85),
	.A2(n_79),
	.A3(sram_c_re),
	.B1(FE_OFN3_debug_cnt_c_10),
	.B2(FE_PHN38_n_35),
	.ZN(n_87), 
	.VSS(DVSS), 
	.VDD(DVDD));
   MOAI22D0 p95771A__5526 (
	.A1(n_85),
	.A2(FE_RN_1),
	.B1(n_85),
	.B2(FE_RN_1),
	.ZN(n_86), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2D0 p95879A__6783 (
	.A1(n_107),
	.A2(FE_PHN35_CHC_START),
	.ZN(n_84), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DFNCND1 \cnt_c_reg[7]  (
	.CDN(FE_PHN55_BUS_RST_N),
	.CPN(CTS_1),
	.D(FE_PHN51_n_80),
	.Q(FE_OFN12_debug_cnt_c_7),
	.QN(UNCONNECTED1), 
	.VSS(DVSS), 
	.VDD(DVDD));
   OAI211D0 p95856A306__1617 (
	.A1(FE_OFN6_debug_cnt_c_9),
	.A2(n_76),
	.B(n_81),
	.C(sram_c_re),
	.ZN(n_82), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DFNCND1 \cnt_c_reg[6]  (
	.CDN(FE_PHN56_BUS_RST_N),
	.CPN(CTS_1),
	.D(FE_PHN49_n_78),
	.Q(FE_OFN15_debug_cnt_c_6),
	.QN(n_3), 
	.VSS(DVSS), 
	.VDD(DVDD));
   OR2D0 p95752A__2802 (
	.A1(n_81),
	.A2(n_18),
	.Z(n_85), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI21D0 p95906A__1705 (
	.A1(n_75),
	.A2(n_54),
	.B(FE_PHN35_CHC_START),
	.ZN(n_80), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKND2D0 p95856A__5122 (
	.A1(n_81),
	.A2(n_18),
	.ZN(n_79), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2D0 p95934A__8246 (
	.A1(n_108),
	.A2(FE_PHN35_CHC_START),
	.ZN(n_78), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DFNCND1 \cnt_c_reg[5]  (
	.CDN(FE_PHN43_BUS_RST_N),
	.CPN(CTS_1),
	.D(FE_PHN48_n_72),
	.Q(FE_OFN18_debug_cnt_c_5),
	.QN(UNCONNECTED2), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI21D0 p95858A__7098 (
	.A1(n_74),
	.A2(n_20),
	.B(n_76),
	.ZN(n_77), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKND2D0 p95742A__6131 (
	.A1(n_76),
	.A2(FE_OFN6_debug_cnt_c_9),
	.ZN(n_81), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DFNCND1 \cnt_c_reg[4]  (
	.CDN(FE_PHN43_BUS_RST_N),
	.CPN(CTS_1),
	.D(FE_PHN46_n_71),
	.Q(FE_OFN21_debug_cnt_c_4),
	.QN(n_0), 
	.VSS(DVSS), 
	.VDD(DVDD));
   OAI211D0 p95912A__1881 (
	.A1(FE_PHN62_FE_OFN12_debug_cnt_c_7),
	.A2(FE_PHN47_n_70),
	.B(n_74),
	.C(sram_c_re),
	.ZN(n_75), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI21D0 p95962A__7482 (
	.A1(n_68),
	.A2(n_47),
	.B(FE_PHN35_CHC_START),
	.ZN(n_72), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2D0 p95716A__4733 (
	.A1(n_74),
	.A2(n_20),
	.ZN(n_76), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2XD0 p95991A__6161 (
	.A1(n_109),
	.A2(FE_PHN35_CHC_START),
	.ZN(n_71), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKND2D0 p95705A__9315 (
	.A1(FE_PHN47_n_70),
	.A2(FE_PHN62_FE_OFN12_debug_cnt_c_7),
	.ZN(n_74), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI21D0 p95914A__9945 (
	.A1(FE_PHN45_n_67),
	.A2(n_3),
	.B(FE_PHN47_n_70),
	.ZN(n_69), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DFNCND1 \cnt_c_reg[3]  (
	.CDN(FE_PHN43_BUS_RST_N),
	.CPN(CTS_1),
	.D(FE_PHN74_n_65),
	.Q(FE_OFN24_debug_cnt_c_3),
	.QN(UNCONNECTED3), 
	.VSS(DVSS), 
	.VDD(DVDD));
   OAI211D0 p95969A__2883 (
	.A1(FE_RN_4),
	.A2(n_63),
	.B(FE_PHN45_n_67),
	.C(sram_c_re),
	.ZN(n_68), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DFNCND1 \cnt_c_reg[2]  (
	.CDN(FE_PHN43_BUS_RST_N),
	.CPN(CTS_1),
	.D(FE_PHN44_n_64),
	.Q(FE_OFN27_debug_cnt_c_2),
	.QN(n_6), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2D0 p95679A__1666 (
	.A1(FE_PHN45_n_67),
	.A2(n_3),
	.ZN(n_70), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI21D0 p96017A__7410 (
	.A1(n_61),
	.A2(n_52),
	.B(FE_PHN35_CHC_START),
	.ZN(n_65), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DFNCND1 \cnt_c_reg[0]  (
	.CDN(FE_PHN43_BUS_RST_N),
	.CPN(CTS_1),
	.D(n_57),
	.Q(FE_OFN32_debug_cnt_c_0),
	.QN(UNCONNECTED4), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2D1 p96050A__6417 (
	.A1(n_110),
	.A2(FE_PHN35_CHC_START),
	.ZN(n_64), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DFNCND1 \cnt_c_reg[1]  (
	.CDN(FE_PHN43_BUS_RST_N),
	.CPN(CTS_1),
	.D(FE_PHN72_n_58),
	.Q(FE_OFN30_debug_cnt_c_1),
	.QN(UNCONNECTED5), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKND2D0 p95668A__5477 (
	.A1(n_63),
	.A2(FE_RN_4),
	.ZN(n_67), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI21D0 p95971A__2398 (
	.A1(n_60),
	.A2(FE_PHN37_n_0),
	.B(n_63),
	.ZN(n_62), 
	.VSS(DVSS), 
	.VDD(DVDD));
   OAI211D0 p96026A__5107 (
	.A1(sram_c_addr[3]),
	.A2(n_48),
	.B(n_60),
	.C(sram_c_re),
	.ZN(n_61), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI21D0 p96073A__4319 (
	.A1(n_51),
	.A2(n_53),
	.B(FE_PHN35_CHC_START),
	.ZN(n_58), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2D0 p96118A__8428 (
	.A1(n_111),
	.A2(FE_PHN35_CHC_START),
	.ZN(n_57), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2D0 p95642A__5526 (
	.A1(n_60),
	.A2(FE_PHN37_n_0),
	.ZN(n_63), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKND2D0 p96142A317__3680 (
	.A1(FE_OFN6_debug_cnt_c_9),
	.A2(FE_PHN38_n_35),
	.ZN(n_55), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKND2D0 p96142A316__1617 (
	.A1(FE_PHN62_FE_OFN12_debug_cnt_c_7),
	.A2(FE_PHN38_n_35),
	.ZN(n_54), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKND2D0 p96142A315__2802 (
	.A1(FE_RN_8),
	.A2(FE_PHN38_n_35),
	.ZN(n_53), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKND2D0 p96142A318__1705 (
	.A1(sram_c_addr[3]),
	.A2(FE_PHN38_n_35),
	.ZN(n_52), 
	.VSS(DVSS), 
	.VDD(DVDD));
   OAI211D0 p96082A__5122 (
	.A1(FE_PHN39_FE_OFN30_debug_cnt_c_1),
	.A2(sram_c_addr[0]),
	.B(n_49),
	.C(sram_c_re),
	.ZN(n_51), 
	.VSS(DVSS), 
	.VDD(DVDD));
   AOI21D0 p96028A__8246 (
	.A1(n_49),
	.A2(FE_PHN36_n_6),
	.B(n_48),
	.ZN(n_50), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKND2D0 p96142A__7098 (
	.A1(FE_RN_4),
	.A2(FE_PHN38_n_35),
	.ZN(n_47), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKND2D0 p95632A__6131 (
	.A1(n_48),
	.A2(sram_c_addr[3]),
	.ZN(n_60), 
	.VSS(DVSS), 
	.VDD(DVDD));
   NR2D1 p95604A__1881 (
	.A1(n_49),
	.A2(FE_PHN36_n_6),
	.ZN(n_48), 
	.VSS(DVSS), 
	.VDD(DVDD));
   INVD12 p23609A (
	.I(FE_PHN38_n_35),
	.ZN(sram_c_re), 
	.VSS(DVSS), 
	.VDD(DVDD));
   CKND2D0 p95591A__5115 (
	.A1(sram_c_addr[0]),
	.A2(FE_RN_8),
	.ZN(n_49), 
	.VSS(DVSS), 
	.VDD(DVDD));
   DFNCND1 chc_rd_s_reg (
	.CDN(FE_PHN43_BUS_RST_N),
	.CPN(CTS_1),
	.D(FE_PHN42_CHC_RD),
	.Q(UNCONNECTED6),
	.QN(n_35), 
	.VSS(DVSS), 
	.VDD(DVDD));
   MUX2ND0 g2 (
	.I0(FE_RN_1),
	.I1(n_86),
	.S(sram_c_re),
	.ZN(n_106), 
	.VSS(DVSS), 
	.VDD(DVDD));
   MUX2ND0 g367 (
	.I0(FE_OFN9_debug_cnt_c_8),
	.I1(n_77),
	.S(sram_c_re),
	.ZN(n_107), 
	.VSS(DVSS), 
	.VDD(DVDD));
   MUX2ND0 g368 (
	.I0(debug_cnt_c[6]),
	.I1(n_69),
	.S(sram_c_re),
	.ZN(n_108), 
	.VSS(DVSS), 
	.VDD(DVDD));
   MUX2ND0 g369 (
	.I0(sram_c_addr[4]),
	.I1(n_62),
	.S(sram_c_re),
	.ZN(n_109), 
	.VSS(DVSS), 
	.VDD(DVDD));
   MUX2ND0 g370 (
	.I0(sram_c_addr[2]),
	.I1(n_50),
	.S(sram_c_re),
	.ZN(n_110), 
	.VSS(DVSS), 
	.VDD(DVDD));
   XNR2D0 g371 (
	.A1(sram_c_addr[0]),
	.A2(sram_c_re),
	.ZN(n_111), 
	.VSS(DVSS), 
	.VDD(DVDD));
endmodule

