
// Generated by Cadence Genus(TM) Synthesis Solution 21.16-s062_1
// Generated on: Mar 31 2026 23:32:31 EDT (Apr  1 2026 03:32:31 UTC)

// Verification Directory fv/sram_wrapper 

module sram_wrapper(clk, rstn, bus_we, bus_addr, bus_din, tpu_re,
     tpu_addr, tpu_dout);
  input clk, rstn, bus_we, tpu_re;
  input [11:0] bus_addr;
  input [7:0] bus_din;
  input [8:0] tpu_addr;
  output [63:0] tpu_dout;
  wire clk, rstn, bus_we, tpu_re;
  wire [11:0] bus_addr;
  wire [7:0] bus_din;
  wire [8:0] tpu_addr;
  wire [63:0] tpu_dout;
  wire [8:0] sram_addr;
  wire [63:0] sram_din;
  wire [8:0] bus_waddr_d1;
  wire [8:0] sram_addr_ff;
  wire [63:0] sram_din_ff;
  wire [63:0] bus_wbuf;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42,
       UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, UNCONNECTED46;
  wire UNCONNECTED47, UNCONNECTED48, UNCONNECTED49, UNCONNECTED50,
       UNCONNECTED51, UNCONNECTED52, UNCONNECTED53, UNCONNECTED54;
  wire UNCONNECTED55, UNCONNECTED56, UNCONNECTED57, UNCONNECTED58,
       UNCONNECTED59, UNCONNECTED60, UNCONNECTED61, UNCONNECTED62;
  wire UNCONNECTED63, UNCONNECTED64, UNCONNECTED65, UNCONNECTED66,
       UNCONNECTED67, UNCONNECTED68, UNCONNECTED69, UNCONNECTED70;
  wire UNCONNECTED71, UNCONNECTED72, bus_we_d1, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_89, n_90, n_91, sram_cen, sram_cen_ff, sram_wen;
  sram00 u_sram(.CLK (clk), .CEN (sram_cen), .WEN (sram_wen), .A
       (sram_addr), .D (sram_din), .EMA (3'b10), .RETN (1'b1), .Q
       (tpu_dout));
  DFCNQD1 \bus_waddr_d1_reg[0] (.CDN (rstn), .CP (clk), .D
       (bus_addr[3]), .Q (bus_waddr_d1[0]));
  DFCNQD1 \bus_waddr_d1_reg[1] (.CDN (rstn), .CP (clk), .D
       (bus_addr[4]), .Q (bus_waddr_d1[1]));
  DFCNQD1 \bus_waddr_d1_reg[2] (.CDN (rstn), .CP (clk), .D
       (bus_addr[5]), .Q (bus_waddr_d1[2]));
  DFCNQD1 \bus_waddr_d1_reg[3] (.CDN (rstn), .CP (clk), .D
       (bus_addr[6]), .Q (bus_waddr_d1[3]));
  DFCNQD1 \bus_waddr_d1_reg[4] (.CDN (rstn), .CP (clk), .D
       (bus_addr[7]), .Q (bus_waddr_d1[4]));
  DFCNQD1 \bus_waddr_d1_reg[5] (.CDN (rstn), .CP (clk), .D
       (bus_addr[8]), .Q (bus_waddr_d1[5]));
  DFCNQD1 \bus_waddr_d1_reg[6] (.CDN (rstn), .CP (clk), .D
       (bus_addr[9]), .Q (bus_waddr_d1[6]));
  DFCNQD1 \bus_waddr_d1_reg[7] (.CDN (rstn), .CP (clk), .D
       (bus_addr[10]), .Q (bus_waddr_d1[7]));
  DFCNQD1 \bus_waddr_d1_reg[8] (.CDN (rstn), .CP (clk), .D
       (bus_addr[11]), .Q (bus_waddr_d1[8]));
  DFNCND1 \sram_addr_ff_reg[0] (.CDN (rstn), .CPN (clk), .D (n_16), .Q
       (UNCONNECTED), .QN (sram_addr_ff[0]));
  DFNCND1 \sram_addr_ff_reg[1] (.CDN (rstn), .CPN (clk), .D (n_76), .Q
       (UNCONNECTED0), .QN (sram_addr_ff[1]));
  DFNCND1 \sram_addr_ff_reg[2] (.CDN (rstn), .CPN (clk), .D (n_50), .Q
       (UNCONNECTED1), .QN (sram_addr_ff[2]));
  DFNCND1 \sram_addr_ff_reg[3] (.CDN (rstn), .CPN (clk), .D (n_15), .Q
       (UNCONNECTED2), .QN (sram_addr_ff[3]));
  DFNCND1 \sram_addr_ff_reg[4] (.CDN (rstn), .CPN (clk), .D (n_19), .Q
       (UNCONNECTED3), .QN (sram_addr_ff[4]));
  DFNCND1 \sram_addr_ff_reg[5] (.CDN (rstn), .CPN (clk), .D (n_17), .Q
       (UNCONNECTED4), .QN (sram_addr_ff[5]));
  DFNCND1 \sram_addr_ff_reg[6] (.CDN (rstn), .CPN (clk), .D (n_28), .Q
       (UNCONNECTED5), .QN (sram_addr_ff[6]));
  DFNCND1 \sram_addr_ff_reg[7] (.CDN (rstn), .CPN (clk), .D (n_22), .Q
       (UNCONNECTED6), .QN (sram_addr_ff[7]));
  DFNCND1 \sram_addr_ff_reg[8] (.CDN (rstn), .CPN (clk), .D (n_20), .Q
       (UNCONNECTED7), .QN (sram_addr_ff[8]));
  DFNCND1 \sram_din_ff_reg[0] (.CDN (rstn), .CPN (clk), .D (n_71), .Q
       (UNCONNECTED8), .QN (sram_din_ff[0]));
  DFNCND1 \sram_din_ff_reg[1] (.CDN (rstn), .CPN (clk), .D (n_21), .Q
       (UNCONNECTED9), .QN (sram_din_ff[1]));
  DFNCND1 \sram_din_ff_reg[2] (.CDN (rstn), .CPN (clk), .D (n_24), .Q
       (UNCONNECTED10), .QN (sram_din_ff[2]));
  DFNCND1 \sram_din_ff_reg[3] (.CDN (rstn), .CPN (clk), .D (n_23), .Q
       (UNCONNECTED11), .QN (sram_din_ff[3]));
  DFNCND1 \sram_din_ff_reg[4] (.CDN (rstn), .CPN (clk), .D (n_69), .Q
       (UNCONNECTED12), .QN (sram_din_ff[4]));
  DFNCND1 \sram_din_ff_reg[5] (.CDN (rstn), .CPN (clk), .D (n_27), .Q
       (UNCONNECTED13), .QN (sram_din_ff[5]));
  DFNCND1 \sram_din_ff_reg[6] (.CDN (rstn), .CPN (clk), .D (n_26), .Q
       (UNCONNECTED14), .QN (sram_din_ff[6]));
  DFNCND1 \sram_din_ff_reg[7] (.CDN (rstn), .CPN (clk), .D (n_25), .Q
       (UNCONNECTED15), .QN (sram_din_ff[7]));
  DFNCND1 \sram_din_ff_reg[8] (.CDN (rstn), .CPN (clk), .D (n_67), .Q
       (UNCONNECTED16), .QN (sram_din_ff[8]));
  DFNCND1 \sram_din_ff_reg[9] (.CDN (rstn), .CPN (clk), .D (n_30), .Q
       (UNCONNECTED17), .QN (sram_din_ff[9]));
  DFNCND1 \sram_din_ff_reg[10] (.CDN (rstn), .CPN (clk), .D (n_68), .Q
       (UNCONNECTED18), .QN (sram_din_ff[10]));
  DFNCND1 \sram_din_ff_reg[11] (.CDN (rstn), .CPN (clk), .D (n_48), .Q
       (UNCONNECTED19), .QN (sram_din_ff[11]));
  DFNCND1 \sram_din_ff_reg[12] (.CDN (rstn), .CPN (clk), .D (n_64), .Q
       (UNCONNECTED20), .QN (sram_din_ff[12]));
  DFNCND1 \sram_din_ff_reg[13] (.CDN (rstn), .CPN (clk), .D (n_33), .Q
       (UNCONNECTED21), .QN (sram_din_ff[13]));
  DFNCND1 \sram_din_ff_reg[14] (.CDN (rstn), .CPN (clk), .D (n_31), .Q
       (UNCONNECTED22), .QN (sram_din_ff[14]));
  DFNCND1 \sram_din_ff_reg[15] (.CDN (rstn), .CPN (clk), .D (n_32), .Q
       (UNCONNECTED23), .QN (sram_din_ff[15]));
  DFNCND1 \sram_din_ff_reg[16] (.CDN (rstn), .CPN (clk), .D (n_61), .Q
       (UNCONNECTED24), .QN (sram_din_ff[16]));
  DFNCND1 \sram_din_ff_reg[17] (.CDN (rstn), .CPN (clk), .D (n_58), .Q
       (UNCONNECTED25), .QN (sram_din_ff[17]));
  DFNCND1 \sram_din_ff_reg[18] (.CDN (rstn), .CPN (clk), .D (n_44), .Q
       (UNCONNECTED26), .QN (sram_din_ff[18]));
  DFNCND1 \sram_din_ff_reg[19] (.CDN (rstn), .CPN (clk), .D (n_40), .Q
       (UNCONNECTED27), .QN (sram_din_ff[19]));
  DFNCND1 \sram_din_ff_reg[20] (.CDN (rstn), .CPN (clk), .D (n_36), .Q
       (UNCONNECTED28), .QN (sram_din_ff[20]));
  DFNCND1 \sram_din_ff_reg[21] (.CDN (rstn), .CPN (clk), .D (n_34), .Q
       (UNCONNECTED29), .QN (sram_din_ff[21]));
  DFNCND1 \sram_din_ff_reg[22] (.CDN (rstn), .CPN (clk), .D (n_35), .Q
       (UNCONNECTED30), .QN (sram_din_ff[22]));
  DFNCND1 \sram_din_ff_reg[23] (.CDN (rstn), .CPN (clk), .D (n_38), .Q
       (UNCONNECTED31), .QN (sram_din_ff[23]));
  DFNCND1 \sram_din_ff_reg[24] (.CDN (rstn), .CPN (clk), .D (n_37), .Q
       (UNCONNECTED32), .QN (sram_din_ff[24]));
  DFNCND1 \sram_din_ff_reg[25] (.CDN (rstn), .CPN (clk), .D (n_47), .Q
       (UNCONNECTED33), .QN (sram_din_ff[25]));
  DFNCND1 \sram_din_ff_reg[26] (.CDN (rstn), .CPN (clk), .D (n_43), .Q
       (UNCONNECTED34), .QN (sram_din_ff[26]));
  DFNCND1 \sram_din_ff_reg[27] (.CDN (rstn), .CPN (clk), .D (n_41), .Q
       (UNCONNECTED35), .QN (sram_din_ff[27]));
  DFNCND1 \sram_din_ff_reg[28] (.CDN (rstn), .CPN (clk), .D (n_62), .Q
       (UNCONNECTED36), .QN (sram_din_ff[28]));
  DFNCND1 \sram_din_ff_reg[29] (.CDN (rstn), .CPN (clk), .D (n_45), .Q
       (UNCONNECTED37), .QN (sram_din_ff[29]));
  DFNCND1 \sram_din_ff_reg[30] (.CDN (rstn), .CPN (clk), .D (n_83), .Q
       (UNCONNECTED38), .QN (sram_din_ff[30]));
  DFNCND1 \sram_din_ff_reg[31] (.CDN (rstn), .CPN (clk), .D (n_65), .Q
       (UNCONNECTED39), .QN (sram_din_ff[31]));
  DFNCND1 \sram_din_ff_reg[32] (.CDN (rstn), .CPN (clk), .D (n_55), .Q
       (UNCONNECTED40), .QN (sram_din_ff[32]));
  DFNCND1 \sram_din_ff_reg[33] (.CDN (rstn), .CPN (clk), .D (n_14), .Q
       (UNCONNECTED41), .QN (sram_din_ff[33]));
  DFNCND1 \sram_din_ff_reg[34] (.CDN (rstn), .CPN (clk), .D (n_49), .Q
       (UNCONNECTED42), .QN (sram_din_ff[34]));
  DFNCND1 \sram_din_ff_reg[35] (.CDN (rstn), .CPN (clk), .D (n_51), .Q
       (UNCONNECTED43), .QN (sram_din_ff[35]));
  DFNCND1 \sram_din_ff_reg[36] (.CDN (rstn), .CPN (clk), .D (n_53), .Q
       (UNCONNECTED44), .QN (sram_din_ff[36]));
  DFNCND1 \sram_din_ff_reg[37] (.CDN (rstn), .CPN (clk), .D (n_52), .Q
       (UNCONNECTED45), .QN (sram_din_ff[37]));
  DFNCND1 \sram_din_ff_reg[38] (.CDN (rstn), .CPN (clk), .D (n_54), .Q
       (UNCONNECTED46), .QN (sram_din_ff[38]));
  DFNCND1 \sram_din_ff_reg[39] (.CDN (rstn), .CPN (clk), .D (n_63), .Q
       (UNCONNECTED47), .QN (sram_din_ff[39]));
  DFNCND1 \sram_din_ff_reg[40] (.CDN (rstn), .CPN (clk), .D (n_46), .Q
       (UNCONNECTED48), .QN (sram_din_ff[40]));
  DFNCND1 \sram_din_ff_reg[41] (.CDN (rstn), .CPN (clk), .D (n_56), .Q
       (UNCONNECTED49), .QN (sram_din_ff[41]));
  DFNCND1 \sram_din_ff_reg[42] (.CDN (rstn), .CPN (clk), .D (n_57), .Q
       (UNCONNECTED50), .QN (sram_din_ff[42]));
  DFNCND1 \sram_din_ff_reg[43] (.CDN (rstn), .CPN (clk), .D (n_86), .Q
       (UNCONNECTED51), .QN (sram_din_ff[43]));
  DFNCND1 \sram_din_ff_reg[44] (.CDN (rstn), .CPN (clk), .D (n_59), .Q
       (UNCONNECTED52), .QN (sram_din_ff[44]));
  DFNCND1 \sram_din_ff_reg[45] (.CDN (rstn), .CPN (clk), .D (n_81), .Q
       (UNCONNECTED53), .QN (sram_din_ff[45]));
  DFNCND1 \sram_din_ff_reg[46] (.CDN (rstn), .CPN (clk), .D (n_73), .Q
       (UNCONNECTED54), .QN (sram_din_ff[46]));
  DFNCND1 \sram_din_ff_reg[47] (.CDN (rstn), .CPN (clk), .D (n_72), .Q
       (UNCONNECTED55), .QN (sram_din_ff[47]));
  DFNCND1 \sram_din_ff_reg[48] (.CDN (rstn), .CPN (clk), .D (n_42), .Q
       (UNCONNECTED56), .QN (sram_din_ff[48]));
  DFNCND1 \sram_din_ff_reg[49] (.CDN (rstn), .CPN (clk), .D (n_70), .Q
       (UNCONNECTED57), .QN (sram_din_ff[49]));
  DFNCND1 \sram_din_ff_reg[50] (.CDN (rstn), .CPN (clk), .D (n_77), .Q
       (UNCONNECTED58), .QN (sram_din_ff[50]));
  DFNCND1 \sram_din_ff_reg[51] (.CDN (rstn), .CPN (clk), .D (n_74), .Q
       (UNCONNECTED59), .QN (sram_din_ff[51]));
  DFNCND1 \sram_din_ff_reg[52] (.CDN (rstn), .CPN (clk), .D (n_75), .Q
       (UNCONNECTED60), .QN (sram_din_ff[52]));
  DFNCND1 \sram_din_ff_reg[53] (.CDN (rstn), .CPN (clk), .D (n_85), .Q
       (UNCONNECTED61), .QN (sram_din_ff[53]));
  DFNCND1 \sram_din_ff_reg[54] (.CDN (rstn), .CPN (clk), .D (n_79), .Q
       (UNCONNECTED62), .QN (sram_din_ff[54]));
  DFNCND1 \sram_din_ff_reg[55] (.CDN (rstn), .CPN (clk), .D (n_78), .Q
       (UNCONNECTED63), .QN (sram_din_ff[55]));
  DFNCND1 \sram_din_ff_reg[56] (.CDN (rstn), .CPN (clk), .D (n_39), .Q
       (UNCONNECTED64), .QN (sram_din_ff[56]));
  DFNCND1 \sram_din_ff_reg[57] (.CDN (rstn), .CPN (clk), .D (n_18), .Q
       (UNCONNECTED65), .QN (sram_din_ff[57]));
  DFNCND1 \sram_din_ff_reg[58] (.CDN (rstn), .CPN (clk), .D (n_29), .Q
       (UNCONNECTED66), .QN (sram_din_ff[58]));
  DFNCND1 \sram_din_ff_reg[59] (.CDN (rstn), .CPN (clk), .D (n_80), .Q
       (UNCONNECTED67), .QN (sram_din_ff[59]));
  DFNCND1 \sram_din_ff_reg[60] (.CDN (rstn), .CPN (clk), .D (n_60), .Q
       (UNCONNECTED68), .QN (sram_din_ff[60]));
  DFNCND1 \sram_din_ff_reg[61] (.CDN (rstn), .CPN (clk), .D (n_84), .Q
       (UNCONNECTED69), .QN (sram_din_ff[61]));
  DFNCND1 \sram_din_ff_reg[62] (.CDN (rstn), .CPN (clk), .D (n_66), .Q
       (UNCONNECTED70), .QN (sram_din_ff[62]));
  DFNCND1 \sram_din_ff_reg[63] (.CDN (rstn), .CPN (clk), .D (n_82), .Q
       (UNCONNECTED71), .QN (sram_din_ff[63]));
  MOAI22D0 p11362A__2398(.A1 (tpu_re), .A2 (sram_addr_ff[5]), .B1
       (tpu_re), .B2 (tpu_addr[5]), .ZN (sram_addr[5]));
  MOAI22D0 p11362A3056__5107(.A1 (tpu_re), .A2 (sram_addr_ff[7]), .B1
       (tpu_re), .B2 (tpu_addr[7]), .ZN (sram_addr[7]));
  MOAI22D0 p11362A3057__6260(.A1 (tpu_re), .A2 (sram_addr_ff[8]), .B1
       (tpu_re), .B2 (tpu_addr[8]), .ZN (sram_addr[8]));
  MOAI22D0 p11362A3058__4319(.A1 (tpu_re), .A2 (sram_addr_ff[2]), .B1
       (tpu_re), .B2 (tpu_addr[2]), .ZN (sram_addr[2]));
  MOAI22D0 p11362A3059__8428(.A1 (tpu_re), .A2 (sram_addr_ff[6]), .B1
       (tpu_re), .B2 (tpu_addr[6]), .ZN (sram_addr[6]));
  MOAI22D0 p11362A3060__5526(.A1 (tpu_re), .A2 (sram_addr_ff[0]), .B1
       (tpu_re), .B2 (tpu_addr[0]), .ZN (sram_addr[0]));
  MOAI22D0 p11362A3061__6783(.A1 (tpu_re), .A2 (sram_addr_ff[1]), .B1
       (tpu_re), .B2 (tpu_addr[1]), .ZN (sram_addr[1]));
  MOAI22D0 p11362A3062__3680(.A1 (tpu_re), .A2 (sram_addr_ff[4]), .B1
       (tpu_re), .B2 (tpu_addr[4]), .ZN (sram_addr[4]));
  MOAI22D0 p11362A3063__1617(.A1 (tpu_re), .A2 (sram_addr_ff[3]), .B1
       (tpu_re), .B2 (tpu_addr[3]), .ZN (sram_addr[3]));
  NR2D0 p11608A__2802(.A1 (tpu_re), .A2 (sram_din_ff[13]), .ZN
       (sram_din[13]));
  NR2D0 p11608A3064__1705(.A1 (tpu_re), .A2 (sram_din_ff[23]), .ZN
       (sram_din[23]));
  NR2D0 p11608A3065__5122(.A1 (tpu_re), .A2 (sram_din_ff[22]), .ZN
       (sram_din[22]));
  NR2D0 p11608A3066__8246(.A1 (tpu_re), .A2 (sram_din_ff[54]), .ZN
       (sram_din[54]));
  NR2D0 p11608A3067__7098(.A1 (tpu_re), .A2 (sram_din_ff[21]), .ZN
       (sram_din[21]));
  NR2D0 p11608A3068__6131(.A1 (tpu_re), .A2 (sram_din_ff[20]), .ZN
       (sram_din[20]));
  NR2D0 p11608A3069__1881(.A1 (tpu_re), .A2 (sram_din_ff[53]), .ZN
       (sram_din[53]));
  NR2D0 p11608A3070__5115(.A1 (tpu_re), .A2 (sram_din_ff[19]), .ZN
       (sram_din[19]));
  NR2D0 p11608A3071__7482(.A1 (tpu_re), .A2 (sram_din_ff[18]), .ZN
       (sram_din[18]));
  NR2D0 p11608A3072__4733(.A1 (tpu_re), .A2 (sram_din_ff[52]), .ZN
       (sram_din[52]));
  NR2D0 p11608A3073__6161(.A1 (tpu_re), .A2 (sram_din_ff[17]), .ZN
       (sram_din[17]));
  NR2D0 p11608A3074__9315(.A1 (tpu_re), .A2 (sram_din_ff[16]), .ZN
       (sram_din[16]));
  NR2D0 p11608A3075__9945(.A1 (tpu_re), .A2 (sram_din_ff[51]), .ZN
       (sram_din[51]));
  NR2D0 p11608A3076__2883(.A1 (tpu_re), .A2 (sram_din_ff[15]), .ZN
       (sram_din[15]));
  NR2D0 p11608A3077__2346(.A1 (tpu_re), .A2 (sram_din_ff[14]), .ZN
       (sram_din[14]));
  NR2D0 p11608A3078__1666(.A1 (tpu_re), .A2 (sram_din_ff[50]), .ZN
       (sram_din[50]));
  NR2D0 p11608A3079__7410(.A1 (tpu_re), .A2 (sram_din_ff[55]), .ZN
       (sram_din[55]));
  NR2D0 p11608A3080__6417(.A1 (tpu_re), .A2 (sram_din_ff[12]), .ZN
       (sram_din[12]));
  NR2D0 p11608A3081__5477(.A1 (tpu_re), .A2 (sram_din_ff[49]), .ZN
       (sram_din[49]));
  NR2D0 p11608A3082__2398(.A1 (tpu_re), .A2 (sram_din_ff[11]), .ZN
       (sram_din[11]));
  NR2D0 p11608A3083__5107(.A1 (tpu_re), .A2 (sram_din_ff[10]), .ZN
       (sram_din[10]));
  NR2D0 p11608A3084__6260(.A1 (tpu_re), .A2 (sram_din_ff[48]), .ZN
       (sram_din[48]));
  NR2D0 p11608A3085__4319(.A1 (tpu_re), .A2 (sram_din_ff[9]), .ZN
       (sram_din[9]));
  NR2D0 p11608A3086__8428(.A1 (tpu_re), .A2 (sram_din_ff[8]), .ZN
       (sram_din[8]));
  NR2D0 p11608A3087__5526(.A1 (tpu_re), .A2 (sram_din_ff[47]), .ZN
       (sram_din[47]));
  NR2D0 p11608A3088__6783(.A1 (tpu_re), .A2 (sram_din_ff[7]), .ZN
       (sram_din[7]));
  NR2D0 p11608A3089__3680(.A1 (tpu_re), .A2 (sram_din_ff[6]), .ZN
       (sram_din[6]));
  NR2D0 p11608A3090__1617(.A1 (tpu_re), .A2 (sram_din_ff[46]), .ZN
       (sram_din[46]));
  NR2D0 p11608A3091__2802(.A1 (tpu_re), .A2 (sram_din_ff[5]), .ZN
       (sram_din[5]));
  NR2D0 p11608A3092__1705(.A1 (tpu_re), .A2 (sram_din_ff[4]), .ZN
       (sram_din[4]));
  NR2D0 p11608A3093__5122(.A1 (tpu_re), .A2 (sram_din_ff[45]), .ZN
       (sram_din[45]));
  NR2D0 p11608A3094__8246(.A1 (tpu_re), .A2 (sram_din_ff[3]), .ZN
       (sram_din[3]));
  NR2D0 p11608A3095__7098(.A1 (tpu_re), .A2 (sram_din_ff[34]), .ZN
       (sram_din[34]));
  NR2D0 p11608A3096__6131(.A1 (tpu_re), .A2 (sram_din_ff[44]), .ZN
       (sram_din[44]));
  NR2D0 p11608A3097__1881(.A1 (tpu_re), .A2 (sram_din_ff[1]), .ZN
       (sram_din[1]));
  NR2D0 p11608A3098__5115(.A1 (tpu_re), .A2 (sram_din_ff[0]), .ZN
       (sram_din[0]));
  NR2D0 p11608A3099__7482(.A1 (tpu_re), .A2 (sram_din_ff[43]), .ZN
       (sram_din[43]));
  NR2D0 p11608A3100__4733(.A1 (tpu_re), .A2 (sram_din_ff[42]), .ZN
       (sram_din[42]));
  NR2D0 p11608A3101__6161(.A1 (tpu_re), .A2 (sram_din_ff[41]), .ZN
       (sram_din[41]));
  NR2D0 p11608A3102__9315(.A1 (tpu_re), .A2 (sram_din_ff[40]), .ZN
       (sram_din[40]));
  NR2D0 p11608A3103__9945(.A1 (tpu_re), .A2 (sram_din_ff[63]), .ZN
       (sram_din[63]));
  NR2D0 p11608A3104__2883(.A1 (tpu_re), .A2 (sram_din_ff[39]), .ZN
       (sram_din[39]));
  NR2D0 p11608A3105__2346(.A1 (tpu_re), .A2 (sram_din_ff[38]), .ZN
       (sram_din[38]));
  NR2D0 p11608A3106__1666(.A1 (tpu_re), .A2 (sram_din_ff[62]), .ZN
       (sram_din[62]));
  NR2D0 p11608A3107__7410(.A1 (tpu_re), .A2 (sram_din_ff[37]), .ZN
       (sram_din[37]));
  NR2D0 p11608A3108__6417(.A1 (tpu_re), .A2 (sram_din_ff[36]), .ZN
       (sram_din[36]));
  NR2D0 p11608A3109__5477(.A1 (tpu_re), .A2 (sram_din_ff[61]), .ZN
       (sram_din[61]));
  NR2D0 p11608A3110__2398(.A1 (tpu_re), .A2 (sram_din_ff[35]), .ZN
       (sram_din[35]));
  NR2D0 p11608A3111__5107(.A1 (tpu_re), .A2 (sram_din_ff[2]), .ZN
       (sram_din[2]));
  NR2D0 p11608A3112__6260(.A1 (tpu_re), .A2 (sram_din_ff[60]), .ZN
       (sram_din[60]));
  NR2D0 p11608A3113__4319(.A1 (tpu_re), .A2 (sram_din_ff[33]), .ZN
       (sram_din[33]));
  NR2D0 p11608A3114__8428(.A1 (tpu_re), .A2 (sram_din_ff[32]), .ZN
       (sram_din[32]));
  NR2D0 p11608A3115__5526(.A1 (tpu_re), .A2 (sram_din_ff[59]), .ZN
       (sram_din[59]));
  NR2D0 p11608A3116__6783(.A1 (tpu_re), .A2 (sram_din_ff[31]), .ZN
       (sram_din[31]));
  NR2D0 p11608A3117__3680(.A1 (tpu_re), .A2 (sram_din_ff[30]), .ZN
       (sram_din[30]));
  NR2D0 p11608A3118__1617(.A1 (tpu_re), .A2 (sram_din_ff[58]), .ZN
       (sram_din[58]));
  NR2D0 p11608A3119__2802(.A1 (tpu_re), .A2 (sram_din_ff[29]), .ZN
       (sram_din[29]));
  NR2D0 p11608A3120__1705(.A1 (tpu_re), .A2 (sram_din_ff[28]), .ZN
       (sram_din[28]));
  NR2D0 p11608A3121__5122(.A1 (tpu_re), .A2 (sram_din_ff[57]), .ZN
       (sram_din[57]));
  NR2D0 p11608A3122__8246(.A1 (tpu_re), .A2 (sram_din_ff[27]), .ZN
       (sram_din[27]));
  NR2D0 p11608A3123__7098(.A1 (tpu_re), .A2 (sram_din_ff[26]), .ZN
       (sram_din[26]));
  NR2D0 p11608A3124__6131(.A1 (tpu_re), .A2 (sram_din_ff[56]), .ZN
       (sram_din[56]));
  NR2D0 p11608A3125__1881(.A1 (tpu_re), .A2 (sram_din_ff[25]), .ZN
       (sram_din[25]));
  NR2D0 p11608A3126__5115(.A1 (tpu_re), .A2 (sram_din_ff[24]), .ZN
       (sram_din[24]));
  CKAN2D0 p11422A__7482(.A1 (bus_wbuf[43]), .A2 (bus_we_d1), .Z (n_86));
  CKAN2D0 p11422A3200__4733(.A1 (bus_wbuf[53]), .A2 (bus_we_d1), .Z
       (n_85));
  CKAN2D0 p11422A3201__6161(.A1 (bus_wbuf[61]), .A2 (bus_we_d1), .Z
       (n_84));
  CKAN2D0 p11422A3202__9315(.A1 (bus_wbuf[30]), .A2 (bus_we_d1), .Z
       (n_83));
  CKAN2D0 p11422A3203__9945(.A1 (bus_wbuf[63]), .A2 (bus_we_d1), .Z
       (n_82));
  CKAN2D0 p11422A3204__2883(.A1 (bus_wbuf[45]), .A2 (bus_we_d1), .Z
       (n_81));
  CKAN2D0 p11422A3205__2346(.A1 (bus_wbuf[59]), .A2 (bus_we_d1), .Z
       (n_80));
  CKAN2D0 p11422A3206__1666(.A1 (bus_wbuf[54]), .A2 (bus_we_d1), .Z
       (n_79));
  CKAN2D0 p11422A3207__7410(.A1 (bus_wbuf[55]), .A2 (bus_we_d1), .Z
       (n_78));
  CKAN2D0 p11422A3208__6417(.A1 (bus_wbuf[50]), .A2 (bus_we_d1), .Z
       (n_77));
  CKAN2D0 p11774A__5477(.A1 (bus_we_d1), .A2 (bus_waddr_d1[1]), .Z
       (n_76));
  CKAN2D0 p11422A3209__2398(.A1 (bus_wbuf[52]), .A2 (bus_we_d1), .Z
       (n_75));
  CKAN2D0 p11422A3210__5107(.A1 (bus_wbuf[51]), .A2 (bus_we_d1), .Z
       (n_74));
  CKAN2D0 p11422A3211__6260(.A1 (bus_wbuf[46]), .A2 (bus_we_d1), .Z
       (n_73));
  CKAN2D0 p11422A3212__4319(.A1 (bus_wbuf[47]), .A2 (bus_we_d1), .Z
       (n_72));
  CKAN2D0 p11422A3213__8428(.A1 (bus_wbuf[0]), .A2 (bus_we_d1), .Z
       (n_71));
  CKAN2D0 p11422A3214__5526(.A1 (bus_wbuf[49]), .A2 (bus_we_d1), .Z
       (n_70));
  CKAN2D0 p11422A3215__6783(.A1 (bus_wbuf[4]), .A2 (bus_we_d1), .Z
       (n_69));
  CKAN2D0 p11422A3216__3680(.A1 (bus_wbuf[10]), .A2 (bus_we_d1), .Z
       (n_68));
  CKAN2D0 p11422A3217__1617(.A1 (bus_wbuf[8]), .A2 (bus_we_d1), .Z
       (n_67));
  CKAN2D0 p11422A3218__2802(.A1 (bus_wbuf[62]), .A2 (bus_we_d1), .Z
       (n_66));
  CKAN2D0 p11422A3219__1705(.A1 (bus_wbuf[31]), .A2 (bus_we_d1), .Z
       (n_65));
  CKAN2D0 p11422A3220__5122(.A1 (bus_wbuf[12]), .A2 (bus_we_d1), .Z
       (n_64));
  CKAN2D0 p11422A3221__8246(.A1 (bus_wbuf[39]), .A2 (bus_we_d1), .Z
       (n_63));
  CKAN2D0 p11422A3222__7098(.A1 (bus_wbuf[28]), .A2 (bus_we_d1), .Z
       (n_62));
  CKAN2D0 p11422A3223__6131(.A1 (bus_wbuf[16]), .A2 (bus_we_d1), .Z
       (n_61));
  CKAN2D0 p11422A3224__1881(.A1 (bus_wbuf[60]), .A2 (bus_we_d1), .Z
       (n_60));
  CKAN2D0 p11422A3225__5115(.A1 (bus_wbuf[44]), .A2 (bus_we_d1), .Z
       (n_59));
  CKAN2D0 p11422A3226__7482(.A1 (bus_wbuf[17]), .A2 (bus_we_d1), .Z
       (n_58));
  CKAN2D0 p11422A3227__4733(.A1 (bus_wbuf[42]), .A2 (bus_we_d1), .Z
       (n_57));
  CKAN2D0 p11422A3228__6161(.A1 (bus_wbuf[41]), .A2 (bus_we_d1), .Z
       (n_56));
  CKAN2D0 p11422A3229__9315(.A1 (bus_wbuf[32]), .A2 (bus_we_d1), .Z
       (n_55));
  CKAN2D0 p11422A3230__9945(.A1 (bus_wbuf[38]), .A2 (bus_we_d1), .Z
       (n_54));
  CKAN2D0 p11422A3231__2883(.A1 (bus_wbuf[36]), .A2 (bus_we_d1), .Z
       (n_53));
  CKAN2D0 p11422A3232__2346(.A1 (bus_wbuf[37]), .A2 (bus_we_d1), .Z
       (n_52));
  CKAN2D0 p11422A3233__1666(.A1 (bus_wbuf[35]), .A2 (bus_we_d1), .Z
       (n_51));
  CKAN2D0 p11774A3234__7410(.A1 (bus_we_d1), .A2 (bus_waddr_d1[2]), .Z
       (n_50));
  CKAN2D0 p11422A3235__6417(.A1 (bus_wbuf[34]), .A2 (bus_we_d1), .Z
       (n_49));
  CKAN2D0 p11422A3236__5477(.A1 (bus_wbuf[11]), .A2 (bus_we_d1), .Z
       (n_48));
  CKAN2D0 p11422A3237__2398(.A1 (bus_wbuf[25]), .A2 (bus_we_d1), .Z
       (n_47));
  CKAN2D0 p11422A3238__5107(.A1 (bus_wbuf[40]), .A2 (bus_we_d1), .Z
       (n_46));
  CKAN2D0 p11422A3239__6260(.A1 (bus_wbuf[29]), .A2 (bus_we_d1), .Z
       (n_45));
  CKAN2D0 p11422A3240__4319(.A1 (bus_wbuf[18]), .A2 (bus_we_d1), .Z
       (n_44));
  CKAN2D0 p11422A3241__8428(.A1 (bus_wbuf[26]), .A2 (bus_we_d1), .Z
       (n_43));
  CKAN2D0 p11422A3242__5526(.A1 (bus_wbuf[48]), .A2 (bus_we_d1), .Z
       (n_42));
  CKAN2D0 p11422A3243__6783(.A1 (bus_wbuf[27]), .A2 (bus_we_d1), .Z
       (n_41));
  CKAN2D0 p11422A3244__3680(.A1 (bus_wbuf[19]), .A2 (bus_we_d1), .Z
       (n_40));
  CKAN2D0 p11422A3245__1617(.A1 (bus_wbuf[56]), .A2 (bus_we_d1), .Z
       (n_39));
  CKAN2D0 p11422A3246__2802(.A1 (bus_wbuf[23]), .A2 (bus_we_d1), .Z
       (n_38));
  CKAN2D0 p11422A3247__1705(.A1 (bus_wbuf[24]), .A2 (bus_we_d1), .Z
       (n_37));
  CKAN2D0 p11422A3248__5122(.A1 (bus_wbuf[20]), .A2 (bus_we_d1), .Z
       (n_36));
  CKAN2D0 p11422A3249__8246(.A1 (bus_wbuf[22]), .A2 (bus_we_d1), .Z
       (n_35));
  CKAN2D0 p11422A3250__7098(.A1 (bus_wbuf[21]), .A2 (bus_we_d1), .Z
       (n_34));
  CKAN2D0 p11422A3251__6131(.A1 (bus_wbuf[13]), .A2 (bus_we_d1), .Z
       (n_33));
  CKAN2D0 p11422A3252__1881(.A1 (bus_wbuf[15]), .A2 (bus_we_d1), .Z
       (n_32));
  CKAN2D0 p11422A3253__5115(.A1 (bus_wbuf[14]), .A2 (bus_we_d1), .Z
       (n_31));
  CKAN2D0 p11422A3254__7482(.A1 (bus_wbuf[9]), .A2 (bus_we_d1), .Z
       (n_30));
  CKAN2D0 p11422A3255__4733(.A1 (bus_wbuf[58]), .A2 (bus_we_d1), .Z
       (n_29));
  CKAN2D0 p11774A3256__6161(.A1 (bus_we_d1), .A2 (bus_waddr_d1[6]), .Z
       (n_28));
  CKAN2D0 p11422A3257__9315(.A1 (bus_wbuf[5]), .A2 (bus_we_d1), .Z
       (n_27));
  CKAN2D0 p11422A3258__9945(.A1 (bus_wbuf[6]), .A2 (bus_we_d1), .Z
       (n_26));
  CKAN2D0 p11422A3259__2883(.A1 (bus_wbuf[7]), .A2 (bus_we_d1), .Z
       (n_25));
  CKAN2D0 p11422A3260__2346(.A1 (bus_wbuf[2]), .A2 (bus_we_d1), .Z
       (n_24));
  CKAN2D0 p11422A3261__1666(.A1 (bus_wbuf[3]), .A2 (bus_we_d1), .Z
       (n_23));
  CKAN2D0 p11774A3262__7410(.A1 (bus_we_d1), .A2 (bus_waddr_d1[7]), .Z
       (n_22));
  CKAN2D0 p11422A3263__6417(.A1 (bus_wbuf[1]), .A2 (bus_we_d1), .Z
       (n_21));
  CKAN2D0 p11774A3264__5477(.A1 (bus_we_d1), .A2 (bus_waddr_d1[8]), .Z
       (n_20));
  CKAN2D0 p11774A3265__2398(.A1 (bus_we_d1), .A2 (bus_waddr_d1[4]), .Z
       (n_19));
  CKAN2D0 p11422A3266__5107(.A1 (bus_wbuf[57]), .A2 (bus_we_d1), .Z
       (n_18));
  CKAN2D0 p11774A3267__6260(.A1 (bus_we_d1), .A2 (bus_waddr_d1[5]), .Z
       (n_17));
  CKAN2D0 p11774A3268__4319(.A1 (bus_we_d1), .A2 (bus_waddr_d1[0]), .Z
       (n_16));
  CKAN2D0 p11774A3269__8428(.A1 (bus_we_d1), .A2 (bus_waddr_d1[3]), .Z
       (n_15));
  CKAN2D0 p11422A3270__5526(.A1 (bus_wbuf[33]), .A2 (bus_we_d1), .Z
       (n_14));
  CKND0 Fp23701A(.I (n_91), .ZN (n_13));
  IND2D0 p23616A__6783(.A1 (n_89), .B1 (bus_addr[1]), .ZN (n_91));
  IND2D0 p23543A__3680(.A1 (n_90), .B1 (bus_addr[2]), .ZN (n_89));
  OR2D0 p11189A__1617(.A1 (sram_cen_ff), .A2 (tpu_re), .Z (sram_wen));
  INR2D0 p11168A__2802(.A1 (sram_cen_ff), .B1 (tpu_re), .ZN (sram_cen));
  CKND2D0 p23533A__1705(.A1 (bus_we), .A2 (bus_addr[0]), .ZN (n_90));
  DFXQD1 \bus_wbuf_reg[0] (.CP (clk), .DA (bus_wbuf[0]), .DB
       (bus_din[0]), .SA (n_11), .Q (bus_wbuf[0]));
  DFXQD1 \bus_wbuf_reg[1] (.CP (clk), .DA (bus_wbuf[1]), .DB
       (bus_din[1]), .SA (n_11), .Q (bus_wbuf[1]));
  DFXQD1 \bus_wbuf_reg[2] (.CP (clk), .DA (bus_wbuf[2]), .DB
       (bus_din[2]), .SA (n_11), .Q (bus_wbuf[2]));
  DFXQD1 \bus_wbuf_reg[3] (.CP (clk), .DA (bus_wbuf[3]), .DB
       (bus_din[3]), .SA (n_11), .Q (bus_wbuf[3]));
  DFXQD1 \bus_wbuf_reg[4] (.CP (clk), .DA (bus_wbuf[4]), .DB
       (bus_din[4]), .SA (n_11), .Q (bus_wbuf[4]));
  DFXQD1 \bus_wbuf_reg[5] (.CP (clk), .DA (bus_wbuf[5]), .DB
       (bus_din[5]), .SA (n_11), .Q (bus_wbuf[5]));
  DFXQD1 \bus_wbuf_reg[6] (.CP (clk), .DA (bus_wbuf[6]), .DB
       (bus_din[6]), .SA (n_11), .Q (bus_wbuf[6]));
  DFXQD1 \bus_wbuf_reg[7] (.CP (clk), .DA (bus_wbuf[7]), .DB
       (bus_din[7]), .SA (n_11), .Q (bus_wbuf[7]));
  DFXQD1 \bus_wbuf_reg[8] (.CP (clk), .DA (bus_wbuf[8]), .DB
       (bus_din[0]), .SA (n_5), .Q (bus_wbuf[8]));
  DFXQD1 \bus_wbuf_reg[9] (.CP (clk), .DA (bus_wbuf[9]), .DB
       (bus_din[1]), .SA (n_5), .Q (bus_wbuf[9]));
  DFXQD1 \bus_wbuf_reg[10] (.CP (clk), .DA (bus_wbuf[10]), .DB
       (bus_din[2]), .SA (n_5), .Q (bus_wbuf[10]));
  DFXQD1 \bus_wbuf_reg[11] (.CP (clk), .DA (bus_wbuf[11]), .DB
       (bus_din[3]), .SA (n_5), .Q (bus_wbuf[11]));
  DFXQD1 \bus_wbuf_reg[12] (.CP (clk), .DA (bus_wbuf[12]), .DB
       (bus_din[4]), .SA (n_5), .Q (bus_wbuf[12]));
  DFXQD1 \bus_wbuf_reg[13] (.CP (clk), .DA (bus_wbuf[13]), .DB
       (bus_din[5]), .SA (n_5), .Q (bus_wbuf[13]));
  DFXQD1 \bus_wbuf_reg[14] (.CP (clk), .DA (bus_wbuf[14]), .DB
       (bus_din[6]), .SA (n_5), .Q (bus_wbuf[14]));
  DFXQD1 \bus_wbuf_reg[15] (.CP (clk), .DA (bus_wbuf[15]), .DB
       (bus_din[7]), .SA (n_5), .Q (bus_wbuf[15]));
  DFXQD1 \bus_wbuf_reg[16] (.CP (clk), .DA (bus_wbuf[16]), .DB
       (bus_din[0]), .SA (n_9), .Q (bus_wbuf[16]));
  DFXQD1 \bus_wbuf_reg[17] (.CP (clk), .DA (bus_wbuf[17]), .DB
       (bus_din[1]), .SA (n_9), .Q (bus_wbuf[17]));
  DFXQD1 \bus_wbuf_reg[18] (.CP (clk), .DA (bus_wbuf[18]), .DB
       (bus_din[2]), .SA (n_9), .Q (bus_wbuf[18]));
  DFXQD1 \bus_wbuf_reg[19] (.CP (clk), .DA (bus_wbuf[19]), .DB
       (bus_din[3]), .SA (n_9), .Q (bus_wbuf[19]));
  DFXQD1 \bus_wbuf_reg[20] (.CP (clk), .DA (bus_wbuf[20]), .DB
       (bus_din[4]), .SA (n_9), .Q (bus_wbuf[20]));
  DFXQD1 \bus_wbuf_reg[21] (.CP (clk), .DA (bus_wbuf[21]), .DB
       (bus_din[5]), .SA (n_9), .Q (bus_wbuf[21]));
  DFXQD1 \bus_wbuf_reg[22] (.CP (clk), .DA (bus_wbuf[22]), .DB
       (bus_din[6]), .SA (n_9), .Q (bus_wbuf[22]));
  DFXQD1 \bus_wbuf_reg[23] (.CP (clk), .DA (bus_wbuf[23]), .DB
       (bus_din[7]), .SA (n_9), .Q (bus_wbuf[23]));
  DFXQD1 \bus_wbuf_reg[24] (.CP (clk), .DA (bus_wbuf[24]), .DB
       (bus_din[0]), .SA (n_7), .Q (bus_wbuf[24]));
  DFXQD1 \bus_wbuf_reg[25] (.CP (clk), .DA (bus_wbuf[25]), .DB
       (bus_din[1]), .SA (n_7), .Q (bus_wbuf[25]));
  DFXQD1 \bus_wbuf_reg[26] (.CP (clk), .DA (bus_wbuf[26]), .DB
       (bus_din[2]), .SA (n_7), .Q (bus_wbuf[26]));
  DFXQD1 \bus_wbuf_reg[27] (.CP (clk), .DA (bus_wbuf[27]), .DB
       (bus_din[3]), .SA (n_7), .Q (bus_wbuf[27]));
  DFXQD1 \bus_wbuf_reg[28] (.CP (clk), .DA (bus_wbuf[28]), .DB
       (bus_din[4]), .SA (n_7), .Q (bus_wbuf[28]));
  DFXQD1 \bus_wbuf_reg[29] (.CP (clk), .DA (bus_wbuf[29]), .DB
       (bus_din[5]), .SA (n_7), .Q (bus_wbuf[29]));
  DFXQD1 \bus_wbuf_reg[30] (.CP (clk), .DA (bus_wbuf[30]), .DB
       (bus_din[6]), .SA (n_7), .Q (bus_wbuf[30]));
  DFXQD1 \bus_wbuf_reg[31] (.CP (clk), .DA (bus_wbuf[31]), .DB
       (bus_din[7]), .SA (n_7), .Q (bus_wbuf[31]));
  DFXQD1 \bus_wbuf_reg[32] (.CP (clk), .DA (bus_din[0]), .DB
       (bus_wbuf[32]), .SA (n_12), .Q (bus_wbuf[32]));
  DFXQD1 \bus_wbuf_reg[33] (.CP (clk), .DA (bus_din[1]), .DB
       (bus_wbuf[33]), .SA (n_12), .Q (bus_wbuf[33]));
  DFXQD1 \bus_wbuf_reg[34] (.CP (clk), .DA (bus_din[2]), .DB
       (bus_wbuf[34]), .SA (n_12), .Q (bus_wbuf[34]));
  DFXQD1 \bus_wbuf_reg[35] (.CP (clk), .DA (bus_din[3]), .DB
       (bus_wbuf[35]), .SA (n_12), .Q (bus_wbuf[35]));
  DFXQD1 \bus_wbuf_reg[36] (.CP (clk), .DA (bus_din[4]), .DB
       (bus_wbuf[36]), .SA (n_12), .Q (bus_wbuf[36]));
  DFXQD1 \bus_wbuf_reg[37] (.CP (clk), .DA (bus_din[5]), .DB
       (bus_wbuf[37]), .SA (n_12), .Q (bus_wbuf[37]));
  DFXQD1 \bus_wbuf_reg[38] (.CP (clk), .DA (bus_din[6]), .DB
       (bus_wbuf[38]), .SA (n_12), .Q (bus_wbuf[38]));
  DFXQD1 \bus_wbuf_reg[39] (.CP (clk), .DA (bus_din[7]), .DB
       (bus_wbuf[39]), .SA (n_12), .Q (bus_wbuf[39]));
  DFXQD1 \bus_wbuf_reg[40] (.CP (clk), .DA (bus_din[0]), .DB
       (bus_wbuf[40]), .SA (n_4), .Q (bus_wbuf[40]));
  DFXQD1 \bus_wbuf_reg[41] (.CP (clk), .DA (bus_din[1]), .DB
       (bus_wbuf[41]), .SA (n_4), .Q (bus_wbuf[41]));
  DFXQD1 \bus_wbuf_reg[42] (.CP (clk), .DA (bus_din[2]), .DB
       (bus_wbuf[42]), .SA (n_4), .Q (bus_wbuf[42]));
  DFXQD1 \bus_wbuf_reg[43] (.CP (clk), .DA (bus_din[3]), .DB
       (bus_wbuf[43]), .SA (n_4), .Q (bus_wbuf[43]));
  DFXQD1 \bus_wbuf_reg[44] (.CP (clk), .DA (bus_din[4]), .DB
       (bus_wbuf[44]), .SA (n_4), .Q (bus_wbuf[44]));
  DFXQD1 \bus_wbuf_reg[45] (.CP (clk), .DA (bus_din[5]), .DB
       (bus_wbuf[45]), .SA (n_4), .Q (bus_wbuf[45]));
  DFXQD1 \bus_wbuf_reg[46] (.CP (clk), .DA (bus_din[6]), .DB
       (bus_wbuf[46]), .SA (n_4), .Q (bus_wbuf[46]));
  DFXQD1 \bus_wbuf_reg[47] (.CP (clk), .DA (bus_din[7]), .DB
       (bus_wbuf[47]), .SA (n_4), .Q (bus_wbuf[47]));
  DFXQD1 \bus_wbuf_reg[48] (.CP (clk), .DA (bus_din[0]), .DB
       (bus_wbuf[48]), .SA (n_10), .Q (bus_wbuf[48]));
  DFXQD1 \bus_wbuf_reg[49] (.CP (clk), .DA (bus_din[1]), .DB
       (bus_wbuf[49]), .SA (n_10), .Q (bus_wbuf[49]));
  DFXQD1 \bus_wbuf_reg[50] (.CP (clk), .DA (bus_din[2]), .DB
       (bus_wbuf[50]), .SA (n_10), .Q (bus_wbuf[50]));
  DFXQD1 \bus_wbuf_reg[51] (.CP (clk), .DA (bus_din[3]), .DB
       (bus_wbuf[51]), .SA (n_10), .Q (bus_wbuf[51]));
  DFXQD1 \bus_wbuf_reg[52] (.CP (clk), .DA (bus_din[4]), .DB
       (bus_wbuf[52]), .SA (n_10), .Q (bus_wbuf[52]));
  DFXQD1 \bus_wbuf_reg[53] (.CP (clk), .DA (bus_din[5]), .DB
       (bus_wbuf[53]), .SA (n_10), .Q (bus_wbuf[53]));
  DFXQD1 \bus_wbuf_reg[54] (.CP (clk), .DA (bus_din[6]), .DB
       (bus_wbuf[54]), .SA (n_10), .Q (bus_wbuf[54]));
  DFXQD1 \bus_wbuf_reg[55] (.CP (clk), .DA (bus_din[7]), .DB
       (bus_wbuf[55]), .SA (n_10), .Q (bus_wbuf[55]));
  DFXQD1 \bus_wbuf_reg[56] (.CP (clk), .DA (bus_wbuf[56]), .DB
       (bus_din[0]), .SA (n_91), .Q (bus_wbuf[56]));
  DFXQD1 \bus_wbuf_reg[57] (.CP (clk), .DA (bus_wbuf[57]), .DB
       (bus_din[1]), .SA (n_91), .Q (bus_wbuf[57]));
  DFXQD1 \bus_wbuf_reg[58] (.CP (clk), .DA (bus_wbuf[58]), .DB
       (bus_din[2]), .SA (n_91), .Q (bus_wbuf[58]));
  DFXQD1 \bus_wbuf_reg[59] (.CP (clk), .DA (bus_wbuf[59]), .DB
       (bus_din[3]), .SA (n_91), .Q (bus_wbuf[59]));
  DFXQD1 \bus_wbuf_reg[60] (.CP (clk), .DA (bus_wbuf[60]), .DB
       (bus_din[4]), .SA (n_91), .Q (bus_wbuf[60]));
  DFXQD1 \bus_wbuf_reg[61] (.CP (clk), .DA (bus_wbuf[61]), .DB
       (bus_din[5]), .SA (n_91), .Q (bus_wbuf[61]));
  DFXQD1 \bus_wbuf_reg[62] (.CP (clk), .DA (bus_wbuf[62]), .DB
       (bus_din[6]), .SA (n_91), .Q (bus_wbuf[62]));
  DFXQD1 \bus_wbuf_reg[63] (.CP (clk), .DA (bus_wbuf[63]), .DB
       (bus_din[7]), .SA (n_91), .Q (bus_wbuf[63]));
  DFNSND1 sram_cen_ff_reg(.SDN (rstn), .CPN (clk), .D (n_1), .Q
       (sram_cen_ff), .QN (UNCONNECTED72));
  NR2D0 p23572A__5122(.A1 (n_8), .A2 (bus_addr[1]), .ZN (n_12));
  CKND2D0 p23649A__8246(.A1 (n_6), .A2 (n_0), .ZN (n_11));
  NR2D0 p23572A3363__7098(.A1 (n_8), .A2 (n_0), .ZN (n_10));
  CKND2D0 p23649A3364__6131(.A1 (n_6), .A2 (bus_addr[1]), .ZN (n_9));
  CKND2D0 p23566A__1881(.A1 (n_2), .A2 (bus_addr[2]), .ZN (n_8));
  CKND2D0 p23658A__5115(.A1 (n_3), .A2 (bus_addr[1]), .ZN (n_7));
  INR2D0 p23607A__7482(.A1 (n_2), .B1 (bus_addr[2]), .ZN (n_6));
  CKND2D0 p23658A3365__4733(.A1 (n_3), .A2 (n_0), .ZN (n_5));
  NR2D0 p23566A3367__6161(.A1 (n_89), .A2 (bus_addr[1]), .ZN (n_4));
  NR2D0 p23639A__9315(.A1 (n_90), .A2 (bus_addr[2]), .ZN (n_3));
  INR2D0 p23529A__9945(.A1 (bus_we), .B1 (bus_addr[0]), .ZN (n_2));
  CKND0 Fp23597A(.I (bus_addr[1]), .ZN (n_0));
  DFCND1 bus_we_d1_reg(.CDN (rstn), .CP (clk), .D (n_13), .Q
       (bus_we_d1), .QN (n_1));
endmodule

