
// Generated by Cadence Genus(TM) Synthesis Solution 21.16-s062_1
// Generated on: Apr 23 2026 22:19:48 EDT (Apr 24 2026 02:19:48 UTC)

// Verification Directory fv/bias_wrapper 

module bias_wrapper(clk, rstn, bus_we, bus_addr, bus_din, tpu_re,
     tpu_addr, tpu_dout);
  input clk, rstn, bus_we, tpu_re;
  input [10:0] bus_addr;
  input [7:0] bus_din;
  input [8:0] tpu_addr;
  output [31:0] tpu_dout;
  wire clk, rstn, bus_we, tpu_re;
  wire [10:0] bus_addr;
  wire [7:0] bus_din;
  wire [8:0] tpu_addr;
  wire [31:0] tpu_dout;
  wire [8:0] sram_addr;
  wire [31:0] bus_wbuf;
  wire [8:0] flush_addr;
  wire [8:0] bus_waddr_d1;
  wire [1:0] last_byte_sel;
  wire [8:0] last_word_addr;
  wire UNCONNECTED, bus_we_d1, bus_we_prev, flush_d1, n_0, n_1, n_2,
       n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_63, sram_cen, sram_wen;
  sram01 u_sram(.CLK (clk), .CEN (sram_cen), .WEN (sram_wen), .A
       (sram_addr), .D (bus_wbuf), .EMA (3'b10), .RETN (1'b1), .Q
       (tpu_dout));
  AO222D0 p23400A__2398(.A1 (tpu_addr[4]), .A2 (sram_wen), .B1 (n_60),
       .B2 (flush_addr[4]), .C1 (bus_waddr_d1[4]), .C2 (bus_we_d1), .Z
       (sram_addr[4]));
  AO222D0 p23400A2254__5107(.A1 (tpu_addr[6]), .A2 (sram_wen), .B1
       (n_60), .B2 (flush_addr[6]), .C1 (bus_waddr_d1[6]), .C2
       (bus_we_d1), .Z (sram_addr[6]));
  AO222D0 p23400A2255__6260(.A1 (tpu_addr[8]), .A2 (sram_wen), .B1
       (n_60), .B2 (flush_addr[8]), .C1 (bus_waddr_d1[8]), .C2
       (bus_we_d1), .Z (sram_addr[8]));
  AO222D0 p23400A2256__4319(.A1 (tpu_addr[0]), .A2 (sram_wen), .B1
       (n_60), .B2 (flush_addr[0]), .C1 (bus_waddr_d1[0]), .C2
       (bus_we_d1), .Z (sram_addr[0]));
  AO222D0 p23400A2257__8428(.A1 (tpu_addr[2]), .A2 (sram_wen), .B1
       (n_60), .B2 (flush_addr[2]), .C1 (bus_waddr_d1[2]), .C2
       (bus_we_d1), .Z (sram_addr[2]));
  AO222D0 p23400A2258__5526(.A1 (tpu_addr[7]), .A2 (sram_wen), .B1
       (n_60), .B2 (flush_addr[7]), .C1 (bus_waddr_d1[7]), .C2
       (bus_we_d1), .Z (sram_addr[7]));
  AO222D0 p23400A2259__6783(.A1 (tpu_addr[3]), .A2 (sram_wen), .B1
       (n_60), .B2 (flush_addr[3]), .C1 (bus_waddr_d1[3]), .C2
       (bus_we_d1), .Z (sram_addr[3]));
  AO222D0 p23400A2260__3680(.A1 (tpu_addr[5]), .A2 (sram_wen), .B1
       (n_60), .B2 (flush_addr[5]), .C1 (bus_waddr_d1[5]), .C2
       (bus_we_d1), .Z (sram_addr[5]));
  AO222D0 p23400A2261__1617(.A1 (tpu_addr[1]), .A2 (sram_wen), .B1
       (n_60), .B2 (flush_addr[1]), .C1 (bus_waddr_d1[1]), .C2
       (bus_we_d1), .Z (sram_addr[1]));
  INR2D0 p23360A__2802(.A1 (flush_d1), .B1 (bus_we_d1), .ZN (n_60));
  NR2D0 p23320A__1705(.A1 (flush_d1), .A2 (bus_we_d1), .ZN (sram_wen));
  DFKCNQD1 flush_d1_reg(.CP (clk), .CN (rstn), .D (n_59), .Q
       (flush_d1));
  DFKCNQD1 bus_we_d1_reg(.CP (clk), .CN (rstn), .D (n_58), .Q
       (bus_we_d1));
  AOI211D0 p23421A__5122(.A1 (last_byte_sel[0]), .A2
       (last_byte_sel[1]), .B (bus_we), .C (bus_we_prev), .ZN (n_59));
  DFKCNQD1 \bus_waddr_d1_reg[1] (.CP (clk), .CN (bus_addr[3]), .D
       (rstn), .Q (bus_waddr_d1[1]));
  DFKCNQD1 \flush_addr_reg[1] (.CP (clk), .CN (rstn), .D
       (last_word_addr[1]), .Q (flush_addr[1]));
  DFKCNQD1 \bus_waddr_d1_reg[5] (.CP (clk), .CN (bus_addr[7]), .D
       (rstn), .Q (bus_waddr_d1[5]));
  DFKCNQD1 \flush_addr_reg[0] (.CP (clk), .CN (rstn), .D
       (last_word_addr[0]), .Q (flush_addr[0]));
  DFKCNQD1 \bus_waddr_d1_reg[0] (.CP (clk), .CN (bus_addr[2]), .D
       (rstn), .Q (bus_waddr_d1[0]));
  DFKCNQD1 \bus_waddr_d1_reg[7] (.CP (clk), .CN (bus_addr[9]), .D
       (rstn), .Q (bus_waddr_d1[7]));
  DFKCNQD1 \bus_waddr_d1_reg[8] (.CP (clk), .CN (bus_addr[10]), .D
       (rstn), .Q (bus_waddr_d1[8]));
  DFKCNQD1 \flush_addr_reg[4] (.CP (clk), .CN (rstn), .D
       (last_word_addr[4]), .Q (flush_addr[4]));
  DFKCNQD1 \flush_addr_reg[7] (.CP (clk), .CN (rstn), .D
       (last_word_addr[7]), .Q (flush_addr[7]));
  DFKCNQD1 \bus_waddr_d1_reg[4] (.CP (clk), .CN (bus_addr[6]), .D
       (rstn), .Q (bus_waddr_d1[4]));
  DFKCNQD1 \flush_addr_reg[3] (.CP (clk), .CN (rstn), .D
       (last_word_addr[3]), .Q (flush_addr[3]));
  DFKCNQD1 \flush_addr_reg[8] (.CP (clk), .CN (rstn), .D
       (last_word_addr[8]), .Q (flush_addr[8]));
  DFKCNQD1 \bus_waddr_d1_reg[3] (.CP (clk), .CN (bus_addr[5]), .D
       (rstn), .Q (bus_waddr_d1[3]));
  DFKCND1 bus_we_prev_reg(.CP (clk), .CN (bus_we), .D (rstn), .Q
       (UNCONNECTED), .QN (bus_we_prev));
  DFKCNQD1 \bus_waddr_d1_reg[6] (.CP (clk), .CN (bus_addr[8]), .D
       (rstn), .Q (bus_waddr_d1[6]));
  DFKCNQD1 \flush_addr_reg[2] (.CP (clk), .CN (rstn), .D
       (last_word_addr[2]), .Q (flush_addr[2]));
  DFKCNQD1 \flush_addr_reg[6] (.CP (clk), .CN (rstn), .D
       (last_word_addr[6]), .Q (flush_addr[6]));
  DFKCNQD1 \bus_waddr_d1_reg[2] (.CP (clk), .CN (bus_addr[4]), .D
       (rstn), .Q (bus_waddr_d1[2]));
  DFKCNQD1 \flush_addr_reg[5] (.CP (clk), .CN (rstn), .D
       (last_word_addr[5]), .Q (flush_addr[5]));
  INR2D0 p23740A__8246(.A1 (bus_we), .B1 (n_63), .ZN (n_58));
  CKND2D0 p23673A__7098(.A1 (bus_addr[1]), .A2 (bus_addr[0]), .ZN
       (n_63));
  INR2D0 g2__6131(.A1 (sram_wen), .B1 (tpu_re), .ZN (sram_cen));
  DFQD1 \bus_wbuf_reg[26] (.CP (clk), .D (n_57), .Q (bus_wbuf[26]));
  DFQD1 \bus_wbuf_reg[25] (.CP (clk), .D (n_52), .Q (bus_wbuf[25]));
  DFQD1 \bus_wbuf_reg[24] (.CP (clk), .D (n_53), .Q (bus_wbuf[24]));
  DFQD1 \bus_wbuf_reg[27] (.CP (clk), .D (n_50), .Q (bus_wbuf[27]));
  DFQD1 \bus_wbuf_reg[30] (.CP (clk), .D (n_55), .Q (bus_wbuf[30]));
  DFQD1 \bus_wbuf_reg[29] (.CP (clk), .D (n_54), .Q (bus_wbuf[29]));
  DFQD1 \bus_wbuf_reg[28] (.CP (clk), .D (n_51), .Q (bus_wbuf[28]));
  DFQD1 \bus_wbuf_reg[31] (.CP (clk), .D (n_56), .Q (bus_wbuf[31]));
  DFQD1 \bus_wbuf_reg[2] (.CP (clk), .D (n_43), .Q (bus_wbuf[2]));
  DFQD1 \bus_wbuf_reg[13] (.CP (clk), .D (n_49), .Q (bus_wbuf[13]));
  DFQD1 \bus_wbuf_reg[14] (.CP (clk), .D (n_46), .Q (bus_wbuf[14]));
  DFQD1 \bus_wbuf_reg[15] (.CP (clk), .D (n_39), .Q (bus_wbuf[15]));
  DFQD1 \bus_wbuf_reg[0] (.CP (clk), .D (n_44), .Q (bus_wbuf[0]));
  DFQD1 \bus_wbuf_reg[1] (.CP (clk), .D (n_47), .Q (bus_wbuf[1]));
  DFQD1 \bus_wbuf_reg[12] (.CP (clk), .D (n_48), .Q (bus_wbuf[12]));
  DFQD1 \bus_wbuf_reg[4] (.CP (clk), .D (n_41), .Q (bus_wbuf[4]));
  DFQD1 \bus_wbuf_reg[3] (.CP (clk), .D (n_42), .Q (bus_wbuf[3]));
  DFQD1 \bus_wbuf_reg[6] (.CP (clk), .D (n_45), .Q (bus_wbuf[6]));
  DFQD1 \bus_wbuf_reg[5] (.CP (clk), .D (n_40), .Q (bus_wbuf[5]));
  DFQD1 \bus_wbuf_reg[7] (.CP (clk), .D (n_38), .Q (bus_wbuf[7]));
  AO22D0 p23454A__1881(.A1 (bus_wbuf[26]), .A2 (n_33), .B1
       (bus_din[2]), .B2 (n_12), .Z (n_57));
  AO22D0 p23454A2715__5115(.A1 (bus_wbuf[31]), .A2 (n_33), .B1
       (bus_din[7]), .B2 (n_12), .Z (n_56));
  AO22D0 p23454A2716__7482(.A1 (bus_wbuf[30]), .A2 (n_33), .B1
       (bus_din[6]), .B2 (n_12), .Z (n_55));
  AO22D0 p23454A2717__4733(.A1 (bus_wbuf[29]), .A2 (n_33), .B1
       (bus_din[5]), .B2 (n_12), .Z (n_54));
  AO22D0 p23454A2718__6161(.A1 (bus_wbuf[24]), .A2 (n_33), .B1
       (bus_din[0]), .B2 (n_12), .Z (n_53));
  AO22D0 p23454A2719__9315(.A1 (bus_wbuf[25]), .A2 (n_33), .B1
       (bus_din[1]), .B2 (n_12), .Z (n_52));
  AO22D0 p23454A2720__9945(.A1 (bus_wbuf[28]), .A2 (n_33), .B1
       (bus_din[4]), .B2 (n_12), .Z (n_51));
  AO22D0 p23454A2721__2883(.A1 (bus_wbuf[27]), .A2 (n_33), .B1
       (bus_din[3]), .B2 (n_12), .Z (n_50));
  DFQD1 \bus_wbuf_reg[10] (.CP (clk), .D (n_35), .Q (bus_wbuf[10]));
  DFQD1 \bus_wbuf_reg[11] (.CP (clk), .D (n_34), .Q (bus_wbuf[11]));
  DFQD1 \bus_wbuf_reg[8] (.CP (clk), .D (n_37), .Q (bus_wbuf[8]));
  DFQD1 \bus_wbuf_reg[9] (.CP (clk), .D (n_36), .Q (bus_wbuf[9]));
  AO22D0 p23436A__2346(.A1 (n_23), .A2 (bus_din[5]), .B1 (n_11), .B2
       (bus_wbuf[13]), .Z (n_49));
  AO22D0 p23436A2726__1666(.A1 (n_23), .A2 (bus_din[4]), .B1 (n_11),
       .B2 (bus_wbuf[12]), .Z (n_48));
  AO22D0 p23454A2727__7410(.A1 (bus_wbuf[1]), .A2 (n_24), .B1
       (bus_din[1]), .B2 (n_9), .Z (n_47));
  AO22D0 p23436A2728__6417(.A1 (n_23), .A2 (bus_din[6]), .B1 (n_11),
       .B2 (bus_wbuf[14]), .Z (n_46));
  DFQD1 \bus_wbuf_reg[20] (.CP (clk), .D (n_27), .Q (bus_wbuf[20]));
  DFQD1 \bus_wbuf_reg[21] (.CP (clk), .D (n_26), .Q (bus_wbuf[21]));
  DFQD1 \bus_wbuf_reg[16] (.CP (clk), .D (n_31), .Q (bus_wbuf[16]));
  DFQD1 \bus_wbuf_reg[23] (.CP (clk), .D (n_28), .Q (bus_wbuf[23]));
  DFQD1 \bus_wbuf_reg[22] (.CP (clk), .D (n_25), .Q (bus_wbuf[22]));
  DFQD1 \bus_wbuf_reg[17] (.CP (clk), .D (n_30), .Q (bus_wbuf[17]));
  DFQD1 \bus_wbuf_reg[18] (.CP (clk), .D (n_29), .Q (bus_wbuf[18]));
  DFQD1 \bus_wbuf_reg[19] (.CP (clk), .D (n_32), .Q (bus_wbuf[19]));
  AO22D0 p23454A2737__5477(.A1 (bus_wbuf[6]), .A2 (n_24), .B1
       (bus_din[6]), .B2 (n_9), .Z (n_45));
  AO22D0 p23454A2738__2398(.A1 (bus_wbuf[0]), .A2 (n_24), .B1
       (bus_din[0]), .B2 (n_9), .Z (n_44));
  AO22D0 p23454A2739__5107(.A1 (bus_wbuf[2]), .A2 (n_24), .B1
       (bus_din[2]), .B2 (n_9), .Z (n_43));
  AO22D0 p23454A2740__6260(.A1 (bus_wbuf[3]), .A2 (n_24), .B1
       (bus_din[3]), .B2 (n_9), .Z (n_42));
  AO22D0 p23454A2741__4319(.A1 (bus_wbuf[4]), .A2 (n_24), .B1
       (bus_din[4]), .B2 (n_9), .Z (n_41));
  AO22D0 p23454A2742__8428(.A1 (bus_wbuf[5]), .A2 (n_24), .B1
       (bus_din[5]), .B2 (n_9), .Z (n_40));
  AO22D0 p23436A2743__5526(.A1 (n_23), .A2 (bus_din[7]), .B1 (n_11),
       .B2 (bus_wbuf[15]), .Z (n_39));
  AO22D0 p23454A2744__6783(.A1 (bus_wbuf[7]), .A2 (n_24), .B1
       (bus_din[7]), .B2 (n_9), .Z (n_38));
  AO22D0 p23436A2745__3680(.A1 (n_23), .A2 (bus_din[0]), .B1 (n_11),
       .B2 (bus_wbuf[8]), .Z (n_37));
  AO22D0 p23436A2746__1617(.A1 (n_23), .A2 (bus_din[1]), .B1 (n_11),
       .B2 (bus_wbuf[9]), .Z (n_36));
  AO22D0 p23436A2747__2802(.A1 (n_23), .A2 (bus_din[2]), .B1 (n_11),
       .B2 (bus_wbuf[10]), .Z (n_35));
  AO22D0 p23436A2748__1705(.A1 (n_23), .A2 (bus_din[3]), .B1 (n_11),
       .B2 (bus_wbuf[11]), .Z (n_34));
  DFQD1 \last_word_addr_reg[8] (.CP (clk), .D (n_19), .Q
       (last_word_addr[8]));
  DFQD1 \last_word_addr_reg[0] (.CP (clk), .D (n_20), .Q
       (last_word_addr[0]));
  DFQD1 \last_word_addr_reg[1] (.CP (clk), .D (n_18), .Q
       (last_word_addr[1]));
  DFQD1 \last_word_addr_reg[2] (.CP (clk), .D (n_17), .Q
       (last_word_addr[2]));
  DFQD1 \last_word_addr_reg[3] (.CP (clk), .D (n_16), .Q
       (last_word_addr[3]));
  DFQD1 \last_word_addr_reg[4] (.CP (clk), .D (n_14), .Q
       (last_word_addr[4]));
  DFQD1 \last_word_addr_reg[5] (.CP (clk), .D (n_15), .Q
       (last_word_addr[5]));
  DFQD1 \last_word_addr_reg[6] (.CP (clk), .D (n_21), .Q
       (last_word_addr[6]));
  DFQD1 \last_word_addr_reg[7] (.CP (clk), .D (n_22), .Q
       (last_word_addr[7]));
  EDFKCNQD1 \last_byte_sel_reg[0] (.CP (clk), .CN (rstn), .D
       (bus_addr[0]), .E (bus_we), .Q (last_byte_sel[0]));
  AO22D0 p23436A2759__5122(.A1 (n_13), .A2 (bus_din[3]), .B1 (n_8), .B2
       (bus_wbuf[19]), .Z (n_32));
  AO22D0 p23436A2760__8246(.A1 (n_13), .A2 (bus_din[0]), .B1 (n_8), .B2
       (bus_wbuf[16]), .Z (n_31));
  AO22D0 p23436A2761__7098(.A1 (n_13), .A2 (bus_din[1]), .B1 (n_8), .B2
       (bus_wbuf[17]), .Z (n_30));
  AO22D0 p23436A2762__6131(.A1 (n_13), .A2 (bus_din[2]), .B1 (n_8), .B2
       (bus_wbuf[18]), .Z (n_29));
  AO22D0 p23436A2763__1881(.A1 (n_13), .A2 (bus_din[7]), .B1 (n_8), .B2
       (bus_wbuf[23]), .Z (n_28));
  AO22D0 p23436A2764__5115(.A1 (n_13), .A2 (bus_din[4]), .B1 (n_8), .B2
       (bus_wbuf[20]), .Z (n_27));
  AO22D0 p23436A2765__7482(.A1 (n_13), .A2 (bus_din[5]), .B1 (n_8), .B2
       (bus_wbuf[21]), .Z (n_26));
  AO22D0 p23436A2766__4733(.A1 (n_13), .A2 (bus_din[6]), .B1 (n_8), .B2
       (bus_wbuf[22]), .Z (n_25));
  EDFKCNQD1 \last_byte_sel_reg[1] (.CP (clk), .CN (rstn), .D
       (bus_addr[1]), .E (bus_we), .Q (last_byte_sel[1]));
  OAI211D0 p23650A__6161(.A1 (bus_addr[0]), .A2 (n_6), .B (n_10), .C
       (n_3), .ZN (n_33));
  AO22D0 p23454A2768__9315(.A1 (last_word_addr[7]), .A2 (n_2), .B1
       (bus_addr[9]), .B2 (n_4), .Z (n_22));
  AO22D0 p23454A2769__9945(.A1 (last_word_addr[6]), .A2 (n_2), .B1
       (bus_addr[8]), .B2 (n_4), .Z (n_21));
  AO22D0 p23454A2770__2883(.A1 (last_word_addr[0]), .A2 (n_2), .B1
       (bus_addr[2]), .B2 (n_4), .Z (n_20));
  CKND2D0 p23696A__2346(.A1 (n_7), .A2 (n_6), .ZN (n_24));
  NR2D0 p23667A__1666(.A1 (n_10), .A2 (n_1), .ZN (n_23));
  AO22D0 p23454A2771__7410(.A1 (last_word_addr[8]), .A2 (n_2), .B1
       (bus_addr[10]), .B2 (n_4), .Z (n_19));
  AO22D0 p23454A2772__6417(.A1 (last_word_addr[1]), .A2 (n_2), .B1
       (bus_addr[3]), .B2 (n_4), .Z (n_18));
  AO22D0 p23454A2773__5477(.A1 (last_word_addr[2]), .A2 (n_2), .B1
       (bus_addr[4]), .B2 (n_4), .Z (n_17));
  AO22D0 p23454A2774__2398(.A1 (last_word_addr[3]), .A2 (n_2), .B1
       (bus_addr[5]), .B2 (n_4), .Z (n_16));
  AO22D0 p23454A2775__5107(.A1 (last_word_addr[5]), .A2 (n_2), .B1
       (bus_addr[7]), .B2 (n_4), .Z (n_15));
  AO22D0 p23454A2776__6260(.A1 (last_word_addr[4]), .A2 (n_2), .B1
       (bus_addr[6]), .B2 (n_4), .Z (n_14));
  NR2D0 p23686A__4319(.A1 (n_0), .A2 (n_6), .ZN (n_13));
  NR2D0 p23684A__8428(.A1 (n_5), .A2 (n_63), .ZN (n_12));
  CKND2D0 p23697A__5526(.A1 (n_3), .A2 (n_6), .ZN (n_11));
  CKND0 Fp23698A(.I (n_7), .ZN (n_8));
  IND3D0 p23630A__6783(.A1 (bus_addr[1]), .B1 (rstn), .B2
       (bus_addr[0]), .ZN (n_10));
  NR3D0 p23633A__3680(.A1 (n_5), .A2 (bus_addr[1]), .A3 (bus_addr[0]),
       .ZN (n_9));
  CKND2D0 p23691A__1617(.A1 (n_0), .A2 (rstn), .ZN (n_7));
  CKND0 Fp23634A(.I (n_5), .ZN (n_4));
  CKND2D0 p23656A__2802(.A1 (rstn), .A2 (bus_addr[1]), .ZN (n_6));
  CKND2D0 p23613A__1705(.A1 (rstn), .A2 (bus_we), .ZN (n_5));
  CKND0 Fp23666A(.I (n_3), .ZN (n_2));
  CKND2D0 p23653A__5122(.A1 (n_1), .A2 (rstn), .ZN (n_3));
  CKND0 Fp23613A(.I (bus_we), .ZN (n_1));
  IND2D0 g2283__8246(.A1 (bus_addr[0]), .B1 (bus_we), .ZN (n_0));
endmodule

