
// Generated by Cadence Genus(TM) Synthesis Solution 21.16-s062_1
// Generated on: Mar 22 2026 13:04:18 EDT (Mar 22 2026 17:04:18 UTC)

// Verification Directory fv/input_idx_controller 

module input_idx_controller(clk, rstn, tpu_start, num_computation, m,
     n, k, a_row_idx, a_col_idx, b_row_idx, b_col_idx, alu_start,
     sram_rd_en, done);
  input clk, rstn, tpu_start;
  input [6:0] num_computation, m, n, k;
  output [8:0] a_row_idx, a_col_idx, b_row_idx, b_col_idx;
  output alu_start, sram_rd_en, done;
  wire clk, rstn, tpu_start;
  wire [6:0] num_computation, m, n, k;
  wire [8:0] a_row_idx, a_col_idx, b_row_idx, b_col_idx;
  wire alu_start, sram_rd_en, done;
  wire [8:0] b_col_idx_temp;
  wire [6:0] num_computated;
  wire [8:0] a_row_idx_temp;
  wire [8:0] a_row_os;
  wire [8:0] u_ac_i;
  wire [8:0] b_col_os;
  wire UNCONNECTED, UNCONNECTED0, last_data_read, n_0, n_1, n_2, n_3,
       n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_16;
  wire n_19, n_25, n_29, n_30, n_33, n_48, n_51, n_52;
  wire n_54, n_57, n_58, n_59, n_60, n_62, n_63, n_64;
  wire n_65, n_67, n_68, n_69, n_70, n_71, n_72, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_89, n_90, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_101;
  wire n_102, n_103, n_104, n_105, n_107, n_109, n_110, n_111;
  wire n_112, n_113, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_137, n_138, n_139;
  wire n_140, n_141, n_143, n_144, n_145, n_146, n_147, n_149;
  wire n_151, n_152, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_171, n_172, n_173, n_174, n_176;
  wire n_177, n_178, n_179, n_180, n_183, n_184, n_185, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_200, n_201, n_202, n_203;
  wire n_204, n_205, n_206, n_207, n_208, n_209, n_210, n_211;
  wire n_212, n_213, n_214, n_215, n_216, n_217, n_218, n_219;
  wire n_220, n_222, n_223, n_226, n_227, n_228, n_229, n_230;
  wire n_231, n_232, n_233, n_234, n_235, n_236, n_237, n_238;
  wire n_239, n_240, n_241, n_244, n_245, n_246, n_247, n_251;
  wire n_253, n_256, n_257, n_258, n_259, n_260, n_262, n_263;
  wire n_264, n_265, n_266, n_267, n_268, n_269, n_270, n_271;
  wire n_272, n_273, n_275, n_276, n_277, n_278, n_279, n_280;
  wire n_281, n_282, n_283, n_284, n_285, n_286, n_287, n_288;
  wire n_289, n_290, n_291, n_292, n_293, n_294, n_295, n_296;
  wire n_297, n_298, n_299, n_300, n_301, n_302, n_303, n_304;
  wire n_305, n_306, n_307, n_308, n_309, n_310, n_311, n_312;
  wire n_314, n_315, n_316, n_317, n_318, n_319, n_320, n_321;
  wire n_322, n_323, n_324, n_325, n_326, n_327, n_329, n_330;
  wire n_331, n_332, n_333, n_334, n_335, n_336, n_337, n_338;
  wire n_339, n_340, n_341, n_342, n_343, n_344, n_345, n_346;
  wire n_348, n_349, n_360, n_361, n_362, n_363, n_364, n_365;
  wire n_366, n_367, n_368, n_369, n_466, n_467, n_468;
  assign b_col_idx[0] = 1'b0;
  assign b_col_idx[1] = 1'b0;
  assign b_col_idx[2] = 1'b0;
  assign b_row_idx[0] = a_row_idx[0];
  assign b_row_idx[1] = a_row_idx[1];
  assign b_row_idx[2] = a_row_idx[2];
  assign a_col_idx[0] = 1'b0;
  assign a_col_idx[1] = 1'b0;
  assign a_col_idx[2] = 1'b0;
  IOA21D0 p18161A__2398(.A1 (n_344), .A2 (b_col_idx_temp[8]), .B
       (n_291), .ZN (n_346));
  DFKCNQD1 \num_computated_reg[3] (.CP (clk), .CN (rstn), .D (n_341),
       .Q (num_computated[3]));
  OAI32D0 p18171A__5107(.A1 (n_89), .A2 (b_col_idx_temp[7]), .A3
       (n_273), .B1 (n_90), .B2 (n_343), .ZN (n_345));
  DFQD1 \u_ac_z_reg[2] (.CP (clk), .D (n_338), .Q (a_row_idx_temp[2]));
  DFQD1 \u_ac_z_reg[1] (.CP (clk), .D (n_329), .Q (a_row_idx_temp[1]));
  DFKCNQD1 \num_computated_reg[4] (.CP (clk), .CN (rstn), .D (n_320),
       .Q (num_computated[4]));
  DFKCNQD1 \num_computated_reg[2] (.CP (clk), .CN (rstn), .D (n_318),
       .Q (num_computated[2]));
  DFKCNQD1 \a_row_os_reg[8] (.CP (clk), .CN (rstn), .D (n_311), .Q
       (a_row_os[8]));
  OAI21D0 p18154A__6260(.A1 (n_322), .A2 (b_col_idx_temp[7]), .B
       (n_343), .ZN (n_344));
  AO22D0 p18177A__4319(.A1 (n_334), .A2 (n_244), .B1
       (a_row_idx_temp[8]), .B2 (n_315), .Z (n_342));
  IOA21D0 p18161A5835__8428(.A1 (n_319), .A2 (num_computated[3]), .B
       (n_316), .ZN (n_341));
  OAI32D0 p18163A__5526(.A1 (u_ac_i[4]), .A2 (n_7), .A3 (n_332), .B1
       (n_11), .B2 (n_325), .ZN (n_340));
  OAI32D0 p18181A__6783(.A1 (b_row_idx[7]), .A2 (n_301), .A3 (n_337),
       .B1 (n_5), .B2 (n_314), .ZN (n_339));
  OAI22D0 p18178A__3680(.A1 (n_337), .A2 (n_101), .B1 (n_327), .B2
       (n_54), .ZN (n_338));
  EDFKCNQD1 \a_row_os_reg[5] (.CP (clk), .CN (rstn), .D (n_239), .E
       (n_336), .Q (a_row_os[5]));
  EDFKCNQD1 \a_row_os_reg[4] (.CP (clk), .CN (rstn), .D (n_178), .E
       (n_336), .Q (a_row_os[4]));
  DFKCNQD1 \num_computated_reg[6] (.CP (clk), .CN (rstn), .D (n_296),
       .Q (num_computated[6]));
  DFKCNQD1 \b_col_os_reg[3] (.CP (clk), .CN (rstn), .D (n_300), .Q
       (b_col_os[3]));
  DFKCNQD1 \num_computated_reg[5] (.CP (clk), .CN (rstn), .D (n_297),
       .Q (num_computated[5]));
  DFKCNQD1 \a_row_os_reg[3] (.CP (clk), .CN (rstn), .D (n_298), .Q
       (a_row_os[3]));
  DFKCNQD1 \num_computated_reg[1] (.CP (clk), .CN (rstn), .D (n_295),
       .Q (num_computated[1]));
  AO22D0 p18188A__1617(.A1 (n_330), .A2 (b_row_idx[3]), .B1 (n_128),
       .B2 (n_334), .Z (n_335));
  OAI22D0 p18197A__2802(.A1 (n_323), .A2 (n_10), .B1 (n_332), .B2
       (n_176), .ZN (n_333));
  AO22D0 p18177A5821__1705(.A1 (n_334), .A2 (n_365), .B1
       (a_row_idx_temp[4]), .B2 (n_330), .Z (n_331));
  OAI32D0 p18170A__5122(.A1 (a_row_idx[1]), .A2 (n_51), .A3 (n_337),
       .B1 (n_52), .B2 (n_327), .ZN (n_329));
  OAI22D0 p18187A__8246(.A1 (n_325), .A2 (n_9), .B1 (n_332), .B2
       (n_87), .ZN (n_326));
  OAI32D0 p18174A__7098(.A1 (a_col_idx[7]), .A2 (n_305), .A3 (n_332),
       .B1 (n_6), .B2 (n_323), .ZN (n_324));
  DFQD1 \u_ac_z_reg[0] (.CP (clk), .D (n_312), .Q (a_row_idx_temp[0]));
  EDFKCNQD1 \b_col_os_reg[5] (.CP (clk), .CN (rstn), .D (n_237), .E
       (n_336), .Q (b_col_os[5]));
  EDFKCNQD1 \b_col_os_reg[4] (.CP (clk), .CN (rstn), .D (n_180), .E
       (n_336), .Q (b_col_os[4]));
  EDFKCNQD1 \b_col_os_reg[8] (.CP (clk), .CN (rstn), .D (n_280), .E
       (n_336), .Q (b_col_os[8]));
  DFKCNQD1 \num_computated_reg[0] (.CP (clk), .CN (rstn), .D (n_299),
       .Q (num_computated[0]));
  IAO21D0 p18150A__6131(.A1 (n_322), .A2 (b_col_idx_temp[6]), .B
       (n_321), .ZN (n_343));
  AO21D0 p18152A5836__1881(.A1 (n_319), .A2 (num_computated[4]), .B
       (n_310), .Z (n_320));
  AO21D0 p18152A__5115(.A1 (n_319), .A2 (num_computated[2]), .B
       (n_307), .Z (n_318));
  OAI32D0 p18218A__7482(.A1 (b_col_idx_temp[5]), .A2 (n_276), .A3
       (n_322), .B1 (n_267), .B2 (n_303), .ZN (n_317));
  OAI211D0 p18135A__4733(.A1 (num_computated[3]), .A2 (n_306), .B
       (n_336), .C (n_309), .ZN (n_316));
  CKND0 Fp18170A(.I (n_314), .ZN (n_315));
  CKND8 p13989A(.I (n_349), .ZN (done));
  OAI21D0 p18254A__6161(.A1 (n_294), .A2 (n_51), .B (n_289), .ZN
       (n_312));
  MOAI22D0 p18171A5844__9315(.A1 (n_319), .A2 (n_283), .B1 (n_319), .B2
       (a_row_os[8]), .ZN (n_311));
  AOI211D0 p18097A__9945(.A1 (n_309), .A2 (n_206), .B (n_319), .C
       (n_210), .ZN (n_310));
  AO21D0 p18222A__2883(.A1 (n_304), .A2 (a_col_idx[3]), .B (n_302), .Z
       (n_308));
  AOI211D0 p18097A5847__2346(.A1 (n_78), .A2 (n_171), .B (n_319), .C
       (n_306), .ZN (n_307));
  DFKCND1 done_reg(.CP (clk), .CN (rstn), .D (n_284), .Q (UNCONNECTED),
       .QN (n_349));
  AOI21D0 p18191A__1666(.A1 (n_271), .A2 (n_305), .B (n_304), .ZN
       (n_323));
  OAI21D0 p18140A__7410(.A1 (n_322), .A2 (b_col_idx_temp[5]), .B
       (n_303), .ZN (n_321));
  NR2D0 p18173A__6417(.A1 (n_302), .A2 (n_304), .ZN (n_325));
  AOI21D0 p18178A5837__5477(.A1 (n_334), .A2 (n_301), .B (n_293), .ZN
       (n_314));
  MOAI22D0 p18171A5841__2398(.A1 (n_319), .A2 (n_77), .B1 (n_319), .B2
       (b_col_os[3]), .ZN (n_300));
  MOAI22D0 p18171A5845__5107(.A1 (n_319), .A2 (num_computated[0]), .B1
       (n_319), .B2 (num_computated[0]), .ZN (n_299));
  MOAI22D0 p18171A5839__6260(.A1 (n_319), .A2 (n_72), .B1 (n_319), .B2
       (a_row_os[3]), .ZN (n_298));
  MOAI22D0 p18171A5840__4319(.A1 (n_319), .A2 (n_211), .B1 (n_319), .B2
       (num_computated[5]), .ZN (n_297));
  MOAI22D0 p18171A5843__8428(.A1 (n_319), .A2 (n_223), .B1 (n_319), .B2
       (num_computated[6]), .ZN (n_296));
  MOAI22D0 p18171A5842__5526(.A1 (n_319), .A2 (n_74), .B1 (n_319), .B2
       (num_computated[1]), .ZN (n_295));
  IOA21D0 p18161A5838__6783(.A1 (n_334), .A2 (n_111), .B (n_294), .ZN
       (n_330));
  NR2D0 p18194A__3680(.A1 (n_288), .A2 (n_293), .ZN (n_327));
  MOAI22D0 p18252A__1617(.A1 (n_332), .A2 (n_368), .B1 (n_304), .B2
       (u_ac_i[6]), .ZN (n_292));
  IND4D0 p18225A__2802(.A1 (b_col_idx_temp[8]), .B1 (n_290), .B2
       (b_col_idx_temp[7]), .B3 (b_col_idx_temp[6]), .ZN (n_291));
  CKND0 Fp18194A(.I (n_288), .ZN (n_289));
  MOAI22D0 p18247A5846__1705(.A1 (n_337), .A2 (n_362), .B1 (n_293), .B2
       (a_row_idx_temp[6]), .ZN (n_287));
  MOAI22D0 p18247A__5122(.A1 (n_337), .A2 (n_363), .B1 (n_293), .B2
       (a_row_idx_temp[5]), .ZN (n_286));
  IND2D0 p18182A__8246(.A1 (n_284), .B1 (rstn), .ZN (n_285));
  MAOI22D0 p18287A__7098(.A1 (n_282), .A2 (n_281), .B1 (n_282), .B2
       (n_281), .ZN (n_283));
  MOAI22D0 p18294A__6131(.A1 (n_279), .A2 (n_278), .B1 (n_279), .B2
       (n_278), .ZN (n_280));
  CKND0 Fp18065A(.I (n_319), .ZN (n_336));
  AOI21D0 p18124A__1881(.A1 (n_277), .A2 (n_276), .B (n_275), .ZN
       (n_303));
  NR2D0 p18159A__5115(.A1 (n_332), .A2 (u_ac_i[3]), .ZN (n_302));
  NR2D0 p18184A__7482(.A1 (n_337), .A2 (a_row_idx[0]), .ZN (n_288));
  CKND0 Fp18219A(.I (n_290), .ZN (n_273));
  INR3D0 p18113A__4733(.A1 (n_268), .B1 (n_269), .B2 (n_270), .ZN
       (n_284));
  CKND0 Fp18126A(.I (n_337), .ZN (n_334));
  MOAI22D0 p18292A__6161(.A1 (n_322), .A2 (n_76), .B1 (n_275), .B2
       (b_col_idx_temp[4]), .ZN (n_272));
  CKND0 Fp18150A(.I (n_332), .ZN (n_271));
  IND3D0 p17858A__9315(.A1 (n_270), .B1 (n_269), .B2 (n_268), .ZN
       (n_319));
  NR3D0 p18163A5848__9945(.A1 (n_322), .A2 (n_276), .A3 (n_267), .ZN
       (n_290));
  NR2D0 p18191A5849__2883(.A1 (n_268), .A2 (n_263), .ZN (n_304));
  CKND2D0 p18101A__2346(.A1 (n_275), .A2 (n_294), .ZN (n_337));
  ND3D0 p18107A__1666(.A1 (n_268), .A2 (n_270), .A3 (rstn), .ZN
       (n_332));
  FA1D0 p18252A5851__7410(.A (b_col_os[7]), .B (k[4]), .CI (n_259), .CO
       (n_279), .S (n_266));
  FA1D0 p18238A__6417(.A (a_row_os[7]), .B (n[4]), .CI (n_257), .CO
       (n_282), .S (n_265));
  CKND0 Fp18109A(.I (n_322), .ZN (n_277));
  ND3D0 p18067A__5477(.A1 (n_264), .A2 (n_262), .A3 (rstn), .ZN
       (n_322));
  NR2D0 p18070A__2398(.A1 (n_264), .A2 (n_263), .ZN (n_275));
  INR2D0 p17796A__5107(.A1 (n_264), .B1 (n_262), .ZN (n_268));
  INR3D0 p17763A__6260(.A1 (sram_rd_en), .B1 (n_163), .B2 (n_256), .ZN
       (n_264));
  FA1D0 p18210A__4319(.A (b_col_os[6]), .B (k[3]), .CI (n_236), .CO
       (n_259), .S (n_260));
  FA1D0 p18196A__8428(.A (a_row_os[6]), .B (n[3]), .CI (n_238), .CO
       (n_257), .S (n_258));
  OAI211D0 p17743A__5526(.A1 (n[6]), .A2 (n_160), .B (n_253), .C
       (n_184), .ZN (n_256));
  OAI211D0 p17920A__3680(.A1 (m[6]), .A2 (n_193), .B (n_241), .C
       (n_194), .ZN (n_270));
  OR2D8 p13248A__1617(.A1 (n_251), .A2 (n_247), .Z (b_col_idx[8]));
  OAI211D0 p17896A__2802(.A1 (k[0]), .A2 (b_col_idx_temp[3]), .B
       (n_240), .C (n_196), .ZN (n_262));
  ND4D0 p18033A__1705(.A1 (n_235), .A2 (n_197), .A3 (n_217), .A4
       (n_207), .ZN (n_269));
  AOI211D0 p17708A__5122(.A1 (n_137), .A2 (b_row_idx[3]), .B (n_234),
       .C (n_138), .ZN (n_253));
  CKAN2D0 p13247A__7098(.A1 (n_246), .A2 (n_245), .Z (n_251));
  NR2D0 p13239A__1881(.A1 (n_246), .A2 (n_245), .ZN (n_247));
  OAI32D0 p18396A__5115(.A1 (b_row_idx[8]), .A2 (n_5), .A3 (n_301), .B1
       (b_row_idx[7]), .B2 (n_4), .ZN (n_244));
  OR2D8 p13291A__7482(.A1 (n_231), .A2 (n_233), .Z (a_row_idx[7]));
  OR2D8 p13293A__4733(.A1 (n_229), .A2 (n_227), .Z (b_col_idx[7]));
  AOI221D0 p17770A__6161(.A1 (n_218), .A2 (a_col_idx[3]), .B1 (n_165),
       .B2 (n_164), .C (n_219), .ZN (n_241));
  AOI221D0 p17747A__9315(.A1 (n_156), .A2 (b_col_idx_temp[3]), .B1
       (n_213), .B2 (n_212), .C (n_214), .ZN (n_240));
  FA1D0 p18154A5855__9945(.A (a_row_os[5]), .B (n[2]), .CI (n_177), .CO
       (n_238), .S (n_239));
  FA1D0 p18169A__2883(.A (b_col_os[5]), .B (k[2]), .CI (n_179), .CO
       (n_236), .S (n_237));
  IOA21D0 p13222A__1666(.A1 (n_228), .A2 (n_99), .B (n_98), .ZN
       (n_246));
  AOI221D0 p18008A__7410(.A1 (n_3), .A2 (n_1), .B1 (num_computated[3]),
       .B2 (n_208), .C (n_209), .ZN (n_235));
  OAI221D0 p17629A__6417(.A1 (n_154), .A2 (n_153), .B1 (n[0]), .B2
       (n_169), .C (n_215), .ZN (n_234));
  NR2D0 p13281A__5477(.A1 (n_232), .A2 (n_230), .ZN (n_233));
  CKAN2D0 p13290A__2398(.A1 (n_232), .A2 (n_230), .Z (n_231));
  CKAN2D0 p13290A5852__5107(.A1 (n_228), .A2 (n_226), .Z (n_229));
  NR2D0 p13282A__6260(.A1 (n_228), .A2 (n_226), .ZN (n_227));
  OR2D8 p13335A__4319(.A1 (n_203), .A2 (n_201), .Z (a_row_idx[6]));
  OR2D8 p13336A__8428(.A1 (n_199), .A2 (n_205), .Z (b_col_idx[6]));
  MAOI22D0 p18357A__5526(.A1 (n_222), .A2 (num_computated[6]), .B1
       (n_222), .B2 (num_computated[6]), .ZN (n_223));
  OAI221D0 p17693A__3680(.A1 (n_191), .A2 (n_190), .B1 (u_ac_i[3]), .B2
       (n_218), .C (n_192), .ZN (n_219));
  MAOI22D0 p18091A__1617(.A1 (num_computated[5]), .A2 (n_216), .B1
       (num_computated[5]), .B2 (n_216), .ZN (n_217));
  IAO21D0 p17617A__2802(.A1 (n_132), .A2 (n_131), .B (n_195), .ZN
       (n_215));
  OAI221D0 p17670A__1705(.A1 (n_213), .A2 (n_212), .B1 (n_187), .B2
       (n_188), .C (n_189), .ZN (n_214));
  OAI21D0 p18374A__5122(.A1 (n_210), .A2 (num_computated[5]), .B
       (n_222), .ZN (n_211));
  IOA21D0 p13196A__8246(.A1 (n_202), .A2 (n_93), .B (n_92), .ZN
       (n_232));
  IOA21D0 p13197A__7098(.A1 (n_204), .A2 (n_97), .B (n_96), .ZN
       (n_228));
  OAI211D0 p18014A__6131(.A1 (n_208), .A2 (num_computated[3]), .B
       (n_174), .C (n_172), .ZN (n_209));
  MUX2ND0 p18093A__1881(.I0 (n_206), .I1 (num_computated[4]), .S
       (n_173), .ZN (n_207));
  IND2D0 p18356A__5115(.A1 (n_220), .B1 (b_row_idx[6]), .ZN (n_301));
  CKAN2D0 p13327A5853__7482(.A1 (n_204), .A2 (n_198), .Z (n_205));
  NR2D0 p13334A__4733(.A1 (n_202), .A2 (n_200), .ZN (n_203));
  CKAN2D0 p13327A__6161(.A1 (n_202), .A2 (n_200), .Z (n_201));
  NR2D0 p13336A5854__9315(.A1 (n_204), .A2 (n_198), .ZN (n_199));
  XNR3D0 p18041A__9945(.A1 (n_183), .A2 (num_computation[6]), .A3
       (num_computated[6]), .ZN (n_197));
  OA211D0 p17886A__2883(.A1 (n_139), .A2 (n_140), .B (n_141), .C
       (n_367), .Z (n_196));
  OAI211D0 p17595A__2346(.A1 (n_151), .A2 (n_152), .B (n_155), .C
       (n_133), .ZN (n_195));
  AOI211D0 p17905A__1666(.A1 (n_193), .A2 (m[6]), .B (n_366), .C
       (n_369), .ZN (n_194));
  AOI221D0 p17562A__7410(.A1 (n_167), .A2 (n_166), .B1 (n_191), .B2
       (n_190), .C (n_168), .ZN (n_192));
  AOI221D0 p17540A__6417(.A1 (n_158), .A2 (n_157), .B1 (n_188), .B2
       (n_187), .C (n_159), .ZN (n_189));
  AOI22D0 p17844A__2398(.A1 (n_162), .A2 (n_161), .B1 (n_129), .B2
       (n[0]), .ZN (n_184));
  AOI21D0 p18270A__5107(.A1 (n_147), .A2 (num_computation[5]), .B
       (n_183), .ZN (n_216));
  IND2D0 p18304A__6260(.A1 (n_185), .B1 (b_row_idx[5]), .ZN (n_220));
  OR2D8 p13382A__4319(.A1 (n_126), .A2 (n_146), .Z (a_row_idx[5]));
  OR2D8 p13383A__8428(.A1 (n_127), .A2 (n_144), .Z (b_col_idx[5]));
  CKND2D0 p18355A__5526(.A1 (n_210), .A2 (num_computated[5]), .ZN
       (n_222));
  FA1D0 p18107A5858__6783(.A (b_col_os[4]), .B (k[1]), .CI (n_65), .CO
       (n_179), .S (n_180));
  FA1D0 p18091A5857__3680(.A (a_row_os[4]), .B (n[1]), .CI (n_59), .CO
       (n_177), .S (n_178));
  OA32D0 p18434A__1617(.A1 (u_ac_i[8]), .A2 (n_6), .A3 (n_305), .B1
       (a_col_idx[7]), .B2 (n_10), .Z (n_176));
  OR2D8 p13399A5860__2802(.A1 (n_466), .A2 (n_122), .Z (a_row_idx[4]));
  OAI21D0 p13184A__1705(.A1 (n_145), .A2 (n_79), .B (n_80), .ZN
       (n_202));
  OAI21D0 p13185A__5122(.A1 (n_143), .A2 (n_83), .B (n_84), .ZN
       (n_204));
  AOI221D0 p17899A__8246(.A1 (num_computated[0]), .A2
       (num_computation[0]), .B1 (num_computated[1]), .B2 (n_119), .C
       (n_120), .ZN (n_174));
  AOI21D0 p18275A__7098(.A1 (n_125), .A2 (num_computation[4]), .B
       (n_130), .ZN (n_173));
  MUX2ND0 p18019A__6131(.I0 (n_171), .I1 (num_computated[2]), .S
       (n_124), .ZN (n_172));
  OAI22D0 p17562A5859__5115(.A1 (n_167), .A2 (n_166), .B1 (n_165), .B2
       (n_164), .ZN (n_168));
  MOAI22D0 p17911A__7482(.A1 (n_162), .A2 (n_161), .B1 (n_160), .B2
       (n[6]), .ZN (n_163));
  OAI22D0 p17541A__4733(.A1 (n_158), .A2 (n_157), .B1 (n_156), .B2
       (b_col_idx_temp[3]), .ZN (n_159));
  AOI22D0 p17584A__6161(.A1 (n_154), .A2 (n_153), .B1 (n_152), .B2
       (n_151), .ZN (n_155));
  NR2D0 p18208A__9945(.A1 (n_147), .A2 (num_computation[5]), .ZN
       (n_183));
  NR2D0 p13373A__2883(.A1 (n_145), .A2 (n_104), .ZN (n_146));
  NR2D0 p13375A__2346(.A1 (n_143), .A2 (n_102), .ZN (n_144));
  OR2D8 p13399A__1666(.A1 (n_118), .A2 (n_117), .Z (b_col_idx[4]));
  AOI22D0 p17874A__7410(.A1 (n_140), .A2 (n_139), .B1
       (b_col_idx_temp[3]), .B2 (k[0]), .ZN (n_141));
  NR2D0 p18328A__6417(.A1 (n_309), .A2 (n_206), .ZN (n_210));
  CKND2D0 p18290A5863__5477(.A1 (n_169), .A2 (a_row_idx_temp[4]), .ZN
       (n_185));
  NR2D0 p17811A__2398(.A1 (n_137), .A2 (a_row_idx_temp[3]), .ZN
       (n_138));
  CKND2D0 p17626A__4319(.A1 (n_132), .A2 (n_131), .ZN (n_133));
  CKND0 Fp18204A(.I (n_147), .ZN (n_130));
  CKND0 Fp17819A(.I (n_128), .ZN (n_129));
  NR2D0 p13380A__8428(.A1 (n_112), .A2 (n_103), .ZN (n_127));
  NR2D0 p13378A__5526(.A1 (n_110), .A2 (n_105), .ZN (n_126));
  OA21D0 p18264A__6783(.A1 (n_123), .A2 (n_109), .B (n_125), .Z
       (n_208));
  AOI21D0 p18226A__3680(.A1 (n_63), .A2 (num_computation[2]), .B
       (n_123), .ZN (n_124));
  NR2D0 p13392A__1617(.A1 (n_107), .A2 (n_121), .ZN (n_122));
  NR2D0 p17917A__2802(.A1 (num_computated[1]), .A2 (n_119), .ZN
       (n_120));
  INR2D0 p13397A5862__1705(.A1 (n_115), .B1 (n_116), .ZN (n_118));
  INR2D0 p13367A__5122(.A1 (n_116), .B1 (n_115), .ZN (n_117));
  CKND0 Fp13166A5856(.I (n_112), .ZN (n_143));
  NR2D0 p17804A__7098(.A1 (n_111), .A2 (a_row_idx_temp[3]), .ZN
       (n_128));
  CKND0 Fp13166A(.I (n_110), .ZN (n_145));
  IND3D0 p18170A5865__6131(.A1 (num_computation[4]), .B1 (n_109), .B2
       (n_123), .ZN (n_147));
  CKND0 Fp18360A(.I (n_293), .ZN (n_294));
  CKND2D0 p18318A__1881(.A1 (n_306), .A2 (num_computated[3]), .ZN
       (n_309));
  NR2D0 p17702A__5115(.A1 (n_111), .A2 (n_2), .ZN (n_169));
  AN2D8 p13469A__7482(.A1 (n_467), .A2 (n_121), .Z (a_row_idx[3]));
  CKND0 Fp13384A5866(.I (n_104), .ZN (n_105));
  CKND0 Fp13384A(.I (n_102), .ZN (n_103));
  AOI32D0 p18568A__4733(.A1 (n_54), .A2 (a_row_idx[1]), .A3
       (a_row_idx[0]), .B1 (n_52), .B2 (a_row_idx[2]), .ZN (n_101));
  OAI21D0 p13168A__6161(.A1 (n_82), .A2 (n_115), .B (n_81), .ZN
       (n_112));
  CKND2D0 p18270A5864__9315(.A1 (n_123), .A2 (n_109), .ZN (n_125));
  AOI21D0 p17509A__9945(.A1 (n_16), .A2 (m[3]), .B (n_190), .ZN
       (n_165));
  CKND2D0 p13383A5869__2883(.A1 (n_99), .A2 (n_98), .ZN (n_226));
  CKND2D0 p13389A__2346(.A1 (n_97), .A2 (n_96), .ZN (n_198));
  CKND2D0 p13383A5870__1666(.A1 (n_95), .A2 (n_94), .ZN (n_230));
  CKND2D0 p13388A__7410(.A1 (n_93), .A2 (n_92), .ZN (n_200));
  AOI21D0 p17720A__6417(.A1 (n_11), .A2 (m[1]), .B (n_166), .ZN
       (n_218));
  OAI21D0 p13167A__5477(.A1 (n_85), .A2 (n_121), .B (n_86), .ZN
       (n_110));
  IND2D0 p18382A__2398(.A1 (n_113), .B1 (u_ac_i[6]), .ZN (n_305));
  AN2D8 p13473A__5107(.A1 (n_468), .A2 (n_115), .Z (b_col_idx[3]));
  AOI21D0 p17516A__6260(.A1 (n_9), .A2 (m[2]), .B (n_164), .ZN (n_167));
  AOI21D0 p17570A__4319(.A1 (n_5), .A2 (n[4]), .B (n_161), .ZN (n_152));
  AOI21D0 p17860A__8428(.A1 (n_57), .A2 (k[5]), .B (n_68), .ZN (n_140));
  AOI21D0 p17490A__5526(.A1 (n_75), .A2 (k[1]), .B (n_69), .ZN (n_156));
  AOI21D0 p17760A__6783(.A1 (n_0), .A2 (n[1]), .B (n_153), .ZN (n_137));
  AOI21D0 p17592A__3680(.A1 (n_90), .A2 (k[4]), .B (n_139), .ZN
       (n_188));
  AOI21D0 p17612A__1617(.A1 (n_6), .A2 (m[4]), .B (n_67), .ZN (n_191));
  AOI21D0 p17864A__2802(.A1 (n_10), .A2 (m[5]), .B (n_70), .ZN (n_149));
  AOI21D0 p17583A__1705(.A1 (n_33), .A2 (n[2]), .B (n_131), .ZN
       (n_154));
  AOI21D0 p17502A__5122(.A1 (n_89), .A2 (k[3]), .B (n_187), .ZN
       (n_158));
  AOI21D0 p17613A__8246(.A1 (n_29), .A2 (n[3]), .B (n_151), .ZN
       (n_132));
  AOI21D0 p17844A5874__7098(.A1 (n_4), .A2 (n[5]), .B (n_71), .ZN
       (n_162));
  AO21D0 p17736A__6131(.A1 (n_267), .A2 (k[2]), .B (n_157), .Z (n_213));
  NR2D0 p18325A__1881(.A1 (sram_rd_en), .A2 (n_263), .ZN (n_293));
  CKND8 p13989A5868(.I (n_348), .ZN (alu_start));
  AOI32D0 p18553A__5115(.A1 (n_9), .A2 (u_ac_i[4]), .A3 (u_ac_i[3]),
       .B1 (n_11), .B2 (a_col_idx[5]), .ZN (n_87));
  INR2D0 p13360A__7482(.A1 (n_86), .B1 (n_85), .ZN (n_107));
  INR2D0 p13356A__4733(.A1 (n_84), .B1 (n_83), .ZN (n_102));
  IND2D0 p13354A__6161(.A1 (n_82), .B1 (n_81), .ZN (n_116));
  INR2D0 p13356A5871__9315(.A1 (n_80), .B1 (n_79), .ZN (n_104));
  AOI21D0 p18154A5872__9945(.A1 (num_computation[1]), .A2
       (num_computation[0]), .B (n_62), .ZN (n_119));
  ND3D0 p17692A__2883(.A1 (a_row_idx[2]), .A2 (a_row_idx[1]), .A3
       (a_row_idx[0]), .ZN (n_111));
  NR2D0 p18290A__2346(.A1 (n_78), .A2 (n_171), .ZN (n_306));
  OAI21D0 p18494A5873__1666(.A1 (b_col_os[3]), .A2 (k[0]), .B (n_64),
       .ZN (n_77));
  AOI22D0 p18584A__7410(.A1 (n_75), .A2 (b_col_idx_temp[3]), .B1
       (n_60), .B2 (b_col_idx_temp[4]), .ZN (n_76));
  OAI21D0 p18488A__6417(.A1 (num_computated[0]), .A2
       (num_computated[1]), .B (n_78), .ZN (n_74));
  OAI21D0 p18494A__2398(.A1 (a_row_os[3]), .A2 (n[0]), .B (n_58), .ZN
       (n_72));
  CKND0 Fp17858A(.I (n_71), .ZN (n_160));
  CKND0 Fp17873A(.I (n_70), .ZN (n_193));
  CKND0 Fp17499A(.I (n_69), .ZN (n_212));
  DFKCND1 alu_start_reg(.CP (clk), .CN (tpu_start), .D (rstn), .Q
       (UNCONNECTED0), .QN (n_348));
  MOAI22D0 p18431A__6260(.A1 (b_col_os[8]), .A2 (k[5]), .B1
       (b_col_os[8]), .B2 (k[5]), .ZN (n_278));
  MOAI22D0 p18428A__4319(.A1 (a_row_os[8]), .A2 (n[5]), .B1
       (a_row_os[8]), .B2 (n[5]), .ZN (n_281));
  NR2D0 p17840A__8428(.A1 (n_4), .A2 (n[5]), .ZN (n_71));
  CKND2D0 p13274A__6783(.A1 (n_29), .A2 (n_8), .ZN (n_93));
  NR2D0 p17598A__3680(.A1 (n_6), .A2 (m[4]), .ZN (n_67));
  MOAI22D0 p13377A__1617(.A1 (b_col_idx_temp[8]), .A2 (b_col_os[8]),
       .B1 (b_col_idx_temp[8]), .B2 (b_col_os[8]), .ZN (n_245));
  NR2D0 p17516A5877__2802(.A1 (n_9), .A2 (m[2]), .ZN (n_164));
  AN2D8 p13496A__1705(.A1 (n_30), .A2 (tpu_start), .Z (sram_rd_en));
  NR2D0 p17568A__5122(.A1 (n_90), .A2 (k[4]), .ZN (n_139));
  NR2D0 p17584A5878__8246(.A1 (n_29), .A2 (n[3]), .ZN (n_151));
  NR2D0 p17545A__7098(.A1 (n_5), .A2 (n[4]), .ZN (n_161));
  ND3D0 p18364A__6131(.A1 (u_ac_i[5]), .A2 (u_ac_i[4]), .A3
       (a_col_idx[3]), .ZN (n_113));
  NR3D0 p18098A__1881(.A1 (num_computation[0]), .A2
       (num_computation[2]), .A3 (num_computation[1]), .ZN (n_123));
  CKND0 Fp18131A(.I (n_64), .ZN (n_65));
  CKND0 Fp18167A(.I (n_62), .ZN (n_63));
  CKND0 Fp18115A(.I (n_58), .ZN (n_59));
  CKND2D0 p13343A__7482(.A1 (n_90), .A2 (n_25), .ZN (n_99));
  CKND2D0 p13277A__4733(.A1 (n_48), .A2 (n_89), .ZN (n_97));
  CKND2D0 p13343A5885__6161(.A1 (n_5), .A2 (n_19), .ZN (n_95));
  NR2D0 p17852A__9315(.A1 (n_57), .A2 (k[5]), .ZN (n_68));
  NR2D0 p17855A__9945(.A1 (n_10), .A2 (m[5]), .ZN (n_70));
  NR2D0 p17503A__2883(.A1 (n_75), .A2 (k[1]), .ZN (n_69));
  NR2D0 p17542A__2346(.A1 (n_267), .A2 (k[2]), .ZN (n_157));
  NR2D0 p17609A__1666(.A1 (n_0), .A2 (n[1]), .ZN (n_153));
  NR2D0 p17557A__7410(.A1 (n_11), .A2 (m[1]), .ZN (n_166));
  NR2D0 p17512A__6417(.A1 (n_89), .A2 (k[3]), .ZN (n_187));
  NR2D0 p17509A5879__5477(.A1 (n_16), .A2 (m[3]), .ZN (n_190));
  NR2D0 p17564A__2398(.A1 (n_33), .A2 (n[2]), .ZN (n_131));
  CKND0 Fp8914A5912(.I (a_row_idx[2]), .ZN (n_54));
  CKND2D0 p13233A5881__5107(.A1 (b_col_os[5]), .A2 (b_col_idx_temp[5]),
       .ZN (n_84));
  NR2D0 p13166A__6260(.A1 (a_row_os[4]), .A2 (b_row_idx[4]), .ZN
       (n_85));
  CKND2D0 p18091A5880__4319(.A1 (a_row_os[3]), .A2 (n[0]), .ZN (n_58));
  CKND2D0 p13175A__8428(.A1 (b_col_os[4]), .A2 (b_col_idx_temp[4]), .ZN
       (n_81));
  CKND2D0 p13310A__5526(.A1 (a_row_os[6]), .A2 (a_row_idx_temp[6]), .ZN
       (n_92));
  CKND2D0 p13312A__6783(.A1 (b_col_os[6]), .A2 (b_col_idx_temp[6]), .ZN
       (n_96));
  NR2D0 p13216A__3680(.A1 (b_col_idx_temp[5]), .A2 (b_col_os[5]), .ZN
       (n_83));
  CKND2D0 p13374A5883__1617(.A1 (a_row_os[7]), .A2 (a_row_idx_temp[7]),
       .ZN (n_94));
  NR2D0 p18165A__2802(.A1 (num_computation[1]), .A2
       (num_computation[0]), .ZN (n_62));
  CKND0 Fp8914A5895(.I (a_row_idx[1]), .ZN (n_52));
  CKND0 Fp8914A5890(.I (a_row_idx[0]), .ZN (n_51));
  CKND2D0 p18107A5886__1705(.A1 (b_col_os[3]), .A2 (k[0]), .ZN (n_64));
  CKND2D0 p13177A__5122(.A1 (a_row_os[4]), .A2 (a_row_idx_temp[4]), .ZN
       (n_86));
  NR2D0 p13167A5882__8246(.A1 (b_col_os[4]), .A2 (b_col_idx_temp[4]),
       .ZN (n_82));
  CKND2D0 p13233A__7098(.A1 (a_row_os[5]), .A2 (a_row_idx_temp[5]), .ZN
       (n_80));
  CKND2D0 p13374A__6131(.A1 (b_col_os[7]), .A2 (b_col_idx_temp[7]), .ZN
       (n_98));
  NR2D0 p13216A5884__1881(.A1 (b_row_idx[5]), .A2 (a_row_os[5]), .ZN
       (n_79));
  CKND2D0 p18432A__5115(.A1 (b_col_idx_temp[4]), .A2
       (b_col_idx_temp[3]), .ZN (n_276));
  CKND2D0 p18275A5876__7482(.A1 (num_computated[0]), .A2
       (num_computated[1]), .ZN (n_78));
  CKND2D0 p13133A__4733(.A1 (a_row_os[3]), .A2 (b_row_idx[3]), .ZN
       (n_121));
  CKND2D0 p13132A__6161(.A1 (b_col_os[3]), .A2 (b_col_idx_temp[3]), .ZN
       (n_115));
  CKND0 Fp18482A(.I (num_computated[4]), .ZN (n_206));
  BUFFD16 Fp8914A5896(.I (a_row_idx_temp[1]), .Z (a_row_idx[1]));
  CKND0 Fp18374A(.I (num_computated[0]), .ZN (n_3));
  CKND0 Fp18108A(.I (num_computation[0]), .ZN (n_1));
  CKND0 Fp18660A(.I (rstn), .ZN (n_263));
  CKND0 Fp18408A(.I (num_computated[2]), .ZN (n_171));
  CKND0 Fp18190A(.I (num_computation[3]), .ZN (n_109));
  BUFFD16 Fp8914A5913(.I (a_row_idx_temp[2]), .Z (a_row_idx[2]));
  BUFFD16 Fp8914A5892(.I (a_row_idx_temp[0]), .Z (a_row_idx[0]));
  XOR3D0 g2(.A1 (n_360), .A2 (b_row_idx[8]), .A3 (a_row_os[8]), .Z
       (n_361));
  IOA21D0 g3(.A1 (n_232), .A2 (n_95), .B (n_94), .ZN (n_360));
  CKXOR2D0 g5971(.A1 (n_220), .A2 (b_row_idx[6]), .Z (n_362));
  CKXOR2D0 g5972(.A1 (n_185), .A2 (b_row_idx[5]), .Z (n_363));
  MUX2ND0 g5973(.I0 (n_364), .I1 (a_row_idx_temp[3]), .S
       (b_row_idx[4]), .ZN (n_365));
  CKND0 g5974(.I (n_169), .ZN (n_364));
  XNR2D0 g5975(.A1 (n_149), .A2 (n_67), .ZN (n_366));
  XNR2D0 g5976(.A1 (n_68), .A2 (k[6]), .ZN (n_367));
  CKXOR2D0 g5977(.A1 (n_113), .A2 (u_ac_i[6]), .Z (n_368));
  XNR2D0 g5978(.A1 (u_ac_i[3]), .A2 (m[0]), .ZN (n_369));
  CKND8 drc_bufs(.I (n_2), .ZN (b_row_idx[3]));
  CKND8 drc_bufs5988(.I (n_5), .ZN (b_row_idx[7]));
  CKND8 drc_bufs5996(.I (n_7), .ZN (a_col_idx[3]));
  CKND8 drc_bufs6005(.I (n_0), .ZN (b_row_idx[4]));
  CKND8 drc_bufs6015(.I (n_11), .ZN (a_col_idx[4]));
  CKND8 drc_bufs6023(.I (n_29), .ZN (b_row_idx[6]));
  CKND8 drc_bufs6032(.I (n_33), .ZN (b_row_idx[5]));
  CKND8 drc_bufs6042(.I (n_9), .ZN (a_col_idx[5]));
  CKND8 drc_bufs6048(.I (n_4), .ZN (b_row_idx[8]));
  CKND8 drc_bufs6054(.I (n_6), .ZN (a_col_idx[7]));
  CKND8 drc_bufs6060(.I (n_16), .ZN (a_col_idx[6]));
  CKND8 drc_bufs6065(.I (n_10), .ZN (a_col_idx[8]));
  CKBD8 drc_bufs6071(.I (n_361), .Z (a_row_idx[8]));
  EDFKCND1 \b_col_os_reg[6] (.CP (clk), .CN (rstn), .D (n_260), .E
       (n_336), .Q (b_col_os[6]), .QN (n_48));
  DFXD1 last_data_read_reg(.CP (clk), .DA (rstn), .DB (last_data_read),
       .SA (n_285), .Q (last_data_read), .QN (n_30));
  EDFKCND1 \b_col_os_reg[7] (.CP (clk), .CN (rstn), .D (n_266), .E
       (n_336), .Q (b_col_os[7]), .QN (n_25));
  DFXD1 \u_ac_j_reg[6] (.CP (clk), .DA (n_321), .DB (n_290), .SA
       (b_col_idx_temp[6]), .Q (b_col_idx_temp[6]), .QN (n_89));
  EDFKCND1 \a_row_os_reg[7] (.CP (clk), .CN (rstn), .D (n_265), .E
       (n_336), .Q (a_row_os[7]), .QN (n_19));
  EDFKCND1 \a_row_os_reg[6] (.CP (clk), .CN (rstn), .D (n_258), .E
       (n_336), .Q (a_row_os[6]), .QN (n_8));
  DFXD1 \u_ac_j_reg[3] (.CP (clk), .DA (n_275), .DB (n_277), .SA
       (b_col_idx_temp[3]), .Q (b_col_idx_temp[3]), .QN (n_60));
  DFD1 \u_ac_j_reg[8] (.CP (clk), .D (n_346), .Q (b_col_idx_temp[8]),
       .QN (n_57));
  DFD1 \u_ac_j_reg[4] (.CP (clk), .D (n_272), .Q (b_col_idx_temp[4]),
       .QN (n_75));
  DFD1 \u_ac_j_reg[7] (.CP (clk), .D (n_345), .Q (b_col_idx_temp[7]),
       .QN (n_90));
  DFD1 \u_ac_j_reg[5] (.CP (clk), .D (n_317), .Q (b_col_idx_temp[5]),
       .QN (n_267));
  DFD1 \u_ac_z_reg[3] (.CP (clk), .D (n_335), .Q (a_row_idx_temp[3]),
       .QN (n_2));
  DFD1 \u_ac_z_reg[7] (.CP (clk), .D (n_339), .Q (a_row_idx_temp[7]),
       .QN (n_5));
  DFD1 \u_ac_i_reg[3] (.CP (clk), .D (n_308), .Q (u_ac_i[3]), .QN
       (n_7));
  DFD1 \u_ac_z_reg[4] (.CP (clk), .D (n_331), .Q (a_row_idx_temp[4]),
       .QN (n_0));
  DFD1 \u_ac_i_reg[4] (.CP (clk), .D (n_340), .Q (u_ac_i[4]), .QN
       (n_11));
  DFD1 \u_ac_z_reg[6] (.CP (clk), .D (n_287), .Q (a_row_idx_temp[6]),
       .QN (n_29));
  DFD1 \u_ac_z_reg[5] (.CP (clk), .D (n_286), .Q (a_row_idx_temp[5]),
       .QN (n_33));
  DFD1 \u_ac_i_reg[5] (.CP (clk), .D (n_326), .Q (u_ac_i[5]), .QN
       (n_9));
  DFD1 \u_ac_z_reg[8] (.CP (clk), .D (n_342), .Q (a_row_idx_temp[8]),
       .QN (n_4));
  DFD1 \u_ac_i_reg[7] (.CP (clk), .D (n_324), .Q (u_ac_i[7]), .QN
       (n_6));
  DFD1 \u_ac_i_reg[6] (.CP (clk), .D (n_292), .Q (u_ac_i[6]), .QN
       (n_16));
  DFD1 \u_ac_i_reg[8] (.CP (clk), .D (n_333), .Q (u_ac_i[8]), .QN
       (n_10));
  CKAN2D0 g6120(.A1 (n_121), .A2 (n_107), .Z (n_466));
  IND2D0 g6121(.A1 (a_row_os[3]), .B1 (n_2), .ZN (n_467));
  IND2D0 g6122(.A1 (b_col_os[3]), .B1 (n_60), .ZN (n_468));
endmodule

